export const mockMovesPCS = {
  currentMove: [
    {
      id: 'testMoveID1',
      moveCode: 'MOVECO',
      orderID: 'testOrderID1',
      status: 'DRAFT',
      orders: {
        id: 'testOrder1',
        NewDutyLocation: {
          id: 'testDDL1',
          name: 'Fort Bragg North Station',
          Address: {
            streetAddress1: '123 Main Ave',
            streetAddress2: 'Apartment 9000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90210',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL1',
          name: 'Fort Bragg North Station',
          Address: {
            streetAddress1: '123 Main Ave',
            streetAddress2: 'Apartment 9000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90210',
            country: 'USA',
          },
        },
        rank: 'E_8',
        reportByDate: '2024-01-25',
        ordersType: 'PERMANENT_CHANGE_OF_STATION',
        orderNumber: 'ORDER3',
        date_issued: '2024-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
  ],
  previousMoves: [
    {
      id: 'testMoveID2',
      moveCode: 'SAMPLE',
      orderID: 'testOrderID2',
      status: 'APPROVED',
      orders: {
        id: 'testOrder2',
        NewDutyLocation: {
          id: 'testDDL2',
          name: 'Fort Bragg South Station',
          Address: {
            streetAddress1: '456 Oak St',
            streetAddress2: 'Apartment 8000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90211',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL2',
          name: 'Fort Bragg South Station',
          Address: {
            streetAddress1: '456 Oak St',
            streetAddress2: 'Apartment 8000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90211',
            country: 'USA',
          },
        },
        rank: 'E_7',
        reportByDate: '2024-01-24',
        ordersType: 'PERMANENT_CHANGE_OF_STATION',
        orderNumber: 'ORDER4',
        date_issued: '2021-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
    {
      id: 'testMoveID3',
      moveCode: 'EXAMPL',
      orderID: 'testOrderID3',
      status: 'APPROVED',
      orders: {
        id: 'testOrder3',
        NewDutyLocation: {
          id: 'testDDL3',
          name: 'Fort Bragg East Station',
          Address: {
            streetAddress1: '789 Pine Ave',
            streetAddress2: 'Apartment 7000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90212',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL3',
          name: 'Fort Bragg East Station',
          Address: {
            streetAddress1: '789 Pine Ave',
            streetAddress2: 'Apartment 7000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90212',
            country: 'USA',
          },
        },
        rank: 'E_6',
        reportByDate: '2024-01-26',
        ordersType: 'PERMANENT_CHANGE_OF_STATION',
        orderNumber: 'ORDER5',
        date_issued: '2018-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
  ],
};

export const mockMovesRetirement = {
  currentMove: [
    {
      id: 'testMoveID1',
      moveCode: 'MOVECO',
      orderID: 'testOrderID1',
      status: 'SUBMITTED',
      orders: {
        id: 'testOrder1',
        NewDutyLocation: {
          id: 'testDDL1',
          name: 'Fort Bragg North Station',
          Address: {
            streetAddress1: '123 Main Ave',
            streetAddress2: 'Apartment 9000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90210',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL1',
          name: 'Fort Bragg North Station',
          Address: {
            streetAddress1: '123 Main Ave',
            streetAddress2: 'Apartment 9000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90210',
            country: 'USA',
          },
        },
        rank: 'E_8',
        reportByDate: '2024-01-25',
        ordersType: 'RETIREMENT',
        orderNumber: 'ORDER3',
        date_issued: '2024-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
  ],
  previousMoves: [
    {
      id: 'testMoveID2',
      moveCode: 'SAMPLE',
      orderID: 'testOrderID2',
      status: 'APPROVED',
      orders: {
        id: 'testOrder2',
        NewDutyLocation: {
          id: 'testDDL2',
          name: 'Fort Bragg South Station',
          Address: {
            streetAddress1: '456 Oak St',
            streetAddress2: 'Apartment 8000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90211',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL2',
          name: 'Fort Bragg South Station',
          Address: {
            streetAddress1: '456 Oak St',
            streetAddress2: 'Apartment 8000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90211',
            country: 'USA',
          },
        },
        rank: 'E_7',
        reportByDate: '2024-01-24',
        ordersType: 'PERMANENT_CHANGE_OF_STATION',
        orderNumber: 'ORDER4',
        date_issued: '2021-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
    {
      id: 'testMoveID3',
      moveCode: 'EXAMPL',
      orderID: 'testOrderID3',
      status: 'APPROVED',
      orders: {
        id: 'testOrder3',
        NewDutyLocation: {
          id: 'testDDL3',
          name: 'Fort Bragg East Station',
          Address: {
            streetAddress1: '789 Pine Ave',
            streetAddress2: 'Apartment 7000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90212',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL3',
          name: 'Fort Bragg East Station',
          Address: {
            streetAddress1: '789 Pine Ave',
            streetAddress2: 'Apartment 7000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90212',
            country: 'USA',
          },
        },
        rank: 'E_6',
        reportByDate: '2024-01-26',
        ordersType: 'PERMANENT_CHANGE_OF_STATION',
        orderNumber: 'ORDER5',
        date_issued: '2018-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
  ],
};

export const mockMovesSeparation = {
  currentMove: [
    {
      id: 'testMoveID1',
      moveCode: 'MOVECO',
      orderID: 'testOrderID1',
      status: 'DRAFT',
      orders: {
        id: 'testOrder1',
        NewDutyLocation: {
          id: 'testDDL1',
          name: 'Fort Bragg North Station',
          Address: {
            streetAddress1: '123 Main Ave',
            streetAddress2: 'Apartment 9000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90210',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL1',
          name: 'Fort Bragg North Station',
          Address: {
            streetAddress1: '123 Main Ave',
            streetAddress2: 'Apartment 9000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90210',
            country: 'USA',
          },
        },
        rank: 'E_8',
        reportByDate: '2024-01-25',
        ordersType: 'SEPARATION',
        orderNumber: 'ORDER3',
        date_issued: '2024-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
  ],
  previousMoves: [
    {
      id: 'testMoveID2',
      moveCode: 'SAMPLE',
      orderID: 'testOrderID2',
      status: 'APPROVED',
      orders: {
        id: 'testOrder2',
        NewDutyLocation: {
          id: 'testDDL2',
          name: 'Fort Bragg South Station',
          Address: {
            streetAddress1: '456 Oak St',
            streetAddress2: 'Apartment 8000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90211',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL2',
          name: 'Fort Bragg South Station',
          Address: {
            streetAddress1: '456 Oak St',
            streetAddress2: 'Apartment 8000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90211',
            country: 'USA',
          },
        },
        rank: 'E_7',
        reportByDate: '2024-01-24',
        ordersType: 'PERMANENT_CHANGE_OF_STATION',
        orderNumber: 'ORDER4',
        date_issued: '2021-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
    {
      id: 'testMoveID3',
      moveCode: 'EXAMPL',
      orderID: 'testOrderID3',
      status: 'APPROVED',
      orders: {
        id: 'testOrder3',
        NewDutyLocation: {
          id: 'testDDL3',
          name: 'Fort Bragg East Station',
          Address: {
            streetAddress1: '789 Pine Ave',
            streetAddress2: 'Apartment 7000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90212',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL3',
          name: 'Fort Bragg East Station',
          Address: {
            streetAddress1: '789 Pine Ave',
            streetAddress2: 'Apartment 7000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90212',
            country: 'USA',
          },
        },
        rank: 'E_6',
        reportByDate: '2024-01-26',
        ordersType: 'PERMANENT_CHANGE_OF_STATION',
        orderNumber: 'ORDER5',
        date_issued: '2018-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
  ],
};

export const mockMovesNoPreviousMoves = {
  currentMove: [
    {
      id: 'testMoveID1',
      moveCode: 'MOVECO',
      orderID: 'testOrderID1',
      status: 'DRAFT',
      orders: {
        id: 'testOrder1',
        NewDutyLocation: {
          id: 'testDDL1',
          name: 'Fort Bragg North Station',
          Address: {
            streetAddress1: '123 Main Ave',
            streetAddress2: 'Apartment 9000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90210',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL1',
          name: 'Fort Bragg North Station',
          Address: {
            streetAddress1: '123 Main Ave',
            streetAddress2: 'Apartment 9000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90210',
            country: 'USA',
          },
        },
        rank: 'E_8',
        reportByDate: '2024-01-25',
        ordersType: 'PERMANENT_CHANGE_OF_STATION',
        orderNumber: 'ORDER3',
        date_issued: '2024-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
  ],
  previousMoves: [],
};

export const mockMovesNoCurrentMoveWithPreviousMoves = {
  currentMove: [],
  previousMoves: [
    {
      id: 'testMoveID2',
      moveCode: 'SAMPLE',
      orderID: 'testOrderID2',
      status: 'APPROVED',
      orders: {
        id: 'testOrder2',
        NewDutyLocation: {
          id: 'testDDL2',
          name: 'Fort Bragg South Station',
          Address: {
            streetAddress1: '456 Oak St',
            streetAddress2: 'Apartment 8000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90211',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL2',
          name: 'Fort Bragg South Station',
          Address: {
            streetAddress1: '456 Oak St',
            streetAddress2: 'Apartment 8000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90211',
            country: 'USA',
          },
        },
        rank: 'E_7',
        reportByDate: '2024-01-24',
        ordersType: 'PERMANENT_CHANGE_OF_STATION',
        orderNumber: 'ORDER4',
        date_issued: '2021-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
    {
      id: 'testMoveID3',
      moveCode: 'EXAMPL',
      orderID: 'testOrderID3',
      status: 'APPROVED',
      orders: {
        id: 'testOrder3',
        NewDutyLocation: {
          id: 'testDDL3',
          name: 'Fort Bragg East Station',
          Address: {
            streetAddress1: '789 Pine Ave',
            streetAddress2: 'Apartment 7000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90212',
            country: 'USA',
          },
        },
        OriginDutyLocation: {
          id: 'testODL3',
          name: 'Fort Bragg East Station',
          Address: {
            streetAddress1: '789 Pine Ave',
            streetAddress2: 'Apartment 7000',
            streetAddress3: '',
            city: 'Anytown',
            state: 'AL',
            postalCode: '90212',
            country: 'USA',
          },
        },
        rank: 'E_6',
        reportByDate: '2024-01-26',
        ordersType: 'PERMANENT_CHANGE_OF_STATION',
        orderNumber: 'ORDER5',
        date_issued: '2018-01-01',
      },
      mtoShipments: [
        {
          id: 'shipment1',
          shipmentType: 'HHG',
          status: 'APPROVED',
          created_at: '2024-01-03 15:28:28.468 -0600',
        },
        {
          id: 'shipment2',
          shipmentType: 'PPM',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment3',
          shipmentType: 'HHG_INTO_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment4',
          shipmentType: 'HHG_OUTOF_NTS_DOMESTIC',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment5',
          shipmentType: 'MOTORHOME',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_HAUL_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
        {
          id: 'shipment6',
          shipmentType: 'BOAT_TOW_AWAY',
          status: 'APPROVED',
          created_at: '2024-01-05 15:28:28.468 -0600',
        },
      ],
    },
  ],
};

export const mockMovesNoCurrentOrPreviousMoves = {
  currentMove: [],
  previousMoves: [],
};

export default {
  mockMovesPCS,
  mockMovesRetirement,
  mockMovesSeparation,
  mockMovesNoPreviousMoves,
  mockMovesNoCurrentMoveWithPreviousMoves,
  mockMovesNoCurrentOrPreviousMoves,
};
