// Package oapi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package oapi

import (
	"time"
)

// createMoveOrderJSONBody defines parameters for CreateMoveOrder.
type createMoveOrderJSONBody struct {
	CreatedAt                    *time.Time `json:"created_at,omitempty"`
	DeletedAt                    *time.Time `json:"deleted_at,omitempty"`
	DestinationDutyStation       *string    `json:"destination_duty_station,omitempty"`
	DestinationPpso              *string    `json:"destination_ppso,omitempty"`
	ElectronicCopyOfOrders       *string    `json:"electronic_copy_of_orders,omitempty"`
	Id                           *string    `json:"id,omitempty"`
	LineOfAccounting             *string    `json:"line_of_accounting,omitempty"`
	MoveDate                     *time.Time `json:"move_date,omitempty"`
	OrdersType                   *string    `json:"orders_type,omitempty"`
	OriginDutyStation            *string    `json:"origin_duty_station,omitempty"`
	OriginPpso                   *string    `json:"origin_ppso,omitempty"`
	PaymentMethod                *string    `json:"payment_method,omitempty"`
	Status                       *string    `json:"status,omitempty"`
	Tac                          *string    `json:"tac,omitempty"`
	TravelAuthorizationDate      *time.Time `json:"travel_authorization_date,omitempty"`
	TravelAuthorizationIssuingHq *string    `json:"travel_authorization_issuing_hq,omitempty"`
	TravelAuthorizationName      *string    `json:"travel_authorization_name,omitempty"`
	UpdatedAt                    *time.Time `json:"updated_at,omitempty"`
}

// updateMoveOrderJSONBody defines parameters for UpdateMoveOrder.
type updateMoveOrderJSONBody struct {
	CreatedAt                    *time.Time `json:"created_at,omitempty"`
	DeletedAt                    *time.Time `json:"deleted_at,omitempty"`
	DestinationDutyStation       *string    `json:"destination_duty_station,omitempty"`
	DestinationPpso              *string    `json:"destination_ppso,omitempty"`
	ElectronicCopyOfOrders       *string    `json:"electronic_copy_of_orders,omitempty"`
	Id                           *string    `json:"id,omitempty"`
	LineOfAccounting             *string    `json:"line_of_accounting,omitempty"`
	MoveDate                     *time.Time `json:"move_date,omitempty"`
	OrdersType                   *string    `json:"orders_type,omitempty"`
	OriginDutyStation            *string    `json:"origin_duty_station,omitempty"`
	OriginPpso                   *string    `json:"origin_ppso,omitempty"`
	PaymentMethod                *string    `json:"payment_method,omitempty"`
	Status                       *string    `json:"status,omitempty"`
	Tac                          *string    `json:"tac,omitempty"`
	TravelAuthorizationDate      *time.Time `json:"travel_authorization_date,omitempty"`
	TravelAuthorizationIssuingHq *string    `json:"travel_authorization_issuing_hq,omitempty"`
	TravelAuthorizationName      *string    `json:"travel_authorization_name,omitempty"`
	UpdatedAt                    *time.Time `json:"updated_at,omitempty"`
}

// updateMoveOrderStatusJSONBody defines parameters for UpdateMoveOrderStatus.
type updateMoveOrderStatusJSONBody struct {
	Status *string `json:"status,omitempty"`
}

// createLineItemJSONBody defines parameters for CreateLineItem.
type createLineItemJSONBody struct {
	Id          *string `json:"id,omitempty"`
	MoveOrderId *string `json:"move_order_id,omitempty"`
	Status      *string `json:"status,omitempty"`
}

// updateLineItemStatusJSONBody defines parameters for UpdateLineItemStatus.
type updateLineItemStatusJSONBody struct {
	Status *string `json:"status,omitempty"`
}

// createPaymentRequestJSONBody defines parameters for CreatePaymentRequest.
type createPaymentRequestJSONBody struct {
	IsFinal               *bool     `json:"isFinal,omitempty"`
	MoveOrderId           *string   `json:"moveOrderId,omitempty"`
	MoveOrderLineItemIds  *[]string `json:"moveOrderLineItemIds,omitempty"`
	ProofOfServicePackage *struct {
		Id      *string `json:"id,omitempty"`
		Uploads *[]struct {
			Bytes       int        `json:"bytes"`
			ContentType *string    `json:"contentType,omitempty"`
			CreatedAt   *time.Time `json:"createdAt,omitempty"`
			Filename    string     `json:"filename"`
			Id          string     `json:"id"`
			UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
			Url         string     `json:"url"`
		} `json:"uploads,omitempty"`
	} `json:"proofOfServicePackage,omitempty"`
}

// updatePaymentRequestJSONBody defines parameters for UpdatePaymentRequest.
type updatePaymentRequestJSONBody struct {
	MoveOrderLineItemIds  *[]string `json:"moveOrderLineItemIds,omitempty"`
	ProofOfServicePackage *struct {
		Id      *string `json:"id,omitempty"`
		Uploads *[]struct {
			Bytes       int        `json:"bytes"`
			ContentType *string    `json:"contentType,omitempty"`
			CreatedAt   *time.Time `json:"createdAt,omitempty"`
			Filename    string     `json:"filename"`
			Id          string     `json:"id"`
			UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
			Url         string     `json:"url"`
		} `json:"uploads,omitempty"`
	} `json:"proofOfServicePackage,omitempty"`
}

// updatePaymentRequestStatusJSONBody defines parameters for UpdatePaymentRequestStatus.
type updatePaymentRequestStatusJSONBody struct {
	RejectionReason *string `json:"rejectionReason,omitempty"`
	Status          *string `json:"status,omitempty"`
}

// CreateMoveOrderRequestBody defines body for CreateMoveOrder for application/json ContentType.
type CreateMoveOrderJSONRequestBody createMoveOrderJSONBody

// UpdateMoveOrderRequestBody defines body for UpdateMoveOrder for application/json ContentType.
type UpdateMoveOrderJSONRequestBody updateMoveOrderJSONBody

// UpdateMoveOrderStatusRequestBody defines body for UpdateMoveOrderStatus for application/json ContentType.
type UpdateMoveOrderStatusJSONRequestBody updateMoveOrderStatusJSONBody

// CreateLineItemRequestBody defines body for CreateLineItem for application/json ContentType.
type CreateLineItemJSONRequestBody createLineItemJSONBody

// UpdateLineItemStatusRequestBody defines body for UpdateLineItemStatus for application/json ContentType.
type UpdateLineItemStatusJSONRequestBody updateLineItemStatusJSONBody

// CreatePaymentRequestRequestBody defines body for CreatePaymentRequest for application/json ContentType.
type CreatePaymentRequestJSONRequestBody createPaymentRequestJSONBody

// UpdatePaymentRequestRequestBody defines body for UpdatePaymentRequest for application/json ContentType.
type UpdatePaymentRequestJSONRequestBody updatePaymentRequestJSONBody

// UpdatePaymentRequestStatusRequestBody defines body for UpdatePaymentRequestStatus for application/json ContentType.
type UpdatePaymentRequestStatusJSONRequestBody updatePaymentRequestStatusJSONBody
