package movetaskorder

// Export internal functions for testing.
var IsValidFakeModelAddress = isValidFakeModelAddress
var IsValidFakeModelMTOAgent = isValidFakeModelMTOAgent
var IsValidFakeModelMTOShipment = isValidFakeModelMTOShipment
var IsValidFakeModelServiceMember = isValidFakeModelServiceMember
var IsValidFakeModelBackupContact = isValidFakeModelBackupContact
