codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "50...70"

  status:
    project:
      default: false     # disable the default status that measures entire project
      go:                # declare a new status context "go"
        paths: "pkg/"    # only include coverage in "pkg/" folder
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: yes   # only post a comment if the coverage changes on a PR
