queue_rules:
  - name: default
    conditions:
      - "label=ready-to-merge"

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - "label=ready-to-merge"
    actions:
      queue:
        name: default
