# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  admin: swagger-def/admin.yaml
  ghc: swagger-def/ghc.yaml
  internal: swagger-def/internal.yaml
  orders: swagger-def/orders.yaml
  prime: swagger-def/prime.yaml
  support: swagger-def/support.yaml
lint:
  extends:
    - recommended
referenceDocs:
  htmlTemplate: swagger/index.html
  # NOTE: modifying most theme attributes won't work here - use Redoc.init for standalone instead
