version: '3.3'

services:
  storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    image: milmove_storybook
    working_dir: /home/circleci/project
    ports:
      - '6006:6006'
  storybook_tests:
    image: milmove_storybook
    working_dir: /home/circleci/project
    command: scripts/start-storybook-tests
    environment:
      - CHROME_CONCURRENCY
    depends_on:
      - storybook
