version: '3.3'

services:
  storybook:
    build:
      dockerfile: Dockerfile.storybook_local
    image: milmove_storybook_local
  storybook_tests:
    image: milmove_storybook_local
    environment:
      - CHROME_CONCURRENCY=4
