version: '3.3'

services:
  database:
    image: postgres:12.7
    restart: always
    ports:
      - '6432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=dev_db

  milmove_migrate:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile.migrations_local
    links:
      - database
    environment:
      - DB_ENV=development
      - DB_HOST=database
      - DB_NAME=dev_db
      - DB_PASSWORD=mysecretpassword
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - DB_USER=postgres
      - ENVIRONMENT=test
      - MIGRATION_PATH=file:///migrate/schema;file:///migrate/secure
      - MIGRATION_MANIFEST=/migrate/migrations_manifest.txt
    entrypoint:
      - '/bin/milmove'
      - 'migrate'
    volumes:
      - ./migrations/app/secure:/migrate/secure

  milmove:
    depends_on:
      - database
      - milmove_migrate
    build:
      context: .
      dockerfile: Dockerfile.local
    links:
      - database
    ports:
      - '4000:4000'
      - '9443:9443'
    environment:
      - CLIENT_AUTH_SECRET_KEY
      - CSRF_AUTH_KEY
      - DB_DEBUG=1
      - DB_ENV=development
      - DB_HOST=database
      - DB_NAME=dev_db
      - DB_PASSWORD=mysecretpassword
      - DB_PASSWORD_LOW_PRIV=mysecretpassword
      - DB_PORT=5432
      - DB_REGION=us-west-2
      - DB_RETRY_INTERVAL=5s
      - DB_SSL_MODE=disable
      - DB_USER=postgres
      - DB_USER_LOW_PRIV=crud
      - DEVLOCAL_AUTH=1
      - DEVLOCAL_CA=/config/tls/devlocal-ca.pem
      - DOD_CA_PACKAGE=/config/tls/milmove-cert-bundle.p7b
      - EIA_KEY=db2522a43820268a41a802a16ae9fd26 # dummy key generated with openssl rand -hex 16
      - ENVIRONMENT=test
      - HERE_MAPS_APP_CODE
      - HERE_MAPS_APP_ID
      - HERE_MAPS_GEOCODE_ENDPOINT
      - HERE_MAPS_ROUTING_ENDPOINT
      - HTTP_MY_SERVER_NAME=milmovelocal
      - HTTP_OFFICE_SERVER_NAME=officelocal
      - HTTP_PRIME_SERVER_NAME=primelocal
      - HTTP_PPTAS_SERVER_NAME=pptaslocal
      - IWS_RBS_ENABLED=1
      - IWS_RBS_HOST
      - LOCAL_STORAGE_ROOT=/tmp
      - LOCAL_STORAGE_WEB_ROOT=storage
      - LOGIN_GOV_ADMIN_CLIENT_ID
      - LOGIN_GOV_CALLBACK_PORT=4000
      - LOGIN_GOV_CALLBACK_PROTOCOL
      - LOGIN_GOV_HOSTNAME
      - LOGIN_GOV_MY_CLIENT_ID
      - LOGIN_GOV_OFFICE_CLIENT_ID
      - LOGIN_GOV_SECRET_KEY
      - MOVE_MIL_DOD_CA_CERT
      - MOVE_MIL_DOD_TLS_CERT
      - MOVE_MIL_DOD_TLS_KEY
      - MUTUAL_TLS_ENABLED=1
      - NO_TLS_ENABLED=1
      - NO_TLS_PORT=4000
      - OKTA_CUSTOMER_CLIENT_ID
      - OKTA_ADMIN_CLIENT_ID
      - OKTA_OFFICE_CLIENT_ID
      - OKTA_TENANT_CALLBACK_PORT=4000
      - OKTA_TENANT_CALLBACK_PROTOCOL=http
      - OKTA_OFFICE_GROUP_ID
      - PGPASSWORD=mysecretpassword
      - SERVE_API_GHC=true
      - SERVE_API_INTERNAL=true
      - SERVE_API_PRIME=true
      - SERVE_API_SUPPORT=true
      - STORAGE_BACKEND=local
      - TZ=UTC
    volumes:
      - ./tmp:/tmp
