FROM alpine:3.11.5

COPY bin/generate-test-data /bin/generate-test-data
COPY bin/prime-api-client /bin/prime-api-client

COPY config/tls/ /bin/config/tls/
COPY pkg/testdatagen/testdata/ /bin/pkg/testdatagen/testdata/

# Install tools needed in container
RUN apk update
RUN apk add postgresql-client bash --no-cache

WORKDIR /bin
