version: '3.3'

services:
  database:
    image: postgres:12.7
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=test_db
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: redis:5.0.6

  milmove:
    depends_on:
      - database
      - redis
    networks:
      default:
        aliases:
          - milmovelocal
          - officelocal
          - adminlocal
          - orderslocal
    image: ${MILMOVE_E2E_IMAGE:-milmove_e2e:local}
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/milmove migrate && /bin/generate-test-data --named-scenario='e2e_basic' && /bin/milmove serve"
    environment:
      - APPLICATION=app
      - CLIENT_AUTH_SECRET_KEY
      - CSRF_AUTH_KEY
      - DB_DEBUG=1
      - DB_ENV=development
      - DB_HOST=database
      - DB_NAME=test_db
      - DB_PASSWORD=mysecretpassword
      - DB_PASSWORD_LOW_PRIV=mysecretpassword
      - DB_PORT=5432
      - DB_REGION=us-west-2
      - DB_RETRY_INTERVAL=5s
      - DB_RETRY_MAX=20
      - DB_SSL_MODE=disable
      - DB_USER=postgres
      - DB_USER_LOW_PRIV=crud
      - DEVLOCAL_AUTH=1
      - DEVLOCAL_CA=/config/tls/devlocal-ca.pem
      - DOD_CA_PACKAGE=/config/tls/Certificates_PKCS7_v5.6_DoD.der.p7b
      - EIA_KEY=db2522a43820268a41a802a16ae9fd26 # dummy key generated with openssl rand -hex 16
      - ENVIRONMENT=test
      - HERE_MAPS_APP_CODE
      - HERE_MAPS_APP_ID
      - HERE_MAPS_GEOCODE_ENDPOINT=https://geocoder.api.here.com/6.2/geocode.json
      - HERE_MAPS_ROUTING_ENDPOINT=https://route.api.here.com/routing/7.2/calculateroute.json
      - HTTP_ADMIN_SERVER_NAME=adminlocal
      - HTTP_MY_SERVER_NAME=milmovelocal
      - HTTP_OFFICE_SERVER_NAME=officelocal
      - HTTP_ORDERS_SERVER_NAME=orderslocal
      - HTTP_PRIME_SERVER_NAME=primelocal
      - IWS_RBS_ENABLED=1
      - IWS_RBS_HOST
      - LOCAL_STORAGE_ROOT=/tmp
      - LOCAL_STORAGE_WEB_ROOT=storage
      - LOGIN_GOV_ADMIN_CLIENT_ID
      - LOGIN_GOV_CALLBACK_PORT=4000
      - LOGIN_GOV_CALLBACK_PROTOCOL=http
      - LOGIN_GOV_MY_CLIENT_ID=urn:gov:gsa:openidconnect.profiles:sp:sso:dod:mymovemillocal
      - LOGIN_GOV_OFFICE_CLIENT_ID=urn:gov:gsa:openidconnect.profiles:sp:sso:dod:officemovemillocal
      - LOGIN_GOV_ADMIN_CLIENT_ID=urn:gov:gsa:openidconnect.profiles:sp:sso:dod:adminmovemillocal
      - LOGIN_GOV_HOSTNAME=idp.int.identitysandbox.gov
      - LOGIN_GOV_SECRET_KEY
      - MIGRATION_PATH=file:///migrate/schema;file:///migrate/secure
      - MIGRATION_MANIFEST=/migrate/migrations_manifest.txt
      - MOVE_MIL_DOD_CA_CERT
      - MOVE_MIL_DOD_TLS_CERT
      - MOVE_MIL_DOD_TLS_KEY
      - MUTUAL_TLS_ENABLED=0
      - NO_TLS_ENABLED=1
      - NO_TLS_PORT=4000
      - PGPASSWORD=mysecretpassword
      - REDIS_HOST=redis
      - SERVE_ADMIN=true
      - SERVE_API_GHC=true
      - SERVE_API_INTERNAL=true
      - SERVE_API_PRIME=false
      - SERVE_API_SUPPORT=false
      - SERVE_PRIME_SIMULATOR=true
      - STORAGE_BACKEND=local
      - TLS_ENABLED=1
      - TZ=UTC

# use a custom external network to ensure consistent naming in
# circleci and locally
networks:
  default:
    external: true
    name: e2e_cypress
