FROM gcr.io/distroless/base:latest

COPY bin/rds-combined-ca-bundle.pem /bin/rds-combined-ca-bundle.pem
COPY bin/rds-ca-2019-root.pem /bin/rds-ca-2019-root.pem
COPY bin/milmove-tasks /bin/milmove-tasks

WORKDIR /bin
