FROM milmove/circleci-docker:milmove-cypress

COPY . ./cypress
COPY cypress.json ./cypress.json
COPY mocha-reporter-config.json ./mocha-reporter-config.json

USER root
RUN chown -R circleci:circleci ./cypress cypress.json mocha-reporter-config.json
USER circleci

ENTRYPOINT ["./node_modules/.bin/cypress"]
CMD ["run"]
