FROM milmove/circleci-docker:milmove-cypress-481405e80a3b6c4ef69c3699ce05b16403da1690

COPY --chown=circleci:circleci . /home/circleci/cypress

COPY --chown=circleci:circleci cypress.json /home/circleci/cypress.json

COPY --chown=circleci:circleci mocha-reporter-config.json /home/circleci/mocha-reporter-config.json
