service: aws-get-file

provider:
  name: aws
  region: us-west-2
  deploymentBucket: transcom-ppp-third-party-artifacts
  runtime: go1.x
  environment:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_REGION: ${env:AWS_REGION}
    VERBOSE: true
    STORAGE_BACKEND: s3
    AWS_S3_BUCKET_NAME: "transcom-ppp-app-devlocal-us-west-2"
    AWS_S3_REGION: "us-west-2"
    AWS_S3_KEY_NAMESPACE: "matthewkrump"
    DB_ENV: "development"

  package:
    exclude:
      - ./**
    include:
      - ./get-file-lambda

functions:
  get-file:
    handler: ./get-file-lambda
    memorySize: 256
    role: "arn:aws:iam::923914045601:role/lamda-serverless-get_file-experimental"
