service: aws-get-file

provider:
  name: aws
  region: us-west-2
  deploymentBucket: transcom-ppp-third-party-artifacts
  runtime: go1.x
#  environment:
#    AWS_PROFILE: ${env:AWS_PROFILE}
#    VERBOSE: true
#    S3_REGION: "us-west-2"
#    S3_BUCKET: "transcom-ppp-app-devlocal-us-west-2"
#    S3_KEY_NAMESPACE: "matthewkrump"
#    DB_ENV: "development"

  package:
    exclude:
      - ./**
    include:
      - ./get-file-lambda

functions:
  get-file:
    handler: ./get-file-lambda
    memorySize: 256
    role: "arn:aws:iam::923914045601:role/lamda-serverless-get_file-experimental"
