swagger: '2.0'
info:
  description: The public API for my.move.mil. This is a work in-progress, and is not a final product. We will be continuously updating this site based on feedback.
  version: 0.0.1
  title: my.move.mil
  license:
    name: MIT
    url: https://github.com/transcom/mymove/blob/main/LICENSE.md
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
definitions:
  TSP:
    type: object
    description: The primary definition of a Transport Service Provider
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      name:
        type: string
        example: Moving Company, Inc.
        minLength: 1
        maxLength: 1024
      scac:
        type: string
        description: The SCAC associated with the TSP
        format: '^[A-Z]{2,4}$'
        example: USPS
      contact_email:
        type: string
        format: x-email
        pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        example: john_bob@example.com
paths:
  /tsps:
    get:
      summary: List all TSPs
      description: Gets a list of all the TSPs which the logged in user has access to.
      operationId: indexTSPs
      tags:
        - tsps
      x-access: Access to this endpoint is restricted to members of the Admin, Transcom & JPPSO user groups
      responses:
        200:
          description: list of TSPs
          schema:
            type: array
            items:
              $ref: '#/definitions/TSP'
        400:
          description: invalid request
        401:
          description: must be authenticated to access this endpoint
        500:
          description: server error
