swagger: '2.0'
info:
  description: The public API for my.move.mil
  version: 0.0.1
  title: my.move.mil
  contact:
    email: ppp@truss.works
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /tsp:
    get:
      summary: List all TSPs
      description: Gets a list of all TSPs registered.
      operationId: indexTSPs
      x-access: Access to this endpoint is restricted to members of the Admin, Transcom & JPPSO user groups
      responses:
        200:
          description: list of TSPs
          schema:
            type: array
            items:
              $ref: '#/definitions/TSP'
        400:
          description: invalid request
        403:
          description: not authorized to get list of TSPs
  /tsp/{tspUUID}/shipments:
    get:
      summary: Retreive shipments associated with a TSP
      description: Gets a list of all shipments associated with a TSP. Shipments can be restricted to be in a certain state, e.g. AWARDED
      operationId: tspShipments
      x-access: Access to this endpoint is restricted to members of the Admin, Transcom and JPPSO user groups along with the agents of the TSP.
      parameters:
        - name: tspUUID
          in: path
          type: string
          format: uuid
          required: true
          description: UUID of the TSP
        - name: status
          in: query
          type: string
          required: false
          description: Status of shipments to load, e.g. AWARDED
      responses:
        200:
          description: list of associated shipments
          schema:
            type: array
            items:
              $ref: '#/definitions/Shipment'
        400:
          description: invalid request
        403:
          description: not authorized to get list of TSPs

definitions:
  TSP:
    type: object
    description: The primary definition of a Transport Service Provider
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      name:
        type: string
        example: Name of the TSP
        minLength: 1
        maxLength: 1024
      contact_email:
        type: string
        format: email
  Shipment:
    type: object
    description: A shipment which may be awarded to a TSP
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      status:
        $ref: '#/definitions/ShipmentStatus'
      customer:
        $ref: '#/definitions/Customer'
      dates:
        $ref: '#/definitions/ShipmentDates'
      estimated_weight:
        type: integer
        description: Estimated weight of the shipment in lbs
        example: 500
      type:
        $ref: '#/definitions/ShipmentType'
      market:
        $ref: '#/definitions/ShipmentMarket'
      channel:
        $ref: '#/definitions/Channel'
      origin_gbloc:
        $ref: '#/definitions/GBLOC'
      destination_gbloc:
        $ref: '#/definitions/GBLOC'
      primary_pickup:
        $ref: '#/definitions/Address'
      secondary_pickup:
        $ref: '#/definitions/Address'
      primary_delivery:
        $ref: '#/definitions/Address'
      secondary_delivery:
        $ref: '#/definitions/Address'
  Customer:
    type: object
    description: The person moving
    properties:
      given_name:
        type: string
        example: Mary
      family_name:
        type: string
        example: Johnson
  ShipmentStatus:
    type: string
    description: The stages in the lifecycle of a Shipment
    enum:
      - IN_PROGRESS
      - COMPLETE
      - AWARDED
      - ACCEPTED
      - REJECTED
      - IN_TRANSIT
      - SIT_ORIGIN
      - SIT_DEST
      - DELIVERED
      - COMPLETED
      - CLAIMS
  ShipmentDates:
    type: object
    description: The various dates associated with a shipment
    properties:
      requested_pack:
        type: string
        format: date
        example: 2018-03-15
      requested_pickup:
        type: string
        format: date
        example: 2018-03-15
      requested_latest_pickup:
        type: string
        format: date
        example: 2018-03-15
      requested_delivery:
        type: string
        format: date
        example: 2018-03-15
      planned_pack:
        type: string
        format: date
        example: 2018-03-15
      planned_pickup:
        type: string
        format: date
        example: 2018-03-15
      planned_latest_pickup:
        type: string
        format: date
        example: 2018-03-15
      planned_delivery:
        type: string
        format: date
        example: 2018-03-15
      scheduled_delivery:
        type: string
        format: date
        example: 2018-03-15
      required_delivery:
        type: string
        format: date
        example: 2018-03-15
      actual_pack:
        type: string
        format: date
        example: 2018-03-15
      actual_pickup:
        type: string
        format: date
        example: 2018-03-15
      actual_delivery:
        type: string
        format: date
        example: 2018-03-15
  ShipmentType:
    type: string
    description: The type of a shipment
    example: HHG
    enum: # Todo(Nick) - There may be more of these
      - HHG
      - PPM
  ShipmentMarket:
    type: string
    description: One of the possible 'Markets' for a shipment (see ?????)
    example: dHHG
    enum: # Todo(nick) - There may be more of these
      - dHHG
      - iHHG
      - iUB
  GBLOC:
    type: string
    description: Office Codes for Transcom offices originating GBLs
    example: LHNQ
    pattern: '^[A-Z]{4}$'
  Channel:
    type: object
    description: The channel (pickup location & destination region)
    properties:
      origin:
        type: string
        enum: # Add other values
          - US49
        example: US49
      destination:
        type: string
        enum: # Add other values
          - REGION_6
        example: REGION_6
  PreMoveSurvey:
    type: object
    description: A shipment which may be awarded to a TSP
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      shipment_id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
  Claim:
    type: object
    description: A claim resulting from an earlier shipment
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      shipment_id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      claim_date:
        type: string
        format: date
        example: 2018-03-15
      description:
        type: string
        example: "During shipment the Grandfather clock was dropped resulting in a break to the glass in front of the face"
  Address:
    type: object
    properties:
      street_address_1:
        type: string
        example: 123 Main Ave
        title: Address Line 1
      street_address_2:
        type: string
        example: Apartment 9000
        x-nullable: true
        title: Address Line 2
      city:
        type: string
        example: Anytown
        title: City
      state:
        title: State
        type: string
        x-display-value:
          AL: AL
          AK: AK
          AZ: AZ
          AR: AR
          CA: CA
          CO: CO
          CT: CT
          DE: DE
          DC: DC
          FL: FL
          GA: GA
          HI: HI
          ID: ID
          IL: IL
          IN: IN
          IA: IA
          KS: KS
          KY: KY
          LA: LA
          ME: ME
          MD: MD
          MA: MA
          MI: MI
          MN: MN
          MS: MS
          MO: MO
          MT: MT
          NE: NE
          NV: NV
          NH: NH
          NJ: NJ
          NM: NM
          NY: NY
          NC: NC
          ND: ND
          OH: OH
          OK: OK
          OR: OR
          PA: PA
          RI: RI
          SC: SC
          SD: SD
          TN: TN
          TX: TX
          UT: UT
          VT: VT
          VA: VA
          WA: WA
          WV: WV
          WI: WI
          WY: WY
        enum:
          - AL
          - AK
          - AZ
          - AR
          - CA
          - CO
          - CT
          - DE
          - DC
          - FL
          - GA
          - HI
          - ID
          - IL
          - IN
          - IA
          - KS
          - KY
          - LA
          - ME
          - MD
          - MA
          - MI
          - MN
          - MS
          - MO
          - MT
          - NE
          - NV
          - NH
          - NJ
          - NM
          - NY
          - NC
          - ND
          - OH
          - OK
          - OR
          - PA
          - RI
          - SC
          - SD
          - TN
          - TX
          - UT
          - VT
          - VA
          - WA
          - WV
          - WI
          - WY
      zip:
        type: string
        title: ZIP/Postal Code
        example: "90210"
        pattern: '^(\d{5}([\-]\d{4})?)$'
    required:
    - street_address_1
    - city
    - state
    - zip
