swagger: '2.0'
info:
  description: MyMove API for DPS
  version: '0.1.0'
  title: MyMove DPS API
  license:
    name: MIT
    url: https://github.com/transcom/mymove/blob/master/LICENSE.md
basePath: /dps/v0
produces:
  - application/json
consumes:
  - application/json
definitions:
  Affiliation:
    type: string
    x-nullable: true
    title: Branch of service
    enum: &AFFILIATION
      - Army
      - Navy
      - Marines
      - Air Force
      - Coast Guard
      - Other
  AuthenticationUserPayload:
    type: object
    properties:
      login_gov_id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      social_security_number:
        type: string
        format: ssn
        pattern: '^\d{9}$'
        example: 666555555
      first_name:
        type: string
        example: John
      middle_name:
        type: string
        example: L.
        x-nullable: true
      last_name:
        type: string
        example: Donut
      suffix:
        type: string
        example: Jr.
        x-nullable: true
      telephone:
        type: string
        format: telephone
        example: 212-555-5555
        x-nullable: true
      email:
        type: string
        format: x-email
        pattern: "^[a-zA-Z0-9.!#$%&'*+/=?^_{|}~-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
        example: john_bob@example.com
      affiliation:
        $ref: '#/definitions/Affiliation'
paths:
  /authentication/user:
    get:
      summary: Retrieve user information given the authentication cookie provided by MyMove
      description: Returns user information necessary for registration and login
      operationId: getUser
      tags:
        - dps
      parameters:
        - name: token
          in: query
          type: string
          description: The value of the authentication cookie set by MyMove
          required: true
      responses:
        200:
          description: Successful
          schema:
            $ref: '#/definitions/AuthenticationUserPayload'
        400:
          description: Bad request
        401:
          description: Must be authenticated to use this endpoint
        404:
          description: Not found
        500:
          description: Server error
