swagger: '2.0'
info:
  title: MilMove PPTAS API
  version: 0.0.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    email: milmove-developers@caci.com
  description: >
    The PPTAS API is a RESTful API that enables the Navy's PPTAS system to
    request

    information relating to current moves in progress.


    All endpoints are located at `/pptas/v1`.
basePath: /pptas/v1
host: primelocal
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
tags:
  - name: moves
paths:
  /moves:
    get:
      summary: PPTASReports
      description: >
        Gets all reports that have been approved. Based on payment requests,
        includes data from Move, Shipments, Orders, and Transportation
        Accounting Codes and Lines of Accounting.
      operationId: pptasReports
      tags:
        - moves
      produces:
        - application/json
      parameters:
        - in: query
          name: since
          type: string
          format: date-time
          description: >-
            Only return moves updated since this time. Formatted like
            "2021-07-23T18:30:47.116Z"
      responses:
        '200':
          description: >-
            Successfully retrieved pptas reports. A successful fetch might still
            return zero pptas reports.
          schema:
            $ref: '#/definitions/PPTASReports'
        '401':
          $ref: '#/responses/PermissionDenied'
        '403':
          $ref: '#/responses/PermissionDenied'
        '500':
          $ref: '#/responses/ServerError'
definitions:
  Affiliation:
    type: string
    x-nullable: true
    title: Branch of service
    description: Military branch of service
    enum:
      - ARMY
      - NAVY
      - MARINES
      - AIR_FORCE
      - COAST_GUARD
      - SPACE_FORCE
      - NAVY_AND_MARINES
      - AIR_AND_SPACE_FORCE
      - OTHER
    x-display-value:
      ARMY: Army
      NAVY: Navy
      MARINES: Marine Corps
      AIR_FORCE: Air Force
      COAST_GUARD: Coast Guard
      SPACE_FORCE: Space Force
      OTHER: OTHER
  Address:
    description: A postal address
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      streetAddress1:
        type: string
        example: 123 Main Ave
        title: Street address 1
      streetAddress2:
        type: string
        example: Apartment 9000
        x-nullable: true
        title: Street address 2
      streetAddress3:
        type: string
        example: Montmârtre
        x-nullable: true
        title: Address Line 3
      city:
        type: string
        example: Anytown
        title: City
      eTag:
        type: string
        readOnly: true
      state:
        title: State
        type: string
        x-display-value:
          AL: AL
          AK: AK
          AR: AR
          AZ: AZ
          CA: CA
          CO: CO
          CT: CT
          DC: DC
          DE: DE
          FL: FL
          GA: GA
          HI: HI
          IA: IA
          ID: ID
          IL: IL
          IN: IN
          KS: KS
          KY: KY
          LA: LA
          MA: MA
          MD: MD
          ME: ME
          MI: MI
          MN: MN
          MO: MO
          MS: MS
          MT: MT
          NC: NC
          ND: ND
          NE: NE
          NH: NH
          NJ: NJ
          NM: NM
          NV: NV
          NY: NY
          OH: OH
          OK: OK
          OR: OR
          PA: PA
          RI: RI
          SC: SC
          SD: SD
          TN: TN
          TX: TX
          UT: UT
          VA: VA
          VT: VT
          WA: WA
          WI: WI
          WV: WV
          WY: WY
        enum:
          - AL
          - AK
          - AR
          - AZ
          - CA
          - CO
          - CT
          - DC
          - DE
          - FL
          - GA
          - HI
          - IA
          - ID
          - IL
          - IN
          - KS
          - KY
          - LA
          - MA
          - MD
          - ME
          - MI
          - MN
          - MO
          - MS
          - MT
          - NC
          - ND
          - NE
          - NH
          - NJ
          - NM
          - NV
          - NY
          - OH
          - OK
          - OR
          - PA
          - RI
          - SC
          - SD
          - TN
          - TX
          - UT
          - VA
          - VT
          - WA
          - WI
          - WV
          - WY
      postalCode:
        type: string
        format: zip
        title: ZIP
        example: '90210'
        pattern: ^(\d{5}([\-]\d{4})?)$
      country:
        type: string
        title: Country
        x-nullable: true
        example: USA
        default: USA
      county:
        type: string
        title: County
        x-nullable: true
        example: LOS ANGELES
      isOconus:
        type: boolean
        title: isOconus
        x-nullable: true
        example: false
    required:
      - streetAddress1
      - city
      - state
      - postalCode
  DimensionType:
    description: Describes a dimension type for a MTOServiceItemDimension.
    type: string
    enum:
      - ITEM
      - CRATE
  MTOServiceItemDimension:
    description: Describes a dimension object for the MTOServiceItem.
    type: object
    properties:
      id:
        example: 1f2270c7-7166-40ae-981e-b200ebdf3054
        format: uuid
        type: string
      type:
        $ref: '#/definitions/DimensionType'
      length:
        description: Length in thousandth inches. 1000 thou = 1 inch.
        example: 1000
        type: integer
        format: int32
      width:
        description: Width in thousandth inches. 1000 thou = 1 inch.
        example: 1000
        type: integer
        format: int32
      height:
        description: Height in thousandth inches. 1000 thou = 1 inch.
        example: 1000
        type: integer
        format: int32
  Crate:
    description: Crate object for PPTAS Reports
    type: object
    properties:
      itemDimensions:
        $ref: '#/definitions/MTOServiceItemDimension'
      crateDimensions:
        $ref: '#/definitions/MTOServiceItemDimension'
      description:
        type: string
    x-nullable: true
  PPTASShipment:
    description: |
      Shipment definition used for PPTAS reports.
    properties:
      originAddress:
        $ref: '#/definitions/Address'
      destinationAddress:
        $ref: '#/definitions/Address'
      travelAdvance:
        type: number
        format: double
        x-nullable: true
      moveDate:
        type: string
        format: date
        x-nullable: true
      fiscalYear:
        type: string
        x-nullable: true
      appro:
        description: Appropriation
        type: string
        x-nullable: true
      subhead:
        description: LoaObjClsID in lines_of_accounting
        type: string
        x-nullable: true
      objClass:
        description: LoaAlltSnID in lines_of_accounting
        type: string
        x-nullable: true
      bcn:
        description: LoaSbaltmtRcpntID in lines_of_accounting
        type: string
        x-nullable: true
      subAllotCD:
        description: LoaInstlAcntgActID in lines_of_accounting
        type: string
        x-nullable: true
      aaa:
        description: LoaTrnsnID in lines_of_accounting
        type: string
        x-nullable: true
      typeCD:
        description: LoaJbOrdNm in lines_of_accounting
        type: string
        x-nullable: true
      paa:
        description: LoaDocID in lines_of_accounting
        type: string
        x-nullable: true
      costCD:
        description: LoaPgmElmntID in lines_of_accounting
        type: string
        x-nullable: true
      ddcd:
        description: LoaDptID in lines_of_accounting
        type: string
        x-nullable: true
      weightEstimate:
        description: Total weight estimate
        type: number
        format: double
        x-nullable: true
      dd2278IssueDate:
        description: Counseling Date
        type: string
        format: date
      miles:
        type: integer
      shipmentId:
        type: string
        format: uuid
      loa:
        description: Line of Accounting
        type: string
        x-nullable: true
      shipmentType:
        type: string
      netWeight:
        type: integer
        x-nullable: true
      pbpAnde:
        description: Pro Gear
        type: number
        format: double
        x-nullable: true
      pickupDate:
        type: string
        format: date
      sitInDate:
        description: Storage in Transit In Date
        type: string
        format: date
        x-nullable: true
      sitOutDate:
        description: Storage in Transit Out Date
        type: string
        format: date
        x-nullable: true
      sitType:
        description: Storage in Transit type
        example: Destination
        type: string
        x-nullable: true
      paidDate:
        type: string
        format: date
        x-nullable: true
      linehaulTotal:
        type: number
        format: double
        x-nullable: true
      linehaulFuelTotal:
        type: number
        format: double
        x-nullable: true
      originPrice:
        type: number
        format: double
        x-nullable: true
      destinationPrice:
        type: number
        format: double
        x-nullable: true
      packingPrice:
        type: number
        format: double
        x-nullable: true
      unpackingPrice:
        type: number
        format: double
        x-nullable: true
      sitOriginFirstDayTotal:
        description: First day of Origin Storage in Transit cost
        type: number
        format: double
        x-nullable: true
      sitOriginAddlDaysTotal:
        description: Additional day of Origin Storage in Transit cost
        type: number
        format: double
        x-nullable: true
      sitDestFirstDayTotal:
        description: First day of Destination Storage in Transit cost
        type: number
        format: double
        x-nullable: true
      sitDestAddlDaysTotal:
        description: Additional day of Destination Storage in Transit cost
        type: number
        format: double
        x-nullable: true
      sitPickupTotal:
        description: Storage in Transit pickup total cost
        type: number
        format: double
        x-nullable: true
      sitDeliveryTotal:
        description: Storage in Transit delivery total cost
        type: number
        format: double
        x-nullable: true
      sitOriginFuelSurcharge:
        description: Storage in Transit origin fuel total cost
        type: number
        format: double
        x-nullable: true
      sitDestFuelSurcharge:
        description: Storage in Transit destination total cost
        type: number
        format: double
        x-nullable: true
      cratingTotal:
        type: number
        format: double
        x-nullable: true
      uncratingTotal:
        type: number
        format: double
        x-nullable: true
      cratingDimensions:
        type: array
        items:
          $ref: '#/definitions/Crate'
      shuttleTotal:
        type: number
        format: double
        x-nullable: true
      moveManagementFeeTotal:
        type: number
        format: double
        x-nullable: true
      counselingFeeTotal:
        type: number
        format: double
        x-nullable: true
      invoicePaidAmt:
        description: Invoice Paid Amounts
        type: number
        format: double
        x-nullable: true
      ppmLinehaul:
        description: Personally Procured Move Linehaul total cost
        type: number
        format: double
        x-nullable: true
      ppmFuelRateAdjTotal:
        description: Personally Procured Move Fuel Rate Adjusted total cost
        type: number
        format: double
        x-nullable: true
      ppmOriginPrice:
        type: number
        format: double
        x-nullable: true
      ppmDestPrice:
        type: number
        format: double
        x-nullable: true
      ppmPacking:
        type: number
        format: double
        x-nullable: true
      ppmUnpacking:
        type: number
        format: double
        x-nullable: true
      ppmStorage:
        type: number
        format: double
        x-nullable: true
      ppmTotal:
        type: number
        format: double
        x-nullable: true
      deliveryDate:
        type: string
        format: date
      actualOriginNetWeight:
        type: number
        format: double
        x-nullable: true
      destinationReweighNetWeight:
        type: number
        format: double
        x-nullable: true
  PPTASReport:
    description: >
      Report for Navy PPTAS, contains information about Service Members, Orders,
      Move Task Orders, Shipments, and Payment Requests.
    type: object
    properties:
      firstName:
        example: Bob
        type: string
      lastName:
        example: Job
        type: string
      middleInitial:
        example: G
        type: string
        x-nullable: true
      affiliation:
        $ref: '#/definitions/Affiliation'
      payGrade:
        type: string
        x-nullable: true
        title: grade
        enum:
          - E_1
          - E_2
          - E_3
          - E_4
          - E_5
          - E_6
          - E_7
          - E_8
          - E_9
          - E_9_SPECIAL_SENIOR_ENLISTED
          - O_1_ACADEMY_GRADUATE
          - O_2
          - O_3
          - O_4
          - O_5
          - O_6
          - O_7
          - O_8
          - O_9
          - O_10
          - W_1
          - W_2
          - W_3
          - W_4
          - W_5
          - AVIATION_CADET
          - CIVILIAN_EMPLOYEE
          - ACADEMY_CADET
          - MIDSHIPMAN
        x-display-value:
          E_1: E-1
          E_2: E-2
          E_3: E-3
          E_4: E-4
          E_5: E-5
          E_6: E-6
          E_7: E-7
          E_8: E-8
          E_9: E-9
          E_9_SPECIAL_SENIOR_ENLISTED: E-9 (Special Senior Enlisted)
          O_1_ACADEMY_GRADUATE: O-1 or Service Academy Graduate
          O_2: O-2
          O_3: O-3
          O_4: O-4
          O_5: O-5
          O_6: O-6
          O_7: O-7
          O_8: O-8
          O_9: O-9
          O_10: O-10
          W_1: W-1
          W_2: W-2
          W_3: W-3
          W_4: W-4
          W_5: W-5
          AVIATION_CADET: Aviation Cadet
          CIVILIAN_EMPLOYEE: Civilian Employee
          ACADEMY_CADET: Service Academy Cadet
          MIDSHIPMAN: Midshipman
      edipi:
        type: string
      phonePrimary:
        type: string
      phoneSecondary:
        type: string
        x-nullable: true
      emailPrimary:
        example: a@b.com
        type: string
      emailSecondary:
        type: string
        x-nullable: true
      address:
        $ref: '#/definitions/Address'
      ordersType:
        type: string
      ordersNumber:
        type: string
      ordersDate:
        type: string
        format: date-time
      originGbloc:
        type: string
        pattern: ^[A-Z]{4}$
        x-nullable: true
      destinationGbloc:
        type: string
        pattern: ^[A-Z]{4}$
        x-nullable: true
      scac:
        example: AGFM
        type: string
        x-nullable: true
      transmitCD:
        description: Transmit Code
        type: string
        x-nullable: true
      tac:
        description: Transportation Accounting Code
        type: string
        x-nullable: true
      shipmentNum:
        description: Number of shipments
        type: integer
      depCD:
        description: Dependent Code
        type: boolean
        x-nullable: true
      weightAuthorized:
        type: number
        format: double
        x-nullable: true
      entitlementWeight:
        type: integer
        x-nullable: true
      counseledDate:
        type: string
        format: date
      orderNumber:
        description: not to be confused with Orders Number
        type: string
        example: 030-00362
        x-nullable: true
      travelType:
        description: Travel Type
        example: Shipment of HHG Permitted
        type: string
      travelClassCode:
        example: PCS
        type: string
      financialReviewFlag:
        type: boolean
        x-nullable: true
      financialReviewRemarks:
        type: string
        x-nullable: true
      shipments:
        type: array
        items:
          $ref: '#/definitions/PPTASShipment'
  PPTASReports:
    type: array
    items:
      $ref: '#/definitions/PPTASReport'
  ClientError:
    type: object
    properties:
      title:
        type: string
      detail:
        type: string
      instance:
        type: string
        format: uuid
    required:
      - title
      - detail
      - instance
responses:
  PermissionDenied:
    description: The request was denied.
    schema:
      $ref: '#/definitions/ClientError'
  ServerError:
    description: An unexpected error has occurred in the server.
    schema:
      $ref: '#/definitions/ClientError'
