openapi: 3.0.2

info:
  title: move.mil API
  description: The API for move.mil
  #  termsOfService:
  contact:
    email: dp3@truss.works
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.0.1

servers:
  - url: http://api.move.mil/v1
    description: Production server
  - url: http://staging-api.move.mil/v1
    description: Staging server
  - url: http://experimental-api.move.mil/v1
    description: Experimental server

paths:
  # Move Task Orders Endpoints
  /move-task-orders:
    $ref: './paths/move-task-orders.yaml#/MoveTaskOrders'
  /move-task-orders/{moveTaskOrderID}:
    $ref: './paths/move-task-orders.yaml#/MoveTaskOrder'
  /move-task-orders/{moveTaskOrderID}/status:
    $ref: './paths/move-task-orders.yaml#/MoveTaskOrderStatus'
  /move-task-orders/{moveTaskOrderID}/service-items:
    $ref: './paths/move-task-orders.yaml#/ServiceItems'
  /move-task-orders/{moveTaskOrderID}/service-items/{serviceItemID}:
    $ref: './paths/move-task-orders.yaml#/ServiceItem'
  /move-task-orders/{moveTaskOrderID}/service-items/{serviceItemID}/status:
    $ref: './paths/move-task-orders.yaml#/ServiceItemStatus'

  # Payment Request Endpoints
  /payment-requests:
    $ref: './paths/payment-requests.yaml#/PaymentRequests'
  /payment-requests/{paymentRequestID}:
    $ref: './paths/payment-requests.yaml#/PaymentRequest'
  /payment-requests/{paymentRequestID}/status:
    $ref: './paths/payment-requests.yaml#/PaymentRequestStatus'
