openapi: 3.0.2

info:
  title: move.mil GHC API
  description: The API for the GHC Prime to interact with move.mil
  #  termsOfService:
  contact:
    email: dp3@truss.works
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.0.1

# servers:

paths:
  /payment-requests:
    post:
      summary: Creates a payment request
      description: Creates a payment request
      operationId: createPaymentRequest
      tags:
        - payment-requests
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequestPayload'
      responses:
        '201':
          description: created instance of payment request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentRequest'
        400:
          $ref: '#/components/responses/InvalidRequest'
        401:
          $ref: '#/components/responses/PermissionDenied'
        403:
          $ref: '#/components/responses/PermissionDenied'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
    get: # TODO add filters when we know what we are filtering
      summary: Gets payment requests
      description: Gets a list of payment requests
      operationId: getPaymentRequests
      tags:
        - payment-requests
      responses:
        '200':
          description: fetched list of payment requests
          content:
            application/json:
              schema:
                type: object # in order to include meta data, plus list
        400:
          $ref: '#/components/responses/InvalidRequest'
        401:
          $ref: '#/components/responses/PermissionDenied'
        403:
          $ref: '#/components/responses/PermissionDenied'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
  /payment-requests/{paymentRequestId}:
    get:
      summary: Fetches a payment request
      description: Fetches an instance of a payment request
      operationId: fetchPaymentRequest
      tags:
        - payment-requests
      parameters:
        - name: paymentRequestId
          in: path
          description: UUID of payment request
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: fetched instance of payment request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentRequest'
        400:
          $ref: '#/components/responses/InvalidRequest'
        401:
          $ref: '#/components/responses/PermissionDenied'
        403:
          $ref: '#/components/responses/PermissionDenied'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
    patch: # GHC can mark final- could be its own endpoint
      summary: Updates a payment request
      description: Updates a payment request
      operationId: updatePaymentRequest
      tags:
        - payment-requests
      parameters:
        - name: paymentRequestId
          in: path
          description: UUID of payment request
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePaymentRequestPayload'
        required: true
      responses:
        '200':
          description: updated payment request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentRequest'
        400:
          $ref: '#/components/responses/InvalidRequest'
        401:
          $ref: '#/components/responses/PermissionDenied'
        403:
          $ref: '#/components/responses/PermissionDenied'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
  /uploads:
    post:
      summary: Create a new upload
      description: Uploads represent a single digital file, such as a JPEG or PDF.
      operationId: createUpload
      tags:
        - uploads
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateUploadPayload'
      responses:
        201:
          description: created upload
          content:
            multipart/form-data:
              schema:
                $ref: '#/components/schemas/Upload'
        400:
          $ref: '#/components/responses/InvalidRequest'
        401:
          $ref: '#/components/responses/PermissionDenied'
        403:
          $ref: '#/components/responses/PermissionDenied'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
  /uploads/{uploadId}:
    get:
      summary: Fetches upload
      description: Fetches an upload by id
      operationId: upload
      parameters:
        - name: uploadId
          in: path
          description: upload id
          required: true
          schema:
            type: string
            format: uuid
      tags:
        - uploads
      responses:
        200:
          description: created upload
          content:
            multipart/form-data:
              schema:
                $ref: '#/components/schemas/Upload'
        400:
          $ref: '#/components/responses/InvalidRequest'
        401:
          $ref: '#/components/responses/PermissionDenied'
        403:
          $ref: '#/components/responses/PermissionDenied'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'

components:
  schemas: # These are guesses at what values will be needed; need to know which fields are required
    PaymentRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: c56a4180-65aa-42ec-a945-5fd21dec0538
          readOnly: true
        documentPackage:
          $ref: '#/components/schemas/ProofOfServicePackage'
        taskOrderId:
          type: string
          format: uuid
          example: c56a4180-65aa-42ec-a945-5fd21dec0538
        taskOrderLineItemIds:
          type: array
          items:
            type: string
            format: uuid
            example: c56a4180-65aa-42ec-a945-5fd21dec0538
        isFinal:
          type: boolean
          default: false
        status:
          $ref: '#/components/schemas/PaymentRequestStatus'
        paymentRejectionReason:
          type: string
          example: documentation was incomplete
          nullable: true
        invoiceRejectionReason:
          type: string
          example: documentation was incomplete
          nullable: true
    CreatePaymentRequestPayload:
      type: object
      properties:
        proofOfServicePackage:
          $ref: '#/components/schemas/ProofOfServicePackage'
        taskOrderId:
          type: string
          format: uuid
          example: c56a4180-65aa-42ec-a945-5fd21dec0538
        taskOrderLineItemIds:
          type: array
          items:
            type: string
            format: uuid
            example: c56a4180-65aa-42ec-a945-5fd21dec0538
        isFinal:
          type: boolean
          default: false
        status:
          $ref: '#/components/schemas/PaymentRequestStatus'
    UpdatePaymentRequestPayload:
      type: object
      properties:
        taskOrderLineItemIds:
          type: array
          items:
            type: string
            format: uuid
            example: c56a4180-65aa-42ec-a945-5fd21dec0538
        proofOfServicePackage:
          $ref: '#/components/schemas/ProofOfServicePackage'
        isFinal:
          type: boolean
          default: false
        status:
          $ref: '#/components/schemas/PaymentRequestStatus'
    ProofOfServicePackage: # Need more info on what a ProofOfServicePackage is, what is in it
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: c56a4180-65aa-42ec-a945-5fd21dec0538
        uploads:
          type: array
          items:
            $ref: '#/components/schemas/Upload' # this could alternatively be a document that holds an upload
    TaskOrder: # stub
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: c56a4180-65aa-42ec-a945-5fd21dec0538
        taskOrderLineItems:
          type: array
          items:
            $ref: '#/components/schemas/TaskOrderLineItem'
    TaskOrderLineItem: #stub
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: c56a4180-65aa-42ec-a945-5fd21dec0538
    PaymentRequestStatus:
      type: string
      title: Payment Request Status
      enum:
        - DRAFT
        - PAYMENT_SUBMITTED
        - PAYMENT_REJECTED
        - PAYMENT_APPROVED
        - INVOICE_SUBMITTED
        - INVOICE_APPROVED
        - INVOICE_REJECTED
    CreateUploadPayload:
      type: object
      properties:
        url:
          type: string
          format: uri
          example: https://uploads.domain.test/dir/c56a4180-65aa-42ec-a945-5fd21dec0538
        filename:
          type: string
          format: binary
          example: filename.pdf
        contentType:
          type: string
          format: mime-type
          example: application/pdf
        bytes:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - url
        - filename
        - content_type
        - bytes
        - created_at
        - updated_at
    Upload:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: c56a4180-65aa-42ec-a945-5fd21dec0538
        url:
          type: string
          format: uri
          example: https://uploads.domain.test/dir/c56a4180-65aa-42ec-a945-5fd21dec0538
        filename:
          type: string
          format: binary
          example: filename.pdf
        contentType:
          type: string
          format: mime-type
          example: application/pdf
        bytes:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - url
        - filename
        - content_type
        - bytes
        - created_at
        - updated_at
    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
  responses:
    InvalidRequest: # 400
      description: The request-response payload is invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound: # 404
      description: The requested resource wasn't found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    PermissionDenied: # 401, 403
      description: The request was denied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServerError: # 500
      description: A server error occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
