// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	route "github.com/transcom/mymove/pkg/route"

	testing "testing"
)

// Planner is an autogenerated mock type for the Planner type
type Planner struct {
	mock.Mock
}

// LatLongTransitDistance provides a mock function with given fields: appCtx, source, destination
func (_m *Planner) LatLongTransitDistance(appCtx appcontext.AppContext, source route.LatLong, destination route.LatLong) (int, error) {
	ret := _m.Called(appCtx, source, destination)

	var r0 int
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, route.LatLong, route.LatLong) int); ok {
		r0 = rf(appCtx, source, destination)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, route.LatLong, route.LatLong) error); ok {
		r1 = rf(appCtx, source, destination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransitDistance provides a mock function with given fields: appCtx, source, destination
func (_m *Planner) TransitDistance(appCtx appcontext.AppContext, source *models.Address, destination *models.Address) (int, error) {
	ret := _m.Called(appCtx, source, destination)

	var r0 int
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.Address, *models.Address) int); ok {
		r0 = rf(appCtx, source, destination)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, *models.Address, *models.Address) error); ok {
		r1 = rf(appCtx, source, destination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Zip3TransitDistance provides a mock function with given fields: appCtx, source, destination
func (_m *Planner) Zip3TransitDistance(appCtx appcontext.AppContext, source string, destination string) (int, error) {
	ret := _m.Called(appCtx, source, destination)

	var r0 int
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, string, string) int); ok {
		r0 = rf(appCtx, source, destination)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, string, string) error); ok {
		r1 = rf(appCtx, source, destination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Zip5TransitDistance provides a mock function with given fields: appCtx, source, destination
func (_m *Planner) Zip5TransitDistance(appCtx appcontext.AppContext, source string, destination string) (int, error) {
	ret := _m.Called(appCtx, source, destination)

	var r0 int
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, string, string) int); ok {
		r0 = rf(appCtx, source, destination)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, string, string) error); ok {
		r1 = rf(appCtx, source, destination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Zip5TransitDistanceLineHaul provides a mock function with given fields: appCtx, source, destination
func (_m *Planner) Zip5TransitDistanceLineHaul(appCtx appcontext.AppContext, source string, destination string) (int, error) {
	ret := _m.Called(appCtx, source, destination)

	var r0 int
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, string, string) int); ok {
		r0 = rf(appCtx, source, destination)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, string, string) error); ok {
		r1 = rf(appCtx, source, destination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlanner creates a new instance of Planner. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPlanner(t testing.TB) *Planner {
	mock := &Planner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
