// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	services "github.com/transcom/mymove/pkg/services"
)

// AdminUserFetcher is an autogenerated mock type for the AdminUserFetcher type
type AdminUserFetcher struct {
	mock.Mock
}

// FetchAdminUser provides a mock function with given fields: appCtx, filters
func (_m *AdminUserFetcher) FetchAdminUser(appCtx appcontext.AppContext, filters []services.QueryFilter) (models.AdminUser, error) {
	ret := _m.Called(appCtx, filters)

	var r0 models.AdminUser
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, []services.QueryFilter) models.AdminUser); ok {
		r0 = rf(appCtx, filters)
	} else {
		r0 = ret.Get(0).(models.AdminUser)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, []services.QueryFilter) error); ok {
		r1 = rf(appCtx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAdminUserFetcher interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdminUserFetcher creates a new instance of AdminUserFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdminUserFetcher(t mockConstructorTestingTNewAdminUserFetcher) *AdminUserFetcher {
	mock := &AdminUserFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
