// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	afero "github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	uuid "github.com/gofrs/uuid"
)

// AOAPacketCreator is an autogenerated mock type for the AOAPacketCreator type
type AOAPacketCreator struct {
	mock.Mock
}

// CreateAOAPacket provides a mock function with given fields: appCtx, ppmShipmentID, isPaymentPacket
func (_m *AOAPacketCreator) CreateAOAPacket(appCtx appcontext.AppContext, ppmShipmentID uuid.UUID, isPaymentPacket bool) (afero.File, error) {
	ret := _m.Called(appCtx, ppmShipmentID, isPaymentPacket)

	if len(ret) == 0 {
		panic("no return value specified for CreateAOAPacket")
	}

	var r0 afero.File
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, bool) (afero.File, error)); ok {
		return rf(appCtx, ppmShipmentID, isPaymentPacket)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, bool) afero.File); ok {
		r0 = rf(appCtx, ppmShipmentID, isPaymentPacket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID, bool) error); ok {
		r1 = rf(appCtx, ppmShipmentID, isPaymentPacket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyAOAPacketInternal provides a mock function with given fields: appCtx, ppmShipmentID
func (_m *AOAPacketCreator) VerifyAOAPacketInternal(appCtx appcontext.AppContext, ppmShipmentID uuid.UUID) error {
	ret := _m.Called(appCtx, ppmShipmentID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAOAPacketInternal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r0 = rf(appCtx, ppmShipmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAOAPacketCreator creates a new instance of AOAPacketCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAOAPacketCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *AOAPacketCreator {
	mock := &AOAPacketCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
