// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// ApprovedSITDurationUpdateCreator is an autogenerated mock type for the ApprovedSITDurationUpdateCreator type
type ApprovedSITDurationUpdateCreator struct {
	mock.Mock
}

// CreateApprovedSITDurationUpdate provides a mock function with given fields: appCtx, sitDurationUpdate, shipmentID, eTag
func (_m *ApprovedSITDurationUpdateCreator) CreateApprovedSITDurationUpdate(appCtx appcontext.AppContext, sitDurationUpdate *models.SITDurationUpdate, shipmentID uuid.UUID, eTag string) (*models.MTOShipment, error) {
	ret := _m.Called(appCtx, sitDurationUpdate, shipmentID, eTag)

	if len(ret) == 0 {
		panic("no return value specified for CreateApprovedSITDurationUpdate")
	}

	var r0 *models.MTOShipment
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.SITDurationUpdate, uuid.UUID, string) (*models.MTOShipment, error)); ok {
		return rf(appCtx, sitDurationUpdate, shipmentID, eTag)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.SITDurationUpdate, uuid.UUID, string) *models.MTOShipment); ok {
		r0 = rf(appCtx, sitDurationUpdate, shipmentID, eTag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MTOShipment)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, *models.SITDurationUpdate, uuid.UUID, string) error); ok {
		r1 = rf(appCtx, sitDurationUpdate, shipmentID, eTag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewApprovedSITDurationUpdateCreator creates a new instance of ApprovedSITDurationUpdateCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApprovedSITDurationUpdateCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApprovedSITDurationUpdateCreator {
	mock := &ApprovedSITDurationUpdateCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
