// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"
)

// BoatShipmentCreator is an autogenerated mock type for the BoatShipmentCreator type
type BoatShipmentCreator struct {
	mock.Mock
}

// CreateBoatShipmentWithDefaultCheck provides a mock function with given fields: appCtx, boatshipment
func (_m *BoatShipmentCreator) CreateBoatShipmentWithDefaultCheck(appCtx appcontext.AppContext, boatshipment *models.BoatShipment) (*models.BoatShipment, error) {
	ret := _m.Called(appCtx, boatshipment)

	if len(ret) == 0 {
		panic("no return value specified for CreateBoatShipmentWithDefaultCheck")
	}

	var r0 *models.BoatShipment
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.BoatShipment) (*models.BoatShipment, error)); ok {
		return rf(appCtx, boatshipment)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.BoatShipment) *models.BoatShipment); ok {
		r0 = rf(appCtx, boatshipment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BoatShipment)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, *models.BoatShipment) error); ok {
		r1 = rf(appCtx, boatshipment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBoatShipmentCreator creates a new instance of BoatShipmentCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBoatShipmentCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *BoatShipmentCreator {
	mock := &BoatShipmentCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
