// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"
)

// CustomerSupportRemarksFetcher is an autogenerated mock type for the CustomerSupportRemarksFetcher type
type CustomerSupportRemarksFetcher struct {
	mock.Mock
}

// ListCustomerSupportRemarks provides a mock function with given fields: appCtx, moveCode
func (_m *CustomerSupportRemarksFetcher) ListCustomerSupportRemarks(appCtx appcontext.AppContext, moveCode string) (*models.CustomerSupportRemarks, error) {
	ret := _m.Called(appCtx, moveCode)

	if len(ret) == 0 {
		panic("no return value specified for ListCustomerSupportRemarks")
	}

	var r0 *models.CustomerSupportRemarks
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, string) (*models.CustomerSupportRemarks, error)); ok {
		return rf(appCtx, moveCode)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, string) *models.CustomerSupportRemarks); ok {
		r0 = rf(appCtx, moveCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CustomerSupportRemarks)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, string) error); ok {
		r1 = rf(appCtx, moveCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerSupportRemarksFetcher creates a new instance of CustomerSupportRemarksFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerSupportRemarksFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerSupportRemarksFetcher {
	mock := &CustomerSupportRemarksFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
