// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/transcom/mymove/pkg/models"

	time "time"

	unit "github.com/transcom/mymove/pkg/unit"
)

// DomesticOriginFirstDaySITPricer is an autogenerated mock type for the DomesticOriginFirstDaySITPricer type
type DomesticOriginFirstDaySITPricer struct {
	mock.Mock
}

// Price provides a mock function with given fields: contractCode, requestedPickupDate, isPeakPeriod, weight, serviceArea
func (_m *DomesticOriginFirstDaySITPricer) Price(contractCode string, requestedPickupDate time.Time, isPeakPeriod bool, weight unit.Pound, serviceArea string) (unit.Cents, error) {
	ret := _m.Called(contractCode, requestedPickupDate, isPeakPeriod, weight, serviceArea)

	var r0 unit.Cents
	if rf, ok := ret.Get(0).(func(string, time.Time, bool, unit.Pound, string) unit.Cents); ok {
		r0 = rf(contractCode, requestedPickupDate, isPeakPeriod, weight, serviceArea)
	} else {
		r0 = ret.Get(0).(unit.Cents)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Time, bool, unit.Pound, string) error); ok {
		r1 = rf(contractCode, requestedPickupDate, isPeakPeriod, weight, serviceArea)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PriceUsingParams provides a mock function with given fields: params
func (_m *DomesticOriginFirstDaySITPricer) PriceUsingParams(params models.PaymentServiceItemParams) (unit.Cents, error) {
	ret := _m.Called(params)

	var r0 unit.Cents
	if rf, ok := ret.Get(0).(func(models.PaymentServiceItemParams) unit.Cents); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(unit.Cents)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.PaymentServiceItemParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
