// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	services "github.com/transcom/mymove/pkg/services"

	time "time"

	unit "github.com/transcom/mymove/pkg/unit"
)

// DomesticDestinationAdditionalDaysSITPricer is an autogenerated mock type for the DomesticDestinationAdditionalDaysSITPricer type
type DomesticDestinationAdditionalDaysSITPricer struct {
	mock.Mock
}

// Price provides a mock function with given fields: appCtx, contractCode, requestedPickupDate, weight, serviceArea, numberOfDaysInSIT, disableWeightMinimum
func (_m *DomesticDestinationAdditionalDaysSITPricer) Price(appCtx appcontext.AppContext, contractCode string, requestedPickupDate time.Time, weight unit.Pound, serviceArea string, numberOfDaysInSIT int, disableWeightMinimum bool) (unit.Cents, services.PricingDisplayParams, error) {
	ret := _m.Called(appCtx, contractCode, requestedPickupDate, weight, serviceArea, numberOfDaysInSIT, disableWeightMinimum)

	var r0 unit.Cents
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, string, time.Time, unit.Pound, string, int, bool) unit.Cents); ok {
		r0 = rf(appCtx, contractCode, requestedPickupDate, weight, serviceArea, numberOfDaysInSIT, disableWeightMinimum)
	} else {
		r0 = ret.Get(0).(unit.Cents)
	}

	var r1 services.PricingDisplayParams
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, string, time.Time, unit.Pound, string, int, bool) services.PricingDisplayParams); ok {
		r1 = rf(appCtx, contractCode, requestedPickupDate, weight, serviceArea, numberOfDaysInSIT, disableWeightMinimum)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(services.PricingDisplayParams)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(appcontext.AppContext, string, time.Time, unit.Pound, string, int, bool) error); ok {
		r2 = rf(appCtx, contractCode, requestedPickupDate, weight, serviceArea, numberOfDaysInSIT, disableWeightMinimum)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PriceUsingParams provides a mock function with given fields: appCtx, params
func (_m *DomesticDestinationAdditionalDaysSITPricer) PriceUsingParams(appCtx appcontext.AppContext, params models.PaymentServiceItemParams) (unit.Cents, services.PricingDisplayParams, error) {
	ret := _m.Called(appCtx, params)

	var r0 unit.Cents
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, models.PaymentServiceItemParams) unit.Cents); ok {
		r0 = rf(appCtx, params)
	} else {
		r0 = ret.Get(0).(unit.Cents)
	}

	var r1 services.PricingDisplayParams
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, models.PaymentServiceItemParams) services.PricingDisplayParams); ok {
		r1 = rf(appCtx, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(services.PricingDisplayParams)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(appcontext.AppContext, models.PaymentServiceItemParams) error); ok {
		r2 = rf(appCtx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewDomesticDestinationAdditionalDaysSITPricer interface {
	mock.TestingT
	Cleanup(func())
}

// NewDomesticDestinationAdditionalDaysSITPricer creates a new instance of DomesticDestinationAdditionalDaysSITPricer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDomesticDestinationAdditionalDaysSITPricer(t mockConstructorTestingTNewDomesticDestinationAdditionalDaysSITPricer) *DomesticDestinationAdditionalDaysSITPricer {
	mock := &DomesticDestinationAdditionalDaysSITPricer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
