// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"

	unit "github.com/transcom/mymove/pkg/unit"
)

// DomesticLinehaulPricer is an autogenerated mock type for the DomesticLinehaulPricer type
type DomesticLinehaulPricer struct {
	mock.Mock
}

// PriceDomesticLinehaul provides a mock function with given fields: moveDate, distance, weight, serviceArea
func (_m *DomesticLinehaulPricer) PriceDomesticLinehaul(moveDate time.Time, distance unit.Miles, weight unit.Pound, serviceArea string) (unit.Cents, error) {
	ret := _m.Called(moveDate, distance, weight, serviceArea)

	var r0 unit.Cents
	if rf, ok := ret.Get(0).(func(time.Time, unit.Miles, unit.Pound, string) unit.Cents); ok {
		r0 = rf(moveDate, distance, weight, serviceArea)
	} else {
		r0 = ret.Get(0).(unit.Cents)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(time.Time, unit.Miles, unit.Pound, string) error); ok {
		r1 = rf(moveDate, distance, weight, serviceArea)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
