// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// EDIErrorFetcher is an autogenerated mock type for the EDIErrorFetcher type
type EDIErrorFetcher struct {
	mock.Mock
}

// FetchEdiErrorByID provides a mock function with given fields: appCtx, id
func (_m *EDIErrorFetcher) FetchEdiErrorByID(appCtx appcontext.AppContext, id uuid.UUID) (models.EdiError, error) {
	ret := _m.Called(appCtx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchEdiErrorByID")
	}

	var r0 models.EdiError
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) (models.EdiError, error)); ok {
		return rf(appCtx, id)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) models.EdiError); ok {
		r0 = rf(appCtx, id)
	} else {
		r0 = ret.Get(0).(models.EdiError)
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r1 = rf(appCtx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchEdiErrors provides a mock function with given fields: appCtx
func (_m *EDIErrorFetcher) FetchEdiErrors(appCtx appcontext.AppContext) (models.EdiErrors, error) {
	ret := _m.Called(appCtx)

	if len(ret) == 0 {
		panic("no return value specified for FetchEdiErrors")
	}

	var r0 models.EdiErrors
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext) (models.EdiErrors, error)); ok {
		return rf(appCtx)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext) models.EdiErrors); ok {
		r0 = rf(appCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.EdiErrors)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext) error); ok {
		r1 = rf(appCtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEDIErrorFetcher creates a new instance of EDIErrorFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEDIErrorFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EDIErrorFetcher {
	mock := &EDIErrorFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
