// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appconfig "github.com/transcom/mymove/pkg/appconfig"

	services "github.com/transcom/mymove/pkg/services"
)

// ElectronicOrderCategoryCountFetcher is an autogenerated mock type for the ElectronicOrderCategoryCountFetcher type
type ElectronicOrderCategoryCountFetcher struct {
	mock.Mock
}

// FetchElectronicOrderCategoricalCounts provides a mock function with given fields: appCfg, filters, andFilters
func (_m *ElectronicOrderCategoryCountFetcher) FetchElectronicOrderCategoricalCounts(appCfg appconfig.AppConfig, filters []services.QueryFilter, andFilters *[]services.QueryFilter) (map[interface{}]int, error) {
	ret := _m.Called(appCfg, filters, andFilters)

	var r0 map[interface{}]int
	if rf, ok := ret.Get(0).(func(appconfig.AppConfig, []services.QueryFilter, *[]services.QueryFilter) map[interface{}]int); ok {
		r0 = rf(appCfg, filters, andFilters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[interface{}]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appconfig.AppConfig, []services.QueryFilter, *[]services.QueryFilter) error); ok {
		r1 = rf(appCfg, filters, andFilters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
