// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	testing "testing"
)

// EvaluationReportCreator is an autogenerated mock type for the EvaluationReportCreator type
type EvaluationReportCreator struct {
	mock.Mock
}

// CreateEvaluationReport provides a mock function with given fields: appCtx, evaluationReport
func (_m *EvaluationReportCreator) CreateEvaluationReport(appCtx appcontext.AppContext, evaluationReport *models.EvaluationReport) (*models.EvaluationReport, error) {
	ret := _m.Called(appCtx, evaluationReport)

	var r0 *models.EvaluationReport
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.EvaluationReport) *models.EvaluationReport); ok {
		r0 = rf(appCtx, evaluationReport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EvaluationReport)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, *models.EvaluationReport) error); ok {
		r1 = rf(appCtx, evaluationReport)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEvaluationReportCreator creates a new instance of EvaluationReportCreator. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewEvaluationReportCreator(t testing.TB) *EvaluationReportCreator {
	mock := &EvaluationReportCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
