// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	appcontext "github.com/transcom/mymove/pkg/appcontext"

	mock "github.com/stretchr/testify/mock"

	services "github.com/transcom/mymove/pkg/services"
)

// FeatureFlagFetcher is an autogenerated mock type for the FeatureFlagFetcher type
type FeatureFlagFetcher struct {
	mock.Mock
}

// GetFlag provides a mock function with given fields: ctx, entityID, key, flagContext
func (_m *FeatureFlagFetcher) GetFlag(ctx context.Context, entityID string, key string, flagContext map[string]string) (services.FeatureFlag, error) {
	ret := _m.Called(ctx, entityID, key, flagContext)

	var r0 services.FeatureFlag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) (services.FeatureFlag, error)); ok {
		return rf(ctx, entityID, key, flagContext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) services.FeatureFlag); ok {
		r0 = rf(ctx, entityID, key, flagContext)
	} else {
		r0 = ret.Get(0).(services.FeatureFlag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, map[string]string) error); ok {
		r1 = rf(ctx, entityID, key, flagContext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFlagForUser provides a mock function with given fields: ctx, appCtx, key, flagContext
func (_m *FeatureFlagFetcher) GetFlagForUser(ctx context.Context, appCtx appcontext.AppContext, key string, flagContext map[string]string) (services.FeatureFlag, error) {
	ret := _m.Called(ctx, appCtx, key, flagContext)

	var r0 services.FeatureFlag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, appcontext.AppContext, string, map[string]string) (services.FeatureFlag, error)); ok {
		return rf(ctx, appCtx, key, flagContext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, appcontext.AppContext, string, map[string]string) services.FeatureFlag); ok {
		r0 = rf(ctx, appCtx, key, flagContext)
	} else {
		r0 = ret.Get(0).(services.FeatureFlag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, appcontext.AppContext, string, map[string]string) error); ok {
		r1 = rf(ctx, appCtx, key, flagContext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsEnabledForUser provides a mock function with given fields: ctx, appCtx, key
func (_m *FeatureFlagFetcher) IsEnabledForUser(ctx context.Context, appCtx appcontext.AppContext, key string) (bool, error) {
	ret := _m.Called(ctx, appCtx, key)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, appcontext.AppContext, string) (bool, error)); ok {
		return rf(ctx, appCtx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, appcontext.AppContext, string) bool); ok {
		r0 = rf(ctx, appCtx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, appcontext.AppContext, string) error); ok {
		r1 = rf(ctx, appCtx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFeatureFlagFetcher creates a new instance of FeatureFlagFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeatureFlagFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeatureFlagFetcher {
	mock := &FeatureFlagFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
