// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	services "github.com/transcom/mymove/pkg/services"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// FetchRecord provides a mock function with given fields: appCtx, model, filters
func (_m *Fetcher) FetchRecord(appCtx appcontext.AppContext, model interface{}, filters []services.QueryFilter) error {
	ret := _m.Called(appCtx, model, filters)

	if len(ret) == 0 {
		panic("no return value specified for FetchRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, interface{}, []services.QueryFilter) error); ok {
		r0 = rf(appCtx, model, filters)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFetcher creates a new instance of Fetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Fetcher {
	mock := &Fetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
