// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	services "github.com/transcom/mymove/pkg/services"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// FetchRecord provides a mock function with given fields: model, filters
func (_m *Fetcher) FetchRecord(model interface{}, filters []services.QueryFilter) error {
	ret := _m.Called(model, filters)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, []services.QueryFilter) error); ok {
		r0 = rf(model, filters)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
