// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appconfig "github.com/transcom/mymove/pkg/appconfig"

	services "github.com/transcom/mymove/pkg/services"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// FetchRecord provides a mock function with given fields: appCfg, model, filters
func (_m *Fetcher) FetchRecord(appCfg appconfig.AppConfig, model interface{}, filters []services.QueryFilter) error {
	ret := _m.Called(appCfg, model, filters)

	var r0 error
	if rf, ok := ret.Get(0).(func(appconfig.AppConfig, interface{}, []services.QueryFilter) error); ok {
		r0 = rf(appCfg, model, filters)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
