// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	ediinvoice "github.com/transcom/mymove/pkg/edi/invoice"

	models "github.com/transcom/mymove/pkg/models"
)

// GHCPaymentRequestInvoiceGenerator is an autogenerated mock type for the GHCPaymentRequestInvoiceGenerator type
type GHCPaymentRequestInvoiceGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: paymentRequest, sendProductionInvoice
func (_m *GHCPaymentRequestInvoiceGenerator) Generate(paymentRequest models.PaymentRequest, sendProductionInvoice bool) (ediinvoice.Invoice858C, error) {
	ret := _m.Called(paymentRequest, sendProductionInvoice)

	var r0 ediinvoice.Invoice858C
	if rf, ok := ret.Get(0).(func(models.PaymentRequest, bool) ediinvoice.Invoice858C); ok {
		r0 = rf(paymentRequest, sendProductionInvoice)
	} else {
		r0 = ret.Get(0).(ediinvoice.Invoice858C)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.PaymentRequest, bool) error); ok {
		r1 = rf(paymentRequest, sendProductionInvoice)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
