// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// GunSafeWeightTicketCreator is an autogenerated mock type for the GunSafeWeightTicketCreator type
type GunSafeWeightTicketCreator struct {
	mock.Mock
}

// CreateGunSafeWeightTicket provides a mock function with given fields: appCtx, ppmShipmentID
func (_m *GunSafeWeightTicketCreator) CreateGunSafeWeightTicket(appCtx appcontext.AppContext, ppmShipmentID uuid.UUID) (*models.GunSafeWeightTicket, error) {
	ret := _m.Called(appCtx, ppmShipmentID)

	if len(ret) == 0 {
		panic("no return value specified for CreateGunSafeWeightTicket")
	}

	var r0 *models.GunSafeWeightTicket
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) (*models.GunSafeWeightTicket, error)); ok {
		return rf(appCtx, ppmShipmentID)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) *models.GunSafeWeightTicket); ok {
		r0 = rf(appCtx, ppmShipmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GunSafeWeightTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r1 = rf(appCtx, ppmShipmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGunSafeWeightTicketCreator creates a new instance of GunSafeWeightTicketCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGunSafeWeightTicketCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *GunSafeWeightTicketCreator {
	mock := &GunSafeWeightTicketCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
