// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	validate "github.com/gobuffalo/validate/v3"
)

// MoveTaskOrderCreator is an autogenerated mock type for the MoveTaskOrderCreator type
type MoveTaskOrderCreator struct {
	mock.Mock
}

// CreateMoveTaskOrder provides a mock function with given fields: appCtx, moveTaskOrder
func (_m *MoveTaskOrderCreator) CreateMoveTaskOrder(appCtx appcontext.AppContext, moveTaskOrder *models.Move) (*models.Move, *validate.Errors, error) {
	ret := _m.Called(appCtx, moveTaskOrder)

	var r0 *models.Move
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.Move) *models.Move); ok {
		r0 = rf(appCtx, moveTaskOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Move)
		}
	}

	var r1 *validate.Errors
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, *models.Move) *validate.Errors); ok {
		r1 = rf(appCtx, moveTaskOrder)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*validate.Errors)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(appcontext.AppContext, *models.Move) error); ok {
		r2 = rf(appCtx, moveTaskOrder)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewMoveTaskOrderCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewMoveTaskOrderCreator creates a new instance of MoveTaskOrderCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMoveTaskOrderCreator(t mockConstructorTestingTNewMoveTaskOrderCreator) *MoveTaskOrderCreator {
	mock := &MoveTaskOrderCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
