// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// MoveOrderUpdater is an autogenerated mock type for the MoveOrderUpdater type
type MoveOrderUpdater struct {
	mock.Mock
}

// UpdateMoveOrder provides a mock function with given fields: moveOrderID, eTag, moveOrder
func (_m *MoveOrderUpdater) UpdateMoveOrder(moveOrderID uuid.UUID, eTag string, moveOrder models.Order) (*models.Order, error) {
	ret := _m.Called(moveOrderID, eTag, moveOrder)

	var r0 *models.Order
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, models.Order) *models.Order); ok {
		r0 = rf(moveOrderID, eTag, moveOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID, string, models.Order) error); ok {
		r1 = rf(moveOrderID, eTag, moveOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
