// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/transcom/mymove/pkg/models"
)

// MoveStatusRouter is an autogenerated mock type for the MoveStatusRouter type
type MoveStatusRouter struct {
	mock.Mock
}

// RouteMove provides a mock function with given fields: move
func (_m *MoveStatusRouter) RouteMove(move *models.Move) error {
	ret := _m.Called(move)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Move) error); ok {
		r0 = rf(move)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
