// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// MoveRouter is an autogenerated mock type for the MoveRouter type
type MoveRouter struct {
	mock.Mock
}

// Approve provides a mock function with given fields: appCtx, move
func (_m *MoveRouter) Approve(appCtx appcontext.AppContext, move *models.Move) error {
	ret := _m.Called(appCtx, move)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.Move) error); ok {
		r0 = rf(appCtx, move)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ApproveAmendedOrders provides a mock function with given fields: appCtx, moveID, orderID
func (_m *MoveRouter) ApproveAmendedOrders(appCtx appcontext.AppContext, moveID uuid.UUID, orderID uuid.UUID) (models.Move, error) {
	ret := _m.Called(appCtx, moveID, orderID)

	var r0 models.Move
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, uuid.UUID) models.Move); ok {
		r0 = rf(appCtx, moveID, orderID)
	} else {
		r0 = ret.Get(0).(models.Move)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(appCtx, moveID, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cancel provides a mock function with given fields: appCtx, reason, move
func (_m *MoveRouter) Cancel(appCtx appcontext.AppContext, reason string, move *models.Move) error {
	ret := _m.Called(appCtx, reason, move)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, string, *models.Move) error); ok {
		r0 = rf(appCtx, reason, move)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompleteServiceCounseling provides a mock function with given fields: appCtx, move
func (_m *MoveRouter) CompleteServiceCounseling(appCtx appcontext.AppContext, move *models.Move) error {
	ret := _m.Called(appCtx, move)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.Move) error); ok {
		r0 = rf(appCtx, move)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendToOfficeUser provides a mock function with given fields: appCtx, move
func (_m *MoveRouter) SendToOfficeUser(appCtx appcontext.AppContext, move *models.Move) error {
	ret := _m.Called(appCtx, move)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.Move) error); ok {
		r0 = rf(appCtx, move)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Submit provides a mock function with given fields: appCtx, move
func (_m *MoveRouter) Submit(appCtx appcontext.AppContext, move *models.Move) error {
	ret := _m.Called(appCtx, move)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.Move) error); ok {
		r0 = rf(appCtx, move)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
