// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/transcom/mymove/pkg/models"

	time "time"

	unit "github.com/transcom/mymove/pkg/unit"

	uuid "github.com/gofrs/uuid"
)

// MoveTaskOrderPrimeEstimatedWeightUpdater is an autogenerated mock type for the MoveTaskOrderPrimeEstimatedWeightUpdater type
type MoveTaskOrderPrimeEstimatedWeightUpdater struct {
	mock.Mock
}

// UpdatePrimeEstimatedWeight provides a mock function with given fields: moveTaskOrderID, primeEstimatedWeight, updateTime
func (_m *MoveTaskOrderPrimeEstimatedWeightUpdater) UpdatePrimeEstimatedWeight(moveTaskOrderID uuid.UUID, primeEstimatedWeight unit.Pound, updateTime time.Time) (*models.MoveTaskOrder, error) {
	ret := _m.Called(moveTaskOrderID, primeEstimatedWeight, updateTime)

	var r0 *models.MoveTaskOrder
	if rf, ok := ret.Get(0).(func(uuid.UUID, unit.Pound, time.Time) *models.MoveTaskOrder); ok {
		r0 = rf(moveTaskOrderID, primeEstimatedWeight, updateTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MoveTaskOrder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID, unit.Pound, time.Time) error); ok {
		r1 = rf(moveTaskOrderID, primeEstimatedWeight, updateTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
