// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	uuid "github.com/gofrs/uuid"
)

// MoveTaskOrderChecker is an autogenerated mock type for the MoveTaskOrderChecker type
type MoveTaskOrderChecker struct {
	mock.Mock
}

// MTOAvailableToPrime provides a mock function with given fields: appCtx, moveTaskOrderID
func (_m *MoveTaskOrderChecker) MTOAvailableToPrime(appCtx appcontext.AppContext, moveTaskOrderID uuid.UUID) (bool, error) {
	ret := _m.Called(appCtx, moveTaskOrderID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) bool); ok {
		r0 = rf(appCtx, moveTaskOrderID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r1 = rf(appCtx, moveTaskOrderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMoveTaskOrderChecker interface {
	mock.TestingT
	Cleanup(func())
}

// NewMoveTaskOrderChecker creates a new instance of MoveTaskOrderChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMoveTaskOrderChecker(t mockConstructorTestingTNewMoveTaskOrderChecker) *MoveTaskOrderChecker {
	mock := &MoveTaskOrderChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
