// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	testing "testing"
)

// MTOAgentCreator is an autogenerated mock type for the MTOAgentCreator type
type MTOAgentCreator struct {
	mock.Mock
}

// CreateMTOAgentPrime provides a mock function with given fields: appCtx, mtoAgent
func (_m *MTOAgentCreator) CreateMTOAgentPrime(appCtx appcontext.AppContext, mtoAgent *models.MTOAgent) (*models.MTOAgent, error) {
	ret := _m.Called(appCtx, mtoAgent)

	var r0 *models.MTOAgent
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.MTOAgent) *models.MTOAgent); ok {
		r0 = rf(appCtx, mtoAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MTOAgent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, *models.MTOAgent) error); ok {
		r1 = rf(appCtx, mtoAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMTOAgentCreator creates a new instance of MTOAgentCreator. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMTOAgentCreator(t testing.TB) *MTOAgentCreator {
	mock := &MTOAgentCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
