// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/transcom/mymove/pkg/models"

	validate "github.com/gobuffalo/validate"
)

// MTOShipmentStatusUpdater is an autogenerated mock type for the MTOShipmentStatusUpdater type
type MTOShipmentStatusUpdater struct {
	mock.Mock
}

// UpdateMTOShipmentStatus provides a mock function with given fields: model, status
func (_m *MTOShipmentStatusUpdater) UpdateMTOShipmentStatus(model *models.MTOShipment, status string) (*validate.Errors, error) {
	ret := _m.Called(model, status)

	var r0 *validate.Errors
	if rf, ok := ret.Get(0).(func(*models.MTOShipment, string) *validate.Errors); ok {
		r0 = rf(model, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*validate.Errors)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.MTOShipment, string) error); ok {
		r1 = rf(model, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
