// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	testing "testing"

	uuid "github.com/gofrs/uuid"
)

// MTOShipmentUpdater is an autogenerated mock type for the MTOShipmentUpdater type
type MTOShipmentUpdater struct {
	mock.Mock
}

// MTOShipmentsMTOAvailableToPrime provides a mock function with given fields: appCtx, mtoShipmentID
func (_m *MTOShipmentUpdater) MTOShipmentsMTOAvailableToPrime(appCtx appcontext.AppContext, mtoShipmentID uuid.UUID) (bool, error) {
	ret := _m.Called(appCtx, mtoShipmentID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) bool); ok {
		r0 = rf(appCtx, mtoShipmentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r1 = rf(appCtx, mtoShipmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMTOShipment provides a mock function with given fields: appCtx, mtoShipment, eTag
func (_m *MTOShipmentUpdater) UpdateMTOShipment(appCtx appcontext.AppContext, mtoShipment *models.MTOShipment, eTag string) (*models.MTOShipment, error) {
	ret := _m.Called(appCtx, mtoShipment, eTag)

	var r0 *models.MTOShipment
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.MTOShipment, string) *models.MTOShipment); ok {
		r0 = rf(appCtx, mtoShipment, eTag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MTOShipment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, *models.MTOShipment, string) error); ok {
		r1 = rf(appCtx, mtoShipment, eTag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMTOShipmentUpdater creates a new instance of MTOShipmentUpdater. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMTOShipmentUpdater(t testing.TB) *MTOShipmentUpdater {
	mock := &MTOShipmentUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
