// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// MTOShipmentStatusUpdater is an autogenerated mock type for the MTOShipmentStatusUpdater type
type MTOShipmentStatusUpdater struct {
	mock.Mock
}

// UpdateMTOShipmentStatus provides a mock function with given fields: appCtx, shipmentID, status, rejectionReason, diversionReason, eTag, featureFlagValues
func (_m *MTOShipmentStatusUpdater) UpdateMTOShipmentStatus(appCtx appcontext.AppContext, shipmentID uuid.UUID, status models.MTOShipmentStatus, rejectionReason *string, diversionReason *string, eTag string, featureFlagValues map[string]bool) (*models.MTOShipment, error) {
	ret := _m.Called(appCtx, shipmentID, status, rejectionReason, diversionReason, eTag, featureFlagValues)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMTOShipmentStatus")
	}

	var r0 *models.MTOShipment
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, models.MTOShipmentStatus, *string, *string, string, map[string]bool) (*models.MTOShipment, error)); ok {
		return rf(appCtx, shipmentID, status, rejectionReason, diversionReason, eTag, featureFlagValues)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, models.MTOShipmentStatus, *string, *string, string, map[string]bool) *models.MTOShipment); ok {
		r0 = rf(appCtx, shipmentID, status, rejectionReason, diversionReason, eTag, featureFlagValues)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MTOShipment)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID, models.MTOShipmentStatus, *string, *string, string, map[string]bool) error); ok {
		r1 = rf(appCtx, shipmentID, status, rejectionReason, diversionReason, eTag, featureFlagValues)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMTOShipmentStatusUpdater creates a new instance of MTOShipmentStatusUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMTOShipmentStatusUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MTOShipmentStatusUpdater {
	mock := &MTOShipmentStatusUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
