// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/transcom/mymove/pkg/models"

	services "github.com/transcom/mymove/pkg/services"

	validate "github.com/gobuffalo/validate/v3"
)

// OfficeUserCreator is an autogenerated mock type for the OfficeUserCreator type
type OfficeUserCreator struct {
	mock.Mock
}

// CreateOfficeUser provides a mock function with given fields: ctx, user, transportationIDFilter
func (_m *OfficeUserCreator) CreateOfficeUser(ctx context.Context, user *models.OfficeUser, transportationIDFilter []services.QueryFilter) (*models.OfficeUser, *validate.Errors, error) {
	ret := _m.Called(ctx, user, transportationIDFilter)

	var r0 *models.OfficeUser
	if rf, ok := ret.Get(0).(func(context.Context, *models.OfficeUser, []services.QueryFilter) *models.OfficeUser); ok {
		r0 = rf(ctx, user, transportationIDFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OfficeUser)
		}
	}

	var r1 *validate.Errors
	if rf, ok := ret.Get(1).(func(context.Context, *models.OfficeUser, []services.QueryFilter) *validate.Errors); ok {
		r1 = rf(ctx, user, transportationIDFilter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*validate.Errors)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *models.OfficeUser, []services.QueryFilter) error); ok {
		r2 = rf(ctx, user, transportationIDFilter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
