// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	testing "testing"

	uuid "github.com/gofrs/uuid"
)

// OfficeUserFetcherPop is an autogenerated mock type for the OfficeUserFetcherPop type
type OfficeUserFetcherPop struct {
	mock.Mock
}

// FetchOfficeUserByID provides a mock function with given fields: appCtx, id
func (_m *OfficeUserFetcherPop) FetchOfficeUserByID(appCtx appcontext.AppContext, id uuid.UUID) (models.OfficeUser, error) {
	ret := _m.Called(appCtx, id)

	var r0 models.OfficeUser
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) models.OfficeUser); ok {
		r0 = rf(appCtx, id)
	} else {
		r0 = ret.Get(0).(models.OfficeUser)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r1 = rf(appCtx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOfficeUserFetcherPop creates a new instance of OfficeUserFetcherPop. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewOfficeUserFetcherPop(t testing.TB) *OfficeUserFetcherPop {
	mock := &OfficeUserFetcherPop{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
