// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appconfig "github.com/transcom/mymove/pkg/appconfig"

	models "github.com/transcom/mymove/pkg/models"

	services "github.com/transcom/mymove/pkg/services"

	uuid "github.com/gofrs/uuid"
)

// OrderFetcher is an autogenerated mock type for the OrderFetcher type
type OrderFetcher struct {
	mock.Mock
}

// FetchOrder provides a mock function with given fields: appCfg, moveTaskOrderID
func (_m *OrderFetcher) FetchOrder(appCfg appconfig.AppConfig, moveTaskOrderID uuid.UUID) (*models.Order, error) {
	ret := _m.Called(appCfg, moveTaskOrderID)

	var r0 *models.Order
	if rf, ok := ret.Get(0).(func(appconfig.AppConfig, uuid.UUID) *models.Order); ok {
		r0 = rf(appCfg, moveTaskOrderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appconfig.AppConfig, uuid.UUID) error); ok {
		r1 = rf(appCfg, moveTaskOrderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrders provides a mock function with given fields: appCfg, officeUserID, params
func (_m *OrderFetcher) ListOrders(appCfg appconfig.AppConfig, officeUserID uuid.UUID, params *services.ListOrderParams) ([]models.Move, int, error) {
	ret := _m.Called(appCfg, officeUserID, params)

	var r0 []models.Move
	if rf, ok := ret.Get(0).(func(appconfig.AppConfig, uuid.UUID, *services.ListOrderParams) []models.Move); ok {
		r0 = rf(appCfg, officeUserID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Move)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(appconfig.AppConfig, uuid.UUID, *services.ListOrderParams) int); ok {
		r1 = rf(appCfg, officeUserID, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(appconfig.AppConfig, uuid.UUID, *services.ListOrderParams) error); ok {
		r2 = rf(appCfg, officeUserID, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
