// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	afero "github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	uuid "github.com/gofrs/uuid"
)

// PaymentPacketCreator is an autogenerated mock type for the PaymentPacketCreator type
type PaymentPacketCreator struct {
	mock.Mock
}

// CleanupPaymentPacketDir provides a mock function with given fields: dirName
func (_m *PaymentPacketCreator) CleanupPaymentPacketDir(dirName string) error {
	ret := _m.Called(dirName)

	if len(ret) == 0 {
		panic("no return value specified for CleanupPaymentPacketDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dirName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CleanupPaymentPacketFile provides a mock function with given fields: packetDir, closeFile
func (_m *PaymentPacketCreator) CleanupPaymentPacketFile(packetDir afero.File, closeFile bool) error {
	ret := _m.Called(packetDir, closeFile)

	if len(ret) == 0 {
		panic("no return value specified for CleanupPaymentPacketFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(afero.File, bool) error); ok {
		r0 = rf(packetDir, closeFile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Generate provides a mock function with given fields: appCtx, ppmShipmentID, addWaterMarks
func (_m *PaymentPacketCreator) Generate(appCtx appcontext.AppContext, ppmShipmentID uuid.UUID, addWaterMarks bool) (afero.File, string, error) {
	ret := _m.Called(appCtx, ppmShipmentID, addWaterMarks)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 afero.File
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, bool) (afero.File, string, error)); ok {
		return rf(appCtx, ppmShipmentID, addWaterMarks)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, bool) afero.File); ok {
		r0 = rf(appCtx, ppmShipmentID, addWaterMarks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID, bool) string); ok {
		r1 = rf(appCtx, ppmShipmentID, addWaterMarks)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(appcontext.AppContext, uuid.UUID, bool) error); ok {
		r2 = rf(appCtx, ppmShipmentID, addWaterMarks)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GenerateDefault provides a mock function with given fields: appCtx, ppmShipmentID
func (_m *PaymentPacketCreator) GenerateDefault(appCtx appcontext.AppContext, ppmShipmentID uuid.UUID) (afero.File, string, error) {
	ret := _m.Called(appCtx, ppmShipmentID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateDefault")
	}

	var r0 afero.File
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) (afero.File, string, error)); ok {
		return rf(appCtx, ppmShipmentID)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) afero.File); ok {
		r0 = rf(appCtx, ppmShipmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) string); ok {
		r1 = rf(appCtx, ppmShipmentID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r2 = rf(appCtx, ppmShipmentID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewPaymentPacketCreator creates a new instance of PaymentPacketCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentPacketCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentPacketCreator {
	mock := &PaymentPacketCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
