// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	uuid "github.com/gofrs/uuid"
)

// PaymentRequestShipmentRecalculator is an autogenerated mock type for the PaymentRequestShipmentRecalculator type
type PaymentRequestShipmentRecalculator struct {
	mock.Mock
}

// ShipmentRecalculatePaymentRequest provides a mock function with given fields: appCtx, shipmentID
func (_m *PaymentRequestShipmentRecalculator) ShipmentRecalculatePaymentRequest(appCtx appcontext.AppContext, shipmentID uuid.UUID) error {
	ret := _m.Called(appCtx, shipmentID)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r0 = rf(appCtx, shipmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
