// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appconfig "github.com/transcom/mymove/pkg/appconfig"

	models "github.com/transcom/mymove/pkg/models"
)

// PaymentRequestReviewedFetcher is an autogenerated mock type for the PaymentRequestReviewedFetcher type
type PaymentRequestReviewedFetcher struct {
	mock.Mock
}

// FetchReviewedPaymentRequest provides a mock function with given fields: appCfg
func (_m *PaymentRequestReviewedFetcher) FetchReviewedPaymentRequest(appCfg appconfig.AppConfig) (models.PaymentRequests, error) {
	ret := _m.Called(appCfg)

	var r0 models.PaymentRequests
	if rf, ok := ret.Get(0).(func(appconfig.AppConfig) models.PaymentRequests); ok {
		r0 = rf(appCfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.PaymentRequests)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appconfig.AppConfig) error); ok {
		r1 = rf(appCfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
