// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appconfig "github.com/transcom/mymove/pkg/appconfig"

	models "github.com/transcom/mymove/pkg/models"
)

// PaymentRequestReviewedProcessor is an autogenerated mock type for the PaymentRequestReviewedProcessor type
type PaymentRequestReviewedProcessor struct {
	mock.Mock
}

// ProcessAndLockReviewedPR provides a mock function with given fields: appCfg, pr
func (_m *PaymentRequestReviewedProcessor) ProcessAndLockReviewedPR(appCfg appconfig.AppConfig, pr models.PaymentRequest) error {
	ret := _m.Called(appCfg, pr)

	var r0 error
	if rf, ok := ret.Get(0).(func(appconfig.AppConfig, models.PaymentRequest) error); ok {
		r0 = rf(appCfg, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessReviewedPaymentRequest provides a mock function with given fields: appCfg
func (_m *PaymentRequestReviewedProcessor) ProcessReviewedPaymentRequest(appCfg appconfig.AppConfig) {
	_m.Called(appCfg)
}
