// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	services "github.com/transcom/mymove/pkg/services"

	testing "testing"
)

// PostalCodeValidator is an autogenerated mock type for the PostalCodeValidator type
type PostalCodeValidator struct {
	mock.Mock
}

// ValidatePostalCode provides a mock function with given fields: appCtx, postalCode, postalCodeType
func (_m *PostalCodeValidator) ValidatePostalCode(appCtx appcontext.AppContext, postalCode string, postalCodeType services.PostalCodeType) (bool, error) {
	ret := _m.Called(appCtx, postalCode, postalCodeType)

	var r0 bool
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, string, services.PostalCodeType) bool); ok {
		r0 = rf(appCtx, postalCode, postalCodeType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, string, services.PostalCodeType) error); ok {
		r1 = rf(appCtx, postalCode, postalCodeType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPostalCodeValidator creates a new instance of PostalCodeValidator. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostalCodeValidator(t testing.TB) *PostalCodeValidator {
	mock := &PostalCodeValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
