// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	unit "github.com/transcom/mymove/pkg/unit"

	uuid "github.com/gofrs/uuid"
)

// PPMCloseoutFetcher is an autogenerated mock type for the PPMCloseoutFetcher type
type PPMCloseoutFetcher struct {
	mock.Mock
}

// GetActualWeight provides a mock function with given fields: ppmShipment
func (_m *PPMCloseoutFetcher) GetActualWeight(ppmShipment *models.PPMShipment) (unit.Pound, error) {
	ret := _m.Called(ppmShipment)

	if len(ret) == 0 {
		panic("no return value specified for GetActualWeight")
	}

	var r0 unit.Pound
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.PPMShipment) (unit.Pound, error)); ok {
		return rf(ppmShipment)
	}
	if rf, ok := ret.Get(0).(func(*models.PPMShipment) unit.Pound); ok {
		r0 = rf(ppmShipment)
	} else {
		r0 = ret.Get(0).(unit.Pound)
	}

	if rf, ok := ret.Get(1).(func(*models.PPMShipment) error); ok {
		r1 = rf(ppmShipment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPPMCloseout provides a mock function with given fields: appCtx, ppmShipmentID
func (_m *PPMCloseoutFetcher) GetPPMCloseout(appCtx appcontext.AppContext, ppmShipmentID uuid.UUID) (*models.PPMCloseout, error) {
	ret := _m.Called(appCtx, ppmShipmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetPPMCloseout")
	}

	var r0 *models.PPMCloseout
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) (*models.PPMCloseout, error)); ok {
		return rf(appCtx, ppmShipmentID)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) *models.PPMCloseout); ok {
		r0 = rf(appCtx, ppmShipmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PPMCloseout)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r1 = rf(appCtx, ppmShipmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPPMCloseoutFetcher creates a new instance of PPMCloseoutFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPPMCloseoutFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PPMCloseoutFetcher {
	mock := &PPMCloseoutFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
