// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// PPMCloseoutFetcher is an autogenerated mock type for the PPMCloseoutFetcher type
type PPMCloseoutFetcher struct {
	mock.Mock
}

// GetPPMCloseout provides a mock function with given fields: appCtx, ppmShipmentID, allowableWeight
func (_m *PPMCloseoutFetcher) GetPPMCloseout(appCtx appcontext.AppContext, ppmShipmentID uuid.UUID, allowableWeight *int64) (*models.PPMCloseout, error) {
	ret := _m.Called(appCtx, ppmShipmentID, allowableWeight)

	var r0 *models.PPMCloseout
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, *int64) (*models.PPMCloseout, error)); ok {
		return rf(appCtx, ppmShipmentID, allowableWeight)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, *int64) *models.PPMCloseout); ok {
		r0 = rf(appCtx, ppmShipmentID, allowableWeight)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PPMCloseout)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID, *int64) error); ok {
		r1 = rf(appCtx, ppmShipmentID, allowableWeight)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPPMCloseoutFetcher creates a new instance of PPMCloseoutFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPPMCloseoutFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PPMCloseoutFetcher {
	mock := &PPMCloseoutFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
