// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// PPMShipmentUpdatedSubmitter is an autogenerated mock type for the PPMShipmentUpdatedSubmitter type
type PPMShipmentUpdatedSubmitter struct {
	mock.Mock
}

// SubmitUpdatedCustomerCloseOut provides a mock function with given fields: appCtx, ppmShipmentID, signedCertification, eTag
func (_m *PPMShipmentUpdatedSubmitter) SubmitUpdatedCustomerCloseOut(appCtx appcontext.AppContext, ppmShipmentID uuid.UUID, signedCertification models.SignedCertification, eTag string) (*models.PPMShipment, error) {
	ret := _m.Called(appCtx, ppmShipmentID, signedCertification, eTag)

	if len(ret) == 0 {
		panic("no return value specified for SubmitUpdatedCustomerCloseOut")
	}

	var r0 *models.PPMShipment
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, models.SignedCertification, string) (*models.PPMShipment, error)); ok {
		return rf(appCtx, ppmShipmentID, signedCertification, eTag)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, models.SignedCertification, string) *models.PPMShipment); ok {
		r0 = rf(appCtx, ppmShipmentID, signedCertification, eTag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PPMShipment)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID, models.SignedCertification, string) error); ok {
		r1 = rf(appCtx, ppmShipmentID, signedCertification, eTag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPPMShipmentUpdatedSubmitter creates a new instance of PPMShipmentUpdatedSubmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPPMShipmentUpdatedSubmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PPMShipmentUpdatedSubmitter {
	mock := &PPMShipmentUpdatedSubmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
