// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"
)

// PPMShipmentRouter is an autogenerated mock type for the PPMShipmentRouter type
type PPMShipmentRouter struct {
	mock.Mock
}

// SendToCustomer provides a mock function with given fields: appCtx, ppmShipment
func (_m *PPMShipmentRouter) SendToCustomer(appCtx appcontext.AppContext, ppmShipment *models.PPMShipment) error {
	ret := _m.Called(appCtx, ppmShipment)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.PPMShipment) error); ok {
		r0 = rf(appCtx, ppmShipment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetToDraft provides a mock function with given fields: appCtx, ppmShipment
func (_m *PPMShipmentRouter) SetToDraft(appCtx appcontext.AppContext, ppmShipment *models.PPMShipment) error {
	ret := _m.Called(appCtx, ppmShipment)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.PPMShipment) error); ok {
		r0 = rf(appCtx, ppmShipment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Submit provides a mock function with given fields: appCtx, ppmShipment
func (_m *PPMShipmentRouter) Submit(appCtx appcontext.AppContext, ppmShipment *models.PPMShipment) error {
	ret := _m.Called(appCtx, ppmShipment)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.PPMShipment) error); ok {
		r0 = rf(appCtx, ppmShipment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubmitCloseOutDocumentation provides a mock function with given fields: appCtx, ppmShipment
func (_m *PPMShipmentRouter) SubmitCloseOutDocumentation(appCtx appcontext.AppContext, ppmShipment *models.PPMShipment) error {
	ret := _m.Called(appCtx, ppmShipment)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.PPMShipment) error); ok {
		r0 = rf(appCtx, ppmShipment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubmitReviewedDocuments provides a mock function with given fields: appCtx, ppmShipment
func (_m *PPMShipmentRouter) SubmitReviewedDocuments(appCtx appcontext.AppContext, ppmShipment *models.PPMShipment) error {
	ret := _m.Called(appCtx, ppmShipment)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.PPMShipment) error); ok {
		r0 = rf(appCtx, ppmShipment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPPMShipmentRouter interface {
	mock.TestingT
	Cleanup(func())
}

// NewPPMShipmentRouter creates a new instance of PPMShipmentRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPPMShipmentRouter(t mockConstructorTestingTNewPPMShipmentRouter) *PPMShipmentRouter {
	mock := &PPMShipmentRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
