// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// PPMShipmentUpdater is an autogenerated mock type for the PPMShipmentUpdater type
type PPMShipmentUpdater struct {
	mock.Mock
}

// UpdatePPMShipmentWithDefaultCheck provides a mock function with given fields: appCtx, ppmshipment, mtoShipmentID
func (_m *PPMShipmentUpdater) UpdatePPMShipmentWithDefaultCheck(appCtx appcontext.AppContext, ppmshipment *models.PPMShipment, mtoShipmentID uuid.UUID) (*models.PPMShipment, error) {
	ret := _m.Called(appCtx, ppmshipment, mtoShipmentID)

	var r0 *models.PPMShipment
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *models.PPMShipment, uuid.UUID) *models.PPMShipment); ok {
		r0 = rf(appCtx, ppmshipment, mtoShipmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PPMShipment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, *models.PPMShipment, uuid.UUID) error); ok {
		r1 = rf(appCtx, ppmshipment, mtoShipmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPPMShipmentUpdater interface {
	mock.TestingT
	Cleanup(func())
}

// NewPPMShipmentUpdater creates a new instance of PPMShipmentUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPPMShipmentUpdater(t mockConstructorTestingTNewPPMShipmentUpdater) *PPMShipmentUpdater {
	mock := &PPMShipmentUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
