// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// PPMShipmentNewSubmitter is an autogenerated mock type for the PPMShipmentNewSubmitter type
type PPMShipmentNewSubmitter struct {
	mock.Mock
}

// SubmitNewCustomerCloseOut provides a mock function with given fields: appCtx, ppmShipmentID, signedCertification
func (_m *PPMShipmentNewSubmitter) SubmitNewCustomerCloseOut(appCtx appcontext.AppContext, ppmShipmentID uuid.UUID, signedCertification models.SignedCertification) (*models.PPMShipment, error) {
	ret := _m.Called(appCtx, ppmShipmentID, signedCertification)

	if len(ret) == 0 {
		panic("no return value specified for SubmitNewCustomerCloseOut")
	}

	var r0 *models.PPMShipment
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, models.SignedCertification) (*models.PPMShipment, error)); ok {
		return rf(appCtx, ppmShipmentID, signedCertification)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, models.SignedCertification) *models.PPMShipment); ok {
		r0 = rf(appCtx, ppmShipmentID, signedCertification)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PPMShipment)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID, models.SignedCertification) error); ok {
		r1 = rf(appCtx, ppmShipmentID, signedCertification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPPMShipmentNewSubmitter creates a new instance of PPMShipmentNewSubmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPPMShipmentNewSubmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PPMShipmentNewSubmitter {
	mock := &PPMShipmentNewSubmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
