// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	services "github.com/transcom/mymove/pkg/services"
)

// PPTASReportListFetcher is an autogenerated mock type for the PPTASReportListFetcher type
type PPTASReportListFetcher struct {
	mock.Mock
}

// BuildPPTASReportsFromMoves provides a mock function with given fields: appCtx, moves
func (_m *PPTASReportListFetcher) BuildPPTASReportsFromMoves(appCtx appcontext.AppContext, moves models.Moves) (models.PPTASReports, error) {
	ret := _m.Called(appCtx, moves)

	if len(ret) == 0 {
		panic("no return value specified for BuildPPTASReportsFromMoves")
	}

	var r0 models.PPTASReports
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, models.Moves) (models.PPTASReports, error)); ok {
		return rf(appCtx, moves)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, models.Moves) models.PPTASReports); ok {
		r0 = rf(appCtx, moves)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.PPTASReports)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, models.Moves) error); ok {
		r1 = rf(appCtx, moves)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMovesForReportBuilder provides a mock function with given fields: appCtx, params
func (_m *PPTASReportListFetcher) GetMovesForReportBuilder(appCtx appcontext.AppContext, params *services.MoveTaskOrderFetcherParams) (models.Moves, error) {
	ret := _m.Called(appCtx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetMovesForReportBuilder")
	}

	var r0 models.Moves
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *services.MoveTaskOrderFetcherParams) (models.Moves, error)); ok {
		return rf(appCtx, params)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, *services.MoveTaskOrderFetcherParams) models.Moves); ok {
		r0 = rf(appCtx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Moves)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, *services.MoveTaskOrderFetcherParams) error); ok {
		r1 = rf(appCtx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPPTASReportListFetcher creates a new instance of PPTASReportListFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPPTASReportListFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PPTASReportListFetcher {
	mock := &PPTASReportListFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
