// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	uuid "github.com/gofrs/uuid"
)

// ProgearWeightTicketDeleter is an autogenerated mock type for the ProgearWeightTicketDeleter type
type ProgearWeightTicketDeleter struct {
	mock.Mock
}

// DeleteProgearWeightTicket provides a mock function with given fields: appCtx, progearWeightTicketID
func (_m *ProgearWeightTicketDeleter) DeleteProgearWeightTicket(appCtx appcontext.AppContext, progearWeightTicketID uuid.UUID) error {
	ret := _m.Called(appCtx, progearWeightTicketID)

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r0 = rf(appCtx, progearWeightTicketID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewProgearWeightTicketDeleter interface {
	mock.TestingT
	Cleanup(func())
}

// NewProgearWeightTicketDeleter creates a new instance of ProgearWeightTicketDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProgearWeightTicketDeleter(t mockConstructorTestingTNewProgearWeightTicketDeleter) *ProgearWeightTicketDeleter {
	mock := &ProgearWeightTicketDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
