// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// ProgearCreator is an autogenerated mock type for the ProgearCreator type
type ProgearCreator struct {
	mock.Mock
}

// CreateProgear provides a mock function with given fields: appCtx, ppmShipmentID
func (_m *ProgearCreator) CreateProgear(appCtx appcontext.AppContext, ppmShipmentID uuid.UUID) (*models.ProgearWeightTicket, error) {
	ret := _m.Called(appCtx, ppmShipmentID)

	var r0 *models.ProgearWeightTicket
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) *models.ProgearWeightTicket); ok {
		r0 = rf(appCtx, ppmShipmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ProgearWeightTicket)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r1 = rf(appCtx, ppmShipmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProgearCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewProgearCreator creates a new instance of ProgearCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProgearCreator(t mockConstructorTestingTNewProgearCreator) *ProgearCreator {
	mock := &ProgearCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
