// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// ReportViolationFetcher is an autogenerated mock type for the ReportViolationFetcher type
type ReportViolationFetcher struct {
	mock.Mock
}

// FetchReportViolationsByReportID provides a mock function with given fields: appCtx, reportID
func (_m *ReportViolationFetcher) FetchReportViolationsByReportID(appCtx appcontext.AppContext, reportID uuid.UUID) (models.ReportViolations, error) {
	ret := _m.Called(appCtx, reportID)

	var r0 models.ReportViolations
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) models.ReportViolations); ok {
		r0 = rf(appCtx, reportID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.ReportViolations)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r1 = rf(appCtx, reportID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewReportViolationFetcher interface {
	mock.TestingT
	Cleanup(func())
}

// NewReportViolationFetcher creates a new instance of ReportViolationFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReportViolationFetcher(t mockConstructorTestingTNewReportViolationFetcher) *ReportViolationFetcher {
	mock := &ReportViolationFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
