// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	appcontext "github.com/transcom/mymove/pkg/appcontext"
	adminmessages "github.com/transcom/mymove/pkg/gen/adminmessages"

	mock "github.com/stretchr/testify/mock"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"

	validate "github.com/gobuffalo/validate/v3"
)

// RequestedOfficeUserUpdater is an autogenerated mock type for the RequestedOfficeUserUpdater type
type RequestedOfficeUserUpdater struct {
	mock.Mock
}

// UpdateRequestedOfficeUser provides a mock function with given fields: appCtx, id, payload
func (_m *RequestedOfficeUserUpdater) UpdateRequestedOfficeUser(appCtx appcontext.AppContext, id uuid.UUID, payload *adminmessages.RequestedOfficeUserUpdate) (*models.OfficeUser, *validate.Errors, error) {
	ret := _m.Called(appCtx, id, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRequestedOfficeUser")
	}

	var r0 *models.OfficeUser
	var r1 *validate.Errors
	var r2 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, *adminmessages.RequestedOfficeUserUpdate) (*models.OfficeUser, *validate.Errors, error)); ok {
		return rf(appCtx, id, payload)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, *adminmessages.RequestedOfficeUserUpdate) *models.OfficeUser); ok {
		r0 = rf(appCtx, id, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OfficeUser)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID, *adminmessages.RequestedOfficeUserUpdate) *validate.Errors); ok {
		r1 = rf(appCtx, id, payload)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*validate.Errors)
		}
	}

	if rf, ok := ret.Get(2).(func(appcontext.AppContext, uuid.UUID, *adminmessages.RequestedOfficeUserUpdate) error); ok {
		r2 = rf(appCtx, id, payload)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewRequestedOfficeUserUpdater creates a new instance of RequestedOfficeUserUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestedOfficeUserUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestedOfficeUserUpdater {
	mock := &RequestedOfficeUserUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
