// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appconfig "github.com/transcom/mymove/pkg/appconfig"

	models "github.com/transcom/mymove/pkg/models"

	unit "github.com/transcom/mymove/pkg/unit"
)

// ServiceItemPricer is an autogenerated mock type for the ServiceItemPricer type
type ServiceItemPricer struct {
	mock.Mock
}

// PriceServiceItem provides a mock function with given fields: appCfg, item
func (_m *ServiceItemPricer) PriceServiceItem(appCfg appconfig.AppConfig, item models.PaymentServiceItem) (unit.Cents, models.PaymentServiceItemParams, error) {
	ret := _m.Called(appCfg, item)

	var r0 unit.Cents
	if rf, ok := ret.Get(0).(func(appconfig.AppConfig, models.PaymentServiceItem) unit.Cents); ok {
		r0 = rf(appCfg, item)
	} else {
		r0 = ret.Get(0).(unit.Cents)
	}

	var r1 models.PaymentServiceItemParams
	if rf, ok := ret.Get(1).(func(appconfig.AppConfig, models.PaymentServiceItem) models.PaymentServiceItemParams); ok {
		r1 = rf(appCfg, item)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(models.PaymentServiceItemParams)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(appconfig.AppConfig, models.PaymentServiceItem) error); ok {
		r2 = rf(appCfg, item)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
