// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"

	appcontext "github.com/transcom/mymove/pkg/appcontext"

	mock "github.com/stretchr/testify/mock"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// ServiceRequestDocumentUploadCreator is an autogenerated mock type for the ServiceRequestDocumentUploadCreator type
type ServiceRequestDocumentUploadCreator struct {
	mock.Mock
}

// CreateUpload provides a mock function with given fields: appCtx, file, mtoServiceItemID, userID, filename
func (_m *ServiceRequestDocumentUploadCreator) CreateUpload(appCtx appcontext.AppContext, file io.ReadCloser, mtoServiceItemID uuid.UUID, userID uuid.UUID, filename string) (*models.Upload, error) {
	ret := _m.Called(appCtx, file, mtoServiceItemID, userID, filename)

	if len(ret) == 0 {
		panic("no return value specified for CreateUpload")
	}

	var r0 *models.Upload
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, io.ReadCloser, uuid.UUID, uuid.UUID, string) (*models.Upload, error)); ok {
		return rf(appCtx, file, mtoServiceItemID, userID, filename)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, io.ReadCloser, uuid.UUID, uuid.UUID, string) *models.Upload); ok {
		r0 = rf(appCtx, file, mtoServiceItemID, userID, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Upload)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, io.ReadCloser, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(appCtx, file, mtoServiceItemID, userID, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceRequestDocumentUploadCreator creates a new instance of ServiceRequestDocumentUploadCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceRequestDocumentUploadCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceRequestDocumentUploadCreator {
	mock := &ServiceRequestDocumentUploadCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
