// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	adminmessages "github.com/transcom/mymove/pkg/gen/adminmessages"

	models "github.com/transcom/mymove/pkg/models"

	redis "github.com/gomodule/redigo/redis"

	uuid "github.com/gofrs/uuid"

	validate "github.com/gobuffalo/validate"
)

// SessionRevocation is an autogenerated mock type for the SessionRevocation type
type SessionRevocation struct {
	mock.Mock
}

// RevokeUserSession provides a mock function with given fields: userID, payload, redisPool
func (_m *SessionRevocation) RevokeUserSession(userID uuid.UUID, payload *adminmessages.RevokedSessionPayload, redisPool *redis.Pool) (*models.User, *validate.Errors, error) {
	ret := _m.Called(userID, payload, redisPool)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(uuid.UUID, *adminmessages.RevokedSessionPayload, *redis.Pool) *models.User); ok {
		r0 = rf(userID, payload, redisPool)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 *validate.Errors
	if rf, ok := ret.Get(1).(func(uuid.UUID, *adminmessages.RevokedSessionPayload, *redis.Pool) *validate.Errors); ok {
		r1 = rf(userID, payload, redisPool)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*validate.Errors)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(uuid.UUID, *adminmessages.RevokedSessionPayload, *redis.Pool) error); ok {
		r2 = rf(userID, payload, redisPool)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
