// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// SFTPFiler is an autogenerated mock type for the SFTPFiler type
type SFTPFiler struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *SFTPFiler) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteTo provides a mock function with given fields: w
func (_m *SFTPFiler) WriteTo(w io.Writer) (int64, error) {
	ret := _m.Called(w)

	var r0 int64
	if rf, ok := ret.Get(0).(func(io.Writer) int64); ok {
		r0 = rf(w)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.Writer) error); ok {
		r1 = rf(w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
