// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	services "github.com/transcom/mymove/pkg/services"

	testing "testing"

	uuid "github.com/gofrs/uuid"
)

// ShipmentsPaymentSITBalance is an autogenerated mock type for the ShipmentsPaymentSITBalance type
type ShipmentsPaymentSITBalance struct {
	mock.Mock
}

// ListShipmentPaymentSITBalance provides a mock function with given fields: appCtx, paymentRequestID
func (_m *ShipmentsPaymentSITBalance) ListShipmentPaymentSITBalance(appCtx appcontext.AppContext, paymentRequestID uuid.UUID) ([]services.ShipmentPaymentSITBalance, error) {
	ret := _m.Called(appCtx, paymentRequestID)

	var r0 []services.ShipmentPaymentSITBalance
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) []services.ShipmentPaymentSITBalance); ok {
		r0 = rf(appCtx, paymentRequestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.ShipmentPaymentSITBalance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r1 = rf(appCtx, paymentRequestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShipmentsPaymentSITBalance creates a new instance of ShipmentsPaymentSITBalance. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewShipmentsPaymentSITBalance(t testing.TB) *ShipmentsPaymentSITBalance {
	mock := &ShipmentsPaymentSITBalance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
