// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	services "github.com/transcom/mymove/pkg/services"
)

// ShipmentBillableWeightCalculator is an autogenerated mock type for the ShipmentBillableWeightCalculator type
type ShipmentBillableWeightCalculator struct {
	mock.Mock
}

// CalculateShipmentBillableWeight provides a mock function with given fields: appCtx, shipment
func (_m *ShipmentBillableWeightCalculator) CalculateShipmentBillableWeight(appCtx appcontext.AppContext, shipment models.MTOShipment) (services.BillableWeightInputs, error) {
	ret := _m.Called(appCtx, shipment)

	var r0 services.BillableWeightInputs
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, models.MTOShipment) services.BillableWeightInputs); ok {
		r0 = rf(appCtx, shipment)
	} else {
		r0 = ret.Get(0).(services.BillableWeightInputs)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, models.MTOShipment) error); ok {
		r1 = rf(appCtx, shipment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
