// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/transcom/mymove/pkg/models"

	services "github.com/transcom/mymove/pkg/services"

	testing "testing"
)

// ShipmentBillableWeightCalculator is an autogenerated mock type for the ShipmentBillableWeightCalculator type
type ShipmentBillableWeightCalculator struct {
	mock.Mock
}

// CalculateShipmentBillableWeight provides a mock function with given fields: shipment
func (_m *ShipmentBillableWeightCalculator) CalculateShipmentBillableWeight(shipment *models.MTOShipment) (services.BillableWeightInputs, error) {
	ret := _m.Called(shipment)

	var r0 services.BillableWeightInputs
	if rf, ok := ret.Get(0).(func(*models.MTOShipment) services.BillableWeightInputs); ok {
		r0 = rf(shipment)
	} else {
		r0 = ret.Get(0).(services.BillableWeightInputs)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.MTOShipment) error); ok {
		r1 = rf(shipment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShipmentBillableWeightCalculator creates a new instance of ShipmentBillableWeightCalculator. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewShipmentBillableWeightCalculator(t testing.TB) *ShipmentBillableWeightCalculator {
	mock := &ShipmentBillableWeightCalculator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
