// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// ShipmentDiversionRequester is an autogenerated mock type for the ShipmentDiversionRequester type
type ShipmentDiversionRequester struct {
	mock.Mock
}

// RequestShipmentDiversion provides a mock function with given fields: shipmentID, eTag
func (_m *ShipmentDiversionRequester) RequestShipmentDiversion(shipmentID uuid.UUID, eTag string) (*models.MTOShipment, error) {
	ret := _m.Called(shipmentID, eTag)

	var r0 *models.MTOShipment
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) *models.MTOShipment); ok {
		r0 = rf(shipmentID, eTag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MTOShipment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(shipmentID, eTag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
