// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	testing "testing"

	uuid "github.com/gofrs/uuid"
)

// ShipmentDiversionRequester is an autogenerated mock type for the ShipmentDiversionRequester type
type ShipmentDiversionRequester struct {
	mock.Mock
}

// RequestShipmentDiversion provides a mock function with given fields: appCtx, shipmentID, eTag
func (_m *ShipmentDiversionRequester) RequestShipmentDiversion(appCtx appcontext.AppContext, shipmentID uuid.UUID, eTag string) (*models.MTOShipment, error) {
	ret := _m.Called(appCtx, shipmentID, eTag)

	var r0 *models.MTOShipment
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID, string) *models.MTOShipment); ok {
		r0 = rf(appCtx, shipmentID, eTag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MTOShipment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID, string) error); ok {
		r1 = rf(appCtx, shipmentID, eTag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShipmentDiversionRequester creates a new instance of ShipmentDiversionRequester. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewShipmentDiversionRequester(t testing.TB) *ShipmentDiversionRequester {
	mock := &ShipmentDiversionRequester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
