// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import apimessages "github.com/transcom/mymove/pkg/gen/apimessages"
import auth "github.com/transcom/mymove/pkg/auth"
import mock "github.com/stretchr/testify/mock"
import models "github.com/transcom/mymove/pkg/models"

import uuid "github.com/gofrs/uuid"
import validate "github.com/gobuffalo/validate"

// StorageInTransitCreator is an autogenerated mock type for the StorageInTransitCreator type
type StorageInTransitCreator struct {
	mock.Mock
}

// CreateStorageInTransit provides a mock function with given fields: storageInTransitPayload, shipmentID, session
func (_m *StorageInTransitCreator) CreateStorageInTransit(storageInTransitPayload apimessages.StorageInTransit, shipmentID uuid.UUID, session *auth.Session) (*models.StorageInTransit, *validate.Errors, error) {
	ret := _m.Called(storageInTransitPayload, shipmentID, session)

	var r0 *models.StorageInTransit
	if rf, ok := ret.Get(0).(func(apimessages.StorageInTransit, uuid.UUID, *auth.Session) *models.StorageInTransit); ok {
		r0 = rf(storageInTransitPayload, shipmentID, session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StorageInTransit)
		}
	}

	var r1 *validate.Errors
	if rf, ok := ret.Get(1).(func(apimessages.StorageInTransit, uuid.UUID, *auth.Session) *validate.Errors); ok {
		r1 = rf(storageInTransitPayload, shipmentID, session)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*validate.Errors)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(apimessages.StorageInTransit, uuid.UUID, *auth.Session) error); ok {
		r2 = rf(storageInTransitPayload, shipmentID, session)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
