// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	services "github.com/transcom/mymove/pkg/services"

	time "time"
)

// SyncadaSFTPReader is an autogenerated mock type for the SyncadaSFTPReader type
type SyncadaSFTPReader struct {
	mock.Mock
}

// FetchAndProcessSyncadaFiles provides a mock function with given fields: syncadaPath, lastRead, processor
func (_m *SyncadaSFTPReader) FetchAndProcessSyncadaFiles(syncadaPath string, lastRead time.Time, processor services.SyncadaFileProcessor) (time.Time, error) {
	ret := _m.Called(syncadaPath, lastRead, processor)

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(string, time.Time, services.SyncadaFileProcessor) time.Time); ok {
		r0 = rf(syncadaPath, lastRead, processor)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Time, services.SyncadaFileProcessor) error); ok {
		r1 = rf(syncadaPath, lastRead, processor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
