// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"
)

// TableFromSliceCreator is an autogenerated mock type for the TableFromSliceCreator type
type TableFromSliceCreator struct {
	mock.Mock
}

// CreateTableFromSlice provides a mock function with given fields: appCtx, slice
func (_m *TableFromSliceCreator) CreateTableFromSlice(appCtx appcontext.AppContext, slice interface{}) error {
	ret := _m.Called(appCtx, slice)

	if len(ret) == 0 {
		panic("no return value specified for CreateTableFromSlice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, interface{}) error); ok {
		r0 = rf(appCtx, slice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTableFromSliceCreator creates a new instance of TableFromSliceCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTableFromSliceCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TableFromSliceCreator {
	mock := &TableFromSliceCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
