// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// TransportationOfficeAssignmentFetcher is an autogenerated mock type for the TransportationOfficeAssignmentFetcher type
type TransportationOfficeAssignmentFetcher struct {
	mock.Mock
}

// FetchTransportationOfficeAssignmentsByOfficeUserID provides a mock function with given fields: appCtx, officeUserId
func (_m *TransportationOfficeAssignmentFetcher) FetchTransportationOfficeAssignmentsByOfficeUserID(appCtx appcontext.AppContext, officeUserId uuid.UUID) (models.TransportationOfficeAssignments, error) {
	ret := _m.Called(appCtx, officeUserId)

	if len(ret) == 0 {
		panic("no return value specified for FetchTransportationOfficeAssignmentsByOfficeUserID")
	}

	var r0 models.TransportationOfficeAssignments
	var r1 error
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) (models.TransportationOfficeAssignments, error)); ok {
		return rf(appCtx, officeUserId)
	}
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) models.TransportationOfficeAssignments); ok {
		r0 = rf(appCtx, officeUserId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.TransportationOfficeAssignments)
		}
	}

	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r1 = rf(appCtx, officeUserId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransportationOfficeAssignmentFetcher creates a new instance of TransportationOfficeAssignmentFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransportationOfficeAssignmentFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransportationOfficeAssignmentFetcher {
	mock := &TransportationOfficeAssignmentFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
