// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appconfig "github.com/transcom/mymove/pkg/appconfig"

	models "github.com/transcom/mymove/pkg/models"

	roles "github.com/transcom/mymove/pkg/models/roles"

	uuid "github.com/gofrs/uuid"
)

// UserRoleAssociator is an autogenerated mock type for the UserRoleAssociator type
type UserRoleAssociator struct {
	mock.Mock
}

// UpdateUserRoles provides a mock function with given fields: appCfg, userID, _a2
func (_m *UserRoleAssociator) UpdateUserRoles(appCfg appconfig.AppConfig, userID uuid.UUID, _a2 []roles.RoleType) ([]models.UsersRoles, error) {
	ret := _m.Called(appCfg, userID, _a2)

	var r0 []models.UsersRoles
	if rf, ok := ret.Get(0).(func(appconfig.AppConfig, uuid.UUID, []roles.RoleType) []models.UsersRoles); ok {
		r0 = rf(appCfg, userID, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UsersRoles)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appconfig.AppConfig, uuid.UUID, []roles.RoleType) error); ok {
		r1 = rf(appCfg, userID, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
