// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appconfig "github.com/transcom/mymove/pkg/appconfig"

	models "github.com/transcom/mymove/pkg/models"

	services "github.com/transcom/mymove/pkg/services"

	validate "github.com/gobuffalo/validate/v3"
)

// WebhookSubscriptionCreator is an autogenerated mock type for the WebhookSubscriptionCreator type
type WebhookSubscriptionCreator struct {
	mock.Mock
}

// CreateWebhookSubscription provides a mock function with given fields: appCfg, subscription, subscriberIDFilter
func (_m *WebhookSubscriptionCreator) CreateWebhookSubscription(appCfg appconfig.AppConfig, subscription *models.WebhookSubscription, subscriberIDFilter []services.QueryFilter) (*models.WebhookSubscription, *validate.Errors, error) {
	ret := _m.Called(appCfg, subscription, subscriberIDFilter)

	var r0 *models.WebhookSubscription
	if rf, ok := ret.Get(0).(func(appconfig.AppConfig, *models.WebhookSubscription, []services.QueryFilter) *models.WebhookSubscription); ok {
		r0 = rf(appCfg, subscription, subscriberIDFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WebhookSubscription)
		}
	}

	var r1 *validate.Errors
	if rf, ok := ret.Get(1).(func(appconfig.AppConfig, *models.WebhookSubscription, []services.QueryFilter) *validate.Errors); ok {
		r1 = rf(appCfg, subscription, subscriberIDFilter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*validate.Errors)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(appconfig.AppConfig, *models.WebhookSubscription, []services.QueryFilter) error); ok {
		r2 = rf(appCfg, subscription, subscriberIDFilter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
