// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	uuid "github.com/gofrs/uuid"
)

// WeightTicketCreator is an autogenerated mock type for the WeightTicketCreator type
type WeightTicketCreator struct {
	mock.Mock
}

// CreateWeightTicket provides a mock function with given fields: appCtx, ppmShipmentID
func (_m *WeightTicketCreator) CreateWeightTicket(appCtx appcontext.AppContext, ppmShipmentID uuid.UUID) (*models.WeightTicket, error) {
	ret := _m.Called(appCtx, ppmShipmentID)

	var r0 *models.WeightTicket
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, uuid.UUID) *models.WeightTicket); ok {
		r0 = rf(appCtx, ppmShipmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WeightTicket)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, uuid.UUID) error); ok {
		r1 = rf(appCtx, ppmShipmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWeightTicketCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewWeightTicketCreator creates a new instance of WeightTicketCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWeightTicketCreator(t mockConstructorTestingTNewWeightTicketCreator) *WeightTicketCreator {
	mock := &WeightTicketCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
