/* eslint-disable import/prefer-default-export */

export const profileStates = {
  EMPTY_PROFILE: 'EMPTY_PROFILE',
  DOD_INFO_COMPLETE: 'DOD_INFO_COMPLETE',
  NAME_COMPLETE: 'NAME_COMPLETE',
  CONTACT_INFO_COMPLETE: 'CONTACT_INFO_COMPLETE',
  DUTY_STATION_COMPLETE: 'DUTY_STATION_COMPLETE',
  ADDRESS_COMPLETE: 'ADDRESS_COMPLETE',
  BACKUP_ADDRESS_COMPLETE: 'BACKUP_ADDRESS_COMPLETE',
  BACKUP_CONTACTS_COMPLETE: 'BACKUP_CONTACTS_COMPLETE',
};

export const orderedProfileStates = [
  profileStates.EMPTY_PROFILE,
  profileStates.DOD_INFO_COMPLETE,
  profileStates.NAME_COMPLETE,
  profileStates.CONTACT_INFO_COMPLETE,
  profileStates.DUTY_STATION_COMPLETE,
  profileStates.ADDRESS_COMPLETE,
  profileStates.BACKUP_ADDRESS_COMPLETE,
  profileStates.BACKUP_CONTACTS_COMPLETE,
];
