const MOVE_STATUSES = {
  DRAFT: 'DRAFT',
  NEEDS_SERVICE_COUNSELING: 'NEEDS SERVICE COUNSELING',
  SERVICE_COUNSELING_COMPLETED: 'SERVICE COUNSELING COMPLETED',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  APPROVALS_REQUESTED: 'APPROVALS REQUESTED',
  CANCELED: 'CANCELED',
};

export default MOVE_STATUSES;
