export const ORDERS_TYPE = {
  PERMANENT_CHANGE_OF_STATION: 'PERMANENT_CHANGE_OF_STATION',
  LOCAL_MOVE: 'LOCAL_MOVE',
  RETIREMENT: 'RETIREMENT',
  SEPARATION: 'SEPARATION',
  TEMPORARY_DUTY: 'TEMPORARY_DUTY',
  EARLY_RETURN_OF_DEPENDENTS: 'EARLY_RETURN_OF_DEPENDENTS',
  STUDENT_TRAVEL: 'STUDENT_TRAVEL',
  WOUNDED_WARRIOR: 'WOUNDED_WARRIOR',
  BLUEBARK: 'BLUEBARK',
};

export const SPECIAL_ORDERS_TYPES = {
  WOUNDED_WARRIOR: 'Wounded Warrior',
  BLUEBARK: 'BLUEBARK',
  SAFETY: 'Safety',
  SAFETY_NON_LABEL: 'SAFETY',
};

export const CHECK_SPECIAL_ORDERS_TYPES = (ordersType) => {
  return ['BLUEBARK', 'WOUNDED_WARRIOR', 'SAFETY'].includes(ordersType);
};

export const ORDERS_TYPE_OPTIONS = {
  PERMANENT_CHANGE_OF_STATION: 'Permanent Change Of Station (PCS)',
  LOCAL_MOVE: 'Local Move',
  RETIREMENT: 'Retirement',
  SEPARATION: 'Separation',
  WOUNDED_WARRIOR: 'Wounded Warrior',
  BLUEBARK: 'BLUEBARK',
  TEMPORARY_DUTY: 'Temporary Duty (TDY)',
  EARLY_RETURN_OF_DEPENDENTS: 'Early Return of Dependents',
  STUDENT_TRAVEL: 'Student Travel',
};

export const ORDERS_TYPE_DETAILS = {
  HHG_PERMITTED: 'HHG_PERMITTED',
  PCS_TDY: 'PCS_TDY',
  HHG_RESTRICTED_PROHIBITED: 'HHG_RESTRICTED_PROHIBITED',
  HHG_RESTRICTED_AREA: 'HHG_RESTRICTED_AREA',
  INSTRUCTION_20_WEEKS: 'INSTRUCTION_20_WEEKS',
  HHG_PROHIBITED_20_WEEKS: 'HHG_PROHIBITED_20_WEEKS',
  DELAYED_APPROVAL: 'DELAYED_APPROVAL',
};

export const ORDERS_TYPE_DETAILS_OPTIONS = {
  HHG_PERMITTED: 'Shipment of HHG Permitted',
  PCS_TDY: 'PCS with TDY Enroute',
  HHG_RESTRICTED_PROHIBITED: 'Shipment of HHG Restricted or Prohibited',
  HHG_RESTRICTED_AREA: 'HHG Restricted Area-HHG Prohibited',
  INSTRUCTION_20_WEEKS: 'Course of Instruction 20 Weeks or More',
  HHG_PROHIBITED_20_WEEKS: 'Shipment of HHG Prohibited but Authorized within 20 weeks',
  DELAYED_APPROVAL: 'Delayed Approval 20 Weeks or More',
};

export const ORDERS_PAY_GRADE_TYPE = {
  E_1: 'E-1',
  E_2: 'E-2',
  E_3: 'E-3',
  E_4: 'E-4',
  E_5: 'E-5',
  E_6: 'E-6',
  E_7: 'E-7',
  E_8: 'E-8',
  E_9: 'E-9',
  E_9_SPECIAL_SENIOR_ENLISTED: 'E-9-SPECIAL-SENIOR-ENLISTED',
  O_1: 'O-1',
  O_2: 'O-2',
  O_3: 'O-3',
  O_4: 'O-4',
  O_5: 'O-5',
  O_6: 'O-6',
  O_7: 'O-7',
  O_8: 'O-8',
  O_9: 'O-9',
  O_10: 'O-10',
  W_1: 'W-1',
  W_2: 'W-2',
  W_3: 'W-3',
  W_4: 'W-4',
  W_5: 'W-5',
  AVIATION_CADET: 'AVIATION_CADET',
  CIVILIAN_EMPLOYEE: 'CIVILIAN_EMPLOYEE',
  ACADEMY_CADET: 'ACADEMY_CADET',
  MIDSHIPMAN: 'MIDSHIPMAN',
};

export const ORDERS_RANK_OPTIONS = {
  ARMY: {
    GEN: { rankAbbv: 'GEN', rankName: 'General' },
    LTG: { rankAbbv: 'LTG', rankName: 'Lieutenant General' },
    MG: { rankAbbv: 'MG', rankName: 'Major General' },
    BG: { rankAbbv: 'BG', rankName: 'Brigadier General' },
    COL: { rankAbbv: 'COL', rankName: 'Colonel' },
    LTC: { rankAbbv: 'LTC', rankName: 'Lieutenant Colonel' },
    MAJ: { rankAbbv: 'MAJ', rankName: 'Major' },
    CPT: { rankAbbv: 'CPT', rankName: 'Captain' },
    '1LT': { rankAbbv: '1LT', rankName: 'First Lieutenant' },
    '2LT': { rankAbbv: '2LT', rankName: 'Second Lieutenant' },
    OC: { rankAbbv: 'OC', rankName: 'Officer Candidate' },
    CDT: { rankAbbv: 'CDT', rankName: 'Cadet' },
    CW5: { rankAbbv: 'CW5', rankName: 'Chief Warrant Officer 5' },
    CW4: { rankAbbv: 'CW4', rankName: 'Chief Warrant Officer 4' },
    CW3: { rankAbbv: 'CW3', rankName: 'Chief Warrant Officer 3' },
    CW2: { rankAbbv: 'CW2', rankName: 'Chief Warrant Officer 2' },
    WO1: { rankAbbv: 'WO1', rankName: 'Warrant Officer 1' },
    SGM: { rankAbbv: 'SGM', rankName: 'Sergeant Major' },
    CSM: { rankAbbv: 'CSM', rankName: 'Command Sergeant Major' },
    MSG: { rankAbbv: 'MSG', rankName: 'Master Sergeant' },
    '1SG': { rankAbbv: '1SG', rankName: '1st Sergeant' },
    SFC: { rankAbbv: 'SFC', rankName: 'Sergeant First Class' },
    SSG: { rankAbbv: 'SSG', rankName: 'Staff Sergeant' },
    SGT: { rankAbbv: 'SGT', rankName: 'Sergeant' },
    CPL: { rankAbbv: 'CPL', rankName: 'Corporal' },
    SPC: { rankAbbv: 'SPC', rankName: 'Specialist' },
    PFC: { rankAbbv: 'PFC', rankName: 'Private First Class' },
    PV2: { rankAbbv: 'PV2', rankName: 'Private' },
    PV1: { rankAbbv: 'PV1', rankName: 'Private' },
    PVT: { rankAbbv: 'PVT', rankName: 'Private' },
  },
  AIR_FORCE: {
    GEN: { rankAbbv: 'Gen', rankName: 'General' },
    LTGEN: { rankAbbv: 'Lt Gen', rankName: 'Lieutenant General' },
    MAJGEN: { rankAbbv: 'Maj Gen', rankName: 'Major General' },
    BRIGGEN: { rankAbbv: 'Brig Gen', rankName: 'Brigadier General' },
    COL: { rankAbbv: 'Col', rankName: 'Colonel' },
    LTCOL: { rankAbbv: 'Lt Col', rankName: 'Lieutenant Colonel' },
    MAJOR: { rankAbbv: 'Maj', rankName: 'Major' },
    CAPTAIN: { rankAbbv: 'Capt', rankName: 'Captain' },
    '1stLt': { rankAbbv: '1st Lt', rankName: 'First Lieutenant' },
    AVC: { rankAbbv: 'AVC', rankName: 'Aviation Cadet' },
    '2dLt': { rankAbbv: '2d Lt', rankName: 'Second Lieutenant' },
    AFC: { rankAbbv: 'AFC', rankName: 'Air Force Academy Cadet' },
    CWO5: { rankAbbv: 'CWO5', rankName: 'Chief Warrant Officer 5' },
    CWO4: { rankAbbv: 'CWO4', rankName: 'Chief Warrant Officer 4' },
    CWO3: { rankAbbv: 'CWO3', rankName: 'Chief Warrant Officer 3' },
    CWO2: { rankAbbv: 'CWO2', rankName: 'Chief Warrant Officer 2' },
    WO: { rankAbbv: 'WO', rankName: 'Warrant Officer 1' },
    CMSgt: { rankAbbv: 'CMSgt', rankName: 'Chief Master Sergeant' },
    SMSgt: { rankAbbv: 'SMSgt', rankName: 'Senior Master Sergeant' },
    MSgt: { rankAbbv: 'MSgt', rankName: 'Master Sergeant' },
    TSgt: { rankAbbv: 'TSgt', rankName: 'Technical Sergeant' },
    SSgt: { rankAbbv: 'SSgt', rankName: 'Staff Sergeant' },
    SrA: { rankAbbv: 'SrA', rankName: 'Senior Airman' },
    A1C: { rankAbbv: 'A1C', rankName: 'Airman First Class' },
    Amn: { rankAbbv: 'Amn', rankName: 'Airman' },
    AB: { rankAbbv: 'AB', rankName: 'Airman Basic' },
  },
  MARINES: {
    GEN: { rankAbbv: 'Gen', rankName: 'General' },
    LTGEN: { rankAbbv: 'LtGen', rankName: 'Lieutenant General' },
    MAJGEN: { rankAbbv: 'MajGen', rankName: 'Major General' },
    BGEN: { rankAbbv: 'BGen', rankName: 'Brigadier General' },
    COL: { rankAbbv: 'Col', rankName: 'Colonel' },
    LTCOL: { rankAbbv: 'LtCol', rankName: 'Lieutenant Colonel' },
    MAJ: { rankAbbv: 'Maj', rankName: 'Major' },
    CAPT: { rankAbbv: 'Capt', rankName: 'Captain' },
    '1stLt': { rankAbbv: '1stLt', rankName: 'First Lieutenant' },
    '2ndLt': { rankAbbv: '2ndLt', rankName: 'Second Lieutenant' },
    CWO5: { rankAbbv: 'CWO5', rankName: 'Chief Warrant Officer 5' },
    CWO4: { rankAbbv: 'CWO4', rankName: 'Chief Warrant Officer 4' },
    CWO3: { rankAbbv: 'CWO3', rankName: 'Chief Warrant Officer 3' },
    CWO2: { rankAbbv: 'CWO2', rankName: 'Chief Warrant Officer 2' },
    WO: { rankAbbv: 'WO', rankName: 'Warrant Officer 1' },
    SGTMAJ: { rankAbbv: 'SgtMaj', rankName: 'Sergeant Major' },
    MGySgt: { rankAbbv: 'MGySgt', rankName: 'Master Gunnery Sergeant' },
    MSGgt: { rankAbbv: 'MSGgt', rankName: 'Master Sergeant' },
    '1stSgt': { rankAbbv: '1stSgt', rankName: '1st Sergeant' },
    GySgt: { rankAbbv: 'GySgt', rankName: 'Gunnery Sergeant' },
    SSgt: { rankAbbv: 'SSgt', rankName: 'Staff Sergeant' },
    Sgt: { rankAbbv: 'Sgt', rankName: 'Sergeant' },
    Cpl: { rankAbbv: 'Cpl', rankName: 'Corporal' },
    LCpl: { rankAbbv: 'LCpl', rankName: 'Lance Corporal' },
    PFC: { rankAbbv: 'PFC', rankName: 'Private First Class' },
    PVT: { rankAbbv: 'PVT', rankName: 'Private' },
  },
  NAVY: {
    ADM: { rankAbbv: 'ADM', rankName: 'Admiral' },
    VADM: { rankAbbv: 'VADM', rankName: 'Vice Admiral' },
    RADM: { rankAbbv: 'RADM', rankName: 'Rear Admiral (Upper Half)' },
    RDML: { rankAbbv: 'RDML', rankName: 'Rear Admiral (Lower Half)' },
    CAPT: { rankAbbv: 'CAPT', rankName: 'Captain' },
    CDR: { rankAbbv: 'CDR', rankName: 'Commander' },
    LCDR: { rankAbbv: 'LCDR', rankName: 'Lieutenant Commander' },
    LT: { rankAbbv: 'LT', rankName: 'Lieutenant' },
    LTJG: { rankAbbv: 'LTJG', rankName: 'Lieutenant JG' },
    ENS: { rankAbbv: 'ENS', rankName: 'Ensign' },
    MID: { rankAbbv: 'MID', rankName: 'Midshipman' },
    CWO5: { rankAbbv: 'CWO5', rankName: 'Chief Warrant Officer 5' },
    CWO4: { rankAbbv: 'CWO4', rankName: 'Chief Warrant Officer 4' },
    CWO3: { rankAbbv: 'CWO3', rankName: 'Chief Warrant Officer 3' },
    CWO2: { rankAbbv: 'CWO2', rankName: 'Chief Warrant Officer 2' },
    WO: { rankAbbv: 'WO', rankName: 'Warrant Officer 1' },
    MCPO: { rankAbbv: 'MCPO', rankName: 'Master Chief Petty Officer' },
    SCPO: { rankAbbv: 'SCPO', rankName: 'Senior Chief Petty Officer' },
    CPO: { rankAbbv: 'CPO', rankName: 'Chief Petty Officer' },
    PO1: { rankAbbv: 'PO1', rankName: 'Petty Officer First Class' },
    PO2: { rankAbbv: 'PO2', rankName: 'Petty Officer Second Class' },
    PO3: { rankAbbv: 'PO3', rankName: 'Petty Officer Third Class' },
    SN: { rankAbbv: 'SN', rankName: 'Seaman' },
    SA: { rankAbbv: 'SA', rankName: 'Seaman Apprentice' },
    SR: { rankAbbv: 'SR', rankName: 'Seaman Recruit' },
  },
  COAST_GUARD: {
    ADM: { rankAbbv: 'ADM', rankName: 'Admiral' },
    VADM: { rankAbbv: 'VADM', rankName: 'Vice Admiral' },
    RADM: { rankAbbv: 'RADM', rankName: 'Rear Admiral (Upper Half)' },
    RDML: { rankAbbv: 'RDML', rankName: 'Rear Admiral (Lower Half)' },
    CAPT: { rankAbbv: 'CAPT', rankName: 'Captain' },
    CDR: { rankAbbv: 'CDR', rankName: 'Commander' },
    LCDR: { rankAbbv: 'LCDR', rankName: 'Lieutenant Commander' },
    LT: { rankAbbv: 'LT', rankName: 'Lieutenant' },
    LTJG: { rankAbbv: 'LTJG', rankName: 'Lieutenant JG' },
    MID: { rankAbbv: 'MID', rankName: 'Midshipman' },
    ENS: { rankAbbv: 'ENS', rankName: 'Ensign' },
    CWO4: { rankAbbv: 'CWO4', rankName: 'Chief Warrant Officer 4' },
    CWO3: { rankAbbv: 'CWO3', rankName: 'Chief Warrant Officer 3' },
    CWO2: { rankAbbv: 'CWO2', rankName: 'Chief Warrant Officer 2' },
    CPM: { rankAbbv: 'CPM', rankName: 'Master Chief Petty Officer' },
    CPS: { rankAbbv: 'CPS', rankName: 'Senior Chief Petty Officer' },
    CPO: { rankAbbv: 'CPO', rankName: 'Chief Petty Officer' },
    PO1: { rankAbbv: 'PO1', rankName: 'Petty Officer First Class' },
    PO2: { rankAbbv: 'PO2', rankName: 'Petty Officer Second Class' },
    PO3: { rankAbbv: 'PO3', rankName: 'Petty Officer Third Class' },
    SN: { rankAbbv: 'SN', rankName: 'Seaman' },
    SA: { rankAbbv: 'SA', rankName: 'Seaman Apprentice' },
    SR: { rankAbbv: 'SR', rankName: 'Seaman Recruit' },
  },
  SPACE_FORCE: {
    GEN: { rankAbbv: 'Gen', rankName: 'General' },
    LTGEN: { rankAbbv: 'Lt Gen', rankName: 'Lieutenant General' },
    MAJGEN: { rankAbbv: 'Maj Gen', rankName: 'Major General' },
    BRIGGEN: { rankAbbv: 'Brig Gen', rankName: 'Brigadier General' },
    COL: { rankAbbv: 'Col', rankName: 'Colonel' },
    LTCOL: { rankAbbv: 'Lt Col', rankName: 'Lieutenant Colonel' },
    MAJOR: { rankAbbv: 'Maj', rankName: 'Major' },
    CAPTAIN: { rankAbbv: 'Capt', rankName: 'Captain' },
    '1st Lt': { rankAbbv: '1st Lt', rankName: 'First Lieutenant' },
    '2d Lt': { rankAbbv: '2d Lt', rankName: 'Second Lieutenant' },
    CMSgt: { rankAbbv: 'CMSgt', rankName: 'Chief Master Sergeant' },
    SMSgt: { rankAbbv: 'SMSgt', rankName: 'Senior Master Sergeant' },
    MSgt: { rankAbbv: 'MSgt', rankName: 'Master Sergeant' },
    TSgt: { rankAbbv: 'TSgt', rankName: 'Technical Sergeant' },
    Sgt: { rankAbbv: 'Sgt', rankName: 'Sergeant' },
    Spc4: { rankAbbv: 'Spc4', rankName: 'Specialist 4' },
    Spc3: { rankAbbv: 'Spc3', rankName: 'Specialist 3' },
    Spc2: { rankAbbv: 'Spc2', rankName: 'Specialist 2' },
    Spc1: { rankAbbv: 'Spc1', rankName: 'Specialist 1' },
  },
  OTHER: {
    CIV: 'Civilian',
  },
  CIVILIAN: {
    CIV: 'Civilian',
  },
};

export const ORDERS_BRANCH_OPTIONS = {
  ARMY: 'Army',
  NAVY: 'Navy',
  MARINES: 'Marine Corps',
  AIR_FORCE: 'Air Force',
  COAST_GUARD: 'Coast Guard',
  SPACE_FORCE: 'Space Force',
  OTHER: 'Other',
};

export const ORDERS_DEPARTMENT_INDICATOR = {
  NAVY_AND_MARINES: 'Navy and Marine Corps',
  ARMY: 'Army',
  ARMY_CORPS_OF_ENGINEERS: 'Army Corps of Engineers',
  AIR_AND_SPACE_FORCE: 'Air Force and Space Force',
  COAST_GUARD: 'Coast Guard',
  OFFICE_OF_SECRETARY_OF_DEFENSE: 'Office of the Secretary of Defense',
};
