export const ORDERS_TYPE = {
  PERMANENT_CHANGE_OF_STATION: 'PERMANENT_CHANGE_OF_STATION',
  RETIREMENT: 'RETIREMENT',
  SEPARATION: 'SEPARATION',
};

export const ORDERS_TYPE_OPTIONS = {
  PERMANENT_CHANGE_OF_STATION: 'Permanent Change Of Station (PCS)',
  RETIREMENT: 'Retirement',
  SEPARATION: 'Separation',
};

export const ORDERS_TYPE_DETAILS = {
  HHG_PERMITTED: 'HHG_PERMITTED',
  PCS_TDY: 'PCS_TDY',
  HHG_RESTRICTED_PROHIBITED: 'HHG_RESTRICTED_PROHIBITED',
  HHG_RESTRICTED_AREA: 'HHG_RESTRICTED_AREA',
  INSTRUCTION_20_WEEKS: 'INSTRUCTION_20_WEEKS',
  HHG_PROHIBITED_20_WEEKS: 'HHG_PROHIBITED_20_WEEKS',
  DELAYED_APPROVAL: 'DELAYED_APPROVAL',
};

export const ORDERS_TYPE_DETAILS_OPTIONS = {
  HHG_PERMITTED: 'Shipment of HHG Permitted',
  PCS_TDY: 'PCS with TDY Enroute',
  HHG_RESTRICTED_PROHIBITED: 'Shipment of HHG Restricted or Prohibited',
  HHG_RESTRICTED_AREA: 'HHG Restricted Area-HHG Prohibited',
  INSTRUCTION_20_WEEKS: 'Course of Instruction 20 Weeks or More',
  HHG_PROHIBITED_20_WEEKS: 'Shipment of HHG Prohibited but Authorized within 20 weeks',
  DELAYED_APPROVAL: 'Delayed Approval 20 Weeks or More',
};
