export const ORDERS_TYPE = {
  PERMANENT_CHANGE_OF_STATION: 'PERMANENT_CHANGE_OF_STATION',
  RETIREMENT: 'RETIREMENT',
  SEPARATION: 'SEPARATION',
};

export const ORDERS_TYPE_DETAILS = {
  HHG_PERMITTED: 'HHG_PERMITTED',
  PCS_TDY: 'PCS_TDY',
  HHG_RESTRICTED_PROHIBITED: 'HHG_RESTRICTED_PROHIBITED',
  HHG_RESTRICTED_AREA: 'HHG_RESTRICTED_AREA',
  INSTRUCTION_20_WEEKS: 'INSTRUCTION_20_WEEKS',
  HHG_PROHIBITED_20_WEEKS: 'HHG_PROHIBITED_20_WEEKS',
  DELAYED_APPROVAL: 'DELAYED_APPROVAL',
};
