export default {
  PENDING: 'PENDING',
  REVIEWED: 'REVIEWED',
  SENT_TO_GEX: 'SENT_TO_GEX',
  TPPS_RECEIVED: 'TPPS_RECEIVED',
  PAID: 'PAID',
  REVIEWED_AND_ALL_SERVICE_ITEMS_REJECTED: 'REVIEWED_AND_ALL_SERVICE_ITEMS_REJECTED',
  EDI_ERROR: 'EDI_ERROR',
  DEPRECATED: 'DEPRECATED',
};

export const PAYMENT_REQUEST_STATUS_LABELS = {
  PENDING: 'Payment Requested',
  REVIEWED: 'Reviewed',
  SENT_TO_GEX: 'Sent to GEX',
  TPPS_RECEIVED: 'TPPS Received',
  REVIEWED_AND_ALL_SERVICE_ITEMS_REJECTED: 'Rejected',
  PAID: 'TPPS Paid',
  EDI_ERROR: 'EDI Error',
  DEPRECATED: 'Deprecated',
};
