export default {
  PENDING: 'PENDING',
  REVIEWED: 'REVIEWED',
  SENT_TO_GEX: 'SENT_TO_GEX',
  RECEIVED_BY_GEX: 'RECEIVED_BY_GEX',
  PAID: 'PAID',
  REVIEWED_AND_ALL_SERVICE_ITEMS_REJECTED: 'REVIEWED_AND_ALL_SERVICE_ITEMS_REJECTED',
  EDI_ERROR: 'EDI_ERROR',
  DEPRECATED: 'DEPRECATED',
};

export const PAYMENT_REQUEST_STATUS_LABELS = {
  PENDING: 'Payment requested',
  REVIEWED: 'Reviewed',
  SENT_TO_GEX: 'Sent to GEX',
  RECEIVED_BY_GEX: 'Received',
  REVIEWED_AND_ALL_SERVICE_ITEMS_REJECTED: 'Rejected',
  PAID: 'Paid',
  EDI_ERROR: 'EDI error',
  DEPRECATED: 'Deprecated',
};
