const SERVICE_ITEM_STATUSES = {
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const SERVICE_ITEM_PARAM_KEYS = {
  ActualPickupDate: 'ActualPickupDate',
  ContractYearName: 'ContractYearName',
  DestinationPrice: 'DestinationPrice',
  DistanceZip3: 'DistanceZip3',
  DistanceZip5: 'DistanceZip5',
  DistanceZipSITDest: 'DistanceZipSITDest',
  EIAFuelPrice: 'EIAFuelPrice',
  EscalationCompounded: 'EscalationCompounded',
  FSCWeightBasedDistanceMultiplier: 'FSCWeightBasedDistanceMultiplier',
  IsPeak: 'IsPeak',
  NumberDaysSIT: 'NumberDaysSIT',
  OriginPrice: 'OriginPrice',
  PriceRateOrFactor: 'PriceRateOrFactor',
  RequestedPickupDate: 'RequestedPickupDate',
  ServiceAreaDest: 'ServiceAreaDest',
  ServiceAreaOrigin: 'ServiceAreaOrigin',
  ServiceSchedule: 'ServiceSchedule',
  ServicesScheduleDest: 'ServicesScheduleDest',
  ServicesScheduleOrigin: 'ServicesScheduleOrigin',
  SITScheduleDest: 'SITScheduleDest',
  WeightActual: 'WeightActual',
  WeightBilledActual: 'WeightBilledActual',
  WeightEstimated: 'WeightEstimated',
  ZipDestAddress: 'ZipDestAddress',
  ZipPickupAddress: 'ZipPickupAddress',
  ZipSITDestHHGFinalAddress: 'ZipSITDestHHGFinalAddress',
};

const SERVICE_ITEM_CALCULATION_LABELS = {
  [SERVICE_ITEM_PARAM_KEYS.ActualPickupDate]: 'Pickup date',
  [SERVICE_ITEM_PARAM_KEYS.ContractYearName]: 'Base year',
  [SERVICE_ITEM_PARAM_KEYS.DestinationPrice]: 'Destination price',
  [SERVICE_ITEM_PARAM_KEYS.EIAFuelPrice]: 'EIA diesel',
  [SERVICE_ITEM_PARAM_KEYS.FSCWeightBasedDistanceMultiplier]: 'Weight-based distance multiplier',
  [SERVICE_ITEM_PARAM_KEYS.IsPeak]: 'Domestic',
  [SERVICE_ITEM_PARAM_KEYS.OriginPrice]: 'Origin price',
  [SERVICE_ITEM_PARAM_KEYS.RequestedPickupDate]: 'Requested pickup',
  [SERVICE_ITEM_PARAM_KEYS.ServiceAreaOrigin]: 'Origin service area',
  [SERVICE_ITEM_PARAM_KEYS.ServicesScheduleDest]: 'Destination service schedule',
  [SERVICE_ITEM_PARAM_KEYS.ServicesScheduleOrigin]: 'Origin service schedule',
  [SERVICE_ITEM_PARAM_KEYS.SITScheduleDest]: 'Destination SIT schedule',
  [SERVICE_ITEM_PARAM_KEYS.WeightActual]: 'Shipment weight',
  [SERVICE_ITEM_PARAM_KEYS.WeightBilledActual]: 'Shipment weight',
  [SERVICE_ITEM_PARAM_KEYS.WeightEstimated]: 'Estimated',
  [SERVICE_ITEM_PARAM_KEYS.ZipDestAddress]: 'ZIP',
  [SERVICE_ITEM_PARAM_KEYS.ZipPickupAddress]: 'ZIP',
  [SERVICE_ITEM_PARAM_KEYS.ZipSITDestHHGFinalAddress]: 'ZIP',
  AdditionalDaySITPrice: 'Additional day SIT price',
  BaselineLinehaulPrice: 'Baseline linehaul price',
  BaselineShorthaulPrice: 'Baseline shorthaul price',
  BillableWeight: 'Billable weight (cwt)',
  DaysInSIT: 'Days in SIT',
  FuelSurchargePrice: 'Fuel surcharge price (per mi)',
  Mileage: 'Mileage',
  PackPrice: 'Pack price',
  PriceEscalationFactor: 'Price escalation factor',
  ServiceArea: 'Service area',
  ServiceSchedule: 'Service schedule',
  SITDeliveryPrice: 'SIT delivery price',
  TotalAmountRequested: 'Total amount requested',
  UnpackPrice: 'Unpack price',
};

const SERVICE_ITEM_CODES = {
  DDDSIT: 'DDDSIT',
  DLH: 'DLH',
  DPK: 'DPK',
  FSC: 'FSC',
  DOP: 'DOP',
  DDP: 'DDP',
  DSH: 'DSH',
  DOASIT: 'DOASIT',
  DOFSIT: 'DOFSIT',
  DUPK: 'DUPK',
};

// TODO - temporary, will remove once all service item calculations are implemented
const allowedServiceItemCalculations = [
  SERVICE_ITEM_CODES.DDDSIT,
  SERVICE_ITEM_CODES.DDP,
  SERVICE_ITEM_CODES.DLH,
  SERVICE_ITEM_CODES.DOASIT,
  SERVICE_ITEM_CODES.DOFSIT,
  SERVICE_ITEM_CODES.DOP,
  SERVICE_ITEM_CODES.DPK,
  SERVICE_ITEM_CODES.DSH,
  SERVICE_ITEM_CODES.DUPK,
  SERVICE_ITEM_CODES.FSC,
];

export {
  SERVICE_ITEM_STATUSES as default,
  SERVICE_ITEM_PARAM_KEYS,
  SERVICE_ITEM_CALCULATION_LABELS,
  SERVICE_ITEM_CODES,
  allowedServiceItemCalculations,
};
