export const AFFILIATION = {
  ARMY: 'ARMY',
  NAVY: 'NAVY',
  MARINES: 'MARINES',
  AIR_FORCE: 'AIR_FORCE',
  COAST_GUARD: 'COAST_GUARD',
};

export const RANK = {
  E_1: 'E_1',
  E_2: 'E_2',
  E_3: 'E_3',
  E_4: 'E_4',
  E_5: 'E_5',
  E_6: 'E_6',
  E_7: 'E_7',
  E_8: 'E_8',
  E_9: 'E_9',
  O_1_ACADEMY_GRADUATE: 'O_1_ACADEMY_GRADUATE',
  O_2: 'O_2',
  O_3: 'O_3',
  O_4: 'O_4',
  O_5: 'O_5',
  O_6: 'O_6',
  O_7: 'O_7',
  O_8: 'O_8',
  O_9: 'O_9',
  O_10: 'O_10',
  W_1: 'W_1',
  W_2: 'W_2',
  W_3: 'W_3',
  W_4: 'W_4',
  W_5: 'W_5',
  AVIATION_CADET: 'AVIATION_CADET',
  CIVILIAN_EMPLOYEE: 'CIVILIAN_EMPLOYEE',
  ACADEMY_CADET: 'ACADEMY_CADET',
  MIDSHIPMAN: 'MIDSHIPMAN',
};
