const SERVICE_ITEM_STATUSES = {
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const SERVICE_ITEM_PARAM_KEYS = {
  ActualPickupDate: 'ActualPickupDate',
  ContractYearName: 'ContractYearName',
  CubicFeetCrating: 'CubicFeetCrating',
  CubicFeetBilled: 'CubicFeetBilled',
  DestinationPrice: 'DestinationPrice',
  DimensionHeight: 'DimensionHeight',
  DimensionLength: 'DimensionLength',
  DimensionWidth: 'DimensionWidth',
  DistanceZip3: 'DistanceZip3',
  DistanceZip5: 'DistanceZip5',
  DistanceZipSITDest: 'DistanceZipSITDest',
  DistanceZipSITOrigin: 'DistanceZipSITOrigin',
  EIAFuelPrice: 'EIAFuelPrice',
  EscalationCompounded: 'EscalationCompounded',
  FSCWeightBasedDistanceMultiplier: 'FSCWeightBasedDistanceMultiplier',
  IsPeak: 'IsPeak',
  NTSPackingFactor: 'NTSPackingFactor',
  NumberDaysSIT: 'NumberDaysSIT',
  OriginPrice: 'OriginPrice',
  PriceRateOrFactor: 'PriceRateOrFactor',
  ReferenceDate: 'ReferenceDate',
  RequestedDeliveryDate: 'RequestedDeliveryDate',
  RequestedPickupDate: 'RequestedPickupDate',
  ServiceAreaDest: 'ServiceAreaDest',
  ServiceAreaOrigin: 'ServiceAreaOrigin',
  ServiceSchedule: 'ServiceSchedule',
  ServicesScheduleDest: 'ServicesScheduleDest',
  ServicesScheduleOrigin: 'ServicesScheduleOrigin',
  SITScheduleDest: 'SITScheduleDest',
  SITScheduleOrigin: 'SITScheduleOrigin',
  WeightAdjusted: 'WeightAdjusted',
  WeightOriginal: 'WeightOriginal',
  WeightBilled: 'WeightBilled',
  WeightEstimated: 'WeightEstimated',
  WeightReweigh: 'WeightReweigh',
  ZipDestAddress: 'ZipDestAddress',
  ZipPickupAddress: 'ZipPickupAddress',
  ZipSITDestHHGFinalAddress: 'ZipSITDestHHGFinalAddress',
  ZipSITOriginHHGActualAddress: 'ZipSITOriginHHGActualAddress',
  ZipSITOriginHHGOriginalAddress: 'ZipSITOriginHHGOriginalAddress',
};

const SERVICE_ITEM_CALCULATION_LABELS = {
  [SERVICE_ITEM_PARAM_KEYS.ActualPickupDate]: 'Pickup date',
  [SERVICE_ITEM_PARAM_KEYS.ContractYearName]: 'Base year',
  [SERVICE_ITEM_PARAM_KEYS.DestinationPrice]: 'Destination price',
  [SERVICE_ITEM_PARAM_KEYS.EIAFuelPrice]: 'EIA diesel',
  [SERVICE_ITEM_PARAM_KEYS.FSCWeightBasedDistanceMultiplier]: 'Weight-based distance multiplier',
  // Domestic non-peak or Domestic peak
  [SERVICE_ITEM_PARAM_KEYS.IsPeak]: 'Domestic',
  [SERVICE_ITEM_PARAM_KEYS.OriginPrice]: 'Origin price',
  [SERVICE_ITEM_PARAM_KEYS.ReferenceDate]: 'Requested pickup',
  [SERVICE_ITEM_PARAM_KEYS.RequestedPickupDate]: 'Requested pickup',
  [SERVICE_ITEM_PARAM_KEYS.ServiceAreaOrigin]: 'Origin service area',
  [SERVICE_ITEM_PARAM_KEYS.ServiceAreaDest]: 'Destination service area',
  [SERVICE_ITEM_PARAM_KEYS.ServicesScheduleDest]: 'Destination service schedule',
  [SERVICE_ITEM_PARAM_KEYS.ServicesScheduleOrigin]: 'Origin service schedule',
  [SERVICE_ITEM_PARAM_KEYS.SITScheduleDest]: 'Destination SIT schedule',
  [SERVICE_ITEM_PARAM_KEYS.SITScheduleOrigin]: 'Origin SIT schedule',
  [SERVICE_ITEM_PARAM_KEYS.WeightAdjusted]: 'Adjusted',
  [SERVICE_ITEM_PARAM_KEYS.WeightOriginal]: 'Original',
  [SERVICE_ITEM_PARAM_KEYS.WeightBilled]: 'Shipment weight',
  [SERVICE_ITEM_PARAM_KEYS.WeightEstimated]: 'Estimated',
  [SERVICE_ITEM_PARAM_KEYS.WeightReweigh]: 'Reweigh',
  [SERVICE_ITEM_PARAM_KEYS.ZipDestAddress]: 'ZIP',
  [SERVICE_ITEM_PARAM_KEYS.ZipPickupAddress]: 'ZIP',
  [SERVICE_ITEM_PARAM_KEYS.ZipSITDestHHGFinalAddress]: 'ZIP',
  AdditionalDaySITPrice: 'Additional day SIT price',
  BaselineLinehaulPrice: 'Baseline linehaul price',
  BaselineShorthaulPrice: 'Baseline shorthaul price',
  BillableWeight: 'Billable weight (cwt)',
  CratingDate: 'Crating date',
  CratingPrice: 'Crating price (per cu ft)',
  CubicFeetBilled: 'Crating size (cu ft)',
  DaysInSIT: 'SIT days invoiced',
  DeliveryDate: 'Delivery date',
  Description: 'Description',
  DestinationSchedule: 'Destination schedule',
  Dimensions: 'Dimensions',
  Domestic: 'Domestic',
  FuelSurchargePrice: 'Fuel surcharge price (per mi)',
  Mileage: 'Mileage',
  NTSPackingFactor: 'NTS packing factor',
  NTSReleaseReferenceDate: 'Actual pickup',
  PackPrice: 'Pack price',
  PickupDate: 'Pickup date',
  PickupSITPrice: 'SIT pickup price',
  PriceEscalationFactor: 'Price escalation factor',
  ServiceSchedule: 'Service schedule',
  ShuttleWeight: 'Shuttle weight',
  SITDeliveryPrice: 'SIT delivery price',
  TotalAmountRequested: 'Total amount requested',
  UnpackPrice: 'Unpack price',
  UncratingDate: 'Uncrating date',
  UncratingPrice: 'Uncrating price (per cu ft)',
};

const SERVICE_ITEM_CODES = {
  DDASIT: 'DDASIT',
  DDDSIT: 'DDDSIT',
  DDFSIT: 'DDFSIT',
  DDP: 'DDP',
  DLH: 'DLH',
  DOASIT: 'DOASIT',
  DOFSIT: 'DOFSIT',
  DOP: 'DOP',
  DOPSIT: 'DOPSIT',
  DOSHUT: 'DOSHUT',
  DPK: 'DPK',
  DNPK: 'DNPK',
  DSH: 'DSH',
  DUPK: 'DUPK',
  FSC: 'FSC',
  DDSHUT: 'DDSHUT',
  DCRT: 'DCRT',
  DUCRT: 'DUCRT',
};

// TODO - temporary, will remove once all service item calculations are implemented
const allowedServiceItemCalculations = [
  SERVICE_ITEM_CODES.DDASIT,
  SERVICE_ITEM_CODES.DDDSIT,
  SERVICE_ITEM_CODES.DDFSIT,
  SERVICE_ITEM_CODES.DDP,
  SERVICE_ITEM_CODES.DLH,
  SERVICE_ITEM_CODES.DOASIT,
  SERVICE_ITEM_CODES.DOFSIT,
  SERVICE_ITEM_CODES.DOP,
  SERVICE_ITEM_CODES.DOPSIT,
  SERVICE_ITEM_CODES.DOSHUT,
  SERVICE_ITEM_CODES.DPK,
  SERVICE_ITEM_CODES.DNPK,
  SERVICE_ITEM_CODES.DSH,
  SERVICE_ITEM_CODES.DUPK,
  SERVICE_ITEM_CODES.FSC,
  SERVICE_ITEM_CODES.DDSHUT,
  SERVICE_ITEM_CODES.DCRT,
  SERVICE_ITEM_CODES.DUCRT,
];

export default SERVICE_ITEM_STATUSES;

export { SERVICE_ITEM_PARAM_KEYS, SERVICE_ITEM_CALCULATION_LABELS, SERVICE_ITEM_CODES, allowedServiceItemCalculations };
