const SERVICE_ITEM_STATUSES = {
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const SERVICE_ITEM_PARAM_KEYS = {
  ActualPickupDate: 'ActualPickupDate',
  ContractYearName: 'ContractYearName',
  CubicFeetCrating: 'CubicFeetCrating',
  CubicFeetBilled: 'CubicFeetBilled',
  DestinationPrice: 'DestinationPrice',
  DimensionHeight: 'DimensionHeight',
  DimensionLength: 'DimensionLength',
  DimensionWidth: 'DimensionWidth',
  DistanceZip: 'DistanceZip',
  DistanceZipSITDest: 'DistanceZipSITDest',
  DistanceZipSITOrigin: 'DistanceZipSITOrigin',
  EIAFuelPrice: 'EIAFuelPrice',
  FSCPriceDifferenceInCents: 'FSCPriceDifferenceInCents',
  EscalationCompounded: 'EscalationCompounded',
  FSCWeightBasedDistanceMultiplier: 'FSCWeightBasedDistanceMultiplier',
  IsPeak: 'IsPeak',
  NTSPackingFactor: 'NTSPackingFactor',
  NumberDaysSIT: 'NumberDaysSIT',
  OriginPrice: 'OriginPrice',
  PriceRateOrFactor: 'PriceRateOrFactor',
  ReferenceDate: 'ReferenceDate',
  RequestedDeliveryDate: 'RequestedDeliveryDate',
  RequestedPickupDate: 'RequestedPickupDate',
  ServiceAreaDest: 'ServiceAreaDest',
  ServiceAreaOrigin: 'ServiceAreaOrigin',
  ServiceSchedule: 'ServiceSchedule',
  ServicesScheduleDest: 'ServicesScheduleDest',
  ServicesScheduleOrigin: 'ServicesScheduleOrigin',
  SITScheduleDest: 'SITScheduleDest',
  SITScheduleOrigin: 'SITScheduleOrigin',
  SITServiceAreaDest: 'SITServiceAreaDest',
  SITServiceAreaOrigin: 'SITServiceAreaOrigin',
  Total: 'TotalAmountRequested',
  WeightAdjusted: 'WeightAdjusted',
  WeightOriginal: 'WeightOriginal',
  WeightBilled: 'WeightBilled',
  WeightEstimated: 'WeightEstimated',
  WeightReweigh: 'WeightReweigh',
  ZipDestAddress: 'ZipDestAddress',
  ZipPickupAddress: 'ZipPickupAddress',
  ZipSITDestHHGFinalAddress: 'ZipSITDestHHGFinalAddress',
  ZipSITDestHHGOriginalAddress: 'ZipSITDestHHGOriginalAddress',
  ZipSITOriginHHGActualAddress: 'ZipSITOriginHHGActualAddress',
  ZipSITOriginHHGOriginalAddress: 'ZipSITOriginHHGOriginalAddress',
  StandaloneCrate: 'StandaloneCrate',
  StandaloneCrateCap: 'StandaloneCrateCap',
  UncappedRequestTotal: 'UncappedRequestTotal',
};

const SERVICE_ITEM_CALCULATION_LABELS = {
  [SERVICE_ITEM_PARAM_KEYS.ActualPickupDate]: 'Pickup date',
  [SERVICE_ITEM_PARAM_KEYS.ContractYearName]: 'Base year',
  [SERVICE_ITEM_PARAM_KEYS.DestinationPrice]: 'Destination price',
  [SERVICE_ITEM_PARAM_KEYS.EIAFuelPrice]: 'EIA diesel',
  [SERVICE_ITEM_PARAM_KEYS.FSCPriceDifferenceInCents]: 'Baseline rate difference',
  [SERVICE_ITEM_PARAM_KEYS.FSCWeightBasedDistanceMultiplier]: 'Weight-based distance multiplier',
  // Domestic non-peak or Domestic peak
  [SERVICE_ITEM_PARAM_KEYS.IsPeak]: 'Domestic',
  [SERVICE_ITEM_PARAM_KEYS.OriginPrice]: 'Origin price',
  [SERVICE_ITEM_PARAM_KEYS.ReferenceDate]: 'Requested pickup',
  [SERVICE_ITEM_PARAM_KEYS.RequestedPickupDate]: 'Requested pickup',
  [SERVICE_ITEM_PARAM_KEYS.ServiceAreaOrigin]: 'Origin service area',
  [SERVICE_ITEM_PARAM_KEYS.ServiceAreaDest]: 'Destination service area',
  [SERVICE_ITEM_PARAM_KEYS.ServicesScheduleDest]: 'Destination service schedule',
  [SERVICE_ITEM_PARAM_KEYS.ServicesScheduleOrigin]: 'Origin service schedule',
  [SERVICE_ITEM_PARAM_KEYS.SITScheduleDest]: 'Destination SIT schedule',
  [SERVICE_ITEM_PARAM_KEYS.SITScheduleOrigin]: 'Origin SIT schedule',
  [SERVICE_ITEM_PARAM_KEYS.SITServiceAreaDest]: 'SIT destination service area',
  [SERVICE_ITEM_PARAM_KEYS.SITServiceAreaOrigin]: 'SIT origin service area',
  [SERVICE_ITEM_PARAM_KEYS.Total]: 'Total',
  [SERVICE_ITEM_PARAM_KEYS.WeightAdjusted]: 'Adjusted',
  [SERVICE_ITEM_PARAM_KEYS.WeightOriginal]: 'Original',
  [SERVICE_ITEM_PARAM_KEYS.WeightBilled]: 'Shipment weight',
  [SERVICE_ITEM_PARAM_KEYS.WeightEstimated]: 'Estimated',
  [SERVICE_ITEM_PARAM_KEYS.WeightReweigh]: 'Reweigh',
  [SERVICE_ITEM_PARAM_KEYS.ZipDestAddress]: 'ZIP',
  [SERVICE_ITEM_PARAM_KEYS.ZipPickupAddress]: 'ZIP',
  [SERVICE_ITEM_PARAM_KEYS.ZipSITDestHHGFinalAddress]: 'ZIP',
  [SERVICE_ITEM_PARAM_KEYS.ZipSITDestHHGOriginalAddress]: 'ZIP',
  AdditionalDaySITPrice: 'Additional day SIT price',
  BaselineLinehaulPrice: 'Baseline linehaul price',
  BaselineShorthaulPrice: 'Baseline shorthaul price',
  BillableWeight: 'Billable weight (cwt)',
  CratingDate: 'Crating date',
  CratingPrice: 'Crating price (per cu ft)',
  CubicFeetBilled: 'Crating size (cu ft)',
  DaysInSIT: 'SIT days invoiced',
  DeliveryDate: 'Delivery date',
  Description: 'Description',
  DestinationSchedule: 'Destination schedule',
  Dimensions: 'Dimensions',
  Domestic: 'Domestic',
  FuelSurchargePrice: 'Mileage factor',
  Mileage: 'Mileage',
  MileageIntoSIT: 'Mileage into SIT',
  MileageOutOfSIT: 'Mileage out of SIT',
  NTSPackingFactor: 'NTS packing factor',
  NTSReleaseReferenceDate: 'Actual pickup',
  PackPrice: 'Pack price',
  PickupDate: 'Pickup date',
  PickupSITPrice: 'SIT pickup price',
  PriceEscalationFactor: 'Price escalation factor',
  ServiceSchedule: 'Service schedule',
  ShuttleWeight: 'Shuttle weight',
  SITDeliveryPrice: 'SIT delivery price',
  FuelRateAdjustment: 'Fuel rate adjustment',
  UnpackPrice: 'Unpack price',
  UncratingDate: 'Uncrating date',
  UncratingPrice: 'Uncrating price (per cu ft)',
  SITFuelSurchargePrice: 'SIT mileage factor',
  StandaloneCrate: 'Standalone Crate Cap',
  UncappedRequestTotal: 'Uncapped Request Total',
  Total: 'Total',
};

const SERVICE_ITEM_CODES = {
  CS: 'CS',
  DDASIT: 'DDASIT',
  DDDSIT: 'DDDSIT',
  DDFSIT: 'DDFSIT',
  DDP: 'DDP',
  DLH: 'DLH',
  DOASIT: 'DOASIT',
  DOFSIT: 'DOFSIT',
  DOP: 'DOP',
  DOPSIT: 'DOPSIT',
  DOSHUT: 'DOSHUT',
  DPK: 'DPK',
  DNPK: 'DNPK',
  DSH: 'DSH',
  DUPK: 'DUPK',
  FSC: 'FSC',
  DDSHUT: 'DDSHUT',
  DCRT: 'DCRT',
  DUCRT: 'DUCRT',
  MS: 'MS',
  DOSFSC: 'DOSFSC',
  DDSFSC: 'DDSFSC',
  IDASIT: 'IDASIT',
  IDDSIT: 'IDDSIT',
  IDFSIT: 'IDFSIT',
  IOASIT: 'IOASIT',
  IOFSIT: 'IOFSIT',
  IOPSIT: 'IOPSIT',
  IOSFSC: 'IOSFSC',
  IDSFSC: 'IDSFSC',
};

const SERVICE_ITEMS_ALLOWED_WEIGHT_BILLED_PARAM = [
  SERVICE_ITEM_CODES.DDASIT,
  SERVICE_ITEM_CODES.DDDSIT,
  SERVICE_ITEM_CODES.DDFSIT,
  SERVICE_ITEM_CODES.DOASIT,
  SERVICE_ITEM_CODES.DOFSIT,
  SERVICE_ITEM_CODES.DOPSIT,
  SERVICE_ITEM_CODES.DOSHUT,
  SERVICE_ITEM_CODES.DDSHUT,
  SERVICE_ITEM_CODES.DLH,
  SERVICE_ITEM_CODES.DSH,
  SERVICE_ITEM_CODES.DUPK,
  SERVICE_ITEM_CODES.DNPK,
  SERVICE_ITEM_CODES.FSC,
];

const SIT_SERVICE_ITEMS_ALLOWED_UPDATE = [
  SERVICE_ITEM_CODES.DDDSIT,
  SERVICE_ITEM_CODES.DDASIT,
  SERVICE_ITEM_CODES.DOASIT,
  SERVICE_ITEM_CODES.DOFSIT,
  SERVICE_ITEM_CODES.DOPSIT,
  SERVICE_ITEM_CODES.DDFSIT,
  SERVICE_ITEM_CODES.DOSFSC,
  SERVICE_ITEM_CODES.DDSFSC,
  SERVICE_ITEM_CODES.IDDSIT,
  SERVICE_ITEM_CODES.IDASIT,
  SERVICE_ITEM_CODES.IOASIT,
  SERVICE_ITEM_CODES.IOFSIT,
  SERVICE_ITEM_CODES.IOPSIT,
  SERVICE_ITEM_CODES.IDFSIT,
  SERVICE_ITEM_CODES.IOSFSC,
  SERVICE_ITEM_CODES.IDSFSC,
];

/**
 * @description Service item codes related to storage in transit (SIT).
 * */
const SIT_SERVICE_ITEM_CODES = {
  /** Domestic origin 1st day SIT */
  DOFSIT: 'DOFSIT',
  /** Domestic origin Additional day SIT */
  DOASIT: 'DOASIT',
  /** Domestic origin SIT pickup */
  DOPSIT: 'DOPSIT',
  /** Domestic destination 1st day SIT */
  DDFSIT: 'DDFSIT',
  /** Domestic destination Additional day SIT */
  DDASIT: 'DDASIT',
  /** Domestic destination SIT delivery */
  DDDSIT: 'DDDSIT',
  /** International origin 1st day SIT */
  IOFSIT: 'IOFSIT',
  /** International origin Additional day SIT */
  IOASIT: 'IOASIT',
  /** International origin SIT pickup */
  IOPSIT: 'IOPSIT',
  /** International destination 1st day SIT */
  IDFSIT: 'IDFSIT',
  /** International destination Additional day SIT */
  IDASIT: 'IDASIT',
  /** International destination SIT delivery */
  IDDSIT: 'IDDSIT',
};

// TODO - temporary, will remove once all service item calculations are implemented
const allowedServiceItemCalculations = [
  SERVICE_ITEM_CODES.DDASIT,
  SERVICE_ITEM_CODES.DDDSIT,
  SERVICE_ITEM_CODES.DDFSIT,
  SERVICE_ITEM_CODES.DDP,
  SERVICE_ITEM_CODES.DLH,
  SERVICE_ITEM_CODES.DOASIT,
  SERVICE_ITEM_CODES.DOFSIT,
  SERVICE_ITEM_CODES.DOP,
  SERVICE_ITEM_CODES.DOPSIT,
  SERVICE_ITEM_CODES.DOSHUT,
  SERVICE_ITEM_CODES.DPK,
  SERVICE_ITEM_CODES.DNPK,
  SERVICE_ITEM_CODES.DSH,
  SERVICE_ITEM_CODES.DUPK,
  SERVICE_ITEM_CODES.FSC,
  SERVICE_ITEM_CODES.DDSHUT,
  SERVICE_ITEM_CODES.DCRT,
  SERVICE_ITEM_CODES.DUCRT,
  SERVICE_ITEM_CODES.DOSFSC,
  SERVICE_ITEM_CODES.DDSFSC,
];

export default SERVICE_ITEM_STATUSES;

export {
  SERVICE_ITEM_PARAM_KEYS,
  SERVICE_ITEM_CALCULATION_LABELS,
  SERVICE_ITEM_CODES,
  SIT_SERVICE_ITEM_CODES,
  allowedServiceItemCalculations,
  SERVICE_ITEM_STATUSES,
  SERVICE_ITEMS_ALLOWED_WEIGHT_BILLED_PARAM,
  SIT_SERVICE_ITEMS_ALLOWED_UPDATE,
};
