export const TOTAL_WEIGHT_SELF = 'total_weight_self';
export const TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS = 'total_weight_self_plus_dependents';
export const PRO_GEAR_WEIGHT = 'pro_gear_weight';
export const PRO_GEAR_WEIGHT_SPOUSE = 'pro_gear_weight_spouse';

const WEIGHT_ENTITLEMENTS = {
  E_1: {
    total_weight_self: 5000,
    total_weight_self_plus_dependents: 8000,
    pro_gear_weight: 2000,
    pro_gear_weight_spouse: 500,
  },
  E_2: {
    [TOTAL_WEIGHT_SELF]: 5000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 8000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  E_3: {
    [TOTAL_WEIGHT_SELF]: 5000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 8000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  E_4: {
    [TOTAL_WEIGHT_SELF]: 7000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 8000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  E_5: {
    [TOTAL_WEIGHT_SELF]: 7000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 8000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  E_6: {
    [TOTAL_WEIGHT_SELF]: 8000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 11000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  E_7: {
    [TOTAL_WEIGHT_SELF]: 11000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 13000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  E_8: {
    [TOTAL_WEIGHT_SELF]: 12000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 14000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  E_9: {
    [TOTAL_WEIGHT_SELF]: 13000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 15000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  E_9_SPECIAL_SENIOR_ENLISTED: {
    [TOTAL_WEIGHT_SELF]: 14000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 17000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  O_1_ACADEMY_GRADUATE: {
    [TOTAL_WEIGHT_SELF]: 10000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 12000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  O_2: {
    [TOTAL_WEIGHT_SELF]: 12500,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 13500,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  O_3: {
    [TOTAL_WEIGHT_SELF]: 13000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 14500,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  O_4: {
    [TOTAL_WEIGHT_SELF]: 14000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 17000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  O_5: {
    [TOTAL_WEIGHT_SELF]: 16000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 17500,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  O_6: {
    [TOTAL_WEIGHT_SELF]: 18000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 18000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  O_7: {
    [TOTAL_WEIGHT_SELF]: 18000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 18000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  O_8: {
    [TOTAL_WEIGHT_SELF]: 18000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 18000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  O_9: {
    [TOTAL_WEIGHT_SELF]: 18000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 18000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  O_10: {
    [TOTAL_WEIGHT_SELF]: 18000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 18000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  W_1: {
    [TOTAL_WEIGHT_SELF]: 10000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 12000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  W_2: {
    [TOTAL_WEIGHT_SELF]: 12500,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 13500,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  W_3: {
    [TOTAL_WEIGHT_SELF]: 13000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 14500,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  W_4: {
    [TOTAL_WEIGHT_SELF]: 14000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 17000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  W_5: {
    [TOTAL_WEIGHT_SELF]: 16000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 17500,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  AVIATION_CADET: {
    [TOTAL_WEIGHT_SELF]: 7000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 8000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  CIVILIAN_EMPLOYEE: {
    [TOTAL_WEIGHT_SELF]: 18000,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 18000,
    [PRO_GEAR_WEIGHT]: 2000,
    [PRO_GEAR_WEIGHT_SPOUSE]: 500,
  },
  ACADEMY_CADET: {
    [TOTAL_WEIGHT_SELF]: 350,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 350,
    [PRO_GEAR_WEIGHT]: 0,
    [PRO_GEAR_WEIGHT_SPOUSE]: 0,
  },
  MIDSHIPMAN: {
    [TOTAL_WEIGHT_SELF]: 350,
    [TOTAL_WEIGHT_SELF_PLUS_DEPENDENTS]: 350,
    [PRO_GEAR_WEIGHT]: 0,
    [PRO_GEAR_WEIGHT_SPOUSE]: 0,
  },
};

export default WEIGHT_ENTITLEMENTS;
