// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	strings "strings"
)

// ViperType is an autogenerated mock type for the ViperType type
type ViperType struct {
	mock.Mock
}

// GetString provides a mock function with given fields: _a0
func (_m *ViperType) GetString(_a0 string) string {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetEnvKeyReplacer provides a mock function with given fields: _a0
func (_m *ViperType) SetEnvKeyReplacer(_a0 *strings.Replacer) {
	_m.Called(_a0)
}

// NewViperType creates a new instance of ViperType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewViperType(t interface {
	mock.TestingT
	Cleanup(func())
}) *ViperType {
	mock := &ViperType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
