// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import auth "github.com/transcom/mymove/pkg/auth"
import mock "github.com/stretchr/testify/mock"
import models "github.com/transcom/mymove/pkg/models"

import uuid "github.com/gofrs/uuid"
import validate "github.com/gobuffalo/validate"

// StorageInTransitDeliverer is an autogenerated mock type for the StorageInTransitDeliverer type
type StorageInTransitDeliverer struct {
	mock.Mock
}

// DeliverStorageInTransit provides a mock function with given fields: shipmentID, session, storageInTransitID
func (_m *StorageInTransitDeliverer) DeliverStorageInTransit(shipmentID uuid.UUID, session *auth.Session, storageInTransitID uuid.UUID) (*models.StorageInTransit, *validate.Errors, error) {
	ret := _m.Called(shipmentID, session, storageInTransitID)

	var r0 *models.StorageInTransit
	if rf, ok := ret.Get(0).(func(uuid.UUID, *auth.Session, uuid.UUID) *models.StorageInTransit); ok {
		r0 = rf(shipmentID, session, storageInTransitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StorageInTransit)
		}
	}

	var r1 *validate.Errors
	if rf, ok := ret.Get(1).(func(uuid.UUID, *auth.Session, uuid.UUID) *validate.Errors); ok {
		r1 = rf(shipmentID, session, storageInTransitID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*validate.Errors)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(uuid.UUID, *auth.Session, uuid.UUID) error); ok {
		r2 = rf(shipmentID, session, storageInTransitID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
