package models

import "github.com/transcom/mymove/pkg/gen/internalmessages"

const (
	// ServiceMemberGradeE1 captures enum value "E_1"
	ServiceMemberGradeE1 internalmessages.OrderPayGrade = "E_1"
	// ServiceMemberGradeE2 captures enum value "E_2"
	ServiceMemberGradeE2 internalmessages.OrderPayGrade = "E_2"
	// ServiceMemberGradeE3 captures enum value "E_3"
	ServiceMemberGradeE3 internalmessages.OrderPayGrade = "E_3"
	// ServiceMemberGradeE4 captures enum value "E_4"
	ServiceMemberGradeE4 internalmessages.OrderPayGrade = "E_4"
	// ServiceMemberGradeE5 captures enum value "E_5"
	ServiceMemberGradeE5 internalmessages.OrderPayGrade = "E_5"
	// ServiceMemberGradeE6 captures enum value "E_6"
	ServiceMemberGradeE6 internalmessages.OrderPayGrade = "E_6"
	// ServiceMemberGradeE7 captures enum value "E_7"
	ServiceMemberGradeE7 internalmessages.OrderPayGrade = "E_7"
	// ServiceMemberGradeE8 captures enum value "E_8"
	ServiceMemberGradeE8 internalmessages.OrderPayGrade = "E_8"
	// ServiceMemberGradeE9 captures enum value "E_9"
	ServiceMemberGradeE9 internalmessages.OrderPayGrade = "E_9"
	// ServiceMemberGradeE9SPECIALSENIORENLISTED captures enum value "E_9_SPECIAL_SENIOR_ENLISTED"
	ServiceMemberGradeE9SPECIALSENIORENLISTED internalmessages.OrderPayGrade = "E_9_SPECIAL_SENIOR_ENLISTED"
	// ServiceMemberGradeO2 captures enum value "O_2"
	ServiceMemberGradeO2 internalmessages.OrderPayGrade = "O_2"
	// ServiceMemberGradeO3 captures enum value "O_3"
	ServiceMemberGradeO3 internalmessages.OrderPayGrade = "O_3"
	// ServiceMemberGradeO4 captures enum value "O_4"
	ServiceMemberGradeO4 internalmessages.OrderPayGrade = "O_4"
	// ServiceMemberGradeO5 captures enum value "O_5"
	ServiceMemberGradeO5 internalmessages.OrderPayGrade = "O_5"
	// ServiceMemberGradeO6 captures enum value "O_6"
	ServiceMemberGradeO6 internalmessages.OrderPayGrade = "O_6"
	// ServiceMemberGradeO7 captures enum value "O_7"
	ServiceMemberGradeO7 internalmessages.OrderPayGrade = "O_7"
	// ServiceMemberGradeO8 captures enum value "O_8"
	ServiceMemberGradeO8 internalmessages.OrderPayGrade = "O_8"
	// ServiceMemberGradeO9 captures enum value "O_9"
	ServiceMemberGradeO9 internalmessages.OrderPayGrade = "O_9"
	// ServiceMemberGradeO10 captures enum value "O_10"
	ServiceMemberGradeO10 internalmessages.OrderPayGrade = "O_10"
	// ServiceMemberGradeW1 captures enum value "W_1"
	ServiceMemberGradeW1 internalmessages.OrderPayGrade = "W_1"
	// ServiceMemberGradeW2 captures enum value "W_2"
	ServiceMemberGradeW2 internalmessages.OrderPayGrade = "W_2"
	// ServiceMemberGradeW3 captures enum value "W_3"
	ServiceMemberGradeW3 internalmessages.OrderPayGrade = "W_3"
	// ServiceMemberGradeW4 captures enum value "W_4"
	ServiceMemberGradeW4 internalmessages.OrderPayGrade = "W_4"
	// ServiceMemberGradeW5 captures enum value "W_5"
	ServiceMemberGradeW5 internalmessages.OrderPayGrade = "W_5"
	// ServiceMemberGradeCIVILIANEMPLOYEE captures enum value "CIVILIAN_EMPLOYEE"
	ServiceMemberGradeCIVILIANEMPLOYEE internalmessages.OrderPayGrade = "CIVILIAN_EMPLOYEE"
)
