package models

import "github.com/transcom/mymove/pkg/gen/internalmessages"

const (
	// ServiceMemberPayGradeE1 captures enum value "E_1"
	ServiceMemberPayGradeE1 internalmessages.OrderPayGrade = "E_1"
	// ServiceMemberPayGradeE2 captures enum value "E_2"
	ServiceMemberPayGradeE2 internalmessages.OrderPayGrade = "E_2"
	// ServiceMemberPayGradeE3 captures enum value "E_3"
	ServiceMemberPayGradeE3 internalmessages.OrderPayGrade = "E_3"
	// ServiceMemberPayGradeE4 captures enum value "E_4"
	ServiceMemberPayGradeE4 internalmessages.OrderPayGrade = "E_4"
	// ServiceMemberPayGradeE5 captures enum value "E_5"
	ServiceMemberPayGradeE5 internalmessages.OrderPayGrade = "E_5"
	// ServiceMemberPayGradeE6 captures enum value "E_6"
	ServiceMemberPayGradeE6 internalmessages.OrderPayGrade = "E_6"
	// ServiceMemberPayGradeE7 captures enum value "E_7"
	ServiceMemberPayGradeE7 internalmessages.OrderPayGrade = "E_7"
	// ServiceMemberPayGradeE8 captures enum value "E_8"
	ServiceMemberPayGradeE8 internalmessages.OrderPayGrade = "E_8"
	// ServiceMemberPayGradeE9 captures enum value "E_9"
	ServiceMemberPayGradeE9 internalmessages.OrderPayGrade = "E_9"
	// ServiceMemberPayGradeE9SPECIALSENIORENLISTED captures enum value "E_9_SPECIAL_SENIOR_ENLISTED"
	ServiceMemberPayGradeE9SPECIALSENIORENLISTED internalmessages.OrderPayGrade = "E_9_SPECIAL_SENIOR_ENLISTED"
	// ServiceMemberPayGradeO1ACADEMYGRADUATE captures enum value "O_1_ACADEMY_GRADUATE"
	ServiceMemberPayGradeO1ACADEMYGRADUATE internalmessages.OrderPayGrade = "O_1_ACADEMY_GRADUATE"
	// ServiceMemberPayGradeO2 captures enum value "O_2"
	ServiceMemberPayGradeO2 internalmessages.OrderPayGrade = "O_2"
	// ServiceMemberPayGradeO3 captures enum value "O_3"
	ServiceMemberPayGradeO3 internalmessages.OrderPayGrade = "O_3"
	// ServiceMemberPayGradeO4 captures enum value "O_4"
	ServiceMemberPayGradeO4 internalmessages.OrderPayGrade = "O_4"
	// ServiceMemberPayGradeO5 captures enum value "O_5"
	ServiceMemberPayGradeO5 internalmessages.OrderPayGrade = "O_5"
	// ServiceMemberPayGradeO6 captures enum value "O_6"
	ServiceMemberPayGradeO6 internalmessages.OrderPayGrade = "O_6"
	// ServiceMemberPayGradeO7 captures enum value "O_7"
	ServiceMemberPayGradeO7 internalmessages.OrderPayGrade = "O_7"
	// ServiceMemberPayGradeO8 captures enum value "O_8"
	ServiceMemberPayGradeO8 internalmessages.OrderPayGrade = "O_8"
	// ServiceMemberPayGradeO9 captures enum value "O_9"
	ServiceMemberPayGradeO9 internalmessages.OrderPayGrade = "O_9"
	// ServiceMemberPayGradeO10 captures enum value "O_10"
	ServiceMemberPayGradeO10 internalmessages.OrderPayGrade = "O_10"
	// ServiceMemberPayGradeW1 captures enum value "W_1"
	ServiceMemberPayGradeW1 internalmessages.OrderPayGrade = "W_1"
	// ServiceMemberPayGradeW2 captures enum value "W_2"
	ServiceMemberPayGradeW2 internalmessages.OrderPayGrade = "W_2"
	// ServiceMemberPayGradeW3 captures enum value "W_3"
	ServiceMemberPayGradeW3 internalmessages.OrderPayGrade = "W_3"
	// ServiceMemberPayGradeW4 captures enum value "W_4"
	ServiceMemberPayGradeW4 internalmessages.OrderPayGrade = "W_4"
	// ServiceMemberPayGradeW5 captures enum value "W_5"
	ServiceMemberPayGradeW5 internalmessages.OrderPayGrade = "W_5"
	// ServiceMemberPayGradeAVIATIONCADET captures enum value "AVIATION_CADET"
	ServiceMemberPayGradeAVIATIONCADET internalmessages.OrderPayGrade = "AVIATION_CADET"
	// ServiceMemberPayGradeCIVILIANEMPLOYEE captures enum value "CIVILIAN_EMPLOYEE"
	ServiceMemberPayGradeCIVILIANEMPLOYEE internalmessages.OrderPayGrade = "CIVILIAN_EMPLOYEE"
	// ServiceMemberPayGradeACADEMYCADET captures enum value "ACADEMY_CADET"
	ServiceMemberPayGradeACADEMYCADET internalmessages.OrderPayGrade = "ACADEMY_CADET"
	// ServiceMemberPayGradeMIDSHIPMAN captures enum value "MIDSHIPMAN"
	ServiceMemberPayGradeMIDSHIPMAN internalmessages.OrderPayGrade = "MIDSHIPMAN"
)
