package models

// ServiceMemberGrade represents a service member's rank
type ServiceMemberGrade string

const (
	// ServiceMemberGradeE1 captures enum value "E_1"
	ServiceMemberGradeE1 ServiceMemberGrade = "E_1"
	// ServiceMemberGradeE2 captures enum value "E_2"
	ServiceMemberGradeE2 ServiceMemberGrade = "E_2"
	// ServiceMemberGradeE3 captures enum value "E_3"
	ServiceMemberGradeE3 ServiceMemberGrade = "E_3"
	// ServiceMemberGradeE4 captures enum value "E_4"
	ServiceMemberGradeE4 ServiceMemberGrade = "E_4"
	// ServiceMemberGradeE5 captures enum value "E_5"
	ServiceMemberGradeE5 ServiceMemberGrade = "E_5"
	// ServiceMemberGradeE6 captures enum value "E_6"
	ServiceMemberGradeE6 ServiceMemberGrade = "E_6"
	// ServiceMemberGradeE7 captures enum value "E_7"
	ServiceMemberGradeE7 ServiceMemberGrade = "E_7"
	// ServiceMemberGradeE8 captures enum value "E_8"
	ServiceMemberGradeE8 ServiceMemberGrade = "E_8"
	// ServiceMemberGradeE9 captures enum value "E_9"
	ServiceMemberGradeE9 ServiceMemberGrade = "E_9"
	// ServiceMemberGradeE9SPECIALSENIORENLISTED captures enum value "E_9_SPECIAL_SENIOR_ENLISTED"
	ServiceMemberGradeE9SPECIALSENIORENLISTED ServiceMemberGrade = "E_9_SPECIAL_SENIOR_ENLISTED"
	// ServiceMemberGradeO1ACADEMYGRADUATE captures enum value "O_1_ACADEMY_GRADUATE"
	ServiceMemberGradeO1ACADEMYGRADUATE ServiceMemberGrade = "O_1_ACADEMY_GRADUATE"
	// ServiceMemberGradeO2 captures enum value "O_2"
	ServiceMemberGradeO2 ServiceMemberGrade = "O_2"
	// ServiceMemberGradeO3 captures enum value "O_3"
	ServiceMemberGradeO3 ServiceMemberGrade = "O_3"
	// ServiceMemberGradeO4 captures enum value "O_4"
	ServiceMemberGradeO4 ServiceMemberGrade = "O_4"
	// ServiceMemberGradeO5 captures enum value "O_5"
	ServiceMemberGradeO5 ServiceMemberGrade = "O_5"
	// ServiceMemberGradeO6 captures enum value "O_6"
	ServiceMemberGradeO6 ServiceMemberGrade = "O_6"
	// ServiceMemberGradeO7 captures enum value "O_7"
	ServiceMemberGradeO7 ServiceMemberGrade = "O_7"
	// ServiceMemberGradeO8 captures enum value "O_8"
	ServiceMemberGradeO8 ServiceMemberGrade = "O_8"
	// ServiceMemberGradeO9 captures enum value "O_9"
	ServiceMemberGradeO9 ServiceMemberGrade = "O_9"
	// ServiceMemberGradeO10 captures enum value "O_10"
	ServiceMemberGradeO10 ServiceMemberGrade = "O_10"
	// ServiceMemberGradeW1 captures enum value "W_1"
	ServiceMemberGradeW1 ServiceMemberGrade = "W_1"
	// ServiceMemberGradeW2 captures enum value "W_2"
	ServiceMemberGradeW2 ServiceMemberGrade = "W_2"
	// ServiceMemberGradeW3 captures enum value "W_3"
	ServiceMemberGradeW3 ServiceMemberGrade = "W_3"
	// ServiceMemberGradeW4 captures enum value "W_4"
	ServiceMemberGradeW4 ServiceMemberGrade = "W_4"
	// ServiceMemberGradeW5 captures enum value "W_5"
	ServiceMemberGradeW5 ServiceMemberGrade = "W_5"
	// ServiceMemberGradeAVIATIONCADET captures enum value "AVIATION_CADET"
	ServiceMemberGradeAVIATIONCADET ServiceMemberGrade = "AVIATION_CADET"
	// ServiceMemberGradeCIVILIANEMPLOYEE captures enum value "CIVILIAN_EMPLOYEE"
	ServiceMemberGradeCIVILIANEMPLOYEE ServiceMemberGrade = "CIVILIAN_EMPLOYEE"
	// ServiceMemberGradeACADEMYCADET captures enum value "ACADEMY_CADET"
	ServiceMemberGradeACADEMYCADET ServiceMemberGrade = "ACADEMY_CADET"
	// ServiceMemberGradeMIDSHIPMAN captures enum value "MIDSHIPMAN"
	ServiceMemberGradeMIDSHIPMAN ServiceMemberGrade = "MIDSHIPMAN"
)
