-- This migration adds a cert that can access the MilMove Demo environment with mTLS.
-- The Orders API and the Prime API use client certificate authentication. Only certificates
-- signed by a trusted CA (such as DISA) are allowed which includes CACs.
INSERT INTO public.client_certs (
	id,
	sha256_digest,
	subject,
	allow_dps_auth_api,
	allow_orders_api,
	created_at,
	updated_at,
	allow_air_force_orders_read,
	allow_air_force_orders_write,
	allow_army_orders_read,
	allow_army_orders_write,
	allow_coast_guard_orders_read,
	allow_coast_guard_orders_write,
	allow_marine_corps_orders_read,
	allow_marine_corps_orders_write,
	allow_navy_orders_read,
	allow_navy_orders_write,
	allow_prime)
VALUES (
   '2fbfb740-cc36-4eeb-a6c6-1e800c74b348',
   '27250e2fbbf5c27931bb38b750a0722b64bf737d9be26b60b78ac34ade7a1f95',
   'CN=api.demo.dp3.us',
   false,
   true,
   now(),
   now(),
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true);
