-- Local migration. This migration is a none-operational migration. The SQL
-- that is commented out in this file is for example purposes only. This
-- migration does not need to run in your local environment.

--- ████████╗██╗  ██╗██╗███████╗    ███████╗ ██████╗ ██╗
--- ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██╔═══██╗██║
---    ██║   ███████║██║███████╗    ███████╗██║   ██║██║
---    ██║   ██╔══██║██║╚════██║    ╚════██║██║▄▄ ██║██║
---    ██║   ██║  ██║██║███████║    ███████║╚██████╔╝███████╗
---    ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚══════╝ ╚══▀▀═╝ ╚══════╝
---
--- ██████╗ ███████╗██╗      ██████╗ ██╗    ██╗    ██╗███████╗
--- ██╔══██╗██╔════╝██║     ██╔═══██╗██║    ██║    ██║██╔════╝
--- ██████╔╝█████╗  ██║     ██║   ██║██║ █╗ ██║    ██║███████╗
--- ██╔══██╗██╔══╝  ██║     ██║   ██║██║███╗██║    ██║╚════██║
--- ██████╔╝███████╗███████╗╚██████╔╝╚███╔███╔╝    ██║███████║
--- ╚═════╝ ╚══════╝╚══════╝ ╚═════╝  ╚══╝╚══╝     ╚═╝╚══════╝
---
---      ██╗██╗   ██╗███████╗████████╗     █████╗ ███╗   ██╗
---      ██║██║   ██║██╔════╝╚══██╔══╝    ██╔══██╗████╗  ██║
---      ██║██║   ██║███████╗   ██║       ███████║██╔██╗ ██║
--- ██   ██║██║   ██║╚════██║   ██║       ██╔══██║██║╚██╗██║
--- ╚█████╔╝╚██████╔╝███████║   ██║       ██║  ██║██║ ╚████║
---  ╚════╝  ╚═════╝ ╚══════╝   ╚═╝       ╚═╝  ╚═╝╚═╝  ╚═══╝
---
--- ███████╗██╗  ██╗ █████╗ ███╗   ███╗██████╗ ██╗     ███████╗
--- ██╔════╝╚██╗██╔╝██╔══██╗████╗ ████║██╔══██╗██║     ██╔════╝
--- █████╗   ╚███╔╝ ███████║██╔████╔██║██████╔╝██║     █████╗
--- ██╔══╝   ██╔██╗ ██╔══██║██║╚██╔╝██║██╔═══╝ ██║     ██╔══╝
--- ███████╗██╔╝ ██╗██║  ██║██║ ╚═╝ ██║██║     ███████╗███████╗
--- ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝
---
--- ███████╗██████╗  ██████╗ ███╗   ███╗
--- ██╔════╝██╔══██╗██╔═══██╗████╗ ████║
--- █████╗  ██████╔╝██║   ██║██╔████╔██║
--- ██╔══╝  ██╔══██╗██║   ██║██║╚██╔╝██║
--- ██║     ██║  ██║╚██████╔╝██║ ╚═╝ ██║
--- ╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝
---
--- ██╗   ██╗ █████╗ ██████╗ ██╗ ██████╗ ██╗   ██╗███████╗
--- ██║   ██║██╔══██╗██╔══██╗██║██╔═══██╗██║   ██║██╔════╝
--- ██║   ██║███████║██████╔╝██║██║   ██║██║   ██║███████╗
--- ╚██╗ ██╔╝██╔══██║██╔══██╗██║██║   ██║██║   ██║╚════██║
---  ╚████╔╝ ██║  ██║██║  ██║██║╚██████╔╝╚██████╔╝███████║
---   ╚═══╝  ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚═════╝  ╚═════╝ ╚══════╝
---
--- ███████╗ ██████╗ ██╗   ██╗██████╗  ██████╗███████╗███████╗
--- ██╔════╝██╔═══██╗██║   ██║██╔══██╗██╔════╝██╔════╝██╔════╝
--- ███████╗██║   ██║██║   ██║██████╔╝██║     █████╗  ███████╗
--- ╚════██║██║   ██║██║   ██║██╔══██╗██║     ██╔══╝  ╚════██║
--- ███████║╚██████╔╝╚██████╔╝██║  ██║╚██████╗███████╗███████║██╗
--- ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝ ╚═════╝╚══════╝╚══════╝╚═╝

-- ===================================
--  DO NOT include any sensitive data.
-- ===================================

-- SET ROLE master;
--
-- DO
-- $do$
-- BEGIN
--	IF NOT EXISTS (
--		SELECT -- SELECT list can stay empty for this
--		FROM   pg_catalog.pg_roles
--		WHERE  rolname = 'rds_superuser') THEN
--
--			CREATE ROLE dms_export WITH LOGIN NOINHERIT;
--			GRANT rds_superuser TO dms_export;
--
--	END IF;
-- END
-- $do$;
--
-- ALTER USER dms_export WITH PASSWORD 'mysecretpassword';
--
-- -- Modify existing tables and sequences.
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dms_export;
-- GRANT USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO dms_export;
--
-- -- Modify future tables and sequences.
-- -- Do not include `FOR ROLE` in the following statements so that:
-- -- 1. when this runs in RDS, it will apply to the role running migrations.
-- -- 2. when this runs in Docker, it will apply to the `postgres` role.
-- ALTER DEFAULT PRIVILEGES GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dms_export;
-- ALTER DEFAULT PRIVILEGES GRANT USAGE, UPDATE ON SEQUENCES TO dms_export;
--

-- ███████╗██████╗  ██████╗ ███╗   ███╗    ████████╗██╗  ██╗███████╗
-- ██╔════╝██╔══██╗██╔═══██╗████╗ ████║    ╚══██╔══╝██║  ██║██╔════╝
-- █████╗  ██████╔╝██║   ██║██╔████╔██║       ██║   ███████║█████╗
-- ██╔══╝  ██╔══██╗██║   ██║██║╚██╔╝██║       ██║   ██╔══██║██╔══╝
-- ██║     ██║  ██║╚██████╔╝██║ ╚═╝ ██║       ██║   ██║  ██║███████╗
-- ╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝       ╚═╝   ╚═╝  ╚═╝╚══════╝
--
--  ██████╗ ███████╗███████╗██╗ ██████╗██╗ █████╗ ██╗          █████╗ ██╗    ██╗███████╗
-- ██╔═══██╗██╔════╝██╔════╝██║██╔════╝██║██╔══██╗██║         ██╔══██╗██║    ██║██╔════╝
-- ██║   ██║█████╗  █████╗  ██║██║     ██║███████║██║         ███████║██║ █╗ ██║███████╗
-- ██║   ██║██╔══╝  ██╔══╝  ██║██║     ██║██╔══██║██║         ██╔══██║██║███╗██║╚════██║
-- ╚██████╔╝██║     ██║     ██║╚██████╗██║██║  ██║███████╗    ██║  ██║╚███╔███╔╝███████║
--  ╚═════╝ ╚═╝     ╚═╝     ╚═╝ ╚═════╝╚═╝╚═╝  ╚═╝╚══════╝    ╚═╝  ╚═╝ ╚══╝╚══╝ ╚══════╝
--
-- ██████╗  ██████╗  ██████╗██╗   ██╗███╗   ███╗███████╗███╗   ██╗████████╗ █████╗ ████████╗██╗ ██████╗ ███╗   ██╗
-- ██╔══██╗██╔═══██╗██╔════╝██║   ██║████╗ ████║██╔════╝████╗  ██║╚══██╔══╝██╔══██╗╚══██╔══╝██║██╔═══██╗████╗  ██║
-- ██║  ██║██║   ██║██║     ██║   ██║██╔████╔██║█████╗  ██╔██╗ ██║   ██║   ███████║   ██║   ██║██║   ██║██╔██╗ ██║
-- ██║  ██║██║   ██║██║     ██║   ██║██║╚██╔╝██║██╔══╝  ██║╚██╗██║   ██║   ██╔══██║   ██║   ██║██║   ██║██║╚██╗██║
-- ██████╔╝╚██████╔╝╚██████╗╚██████╔╝██║ ╚═╝ ██║███████╗██║ ╚████║   ██║   ██║  ██║   ██║   ██║╚██████╔╝██║ ╚████║
-- ╚═════╝  ╚═════╝  ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
--
-- README: Taken from this link here: https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.PostgreSQL.html#CHAP_Source.PostgreSQL.RDSPostgreSQL.NonMasterUser
--
-- CREATE TABLE IF NOT EXISTS public.awsdms_ddl_audit
-- (
--   c_key    bigserial primary key,
--   c_time   timestamp,    -- Informational
--   c_user   varchar(64),  -- Informational: current_user
--   c_txn    varchar(16),  -- Informational: current transaction
--   c_tag    varchar(24),  -- Either 'CREATE TABLE' or 'ALTER TABLE' or 'DROP TABLE'
--   c_oid    integer,      -- For future use - TG_OBJECTID
--   c_name   varchar(64),  -- For future use - TG_OBJECTNAME
--   c_schema varchar(64),  -- For future use - TG_SCHEMANAME. For now - holds current_schema
--   c_ddlqry  text         -- The DDL query associated with the current DDL event
-- );
--
--
-- CREATE OR REPLACE FUNCTION public.awsdms_intercept_ddl()
--   RETURNS event_trigger
-- LANGUAGE plpgsql
-- SECURITY DEFINER
--   AS $$
--   declare _qry text;
-- BEGIN
--   if (tg_tag='CREATE TABLE' or tg_tag='ALTER TABLE' or tg_tag='DROP TABLE') THEN
--          SELECT current_query() into _qry;
--          INSERT INTO public.awsdms_ddl_audit
--          values
--          (
--          default,current_timestamp,current_user,cast(TXID_CURRENT()as varchar(16)),tg_tag,0,'',current_schema,_qry
--          );
--          DELETE FROM public.awsdms_ddl_audit;
-- end if;
-- END;
-- $$;
--
-- --- This needs to be run as the dms_export
-- CREATE EVENT TRIGGER awsdms_intercept_ddl ON ddl_command_end
-- 	EXECUTE PROCEDURE public.awsdms_intercept_ddl();
--
--
-- --- All users and roles need access to the events
-- GRANT ALL ON public.awsdms_ddl_audit TO public;
-- GRANT ALL ON public.awsdms_ddl_audit_c_key_seq TO public;
--
-- RESET ROLE;
