UPDATE duty_stations
    SET provides_services_counseling = TRUE
    WHERE name in (
       'Aberdeen Proving Ground',
       'Altus AFB',
       'Base Elizabeth City',
       'Barksdale AFB',
       'Base Cape Cod',
       'JB Charleston',
       'Base Portsmouth',
       'Base Seattle',
       'Blue Grass Army Depot',
       'Carlisle Barracks',
       'Columbus AFB',
       'Camp Pendleton',
       'Dover AFB',
       'Dugway Proving Ground',
       'Dyess AFB',
       'Eglin AFB',
       'Ellington Field ANGB',
       'NS Norfolk',
       'NAVSTA Everett',
       'NAS Whidbey Island',
       'Fort Belvoir',
       'Fort Benning',
       'Fort Bliss',
       'Fort Bragg',
       'Fort Campbell',
       'Fort Detrick',
       'Fort Drum',
       'Fort Gordon',
       'Fort Greely',
       'Fort Hamilton',
       'Fort Hood',
       'Fort Huachuca',
       'Fort Irwin',
       'Fort Jackson',
       'Fort Knox',
       'Fort Leavenworth',
       'Fort Lee',
       'Fort Leonard Wood',
       'Fort McCoy',
       'Fort George G. Meade',
       'Fort Polk',
       'Fort Riley',
       'Fort Rucker',
       'Fort Sill',
       'Fort Stewart-Hunter',
       'Fort Wainwright',
       'Goodfellow AFB',
       'Hanscom AFB',
       'Hunter AAF',
       'Hurlburt Field AFB',
       'JB Langley-Eustis',
       'JB Lewis-McChord',
       'JB McGuire-Dix-Lakehurst',
       'Keesler AFB',
       'JBSA Lackland',
       'Laughlin AFB',
       'Little Rock AFB',
       'MacDill AFB',
       'Maxwell AFB',
       'McAlester AAP',
       'Moody AFB',
       'NSA Saratoga Springs',
       'Patrick AFB',
       'Pine Bluff Arsenal',
       'Presidio of Monterey',
       'JBSA Randolph',
       'Red River Army Depot',
       'Redstone Arsenal',
       'Robins AFB',
       'Scott AFB',
       'Seymour Johnson AFB',
       'Shaw AFB',
       'Sheppard AFB',
       'Tinker AFB',
       'MARCORSYSCOM TOBYHANNA ARMY DEPOT',
       'Tooele Army Depot',
       'Training Center Petaluma',
       'Tyndall AFB',
       'Vance AFB',
       'West Point',
       'White Sands Missile Range',
       'Wright-Patterson AFB'
);

