UPDATE re_services
SET name = new_service_names.name
FROM ( VALUES
    ('MS', 'Move management'),
    ('CS', 'Counseling'),
    ('DLH','Domestic linehaul'),
    ('DSH','Domestic shorthaul'),
    ('DOP','Domestic origin price'),
    ('DDP','Domestic destination price'),
    ('DOFSIT','Domestic origin 1st day SIT'),
    ('DDFSIT','Domestic destination 1st day SIT'),
    ('DOASIT','Domestic origin add''l SIT'),
    ('DDASIT','Domestic destination add''l SIT'),
    ('DOPSIT','Domestic origin SIT pickup'),
    ('DDDSIT','Domestic destination SIT delivery'),
    ('DPK','Domestic packing'),
    ('DUPK','Domestic unpacking'),
    ('DCRT','Domestic crating'),
    ('DCRTSA','Domestic crating - standalone'),
    ('DUCRT','Domestic uncrating'),
    ('DOSHUT','Domestic origin shuttle service'),
    ('DDSHUT','Domestic destination shuttle service'),
    ('IOOLH','International O->O shipping & LH'),
    ('IOOUB','International O->O UB'),
    ('ICOLH','International C->O shipping & LH'),
    ('ICOUB','International C->O UB'),
    ('IOCLH','International O->C shipping & LH'),
    ('IOCUB','International O->C UB'),
    ('IHPK','International HHG pack'),
    ('IHUPK','International HHG unpack'),
    ('IUBPK','International UB pack'),
    ('IUBUPK','International UB unpack'),
    ('IOFSIT','International origin 1st day SIT'),
    ('IDFSIT','International destination 1st day SIT'),
    ('IOASIT','International origin add''l day SIT'),
    ('IDASIT','International destination add''l day SIT'),
    ('IOPSIT','International origin SIT pickup'),
    ('IDDSIT','International destination SIT delivery'),
    ('ICRT','International crating'),
    ('ICRTSA','International crating - standalone'),
    ('IUCRT','International uncrating'),
    ('IOSHUT','International origin shuttle service'),
    ('IDSHUT','International destination shuttle service'),
    ('NSTH','Nonstandard HHG'),
    ('NSTUB','Nonstandard UB'),
    ('FSC','Fuel surcharge'),
    ('DMHF','Domestic mobile home factor'),
    ('DBTF','Domestic tow away boat factor'),
    ('DBHF','Domestic haul away boat factor'),
    ('IBTF','International tow away boat factor'),
    ('IBHF','International haul away boat factor'),
    ('DNPKF','Domestic NTS packing factor'),
    ('INPKF','International NTS packing factor')
) as new_service_names (code, name)
WHERE re_services.code = new_service_names.code;