CREATE TABLE archived_personally_procured_move_data (
    id uuid PRIMARY KEY,
    move_id uuid REFERENCES moves,
	FOREIGN KEY (move_id) REFERENCES moves (id) ON DELETE CASCADE,
    weight_estimate INT NULL,
	created_at timestamp without time zone NOT NULL,
	updated_at timestamp without time zone NOT NULL,
    pickup_postal_code varchar(255),
    additional_pickup_postal_code varchar(255),
    destination_postal_code varchar(255),
    days_in_storage INT,
    status varchar(255),
    has_additional_postal_code bool,
    has_sit bool,
    has_requested_advance bool,
    advance_id uuid REFERENCES reimbursements,
    estimated_storage_reimbursement varchar(255),
    mileage INT,
    planned_sit_max INT,
    sit_max INT,
    incentive_estimate_min INT,
    incentive_estimate_max INT,
    advance_worksheet_id uuid REFERENCES documents,
    net_weight INT,
    original_move_date timestamp with time zone,
    actual_move_date timestamp with time zone,
    total_sit_cost INT,
    submit_date timestamp with time zone,
    approve_date timestamp with time zone,
    reviewed_date timestamp with time zone,
    has_pro_gear text,
    has_pro_gear_over_thousand text,
    move_document_id uuid REFERENCES move_documents,
    move_document_move_id uuid REFERENCES moves,
    document_id uuid REFERENCES documents,
    move_document_type varchar(255),
    move_document_status varchar(255),
    notes text,
    move_document_created_at timestamp with time zone,
    move_document_updated_at timestamp with time zone,
    move_document_deleted_at timestamp with time zone,
    title varchar(255),
    move_document_ppm_id uuid REFERENCES personally_procured_moves,
    signed_certificate_id uuid REFERENCES signed_certifications,
    submitting_user_id uuid REFERENCES users,
    signed_certificate_move_id uuid REFERENCES moves,
    certification_text text,
    signature text,
    date timestamp,
	signed_certificate_created_at timestamp without time zone,
	signed_certificate_updated_at timestamp without time zone,
    personally_procured_move_id uuid REFERENCES moves,
    certification_type text,
    weight_ticket_set_document_id uuid REFERENCES weight_ticket_set_documents,
    weight_ticket_set_type text,
    vehicle_nickname text,
    weight_ticket_set_move_document_id uuid REFERENCES move_documents,
    empty_weight INT,
    empty_weight_ticket_missing bool,
    full_weight INT,
    full_weight_ticket_missing bool,
    weight_ticket_date timestamp,
    weight_ticket_set_document_created_at timestamp without time zone,
    weight_ticket_set_document_updated_at timestamp without time zone,
    weight_ticket_set_document_deleted_at timestamp without time zone,
    trailer_ownership_missing bool,
    vehicle_make text,
    vehicle_model text,
    moving_expense_document_id uuid REFERENCES moving_expense_documents,
    moving_expense_document_move_document_id uuid REFERENCES documents,
    moving_expense_type varchar(255),
    moving_expense_document_created_at timestamp without time zone,
    moving_expense_document_updated_at timestamp without time zone,
    moving_expense_document_deleted_at timestamp without time zone,
    requested_amount_cents INT,
    payment_method varchar(255),
    receipt_missing bool,
    storage_start_date timestamp,
    storage_end_date timestamp
);

CREATE INDEX ON archived_personally_procured_move_data (move_id);
CREATE INDEX ON archived_personally_procured_move_data (advance_id);
CREATE INDEX ON archived_personally_procured_move_data (advance_worksheet_id);
CREATE INDEX ON archived_personally_procured_move_data (move_document_id);
CREATE INDEX ON archived_personally_procured_move_data (move_document_move_id);
CREATE INDEX ON archived_personally_procured_move_data (document_id);
CREATE INDEX ON archived_personally_procured_move_data (move_document_ppm_id);
CREATE INDEX ON archived_personally_procured_move_data (signed_certificate_id);
CREATE INDEX ON archived_personally_procured_move_data (submitting_user_id);
CREATE INDEX ON archived_personally_procured_move_data (signed_certificate_move_id);
CREATE INDEX ON archived_personally_procured_move_data (personally_procured_move_id);
CREATE INDEX ON archived_personally_procured_move_data (weight_ticket_set_document_id);
CREATE INDEX ON archived_personally_procured_move_data (weight_ticket_set_move_document_id);
CREATE INDEX ON archived_personally_procured_move_data (moving_expense_document_id);
CREATE INDEX ON archived_personally_procured_move_data (moving_expense_document_move_document_id);

INSERT INTO archived_personally_procured_move_data (id, move_id, weight_estimate, created_at, updated_at,
pickup_postal_code, additional_pickup_postal_code,
destination_postal_code, days_in_storage, has_additional_postal_code,
advance_id, has_requested_advance, advance_worksheet_id,
estimated_storage_reimbursement, mileage, planned_sit_max, sit_max, status,
incentive_estimate_max, incentive_estimate_min,
net_weight, original_move_date, actual_move_date,
total_sit_cost, has_sit, submit_date, reviewed_date, approve_date,
has_pro_gear, has_pro_gear_over_thousand,
signed_certificate_id, submitting_user_id, signed_certificate_move_id,
certification_text, signature, date, signed_certificate_created_at,
signed_certificate_updated_at, certification_type,
personally_procured_move_id,
move_document_id, move_document_move_id, document_id,
move_document_type, move_document_status, notes,
move_document_updated_at, move_document_created_at,
title, move_document_ppm_id, move_document_deleted_at,
weight_ticket_set_document_id, weight_ticket_set_type, vehicle_nickname,
weight_ticket_set_move_document_id, empty_weight,
empty_weight_ticket_missing, full_weight, full_weight_ticket_missing, weight_ticket_date,
weight_ticket_set_document_created_at, weight_ticket_set_document_updated_at, trailer_ownership_missing,
weight_ticket_set_document_deleted_at, vehicle_make, vehicle_model,
moving_expense_document_id, moving_expense_document_move_document_id, moving_expense_type,
moving_expense_document_created_at, moving_expense_document_updated_at, requested_amount_cents,
payment_method, receipt_missing, storage_start_date, storage_end_date, moving_expense_document_deleted_at)


SELECT ppm.id, ppm.move_id, ppm.weight_estimate,
ppm.created_at, ppm.updated_at,
ppm.pickup_postal_code,
ppm.additional_pickup_postal_code,
ppm.destination_postal_code, ppm.days_in_storage,
ppm.has_additional_postal_code, ppm.advance_id,
ppm.has_requested_advance, ppm.advance_worksheet_id,
ppm.estimated_storage_reimbursement, ppm.mileage,
ppm.planned_sit_max, ppm.sit_max,
ppm.status,
ppm.incentive_estimate_max,
ppm.incentive_estimate_min,
ppm.net_weight, ppm.original_move_date,
ppm.actual_move_date, ppm.total_sit_cost,
ppm.has_sit, ppm.submit_date,
ppm.reviewed_date, ppm.approve_date,
ppm.has_pro_gear, ppm.has_pro_gear_over_thousand,

sc.id AS signed_certificate_id, sc.submitting_user_id,
sc.move_id AS signed_certificate_move_id,
sc.certification_text, sc.signature, sc.date,
sc.created_at AS signed_certificate_created_at,
sc.updated_at AS signed_certificate_updated_at, sc.certification_type,
sc.personally_procured_move_id,

md.id AS move_document_id, md.move_id AS move_document_move_id,
md.document_id, md.move_document_type, md.status AS move_document_status, md.notes,
md.updated_at AS move_document_updated_at, md.created_at AS move_document_created_at,
md.title, md.personally_procured_move_id AS move_document_ppm_id,
md.deleted_at AS move_document_deleted_at,

wtsd.id AS weight_ticket_set_document_id, wtsd.weight_ticket_set_type,
wtsd.vehicle_nickname, wtsd.move_document_id AS weight_ticket_set_move_document_id,
wtsd.empty_weight,
wtsd.empty_weight_ticket_missing, wtsd.full_weight,
wtsd.full_weight_ticket_missing, wtsd.weight_ticket_date,
wtsd.created_at AS weight_ticket_set_document_created_at,
wtsd.updated_at AS weight_ticket_set_document_updated_at, wtsd.trailer_ownership_missing,
wtsd.deleted_at AS weight_ticket_set_document_deleted_at,
wtsd.vehicle_make, wtsd.vehicle_model,

med.id AS moving_expense_document_id,
med.move_document_id AS moving_expense_document_move_document_id,
med.moving_expense_type,
med.created_at AS moving_expense_document_created_at,
med.updated_at AS moving_expense_document_updated_at,
med.requested_amount_cents,
med.payment_method, med.receipt_missing,
med.storage_start_date, med.storage_end_date,
med.deleted_at AS moving_expense_document_deleted_at

FROM personally_procured_moves ppm
FULL OUTER JOIN signed_certifications sc ON sc.personally_procured_move_id = ppm.id
FULL OUTER JOIN move_documents md ON md.personally_procured_move_id = ppm.id
FULL OUTER JOIN weight_ticket_set_documents wtsd ON wtsd.move_document_id = md.id
FULL OUTER JOIN moving_expense_documents med ON med.move_document_id = md.id;