UPDATE transportation_offices
    SET provides_ppm_closeout = TRUE
    WHERE name in (
	'Altus AFB',
	'Army Sustainment Command DTA Warren MI',
	'Barksdale AFB',
	'Base Alameda',
	'Base Cape Cod',
	'Base Ketchikan',
	'Beale AFB',
	'Blue Grass Army Depot',
	'Buckley AFB',
	'Camp LeJeune (USMC)',
	'Camp Smith Personal Property Office',
	'Cannon AFB',
	'CG BASE KETCHIKAN',
	'CG BASE KETCHIKAN, AK',
	'CG BASE KODIAK, AK',
	'CG BSU, KODIAK, AK',
	'Charleston Naval Weapon Station',
	'Columbus AFB',
	'Consolidated Personal Property Shipping Office',
	'CPPSO - Carlilse Barracks, PA',
	'CPPSO - Carlisle Barracks',
	'CPPSO - HD, FORT HOOD, TX',
	'CPPSO, CARLISLE BARRACKS, PA',
	'Creech AFB',
	'Davis Monthan AFB',
	'Department of the Army Transportation Office PPPO Fort Lee, VA',
	'Detroit Arsenal',
	'DMO Albany, GA',
	'DMO Camp Lejeune',
	'DMO MCAGCC 29 PALMS CA',
	'DMO MCAS Beaufort',
	'DMO MCAS Yuma AZ',
	'Dover AFB',
	'Dyess AFB',
	'Edwards AFB',
	'Eglin AFB',
	'Eielson AFB',
	'Ellington Field ANGB',
	'Ellsworth AFB',
	'F.E. Warren AFB',
	'Fairchild AFB',
	'FLCJ DET New Orleans',
	'FLCJ MERIDIAN DET',
	'Fort Bliss PPPO',
	'Fort Bragg',
	'Fort Drum Personal Property Shipping Office',
	'Fort Gordon Transportation Office',
	'Fort Leonard Wood, Personal Property Processing Office',
	'Fort McCoy PPPO',
	'Fort Meade Transportation Office',
	'Fort Riley Transportation (KOAT)',
	'FORT RUCKER COUNSELING OFFICE',
	'Fort Sam Houston',
	'Fort Stewart - Transportation Office',
	'Ft Carson',
	'Ft. Eustis',
	'Goodfellow AFB',
	'Grand Forks',
	'Hanscom AFB',
	'Hill AFB',
	'Holloman AFB',
	'Household Goods/Transportation Office',
	'Hunter Army Airfield - Transportation Office',
	'Hurlburt AFB',
	'JBAB PPPO',
	'JBER Travel Center-Elmendorf',
	'JBER Travel Center-Richardson',
	'JBMDL Household Goods/Transportation Office',
	'Joint Base Charleston',
	'Joint Base Charleston (Naval Weapon Station)',
	'Joint Base Langley-Eustis',
	'Joint Base Lewis-McChord (Fort Lewis)',
	'JOINT PERS PROP SHIPPING OFFICE - MA',
	'JPPSO NORTHWEST',
	'Kaneohe Marine Corps Air Station Personal Property Office',
	'Keesler AFB',
	'Kirtland AFB',
	'Lackland AFB',
	'Laughlin AFB',
	'Little Rock AFB',
	'Los Angeles AFB',
	'LRC Fort Knox',
	'LRC ITD PPPO',
	'LRC, Dugway Proving Ground, Transportation Div',
	'LRC, Installation Transportation Office',
	'Luke AFB',
	'MacDill AFB',
	'Malmstrom AFB',
	'Maxwell AFB',
	'McAlester Personal Property Office',
	'MCAS Cherry Point, NC. DMO',
	'McChord AFB',
	'McConnell AFB',
	'MEPS',
	'Minot AFB',
	'Moody AFB',
	'Mountain Home AFB',
	'Mountain Warfare Training Center',
	'NAS Fallon HHG Office',
	'NAS Pensacola PPO',
	'Naval Postgraduate School',
	'Naval Station Newport',
	'Naval Training Center PPO',
	'NAVSUP FLC PPSO CHINA LAKE',
	'NAVSUP FLC PS PPPO EVERETT',
	'NAVSUP FLC PUGET SOUND',
	'NAVSUP FLC Puget Sound Whidbey',
	'NAVSUP FLC San Diego',
	'NAVSUP FLC Seal Beach',
	'NAVSUP FLCN Annapolis',
	'Navy Submarine Base New London',
	'NCBC GULFPORT',
	'Nellis AFB',
	'NSA Mid-South Personal Property Office',
	'NSA MidSouth Personal Property Office',
	'NSA Saratoga Springs',
	'Offutt AFB',
	'PACIFIC MISSILE RANGE FACILITY (KAUAI) - NAVY',
	'Patrick AFB',
	'Personal Property Activity HQ',
	'Personal Property Dept, Joint Base Pearl Harbor Hickam (JBPHH)',
	'Personal Property Office',
	'Personal Property Office - Outbound',
	'Personal Property Office, Ventura County Site',
	'Personal Property Petaluma',
	'Personal Property Processing Office Fort Greely, AK',
	'Personal Property Processing Office Fort Leavenworth',
	'Personal Property Processing Office Fort Leonard Wood',
	'Personal Property Processing Office Fort Wainwright, AK',
	'Personal Property Processing Office Lewis-Main',
	'Personal Property Processing Office McChord Field, WA',
	'Personal Property Shipping Office Fort Sill',
	'Personal Property Shipping Office Miami Beach',
	'Peterson AFB',
	'Pine Bluff Arsenal Transportation Office',
	'Portsmouth Navy Shipyard',
	'PPM Processing (NAVY)',
	'PPM Processing (USCG)',
	'PPM Processing (USMC)',
	'PPO Seal Beach NWS, CA',
	'PPO USCG SUPPORT CENTER Elizabeth City',
	'PPPO / BASE PORTSMOUTH VA',
	'PPPO Corpus Christi',
	'PPPO COUNSELING OFFICE ABERDEEN PROVING GROUND',
	'PPPO Counseling Office DMO Quantico',
	'PPPO Counseling Office JB Andrews AFB, MD',
	'PPPO COUNSELING OFFICE NAVSUP BETHESDA',
	'PPPO Counseling Office, DMO JB Myer-Henderson Hall',
	'PPPO Counseling Office, USCG Baltimore',
	'PPPO Fort Belvoir / Logistics Readiness Center (LRC)',
	'PPPO FORT BENNING, GA',
	'PPPO Fort Detrick MD',
	'PPPO Fort Hamilton',
	'PPPO Fort Irwin',
	'PPPO Fort Leavenworth',
	'PPPO Fort Polk',
	'PPPO Hood',
	'PPPO Marine Corps Base Camp Pendleton',
	'PPPO-USCG Counseling Office, Washington DC',
	'PPPO, Fort Benning, GA',
	'PPSO Ft. Huachuca',
	'PPSO Key West',
	'PPSO NAVSUP FLC CHINA LAKE',
	'PPSO Puget Sound Household Goods',
	'Presidio of Monterey',
	'Randolph AFB',
	'Red River Army Depot',
	'Robins AFB',
	'Rock Island Arsenal Transportation Office',
	'Rome NY',
	'Schofield Barracks  / Fort Shafter Transportation office',
	'Scott AFB',
	'Sector Humboldt Bay',
	'Seymour Johnson AFB, NC',
	'Shaw AFB, SC',
	'Sheppard AFB',
	'Tinker AFB',
	'Tooele Army Depot',
	'Transportation Office Fort Jackson',
	'Transportation Personal Property',
	'Travis AFB',
	'Tyndall AFB',
	'USAF Academy',
	'USCG',
	'USCG BASE ALAMEDA, CA',
	'USCG Base Boston',
	'USCG Base Charleston',
	'USCG Base Honolulu Transportation',
	'USCG Base Los Angeles/Long Beach',
	'USCG Base Saint Louis',
	'USCG Base Seattle',
	'USCG Mobile Personal Property Office',
	'USCG Training Center Cape May',
	'USCG Training Center Yorktown',
	'USMC Miramar Personal Property Office',
	'USMC San Diego Personal Property Office',
	'Vance AFB',
	'Vandenberg AFB',
	'West Point Military Academy ITO',
	'White Sands Missile Range',
	'Whiteman AFB',
	'Wright-Patterson AFB',
	'Yuma Proving Ground'
);
