CREATE TYPE category_type AS enum (
	'Pre-Move Services',
	'Physical Move Services',
	'Liability'
);

CREATE TYPE sub_category_type AS enum (
    'Customer Support',
    'Counseling',
    'Weight Estimate',
	'Additional Services',
	'Inventory & Documentation',
	'Packing/Unpacking',
	'Shipment Schedule',
	'Shipment Weights',
	'Storage',
	'Workforce/Sub-Contractor Management',
	'Loss & Damage',
	'Inconvenience & Hardship Claims'
);

CREATE TABLE IF NOT EXISTS pws_violations (
    id integer PRIMARY KEY,
    paragraph_number text,
    title text,
    category text,
    sub_category sub_category_type,
    requirement_summary text,
    requirement_statement text,
    is_kpi boolean,
	additional_data_elem text
);

CREATE INDEX pws_violations_id_idx ON pws_violations (id);

COMMENT ON TABLE pws_violations IS 'Contains QAE evaluation reports. There are two kinds of reports: shipment and counseling. You can tell them apart based on whether shipment_id is NULL.';
COMMENT ON COLUMN pws_violations.paragraph_number IS 'Paragraph number the violation relates to (1.2.3.4.5)';
COMMENT ON COLUMN pws_violations.title IS 'Paragraph title of the violation';
COMMENT ON COLUMN pws_violations.category IS 'Top level category of the violation (Pre-Move Services, Physical Move Services, etc.)';
COMMENT ON COLUMN pws_violations.sub_category IS 'Sub-category of the violation (Customer Support, Counseling, etc.)';
COMMENT ON COLUMN pws_violations.requirement_summary IS 'PWS Requirement Summary';
COMMENT ON COLUMN pws_violations.requirement_statement IS 'Requirement Statement in PWS';
COMMENT ON COLUMN pws_violations.is_kpi IS 'Whether the violation is a Key Performance Indicator (KPI)';
COMMENT ON COLUMN pws_violations.additional_data_elem IS 'Desired Additional Data Element (KPIs Only)';

INSERT INTO pws_violations VALUES (1, '1.2.3', 'Customer Support', 'Pre-Move Services', 'Customer Support', 'Provide 24/7 customer support capability', 'The contractor shall maintain a 24-hour, 7-day per week customer support capability for all issues pertaining to a customer’s move. The contractor shall staff the customer support capability such that all customer calls, to include Interactive Voice Response (IVR) time, will be answered within four (4) minutes. Wait time is cumulative and does not restart if a call is handed off or escalated to Level 2/3.', 'false', NULL);
INSERT INTO pws_violations VALUES (2, '1.2.5.1', 'Point of Contact (POC)', 'Pre-Move Services', 'Customer Support', 'Provide a single point of contact (POC)', 'The contractor shall assign, during initial communication with each customer, a single POC responsible for coordination and communication throughout all phases of the move. The POC’s contact information shall be maintained throughout the entire shipment process and until all associated actions are final.', 'false', '');
INSERT INTO pws_violations VALUES (3, '1.2.5.2', 'Pre-Move Services','Pre-Move Services','Counseling','Establish contact with the customer within one (1) government business day (GBD) of receiving an order','When ordered, the contractor shall establish contact with the customer within one (1) GBD of receiving an order and customer contact information and shall then provide ordered services.', 'false', '');
INSERT INTO pws_violations VALUES (4, '1.2.5.2', 'Customer Counseling','Pre-Move Services','Counseling','Provide accurate entitlement counseling and forms','The contractor shall provide accurate entitlement and shipment counseling in accordance with all applicable US Government, DoD, Joint, Military Service-specific, and International regulations and instructions to all customers regardless of location and accessibility, to include customers in remote locations, or customers who lack the ability to conduct counseling via face-to-face communication or the Internet. Upon counseling completion, the contractor shall provide an electronic or hard copy form as a record of the customer application for shipment or storage of personal property. The inventory shall include all details listed in Appendix H. The Government may issue task orders for site-specific in-person counseling services IAW Appendix D, para D.5. Customers shall be offered either an in-person or virtual pre-move survey as part of the counseling process.', 'false', '');
INSERT INTO pws_violations VALUES (5, '1.2.5.2.1', 'Personally Procured Moves (PPM)','Pre-Move Services','Counseling','Provide accurate PPM counseling','When ordered, the contractor shall provide accurate entitlement on PPMs during counseling in accordance with all applicable US Government, DoD, Joint, Military Service-specific, and International regulations and instructions.','false');
INSERT INTO pws_violations VALUES (6, '1.2.5.3', 'Scheduling','Pre-Move Services','Counseling','Schedule relocation during counseling','The contractor shall schedule shipment relocation services during customer counseling, which must be conducted IAW scheduling timelines referenced in §1.2.5.3.1 below. Based on customer request, the contractor shall provide a pickup date spread for required packing, pickup, and delivery during counseling and firm dates after counseling as summarized below.','true','QAE Observed Pickup Spread Start (Date); QAE Observed Pickup Spread End (Date)');
INSERT INTO pws_violations VALUES (7, '1.2.5.3.1', 'Scheduling Requirements','Pre-Move Services','Counseling','Schedule relocation using pickup spread rules','During Customer Counseling, or Scheduling if Customer Counseling is not ordered, the contractor shall provide a pickup date spread in accordance with the timelines in the table below, agreeable to the customer, which shall not to exceed seven (7) consecutive calendar days from the members requested pickup date contained within that spread. The contractor shall document the start and end of the spread, and the customer’s acceptance. The contractor shall provide a firm schedule for all applicable relocation services in accordance with the timelines in the table below (See PWS Paragraph 1.2.5.3.1.). The contractor shall ensure all firm dates are within the previously agreed upon spread. An “approved order” is an order sent to the contractor after the Ordering Officer (OO) validates the requirement.','true','QAE Observed Pickup Spread Start (Date); QAE Observed Pickup Spread End (Date)');
INSERT INTO pws_violations VALUES (8, '1.2.5.4.1', 'Weight Estimates','Pre-Move Services','Weight Estimate','Provide accurate weight estimate','The contractor shall provide the government and customer weight estimates on all shipments no later than 10 days prior to the first scheduled pack or pickup date. For shipments ordered less than ten (10) days prior to first scheduled pack or pickup date, weight estimates must be provided no later than three (3) days prior to first scheduled pack or pickup date. For shipments ordered less than three (3) days prior to the first scheduled pack or pickup date, weight estimates must be provided no later than one (1) day prior to first scheduled pack or pickup date. The government will only pay costs associated with shipments up to 110% of the estimated weight.', 'false', '');
INSERT INTO pws_violations VALUES (9, '1.2.6.4', 'Items Requiring Government Pre-Approval','Physical Move Services','Additional Services','Obtain pre-approvals for additional services','The following services referenced in §1.2.6.4.1 and §1.2.6.4.2. must be approved by the government prior to performance. Requests for approval shall be sent to the OO at the responsible origin or destination of the shipment.', 'false', '');
INSERT INTO pws_violations VALUES (10, '1.2.6.4.1', 'Crating','Physical Move Services','Additional Services','Provide appropriate crating services','Upon approval, the contractor shall perform crating services for items such as mirrors, paintings, glass or marble tabletops and similar fragile articles, and taxidermy when crates are not provided by the customer or when the customer provided crates are not serviceable. This does not include cases, footlockers, passenger bags, cartons, boxes, tri-wall containers, liftvans, and barrels that may be placed in a cargo transporter (commercial sea vans; container express cargo transporters and other transoceanic cargo transporters) for ocean or air transport. The customer retains ownership of all crates. (Per Attachment 2, Pricing Rate Table, the price for crating services is for the construction of new crates only).', 'false', '');
INSERT INTO pws_violations VALUES (11, '1.2.6.4.2', 'Shuttles','Physical Move Services','Additional Services','Provide appropriate shuttle services','Upon approval, the contractor shall perform shuttle services to pick up or deliver shipments when the origin or destination delivery location is inaccessible due to building design, nonexistent or inaccessible roadway, inadequate or unsafe public or private road, overhead obstruction, deterioration of roadway due to rain, flood, or snow, construction, or other obstacles preventing the linehaul truck from accessing the pickup or delivery location. A shuttle is defined as a truck-to-truck transfer between a larger and smaller vehicle (or vice versa) that allows for safe pickup or delivery from the nearest safely accessible point to the pickup or final delivery, not a truck-to-warehouse or warehouse-to-truck transfer.', 'false', '');
INSERT INTO pws_violations VALUES (12, '1.2.5.4', 'Documentation','Physical Move Services','Inventory & Documentation','Prepare accurate and legible documentation','The contractor shall prepare and retain accurate and legible documentation (written or electronic) which reflects the true condition of all household goods. Documentation shall include, but is not limited to, weight estimates, inventory sheets, warehouse receipt, warehouse exception sheets, pickup and delivery confirmations, certified weight tickets, entitlement and any changes to such, customer notifications, record of loss and damage, claims, and record of all correspondence between contractor and customer.', 'false', '');
INSERT INTO pws_violations VALUES (13, '1.2.6.1', 'Inventory','Physical Move Services','Inventory & Documentation','Properly prepare inventories electronically and provide hard copies when requested','The contractor shall prepare all shipment inventories in accordance with International Organization for Standardization (ISO) Standard 17451-1. The contractor shall separately weigh or cube and annotate Professional Books, Papers & Equipment (PBP&E); Organizational Clothing and Individual Equipment (OCIE); and required medical equipment in accordance with government regulations. The contractor’s IT system shall be utilized 100% of the time to electronically collect inventory and condition information for each customer’s shipment. Serial numbers from electronics, major appliances, firearms, and other items shall be scanned for accurate collection and documentation. If requested, a hard paper copy inventory shall be provided to the customer.', 'false', '');
INSERT INTO pws_violations VALUES (14, '1.2.6.7.2', 'Transfer of Custody','Physical Move Services','Inventory & Documentation','Conduct transfer of custody and retain documents','When custody of a shipment is transferred to or from the contractor to another contractor, the contractor transferring custody shall furnish the contractor receiving custody with two (2) legible duplicate copies of the shipment inventory. A joint inspection shall be performed at any point liability for shipment transfers to or from the contractor and another service provider or the customer at no cost to the government. In the event a difference of opinion arises between the contractor and the receiving party regarding shortage, overage, or the condition of any element of the inventory, the contractor shall annotate such discrepancies accordingly. If no new damage or loss is discovered, the inspection documents shall state ''no differences noted.'' The absence of any annotation beside an inventory item denotes that the container and items were received in good condition. The contractor shall sign and date the completed inspection documents, obtain a signature from and provide a completed copy to the receiving party, and retain a copy for the customer’s file.', 'false', '');
INSERT INTO pws_violations VALUES (15, '1.2.6.11', 'Weight Tickets','Physical Move Services','Inventory & Documentation','Obtain proper certified weight tickets','The contractor shall obtain certified, legible, and unaltered weight tickets for each shipment or piece of a shipment if transported separately by weighing on a certified weight scale as defined in the CFR Title 49, Part 375.103. Weighing shall be conducted as defined in the CFR Title 49, Part 375.509 and shall comply with all applicable local, state, federal, and foreign country laws.', 'false', '');
INSERT INTO pws_violations VALUES (16, '1.2.6.14', 'Safeguarding PII for International Shipments','Physical Move Services','Inventory & Documentation','Safeguard customer PII for international shipments','IAW Homeland Security Customs and Border Protection guidance for safeguarding Personally Identifiable Information (PII); the contractor shall ensure its associated port agents, overseas general agents, and other responsible parties do not include the customer’s Social Security Number (SSN); the customer’s rank or grade, the words “DOD Personal Property, DOD Shipment or Military Shipment.”', 'false', '');
INSERT INTO pws_violations VALUES (17, '1.2.6.3', 'Packing/Loading','Physical Move Services','Packing/Unpacking','Protect against real and personal property damage','The contractor shall prepare, pack, unpack, load, and unload all personal property to protect all real and personal property against loss or damage.', 'false', '');
INSERT INTO pws_violations VALUES (18, '1.2.6.3.1', 'Packing Materials','Physical Move Services','Packing/Unpacking','Use appropriate packing materials','The contractor shall provide packing materials that are new or in sound condition, except in the case when the customer has provided original or specially designed packaging that the contractor has inspected and accepted as being as good or in sound condition. When allowed, and if material is not new, all marks pertaining to any previous shipment must be obliterated.', 'false', '');
INSERT INTO pws_violations VALUES (19, '1.2.6.6', 'Shipment Preparation for Non-Temporary Storage (NTS)','Physical Move Services','Packing/Unpacking','Containerize NTS shipments','The contractor shall prepare and load property going into NTS in containers at residence for shipment to NTS.', 'false', '');
INSERT INTO pws_violations VALUES (20, '1.2.6.15.1', 'Unpacking and Re-assembly','Physical Move Services','Packing/Unpacking','Properly unpack and reassemble personal property','Unloading and unpacking at destination includes the one-time laying of rugs and the one-time placement of furniture and like items in a room or dwelling designated by the customer or their representative. All articles disassembled by the contractor or originating from NTS shall be reassembled. If hardware is missing, the contractor shall obtain appropriate hardware to reassemble. On a one-time basis, all barrels, boxes, cartons, and crates shall be unpacked (upon request) and the contents placed in a room designated by the customer. This includes the placement of articles in closets, cabinets, cupboards, or on shelving in the kitchen when convenient and consistent with safety of the article(s) and proximity of the area desired by the customer, but does not include arranging the articles in a manner desired by the customer.', 'false', '');
INSERT INTO pws_violations VALUES (21, '1.2.6.15.3','Debris removal','Physical Move Services','Packing/Unpacking','Remove debris from residence','All debris incident to the packing, unpacking, loading, or unloading of the delivered shipment shall be removed on the date(s) of delivery, unless otherwise waived by the customer.', 'false', '');
INSERT INTO pws_violations VALUES (22, '1.2.6.5', 'Restricted Items','Physical Move Services','Packing/Unpacking','Improper acceptance of restricted items','The contractor shall not knowingly provide service for any item defined as restricted by law, policy or agency of the U.S. Government or any foreign entity in an international point-to-point move.', 'false', '');
INSERT INTO pws_violations VALUES (23, '1.2.5.3.2', 'Changes to Schedule','Physical Move Services','Shipment Schedule','Accommodate changes to schedule','The contractor shall accommodate all requests for a change of schedule that are received prior to delivery. Examples [not all inclusive] for changes to schedule may include: termination of shipment, rescheduling of pickup or delivery dates, diversion of shipment to a different destination, more than one pickup location for a shipment, more than one delivery location for a shipment.', 'false', '');
INSERT INTO pws_violations VALUES (24, '1.2.5.3.3', 'Cancellations','Physical Move Services','Shipment Schedule','Accommodate shipment cancellation','The contractor shall accommodate shipment cancellation up to the day of scheduled packing or pickup without cost or obligation to the government, provided packing has not begun.', 'false', '');
INSERT INTO pws_violations VALUES (25, '1.2.5.3.4', 'Diversions (D)/Terminations (T)/Reshipment (R)', 'Physical Move Services','Shipment Schedule','Properly process diversions','The contractor shall process all D/T/R based on the location of the shipment when notified, and will invoice IAW PWS, Appendix F, for services completed. Subsequent movement of the shipment(s) will be made in the most cost-effective manner based on the date and location of the shipment when the order modification was received.', 'false', '');
INSERT INTO pws_violations VALUES (26, '1.2.2.3', 'Shipment ITV','Physical Move Services','Shipment Schedule','Provide In-Transit Visibility','The contractor’s IT system shall provide geofencing tracking services within its mobile application that provides customers with real-time location tracking of the shipment once the supplier is within at least ten (10) miles of the customer’s residence. Outside of the at least ten (10) mile radius in which geofencing tracking services will be provided, the contractor’s IT system shall provide detailed point-to-point status updates including arrival and departure time and estimated arrival at destination no later than one (1) Government Business Day (GBD) from a shipment location or status change.', 'false', '');
INSERT INTO pws_violations VALUES (27, '1.2.5.3.5', 'Installation Scheduling','Physical Move Services','Workforce/Sub-Contractor Management','Adhere to military facility / base access guidelines','The contractor shall schedule all pickups or deliveries in accordance with specific installation or facility requirements. Any delay due to personnel disqualification from specific installation access or failure to follow published access guidelines shall be considered an unacceptable delay.', 'false', '');
INSERT INTO pws_violations VALUES (28, '1.2.6.7', 'Pickup','Physical Move Services','Shipment Schedule','Pick up shipment on time','The contractor shall pickup all pieces of a shipment on the scheduled pickup date. The shipment is not considered an on-time pickup if the contractor changes the date at any time without approval of the customer.','true','QAE Observed Pickup Date');
INSERT INTO pws_violations VALUES (29, '1.2.6.8', 'Hours of Operation','Physical Move Services','Shipment Schedule','Adhere to Hours of Operation','The contractor shall not begin pickup or delivery at the customer’s residence before 0800 hours or after 1700 hours without prior approval of the customer or the government.', 'false', '');
INSERT INTO pws_violations VALUES (30, '1.2.6.9', 'Transport','Physical Move Services','Shipment Schedule','Deliver by Required Delivery Date','The contractor shall transport shipments, including non-standard shipments (Appendix D); from origin to destination so as to ensure delivery by the RDD as determined by the domestic and international (to include household goods shipments and unaccompanied baggage shipments) transit times located in Appendix C, attached hereto.','true','QAE Observed Delivery Date');
INSERT INTO pws_violations VALUES (31, '1.2.6.15', 'Delivery','Physical Move Services','Shipment Schedule','Deliver by Required Delivery Date','The contractor shall deliver and unload all pieces of a shipment as scheduled by the RDD.','true','QAE Observed Delivery Date');
INSERT INTO pws_violations VALUES (32, '1.2.8.2','Scheduling Notifications','Physical Move Services','Shipment Schedule','Notify customer of scheduled dates','The contractor shall notify the customer of all scheduled dates as soon as known for counseling, packing, unpacking, pickup, delivery, and all other dates for which interaction with the contractor by the customer is required.', 'false', '');
INSERT INTO pws_violations VALUES (33, '1.2.8.5','Inbound Shipment Notification','Physical Move Services','Shipment Schedule','Notify customer at least 24 hours in advance of delivery','The contractor shall notify and confirm with the customer no later than twenty-four (24) hours in advance of shipment delivery.', 'false', '');
INSERT INTO pws_violations VALUES (34, '1.2.8.6','Quality Assurance Schedule Notification','Physical Move Services','Shipment Schedule','Provide QA Forecast','On a daily basis, NLT 0800 local installation time, the contractor shall provide the government a rolling 30-day Shipment Schedule containing the schedule for all shipments being packed, picked-up, or delivered for the purposes of scheduling government QAE. The report shall contain all dates, shall be filterable by installation, city, county, state, country, and shall contain the address location of the origin or destination activities to be observed.', 'false', '');
INSERT INTO pws_violations VALUES (35, '1.2.6.12', 'Reweighs','Physical Move Services','Shipment Weights','Conduct reweigh when requested','When requested by the customer or the COR, the contractor shall conduct a reweigh before the actual commencement of unloading for delivery.', 'false', '');
INSERT INTO pws_violations VALUES (36, '1.2.8.3','Weight Notifications','Physical Move Services','Shipment Weights','Notify customer and government of shipment weight in a timely fashion','The contractor shall notify the customer and the government of the actual weight of each shipment within one (1) GBD of shipment pickup or prior to delivery or placement into SIT, whichever is earlier.', 'false', '');
INSERT INTO pws_violations VALUES (37, '1.2.8.4','Excess Cost Notifications','Physical Move Services','Shipment Weights','Notify customer of excess cost','If a customer is at risk for excess costs based on any shipment or combination of shipments exceeding or being within 10% or closer to their total weight entitlement or any other entitlement, the contractor shall notify the customer within one (1) day of discovery. Notification shall include that the customer is responsible for any excess costs that may be incurred, provide an estimated excess cost amount, and obtain written acknowledgment from the customer', 'false', '');
INSERT INTO pws_violations VALUES (38, '1.2.6.15.4','Storage-in-Transit (SIT)', 'Physical Move Services','Storage','Request ordering and payment of storage in accordance with SIT eligibility window','The contractor’s period of SIT eligibility begins on the First Available Delivery Date (FADD) and ends by the 5th day after the requested delivery date from storage or the actual delivery date, whichever is earlier', 'false', '');
INSERT INTO pws_violations VALUES (39, '1.2.6.16', 'Storage','Physical Move Services','Storage','Provide adequate storage facilities','The contractor shall provide warehouse storage facilities to accommodate SIT as required in accordance with all local, state, federal, and country fire, safety and construction codes, standards and ordinances, ensuring that all stored shipments are adequately protected. For SIT facilities residing in a multi-occupancy structure, the SIT provider’s storage area will be separated from other occupants of the building by a firewall or partition having a fire resistance rating sufficient to protect the warehouse from the fire exposure of the other occupant. The minimum separation shall be a solid wall or partition, without windows, doors or other openings, having a fire resistance rating of not less than one hour. The construction, upkeep, purchase, lease or rental of any commercial structure, land, or equipment for the storage facility shall be the responsibility of the contractor. All SIT facilities shall maintain at least an operational Class 3 supervised detection and reporting system. All facilities shall meet all requirements for insurance rate credit by the Insurance Services Office (ISO) or other cognizant fire insurance rating organization for an other than wood frame or pole building and shall provide a fire wall separation resistance rating sufficient to protect the warehouse from the fire exposure of another occupant. If host country standards, practices, or customs conflict with SIT standards, exceptions may be granted by the Government Representative. All storage facilities shall be located above the 100-year flood plain for the area.', 'false', '');
INSERT INTO pws_violations VALUES (40, '1.2.6.16.1', 'Shipment Hostage','Physical Move Services','Storage','No contractor entity shall hold a shipment hostage','The contractor and all subcontractors performing services under this contract acknowledge that holding shipments hostage is a violation of USC Title 37, Section 453, at subparagraph (c)(5) which provides, ''No carrier, port agent, warehouseman, freight forwarder, or other person involved in the transportation of property may have a lien on, or hold, impound, or otherwise interfere with the movement of baggage and household goods being transported under this section.”', 'false', '');
INSERT INTO pws_violations VALUES (41, '1.2.8.7.1', 'Advance Notice of SIT Expirations & Extensions','Physical Move Services','Storage','Provide notice of SIT expiration','Thirty (30) days prior to expiration of any SIT entitlement, the contractor shall provide the customer written notification via traceable means of the upcoming expiration and seek a desired disposition from the customer. The notification shall include, at a minimum, the exact date responsibility for storage charges and fees transfers to the customer, all costs and fees the customer can expect to incur, and changes in insurance coverage.', 'false', '');
INSERT INTO pws_violations VALUES (42, '1.2.8.7.2','SIT Extension','Physical Move Services','Storage','Request SIT extension for customer','If the customer requests delivery after the SIT expiration date or requests an extension of storage, the contractor shall prepare and submit a written request to extend the storage period at government expense.', 'false', '');
INSERT INTO pws_violations VALUES (43, '1.2.8.7.3','Conversion to Customer’s Expense','Physical Move Services','Storage','Properly convert storage lot to customer expense','Upon approval by the Government and expiration of the SIT entitlement, the contractor shall consider the DoD customer’s property converted to customer’s expense. Once converted, the contractor shall provide the customer written notification by traceable means, within five (5) days from the date their account converted to customer’s expense.', 'false', '');
INSERT INTO pws_violations VALUES (44, '1.2.8.7.4', 'Disposition of Converted Shipments','Physical Move Services','Storage','Properly dispose of storage lot','The contractor shall seek authorization from the customer by way of a notarized authorization to dispose of the property. If authorization is not obtained, the contractor shall follow all applicable local, state and federal laws when disposing of lots converted to customer’s expense.', 'false', '');
INSERT INTO pws_violations VALUES (45, '1.2.1.1', 'Background Checks/Records','Physical Move Services','Workforce/Sub-Contractor Management','Conduct background checks','Prior to engaging in any services identified herein, the contractor shall ensure a background check is conducted (at contractor expense); IAW industry standard, for all persons performing under this contract whose role involves interacting with a customer or handling or transporting shipments. The contractor shall provide employment records to Government upon request, to the extent allowed by law.', 'false', '');
INSERT INTO pws_violations VALUES (46, '1.2.1.1', 'Background Checks/Records','Physical Move Services','Workforce/Sub-Contractor Management','Government disqualification of employee','The government has the right to prevent certain employees from performing under the contract due to an unfavorable background check.', 'false', '');
INSERT INTO pws_violations VALUES (47, '1.2.1.2', 'Workforce Requirements' ,'Physical Move Services','Workforce/Sub-Contractor Management','Personnel are trained in assigned duties','The contractor shall ensure all employees remain trained and qualified in their assigned duties.', 'false', '');
INSERT INTO pws_violations VALUES (48, '1.2.1.2', 'Workforce Requirements','Physical Move Services','Workforce/Sub-Contractor Management','Prohibition of smoking','Smoking is prohibited in the customer’s residence or within 50 feet of personal property during all phases of shipment and storage.', 'false', '');
INSERT INTO pws_violations VALUES (49, '1.2.1.2', 'Workforce Requirements','Physical Move Services','Workforce/Sub-Contractor Management','Possession or Under Influence of Drugs or Alcohol','The contractor shall ensure all employees and sub-contractors are free from possession of and not under the influence of drugs or alcohol while in a customer’s residence or handling a customer’s personal property.', 'false', '');
INSERT INTO pws_violations VALUES (50, '1.2.1.2.1', 'Defense Personal Property Program (DP3) Performance History','Physical Move Services','Workforce/Sub-Contractor Management','Use of disqualified entity (3 years)','Contractor shall ensure no entity that has been disqualified or revoked from DP3 within three (3) years of move execution date will perform work under this contract.', 'false', '');
INSERT INTO pws_violations VALUES (51, '1.2.1.3','Customer Interaction','Physical Move Services','Workforce/Sub-Contractor Management','At least one crewmember fluent in English language','At least one crewmember or warehouse employee, where applicable, shall be fluent in English for the purposes of customer interaction.', 'false', '');
INSERT INTO pws_violations VALUES (52, '1.2.1.3','Customer Interaction','Physical Move Services','Workforce/Sub-Contractor Management','Appearance of contractor personnel','All personnel shall be clean and neat and be easily identifiable as company personnel.', 'false', '');
INSERT INTO pws_violations VALUES (53, '1.2.1.3', 'Customer Interaction','Physical Move Services','Workforce/Sub-Contractor Management','Replacement of employees exhibiting unprofessional behavior','The contractor shall replace any individuals exhibiting unprofessional behavior, when requested by the customer or a government representative.', 'false', '');
INSERT INTO pws_violations VALUES (54, '1.2.1.4', 'Driver Identification/Qualification Requirements','Physical Move Services','Workforce/Sub-Contractor Management','Use of qualified drivers','The contractor shall ensure all drivers who perform under this contract are qualified and licensed in accordance with local, state, federal, and foreign country or international laws.', 'false', '');
INSERT INTO pws_violations VALUES (55, '1.2.6.16.3', 'Damage Mitigation','Liability','Loss & Damage','Takes reasonable steps to reduce damage (Liability exclusions)','In the event a shipment is damaged as a result of any one of the excluded causes listed in Appendix E, para E.3., Exclusions from Liability, the contractor shall take reasonable steps to mitigate the extent of the damage.', 'false', '');
INSERT INTO pws_violations VALUES (56, '1.2.6.16.4', 'Possible Contamination','Liability','Loss & Damage','Notify COR of contaminated containers','The contractor shall contact the responsible contracting officer representative (COR) when containers show signs of possible contamination, for example water saturation or mold growth on the exterior.', 'false', '');
INSERT INTO pws_violations VALUES (57, '1.2.6.16.8' , 'Shipment Inspection','Liability','Loss & Damage','Inspect and remove items of sentimental value','The contractor shall offer the customer an opportunity to inspect the shipment and remove items of sentimental or special value at the owner’s discretion in coordination with the responsible QAE or COR.', 'false', '');
INSERT INTO pws_violations VALUES (58, '1.2.6.16.10', 'Delivery of Remediated Items','Liability','Loss & Damage','Provide notification and delivery of remediated items','Before delivery, contractor shall notify the customer and destination QAE or COR that the items have been remediated, are ready for delivery, and provide a reasonable opportunity to inspect the remediated items before delivery begins.', 'false', '');
INSERT INTO pws_violations VALUES (59, '1.2.6.16.11','Customer Elects to Inspect Remediated Items','Liability','Loss & Damage','Facilitate customer inspection and acceptance of remediated items','If the customer does not accept the remediation on any item during the inspection, that item shall be separated from the accepted items. If the contractor agrees with the customer that those items are unacceptable, the contractor shall deliver the accepted items and process claims on the unacceptable items for compensation at FRV.', 'false', '');
INSERT INTO pws_violations VALUES (60, '1.2.6.16.13', 'Mold Remediation','Liability','Loss & Damage','Payment of mold remediation services','Services for mold remediation will normally be at the expense of the contractor, however, service payments may be authorized when the Government determines the mitigating contractor is not liable for the damage. Contractor shall request the service authorization from the local Ordering OO.', 'false', '');
INSERT INTO pws_violations VALUES (61, '1.2.7.2.3', 'Inconvenience Claim','Liability','Inconvenience & Hardship Claims','Payment for inconvenience claims','The contractor shall pay the customer a daily amount equal to the applicable pickup or delivery location government per diem (to exclude lodging) for all individuals on the relocation order according to the JTR for all days past the missed pickup or delivery date. The contractor shall, in addition, pay the customer the applicable daily amount for each day the customer is awaiting delivery out of SIT if not completed on customer’s first requested date and scheduled delivery date is not within five (5) GBDs (within ten (10) GBDs for shipments with a requested delivery date between June 15 through August 15).', 'false', '');
INSERT INTO pws_violations VALUES (62, '1.2.7.2.1', 'Scope of Liability','Liability','Loss & Damage','Liability for Full Replacement Value','The contractor shall be liable for all loss or damage up to Full Replacement Value (FRV) for all shipments from the point of origin to the point custody transfers to a customer as defined in the Claims and Liability Rules (Appendix E). For the contractor to claim any exemptions, contractor must prove it was free from negligence. The contractor accepts full responsibility for performance of all of its employees, subcontractors, and agents. In the event of any damage to public or private property from acts or omissions of persons performing under this contract, the contractor shall immediately repair and correct damages at contractor’s expense.', 'false', '');
INSERT INTO pws_violations VALUES (63, '1.2.7.2.2', 'Claims Settlement','Liability','Loss & Damage','Respond to claims in a timely fashion','The contractor shall pay, deny, or make an offer on all claims valued at $1000 or less within 30 calendar days of receipt of the claim and of all other claims within 60 calendar days of receipt IAW the Claims and Liability Rules (Appendix E).','true','Observed Claim Response Date (Or None)');
INSERT INTO pws_violations VALUES (64, '1.2.7.2.4','Hardship Expenses','Liability','Inconvenience & Hardship Claims','Pay for customer’s hardship expenses due to service failure','In the event the contractor fails to perform IAW the agreed to schedule, the contractor shall reimburse the customer for any out of pocket expenses incurred which are determined unavoidable and unrecoverable under any other means by the COR. These amounts shall be in addition to amounts paid in relation to an inconvenience claim.', 'false', '');
