CREATE TABLE lines_of_accounting
(
	id uuid PRIMARY KEY,
	loa_sys_id integer,
	loa_dpt_id char(2),
	loa_tnsfr_dpt_nm varchar(4),
	loa_baf_id varchar(4),
	loa_trsy_sfx_tx varchar(4),
	loa_maj_clm_nm varchar(4),
	loa_op_agncy_id varchar(4),
	loa_allt_sn_id varchar(5),
	loa_pgm_elmnt_id varchar(12),
	loa_tsk_bdgt_sbln_tx varchar(8),
	loa_df_agncy_alctn_rcpnt_id varchar(4),
	loa_jb_ord_nm varchar(10),
	loa_sbaltmt_rcpnt_id char(1),
	loa_wk_cntr_rcpnt_nm varchar(6),
	loa_maj_rmbsmt_src_id char(1),
	loa_dtl_rmbsmt_src_id varchar(3),
	loa_cust_nm varchar(6),
	loa_obj_cls_id varchar(6),
	loa_srv_src_id char(1),
	loa_spcl_intr_id char(2),
	loa_bdgt_acnt_cls_nm varchar(8),
	loa_doc_id varchar(15),
	loa_cls_ref_id char(2),
	loa_instl_acntg_act_id varchar(6),
	loa_lcl_instl_id varchar(18),
	loa_fms_trnsactn_id varchar(12),
	loa_dsc_tx text,
	loa_bgn_dt date,
	loa_end_dt date,
	loa_fnct_prs_nm varchar(255),
	loa_stat_cd char(1),
	loa_hist_stat_cd char(1),
	loa_hs_gds_cd char(2),
	org_grp_dfas_cd char(2),
	loa_uic char(6),
	loa_trnsn_id varchar(255),
	loa_sub_acnt_id char(3),
	loa_bet_cd char(4),
	loa_fnd_ty_fg_cd char(1),
	loa_bgt_ln_itm_id varchar(8),
	loa_scrty_coop_impl_agnc_cd char(1),
	loa_scrty_coop_dsgntr_cd varchar(4),
	loa_scrty_coop_ln_itm_id varchar(3),
	loa_agnc_dsbr_cd char(6),
	loa_agnc_acntng_cd char(6),
	loa_fnd_cntr_id varchar(12),
	loa_cst_cntr_id varchar(16),
	loa_prj_id varchar(12),
	loa_actvty_id varchar(11),
	loa_cst_cd varchar(16),
	loa_wrk_ord_id varchar(16),
	loa_fncl_ar_id varchar(6),
	loa_scrty_coop_cust_cd char(2),
	loa_end_fy_tx integer,
	loa_bg_fy_tx integer,
	loa_bgt_rstr_cd char(1),
	loa_bgt_sub_act_cd char(4),
	created_at timestamp without time zone NOT NULL,
	updated_at timestamp without time zone NOT NULL
);

ALTER TABLE transportation_accounting_codes
ADD loa_id uuid NOT NULL,
ADD tac_sys_id integer,
ADD loa_sys_id integer,
ADD tac_fy_txt integer NOT NULL,
ADD tac_fn_bl_mod_cd char(1),
ADD org_grp_dfas_cd char(2),
ADD tac_mvt_dsg_id varchar(255),
ADD tac_ty_cd char(1),
ADD tac_use_cd varchar(2),
ADD tac_maj_clmt_id varchar(6),
ADD tac_bill_act_txt varchar(6),
ADD tac_cost_ctr_nm varchar(6),
ADD buic char(6),
ADD tac_hist_cd char(1),
ADD tac_stat_cd char(1),
ADD trnsprtn_acnt_tx text,
ADD trnsprtn_acnt_bgn_dt date,
ADD trnsprtn_acnt_end_dt date,
ADD dd_actvty_adrs_id char(6),
ADD tac_blld_add_frst_ln_tx varchar(255),
ADD tac_blld_add_scnd_ln_tx varchar(255),
ADD tac_blld_add_thrd_ln_tx varchar(255),
ADD tac_blld_add_frth_ln_tx varchar(255),
ADD tac_fnct_poc_nm varchar(255);

ALTER TABLE transportation_accounting_codes
	ADD CONSTRAINT transportation_accounting_codes_loa_id_fkey FOREIGN KEY (loa_id) REFERENCES lines_of_accounting (id);
