UPDATE pws_violations SET display_order = 71 WHERE display_order = 64;
UPDATE pws_violations SET display_order = 70 WHERE display_order = 63;
UPDATE pws_violations SET display_order = 69 WHERE display_order = 62;
UPDATE pws_violations SET display_order = 68 WHERE display_order = 61;
UPDATE pws_violations SET display_order = 67 WHERE display_order = 60;
UPDATE pws_violations SET display_order = 66 WHERE display_order = 59;
UPDATE pws_violations SET display_order = 65 WHERE display_order = 58;
UPDATE pws_violations SET display_order = 64 WHERE display_order = 57;
UPDATE pws_violations SET display_order = 63 WHERE display_order = 56;
UPDATE pws_violations SET display_order = 62 WHERE display_order = 55;
UPDATE pws_violations SET display_order = 61 WHERE display_order = 54;
UPDATE pws_violations SET display_order = 60 WHERE display_order = 53;
UPDATE pws_violations SET display_order = 59 WHERE display_order = 52;
UPDATE pws_violations SET display_order = 58 WHERE display_order = 51;
UPDATE pws_violations SET display_order = 57 WHERE display_order = 50;
UPDATE pws_violations SET display_order = 56 WHERE display_order = 49;
UPDATE pws_violations SET display_order = 55 WHERE display_order = 48;
UPDATE pws_violations SET display_order = 54 WHERE display_order = 47;
UPDATE pws_violations SET display_order = 53 WHERE display_order = 46;
UPDATE pws_violations SET display_order = 52 WHERE display_order = 45;
UPDATE pws_violations SET display_order = 51 WHERE display_order = 44;
UPDATE pws_violations SET display_order = 50 WHERE display_order = 43;
UPDATE pws_violations SET display_order = 49 WHERE display_order = 42;
UPDATE pws_violations SET display_order = 48 WHERE display_order = 41;
UPDATE pws_violations SET display_order = 47 WHERE display_order = 40;
UPDATE pws_violations SET display_order = 46 WHERE display_order = 39;
UPDATE pws_violations SET display_order = 45 WHERE display_order = 38;
UPDATE pws_violations SET display_order = 44 WHERE display_order = 37;
UPDATE pws_violations SET display_order = 43 WHERE display_order = 36;
UPDATE pws_violations SET display_order = 42 WHERE display_order = 35;
UPDATE pws_violations SET display_order = 41 WHERE display_order = 34;
UPDATE pws_violations SET display_order = 40 WHERE display_order = 33;
UPDATE pws_violations SET display_order = 39 WHERE display_order = 32;
UPDATE pws_violations SET display_order = 38 WHERE display_order = 31;
UPDATE pws_violations SET display_order = 37 WHERE display_order = 30;
UPDATE pws_violations SET display_order = 36 WHERE display_order = 29;
UPDATE pws_violations SET display_order = 35 WHERE display_order = 28;
UPDATE pws_violations SET display_order = 34 WHERE display_order = 27;
UPDATE pws_violations SET display_order = 33 WHERE display_order = 26;
UPDATE pws_violations SET display_order = 32 WHERE display_order = 25;
UPDATE pws_violations SET display_order = 31 WHERE display_order = 24;
UPDATE pws_violations SET display_order = 30 WHERE display_order = 23;

UPDATE pws_violations SET display_order = 24 WHERE display_order = 22;
UPDATE pws_violations SET display_order = 23 WHERE display_order = 21;
UPDATE pws_violations SET display_order = 22 WHERE display_order = 20;
UPDATE pws_violations SET display_order = 21 WHERE display_order = 19;
UPDATE pws_violations SET display_order = 20 WHERE display_order = 18;
UPDATE pws_violations SET display_order = 19 WHERE display_order = 17;

INSERT INTO pws_violations VALUES ('2ff1116a-17a9-4624-a462-72c3cbbaefc5', 17, '1.2.6.1.2', 'Inventory Barcoding','Physical Move Services','Inventory & Documentation','Items must be barcoded. Barcodes must be scanned during inventory process.','Each item, crate, and carton shall be affixed with a unique barcoded sticker label and tag number to enable in-app scanning and enhance load and delivery inventory confirmation. No items shall be loaded on the truck unless the item has been barcoded and inventoried. At destination, each item or carton shall be scanned as it is unloaded from the truck to ensure all pieces are delivered.', 'false', '');
INSERT INTO pws_violations VALUES ('0220ef66-03f2-419b-a4e4-e6d87c51191c', 18, '1.2.6.2', 'Organizational Clothing & Individual Equipment','Physical Move Services','Inventory & Documentation','Identify and separate Organizational Clothing & Individual Equipment (OCIE)','OCIE is clothing and equipment issued to customers for use in the performance of duty. It is common for customers to personally purchase items for use in their duties that appear to be OCIE items but are not. These items are commonly referred to as “personal kit”. The contractor shall request that the customer identify personal kit items. The contractor shall separate personal kit items from OCIE for inventory and claims purposes. The contractor shall conduct an inventory of OCIE at pack-out and delivery. The contractor shall identify OCIE as “M-PRO” on the inventory.', 'false', '');
INSERT INTO pws_violations VALUES ('8efbb25a-7182-4123-b739-61af57c33168', 25, '1.2.6.3.3', 'Packing/Unpacking Unaccompanied Baggage', 'Physical Move Services', 'Packing/Unpacking', 'Unaccompanied Baggage (UB) packing / unpacking done in accordance with JTR. UB rates apply.', 'Unaccompanied baggage packing and unpacking rates shall be used when the task order includes unaccompanied baggage, and for all items being transported under an unaccompanied baggage rate. Unaccompanied baggage shall be packed and unpacked in accordance with the Joint Travel Regulation.',	'false', '');
INSERT INTO pws_violations VALUES ('7f934ba0-2322-4642-99d7-359ba413882a', 26, '1.2.6.6.1', 'Cartons & Packing Material (Shipment Preparation for NTS)', 'Physical Move Services', 'Packing/Unpacking', 'Cartons and other packing material must meet contract specifications. (Shipment Preparation for NTS)', 'All cartons and wrapping material shall be in new or sound condition and adequate for the use employed. New packing material shall be used for mattresses, box springs, linens, bedding, and clothing. After packing, cartons shall be closed and sealed by taping lengthwise at all joints. Cartons shall have a minimum average bursting strength of 200 pounds per square inch and dish packs shall have a minimum average bursting strength of 350 pounds per square inch. Cartons shall be stacked in an upright position to minimize crushing, with the exception of mattress cartons. Plastic containers (tote or similar) and similar types of containers shall not be used. However, if items are packed by the customer in plastic or similar type containers, the contractor may pack these containers in an approved carton if a carton is available that will accommodate the container. If the plastic container cannot be packed in an approved carton, the contractor shall empty and pack the contents into an appropriate approved carton.', 'false', '');
INSERT INTO pws_violations VALUES ('b41a9f7b-07ed-481b-8c59-0e26f442aca5', 27, '1.2.6.6.3', 'Mattresses & Box Springs (Shipment Preparation for NTS)', 'Physical Move Services', 'Packing/Unpacking', 'Mattresses and box springs must be placed in cartons and sealed. (Shipment Preparation for NTS)', 'All mattresses and box springs, except those in hide-a-beds or sofa beds, shall be placed in cartons and completely sealed.', 'false', '');
INSERT INTO pws_violations VALUES ('30a4e886-a4f6-4cd8-85b7-bf72d52b3b2e', 28, '1.2.6.6.5', 'Rugs, Rug Pads, Carpet (Shipment Preparation for NTS)', 'Physical Move Services', 'Packing/Unpacking', 'Rugs, rug pads, carpet must be rolled, covered and taped. (Shipment Preparation for NTS)', 'All rugs, rug pads and carpets shall be properly rolled (not folded) and covered by paper and secured with tape or equivalent materials.', 'false', '');
INSERT INTO pws_violations VALUES ('0e596cb5-fe04-4214-9644-8432c0aeaf72', 29, '1.2.6.6.8', 'Appliance packing rules (Shipment Preparation for NTS)', 'Physical Move Services', 'Packing/Unpacking', 'Nothing shall be packed in appliances excepting integral parts. (Shipment Preparation for NTS)', 'Nothing shall be packed in washers, dryers, refrigerators, freezers, stoves, or other major appliances except such items as electrical cords, connecting hoses and similar items that are required as an integral part of the appliance in its normal operation.', 'false', '');