-- Set temp timeout due to large modification
-- Time is 5 minutes in milliseconds
SET statement_timeout = 300000;
SET lock_timeout = 300000;
SET idle_in_transaction_session_timeout = 300000;

-- remove trailing spaces and reset empty strings to null of tget tables

UPDATE transportation_accounting_codes
SET
    tac_sys_id = CASE WHEN TRIM(tac_sys_id) = '' THEN NULL ELSE TRIM(tac_sys_id) END,
    loa_sys_id = CASE WHEN TRIM(loa_sys_id) = '' THEN NULL ELSE TRIM(loa_sys_id) END,
    tac_fn_bl_mod_cd = CASE WHEN TRIM(tac_fn_bl_mod_cd) = '' THEN NULL ELSE TRIM(tac_fn_bl_mod_cd) END,
    org_grp_dfas_cd = CASE WHEN TRIM(org_grp_dfas_cd) = '' THEN NULL ELSE TRIM(org_grp_dfas_cd) END,
    tac_mvt_dsg_id = CASE WHEN TRIM(tac_mvt_dsg_id) = '' THEN NULL ELSE TRIM(tac_mvt_dsg_id) END,
    tac_fy_txt = CASE WHEN TRIM(tac_fy_txt) = '' THEN NULL ELSE TRIM(tac_fy_txt) END,
    tac_ty_cd = CASE WHEN TRIM(tac_ty_cd) = '' THEN NULL ELSE TRIM(tac_ty_cd) END,
    tac_use_cd = CASE WHEN TRIM(tac_use_cd) = '' THEN NULL ELSE TRIM(tac_use_cd) END,
    tac_maj_clmt_id = CASE WHEN TRIM(tac_maj_clmt_id) = '' THEN NULL ELSE TRIM(tac_maj_clmt_id) END,
    tac_bill_act_txt = CASE WHEN TRIM(tac_bill_act_txt) = '' THEN NULL ELSE TRIM(tac_bill_act_txt) END,
    tac_cost_ctr_nm = CASE WHEN TRIM(tac_cost_ctr_nm) = '' THEN NULL ELSE TRIM(tac_cost_ctr_nm) END,
    buic = CASE WHEN TRIM(buic) = '' THEN NULL ELSE TRIM(buic) END,
    tac_hist_cd = CASE WHEN TRIM(tac_hist_cd) = '' THEN NULL ELSE TRIM(tac_hist_cd) END,
    tac_stat_cd = CASE WHEN TRIM(tac_stat_cd) = '' THEN NULL ELSE TRIM(tac_stat_cd) END,
    trnsprtn_acnt_tx = CASE WHEN TRIM(trnsprtn_acnt_tx) = '' THEN NULL ELSE TRIM(trnsprtn_acnt_tx) END,
    dd_actvty_adrs_id = CASE WHEN TRIM(dd_actvty_adrs_id) = '' THEN NULL ELSE TRIM(dd_actvty_adrs_id) END,
    tac_blld_add_frst_ln_tx = CASE WHEN TRIM(tac_blld_add_frst_ln_tx) = '' THEN NULL ELSE TRIM(tac_blld_add_frst_ln_tx) END,
    tac_blld_add_scnd_ln_tx = CASE WHEN TRIM(tac_blld_add_scnd_ln_tx) = '' THEN NULL ELSE TRIM(tac_blld_add_scnd_ln_tx) END,
    tac_blld_add_thrd_ln_tx = CASE WHEN TRIM(tac_blld_add_thrd_ln_tx) = '' THEN NULL ELSE TRIM(tac_blld_add_thrd_ln_tx) END,
    tac_blld_add_frth_ln_tx = CASE WHEN TRIM(tac_blld_add_frth_ln_tx) = '' THEN NULL ELSE TRIM(tac_blld_add_frth_ln_tx) END,
    tac_fnct_poc_nm = CASE WHEN TRIM(tac_fnct_poc_nm) = '' THEN NULL ELSE TRIM(tac_fnct_poc_nm) END;

UPDATE lines_of_accounting
SET
    loa_sys_id = CASE WHEN TRIM(loa_sys_id) = '' THEN NULL ELSE TRIM(loa_sys_id) END,
    loa_dpt_id = CASE WHEN TRIM(loa_dpt_id) = '' THEN NULL ELSE TRIM(loa_dpt_id) END,
    loa_tnsfr_dpt_nm = CASE WHEN TRIM(loa_tnsfr_dpt_nm) = '' THEN NULL ELSE TRIM(loa_tnsfr_dpt_nm) END,
    loa_baf_id = CASE WHEN TRIM(loa_baf_id) = '' THEN NULL ELSE TRIM(loa_baf_id) END,
    loa_trsy_sfx_tx = CASE WHEN TRIM(loa_trsy_sfx_tx) = '' THEN NULL ELSE TRIM(loa_trsy_sfx_tx) END,
    loa_maj_clm_nm = CASE WHEN TRIM(loa_maj_clm_nm) = '' THEN NULL ELSE TRIM(loa_maj_clm_nm) END,
    loa_op_agncy_id = CASE WHEN TRIM(loa_op_agncy_id) = '' THEN NULL ELSE TRIM(loa_op_agncy_id) END,
    loa_allt_sn_id = CASE WHEN TRIM(loa_allt_sn_id) = '' THEN NULL ELSE TRIM(loa_allt_sn_id) END,
    loa_pgm_elmnt_id = CASE WHEN TRIM(loa_pgm_elmnt_id) = '' THEN NULL ELSE TRIM(loa_pgm_elmnt_id) END,
    loa_tsk_bdgt_sbln_tx = CASE WHEN TRIM(loa_tsk_bdgt_sbln_tx) = '' THEN NULL ELSE TRIM(loa_tsk_bdgt_sbln_tx) END,
    loa_df_agncy_alctn_rcpnt_id = CASE WHEN TRIM(loa_df_agncy_alctn_rcpnt_id) = '' THEN NULL ELSE TRIM(loa_df_agncy_alctn_rcpnt_id) END,
    loa_jb_ord_nm = CASE WHEN TRIM(loa_jb_ord_nm) = '' THEN NULL ELSE TRIM(loa_jb_ord_nm) END,
    loa_sbaltmt_rcpnt_id = CASE WHEN TRIM(loa_sbaltmt_rcpnt_id) = '' THEN NULL ELSE TRIM(loa_sbaltmt_rcpnt_id) END,
    loa_wk_cntr_rcpnt_nm = CASE WHEN TRIM(loa_wk_cntr_rcpnt_nm) = '' THEN NULL ELSE TRIM(loa_wk_cntr_rcpnt_nm) END,
    loa_maj_rmbsmt_src_id = CASE WHEN TRIM(loa_maj_rmbsmt_src_id) = '' THEN NULL ELSE TRIM(loa_maj_rmbsmt_src_id) END,
    loa_dtl_rmbsmt_src_id = CASE WHEN TRIM(loa_dtl_rmbsmt_src_id) = '' THEN NULL ELSE TRIM(loa_dtl_rmbsmt_src_id) END,
    loa_cust_nm = CASE WHEN TRIM(loa_cust_nm) = '' THEN NULL ELSE TRIM(loa_cust_nm) END,
    loa_obj_cls_id = CASE WHEN TRIM(loa_obj_cls_id) = '' THEN NULL ELSE TRIM(loa_obj_cls_id) END,
    loa_srv_src_id = CASE WHEN TRIM(loa_srv_src_id) = '' THEN NULL ELSE TRIM(loa_srv_src_id) END,
    loa_spcl_intr_id = CASE WHEN TRIM(loa_spcl_intr_id) = '' THEN NULL ELSE TRIM(loa_spcl_intr_id) END,
    loa_bdgt_acnt_cls_nm = CASE WHEN TRIM(loa_bdgt_acnt_cls_nm) = '' THEN NULL ELSE TRIM(loa_bdgt_acnt_cls_nm) END,
    loa_doc_id = CASE WHEN TRIM(loa_doc_id) = '' THEN NULL ELSE TRIM(loa_doc_id) END,
    loa_cls_ref_id = CASE WHEN TRIM(loa_cls_ref_id) = '' THEN NULL ELSE TRIM(loa_cls_ref_id) END,
    loa_instl_acntg_act_id = CASE WHEN TRIM(loa_instl_acntg_act_id) = '' THEN NULL ELSE TRIM(loa_instl_acntg_act_id) END,
    loa_lcl_instl_id = CASE WHEN TRIM(loa_lcl_instl_id) = '' THEN NULL ELSE TRIM(loa_lcl_instl_id) END,
    loa_fms_trnsactn_id = CASE WHEN TRIM(loa_fms_trnsactn_id) = '' THEN NULL ELSE TRIM(loa_fms_trnsactn_id) END,
    loa_dsc_tx = CASE WHEN TRIM(loa_dsc_tx) = '' THEN NULL ELSE TRIM(loa_dsc_tx) END,
    loa_fnct_prs_nm = CASE WHEN TRIM(loa_fnct_prs_nm) = '' THEN NULL ELSE TRIM(loa_fnct_prs_nm) END,
    loa_stat_cd = CASE WHEN TRIM(loa_stat_cd) = '' THEN NULL ELSE TRIM(loa_stat_cd) END,
    loa_hist_stat_cd = CASE WHEN TRIM(loa_hist_stat_cd) = '' THEN NULL ELSE TRIM(loa_hist_stat_cd) END,
    loa_hs_gds_cd = CASE WHEN TRIM(loa_hs_gds_cd) = '' THEN NULL ELSE TRIM(loa_hs_gds_cd) END,
    org_grp_dfas_cd = CASE WHEN TRIM(org_grp_dfas_cd) = '' THEN NULL ELSE TRIM(org_grp_dfas_cd) END,
    loa_uic = CASE WHEN TRIM(loa_uic) = '' THEN NULL ELSE TRIM(loa_uic) END,
    loa_trnsn_id = CASE WHEN TRIM(loa_trnsn_id) = '' THEN NULL ELSE TRIM(loa_trnsn_id) END,
    loa_sub_acnt_id = CASE WHEN TRIM(loa_sub_acnt_id) = '' THEN NULL ELSE TRIM(loa_sub_acnt_id) END,
    loa_bet_cd = CASE WHEN TRIM(loa_bet_cd) = '' THEN NULL ELSE TRIM(loa_bet_cd) END,
    loa_fnd_ty_fg_cd = CASE WHEN TRIM(loa_fnd_ty_fg_cd) = '' THEN NULL ELSE TRIM(loa_fnd_ty_fg_cd) END,
    loa_bgt_ln_itm_id = CASE WHEN TRIM(loa_bgt_ln_itm_id) = '' THEN NULL ELSE TRIM(loa_bgt_ln_itm_id) END,
    loa_scrty_coop_impl_agnc_cd = CASE WHEN TRIM(loa_scrty_coop_impl_agnc_cd) = '' THEN NULL ELSE TRIM(loa_scrty_coop_impl_agnc_cd) END,
    loa_scrty_coop_dsgntr_cd = CASE WHEN TRIM(loa_scrty_coop_dsgntr_cd) = '' THEN NULL ELSE TRIM(loa_scrty_coop_dsgntr_cd) END,
    loa_scrty_coop_ln_itm_id = CASE WHEN TRIM(loa_scrty_coop_ln_itm_id) = '' THEN NULL ELSE TRIM(loa_scrty_coop_ln_itm_id) END,
    loa_agnc_dsbr_cd = CASE WHEN TRIM(loa_agnc_dsbr_cd) = '' THEN NULL ELSE TRIM(loa_agnc_dsbr_cd) END,
    loa_agnc_acntng_cd = CASE WHEN TRIM(loa_agnc_acntng_cd) = '' THEN NULL ELSE TRIM(loa_agnc_acntng_cd) END,
    loa_fnd_cntr_id = CASE WHEN TRIM(loa_fnd_cntr_id) = '' THEN NULL ELSE TRIM(loa_fnd_cntr_id) END,
    loa_cst_cntr_id = CASE WHEN TRIM(loa_cst_cntr_id) = '' THEN NULL ELSE TRIM(loa_cst_cntr_id) END,
    loa_prj_id = CASE WHEN TRIM(loa_prj_id) = '' THEN NULL ELSE TRIM(loa_prj_id) END,
    loa_actvty_id = CASE WHEN TRIM(loa_actvty_id) = '' THEN NULL ELSE TRIM(loa_actvty_id) END,
    loa_cst_cd = CASE WHEN TRIM(loa_cst_cd) = '' THEN NULL ELSE TRIM(loa_cst_cd) END,
    loa_wrk_ord_id = CASE WHEN TRIM(loa_wrk_ord_id) = '' THEN NULL ELSE TRIM(loa_wrk_ord_id) END,
    loa_fncl_ar_id = CASE WHEN TRIM(loa_fncl_ar_id) = '' THEN NULL ELSE TRIM(loa_fncl_ar_id) END,
    loa_scrty_coop_cust_cd = CASE WHEN TRIM(loa_scrty_coop_cust_cd) = '' THEN NULL ELSE TRIM(loa_scrty_coop_cust_cd) END,
    loa_bgt_rstr_cd = CASE WHEN TRIM(loa_bgt_rstr_cd) = '' THEN NULL ELSE TRIM(loa_bgt_rstr_cd) END,
    loa_bgt_sub_act_cd = CASE WHEN TRIM(loa_bgt_sub_act_cd) = '' THEN NULL ELSE TRIM(loa_bgt_sub_act_cd) END;
