-- Local test migration.
-- This will be run on development environments. It should mirror what you
-- intend to apply on production, but do not include any sensitive data.
-- Leaving empty since these users are going to be removed in the near future.