export default {
  PLAIN_TEXT: 'PLAIN_TEXT',
  LABELED: 'LABELED',
  LABELED_SHIPMENT: 'LABELED_SHIPMENT',
  PAYMENT: 'PAYMENT',
  LABELED_PAYMENT_REQUEST: 'LABELED_PAYMENT_REQUEST',
  STATUS: 'STATUS',
};
