# This file is used only by soda, as that tool does not accept database connection information
# in any other way.

# This block is used in both development AND test environments for local development.
development:
  dialect: "postgres"
  database: {{ env "DB_NAME" }}
  host: {{ env "DB_HOST" }}
  port: {{ env "DB_PORT" }}
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}

# This block is used by integration tests on CircleCI.
test:
  dialect: "postgres"
  database: {{ env "TEST_DB_NAME" }}
  host: {{ env "DB_HOST" }}
  port: {{ env "DB_PORT" }}
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}

# This block is used by experimental, staging, and production migrations on CircleCI.
container:
  dialect: "postgres"
  database: {{ env "DB_NAME" }}
  host: {{ env "DB_HOST" }}
  port: {{ env "DB_PORT" }}
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}
  options:
    sslmode: "require"