package paperwork

// Form1203Layout specifies the layout and template of a 1203 form
var Form1203Layout = FormLayout{
	TemplateImagePath: "./pkg/paperwork/formtemplates/form1203template.png",

	FieldsLayout: map[string]FieldPos{
		"ServiceAgentName":         FormField(28, 12, 79, nil, nil),
		"StandardCarrierAlphaCode": FormField(109, 16, 19, nil, nil),
		"CodeOfService":            FormField(131, 16, 19, nil, nil),
		"ShipmentNumber":           FormField(152, 16, 19, nil, nil),
		"DateIssued":               FormField(173, 16, 40, nil, nil),
		"RequestedPackDate":        FormField(3, 29.5, 19, nil, nil),
		"RequestedPickupDate":      FormField(24, 29.5, 19, nil, nil),
		"RequiredDeliveryDate":     FormField(45, 29.5, 19, nil, nil),
		"ServiceMemberFullName":    FormField(109, 26.5, 30, nil, nil),
		"ServiceMemberEdipi":       FormField(140, 26.5, 25, nil, nil),
		"ServiceMemberRank":        FormField(165, 26.5, 50, nil, nil),

		// "TSPName": FormField(),
		// "ServiceMemberStatus": FormField(),
		// "ServiceMemberDependentStatus": FormField(),

		"AuthorityForShipment":        FormField(110, 37.5, 60, nil, nil),
		"OrdersIssueDate":             FormField(174, 37.5, 25, nil, nil),
		"SecondaryPickupAddress":      FormField(3, 39, 60, nil, nil),
		"ServiceMemberAffiliation":    FormField(110, 47, 60, nil, nil),
		"TransportationControlNumber": FormField(174, 47, 25, nil, nil),
		"FullNameOfShipper":           FormField(110, 58, 100, nil, nil),
		"ConsigneeName":               FormField(3, 75, 100, floatPtr(5.5), floatPtr(2)),
		"ConsigneeAddress":            FormField(3, 78, 100, floatPtr(5.5), floatPtr(2)),
		"PickupAddress":               FormField(110, 75, 100, nil, nil),

		// "NTSDetails": FormField(),

		"ResponsibleDestinationOffice": FormField(3, 92, 80, nil, nil),
		"DestinationGbloc":             FormField(95, 89, 17, nil, nil),
		"BillChargesToName":            FormField(110, 92, 80, nil, nil),
		"BillChargesToAddress":         FormField(110, 96, 80, nil, nil),

		// "FreightBillNumber": FormField(),

		"AppropriationsChargeable": FormField(110, 109, 80, nil, nil),

		"Remarks": FormField(3, 125, 160, nil, nil),
		// "PackagesNumber": FormField(),
		// "PackagesKind": FormField(),
		"DescriptionOfShipment": FormField(45, 151, 60, nil, nil),
		// "WeightGrossPounds": FormField(),
		// "WeightTarePounds": FormField(),
		// "WeightNetPounds": FormField(),
		// "LineHaulTransportationRate": FormField(),
		// "LineHaulTransportationCharges": FormField(),
		// "PackingUnpackingCharges": FormField(),
		// "OtherAccessorialServices": FormField(),
		// "TariffOrSpecialRateAuthorities": FormField(),
		// "IssuingOfficerFullName": FormField(),
		// "IssuingOfficerTitle": FormField(),
		// "IssuingOfficeName": FormField(),
		// "IssuingOfficeAddress": FormField(),
		// "IssuingOfficeGBLOC": FormField(),
		// "DateOfReceiptOfShipment": FormField(),
		// "SignatureOfAgentOrDriver": FormField(),
		// "PerInitials": FormField(),
		// "ForUsePayingOfficerUnauthorizedItems": FormField(),
		// "ForUsePayingOfficerExcessDistance": FormField(),
		// "ForUsePayingOfficerExcessValuation": FormField(),
		// "ForUsePayingOfficerExcessWeight": FormField(),
		// "ForUsePayingOfficerOther": FormField(),
		// "CertOfTSPBillingDate": FormField(),
		// "CertOfTSPBillingDeliveryPoint": FormField(),
		// "CertOfTSPBillingNameOfDeliveringCarrier": FormField(),
		// "CertOfTSPBillingPlaceDelivered": FormField(),
		// "CertOfTSPBillingShortage": FormField(),
		// "CertOfTSPBillingDamage": FormField(),
		// "CertOfTSPBillingCarrierOSD": FormField(),
		// "CertOfTSPBillingDestinationCarrierName": FormField(),
		// "CertOfTSPBillingAuthorizedAgentSignature": FormField(),
	},
}
