package paperwork

// Form1203Layout specifies the layout and template of a 1203 form
var Form1203Layout = FormLayout{
	TemplateImagePath: "./pkg/paperwork/formtemplates/form1203template.png",

	FieldsLayout: map[string]FieldPos{
		"ServiceAgentName":         NewFieldPos(28, 12, 79),
		"StandardCarrierAlphaCode": NewFieldPos(109, 16, 19),
		"CodeOfService":            NewFieldPos(131, 16, 19),
		"ShipmentNumber":           NewFieldPos(152, 16, 19),
		"DateIssued":               NewFieldPos(173, 16, 40),
		"RequestedPackDate":        NewFieldPos(3, 29.5, 19),
		"RequestedPickupDate":      NewFieldPos(24, 29.5, 19),
		"RequiredDeliveryDate":     NewFieldPos(45, 29.5, 19),
		"ServiceMemberFullName":    NewFieldPos(109, 26.5, 30),
		"ServiceMemberEdipi":       NewFieldPos(140, 26.5, 25),
		"ServiceMemberRank":        NewFieldPos(165, 26.5, 50),

		// "TSPName": NewFieldPos(),
		// "ServiceMemberStatus": NewFieldPos(),
		// "ServiceMemberDependentStatus": NewFieldPos(),

		"AuthorityForShipment":        NewFieldPos(110, 37.5, 60),
		"OrdersIssueDate":             NewFieldPos(174, 37.5, 25),
		"SecondaryPickupAddress":      NewFieldPos(3, 39, 60),
		"ServiceMemberAffiliation":    NewFieldPos(110, 47, 60),
		"TransportationControlNumber": NewFieldPos(174, 47, 25),
		"FullNameOfShipper":           NewFieldPos(110, 58, 100),
		"ConsigneeName":               NewFieldPos(3, 75, 100),
		"ConsigneeAddress":            NewFieldPos(3, 78, 100),
		"PickupAddress":               NewFieldPos(110, 75, 100),

		// "NTSDetails": NewFieldPos(),

		"ResponsibleDestinationOffice": NewFieldPos(3, 92, 80),
		"DestinationGbloc":             NewFieldPos(95, 89, 17),
		"BillChargesToName":            NewFieldPos(110, 92, 80),
		"BillChargesToAddress":         NewFieldPos(110, 96, 80),

		// "FreightBillNumber": NewFieldPos(),

		"AppropriationsChargeable": NewFieldPos(110, 109, 80),

		"Remarks": NewFieldPos(3, 125, 160),
		// "PackagesNumber": NewFieldPos(),
		// "PackagesKind": NewFieldPos(),
		"DescriptionOfShipment": NewFieldPos(45, 151, 60),
		// "WeightGrossPounds": NewFieldPos(),
		// "WeightTarePounds": NewFieldPos(),
		// "WeightNetPounds": NewFieldPos(),
		// "LineHaulTransportationRate": NewFieldPos(),
		// "LineHaulTransportationCharges": NewFieldPos(),
		// "PackingUnpackingCharges": NewFieldPos(),
		// "OtherAccessorialServices": NewFieldPos(),
		// "TariffOrSpecialRateAuthorities": NewFieldPos(),
		// "IssuingOfficerFullName": NewFieldPos(),
		// "IssuingOfficerTitle": NewFieldPos(),
		// "IssuingOfficeName": NewFieldPos(),
		// "IssuingOfficeAddress": NewFieldPos(),
		// "IssuingOfficeGBLOC": NewFieldPos(),
		// "DateOfReceiptOfShipment": NewFieldPos(),
		// "SignatureOfAgentOrDriver": NewFieldPos(),
		// "PerInitials": NewFieldPos(),
		// "ForUsePayingOfficerUnauthorizedItems": NewFieldPos(),
		// "ForUsePayingOfficerExcessDistance": NewFieldPos(),
		// "ForUsePayingOfficerExcessValuation": NewFieldPos(),
		// "ForUsePayingOfficerExcessWeight": NewFieldPos(),
		// "ForUsePayingOfficerOther": NewFieldPos(),
		// "CertOfTSPBillingDate": NewFieldPos(),
		// "CertOfTSPBillingDeliveryPoint": NewFieldPos(),
		// "CertOfTSPBillingNameOfDeliveringCarrier": NewFieldPos(),
		// "CertOfTSPBillingPlaceDelivered": NewFieldPos(),
		// "CertOfTSPBillingShortage": NewFieldPos(),
		// "CertOfTSPBillingDamage": NewFieldPos(),
		// "CertOfTSPBillingCarrierOSD": NewFieldPos(),
		// "CertOfTSPBillingDestinationCarrierName": NewFieldPos(),
		// "CertOfTSPBillingAuthorizedAgentSignature": NewFieldPos(),
	},
}
