package paperwork

// Form1203Layout specifies the layout and template of a 1203 form
var Form1203Layout = FormLayout{
	TemplateImagePath: "pkg/paperwork/formtemplates/form1203template.png",

	FieldsLayout: map[string]FieldPos{
		"GBLNumber1":               FormField(173, 5, 40, floatPtr(10), floatPtr(4), nil),
		"GBLNumber2":               FormField(79, 197, 30, floatPtr(10), floatPtr(4), nil),
		"TSPName":                  FormField(28, 12, 79, nil, nil, nil),
		"StandardCarrierAlphaCode": FormField(109, 16, 19, nil, nil, nil),
		"CodeOfService":            FormField(131, 16, 19, nil, nil, nil),
		"ShipmentNumber":           FormField(152, 16, 19, nil, nil, nil),
		"DateIssued":               FormField(173, 16, 40, nil, nil, nil),
		"RequestedPackDate":        FormField(3, 29.5, 19, nil, nil, nil),
		"RequestedPickupDate":      FormField(24, 29.5, 19, nil, nil, nil),
		"RequiredDeliveryDate":     FormField(45, 29.5, 19, nil, nil, nil),
		"ServiceMemberFullName":    FormField(109, 26.5, 30, nil, nil, nil),
		"ServiceMemberEdipi":       FormField(140, 26.5, 25, nil, nil, nil),
		"ServiceMemberRank":        FormField(165, 26.5, 50, nil, nil, nil),
		// "ServiceMemberStatus": FormField(),
		// "ServiceMemberDependentStatus": FormField(),
		"AuthorityForShipment":         FormField(110, 37.5, 60, nil, nil, nil),
		"OrdersIssueDate":              FormField(174, 37.5, 25, nil, nil, nil),
		"SecondaryPickupAddress":       FormField(3, 39, 60, nil, nil, nil),
		"ServiceMemberAffiliation":     FormField(110, 47, 60, nil, nil, nil),
		"TransportationControlNumber":  FormField(174, 47, 25, nil, nil, nil),
		"FullNameOfShipper":            FormField(110, 58, 100, nil, nil, nil),
		"ConsigneeName":                FormField(3, 75, 100, floatPtr(5.5), floatPtr(2), nil),
		"ConsigneeAddress":             FormField(3, 78, 100, floatPtr(5.5), floatPtr(2), nil),
		"PickupAddress":                FormField(110, 75, 100, nil, nil, nil),
		"ResponsibleDestinationOffice": FormField(3, 92, 80, nil, nil, nil),
		"DestinationGbloc":             FormField(95, 89, 17, nil, nil, nil),
		"BillChargesToName":            FormField(110, 92, 80, nil, nil, nil),
		"BillChargesToAddress":         FormField(110, 96, 80, nil, nil, nil),
		// "FreightBillNumber": FormField(),
		"DepartmentIndicator": FormField(110, 110, 80, nil, nil, nil),
		"TAC":                 FormField(110, 113, 80, nil, nil, nil),
		"SAC":                 FormField(110, 116, 80, nil, nil, nil),
		"Remarks":             FormField(3, 125, 160, nil, nil, nil),
		// "PackagesNumber": FormField(),
		// "PackagesKind": FormField(),
		"DescriptionOfShipment": FormField(45, 151, 60, nil, nil, nil),
		// "WeightGrossPounds": FormField(),
		// "WeightTarePounds": FormField(),
		// "WeightNetPounds": FormField(),
		// "LineHaulTransportationRate": FormField(),
		// "LineHaulTransportationCharges": FormField(),
		// "PackingUnpackingCharges": FormField(),
		// "OtherAccessorialServices": FormField(),
		"TariffOrSpecialRateAuthorities": FormField(152, 191, 60, nil, nil, nil),
		// "IssuingOfficerFullName": FormField(),
		// "IssuingOfficerTitle": FormField(),
		"IssuingOfficeName":    FormField(110, 203, 80, floatPtr(5.5), floatPtr(2), nil),
		"IssuingOfficeAddress": FormField(110, 205, 80, floatPtr(5.5), floatPtr(2), nil),
		"IssuingOfficeGBLOC":   FormField(202, 204, 17, nil, nil, nil),
		// "DateOfReceiptOfShipment": FormField(),
		// "SignatureOfAgentOrDriver": FormField(),
		// "PerInitials": FormField(),
		// "ForUsePayingOfficerUnauthorizedItems": FormField(),
		// "ForUsePayingOfficerExcessDistance": FormField(),
		// "ForUsePayingOfficerExcessValuation": FormField(),
		// "ForUsePayingOfficerExcessWeight": FormField(),
		// "ForUsePayingOfficerOther": FormField(),
		// "CertOfTSPBillingDate": FormField(),
		// "CertOfTSPBillingDeliveryPoint": FormField(),
		// "CertOfTSPBillingNameOfDeliveringCarrier": FormField(),
		// "CertOfTSPBillingPlaceDelivered": FormField(),
		// "CertOfTSPBillingShortage": FormField(),
		// "CertOfTSPBillingDamage": FormField(),
		// "CertOfTSPBillingCarrierOSD": FormField(),
		// "CertOfTSPBillingDestinationCarrierName": FormField(),
		// "CertOfTSPBillingAuthorizedAgentSignature": FormField(),
	},
}
