import React from 'react';
import { render, screen } from '@testing-library/react';

import MoveHistory from './MoveHistory';

import { MockProviders } from 'testUtils';

const mockMoveCode = 'DVRS0N';

jest.mock('hooks/queries', () => ({
  useGHCGetMoveHistory: () => {
    return {
      isLoading: false,
      isError: false,
      queueResult: {
        data: [
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-18T17:19:05.092Z',
            actionTstampStm: '2024-03-18T17:19:05.092Z',
            actionTstampTx: '2024-03-18T17:19:05.052Z',
            changedValues: {
              has_requested_advance: false,
              sit_estimated_cost: null,
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            contextId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            eventName: 'updateMTOShipment',
            id: 'dfd8f52a-b62e-4207-9878-1338d731c431',
            objectId: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
            oldValues: {
              actual_destination_postal_code: null,
              actual_move_date: null,
              actual_pickup_postal_code: null,
              advance_amount_received: null,
              advance_amount_requested: null,
              advance_status: null,
              aoa_packet_id: null,
              approved_at: null,
              deleted_at: null,
              destination_postal_address_id: 'd1fe1b5c-624c-4ab3-8b72-b58bedab2a63',
              destination_postal_code: '01730',
              estimated_incentive: 146135160,
              estimated_weight: 12314,
              expected_departure_date: '2024-03-12',
              final_incentive: null,
              has_pro_gear: true,
              has_received_advance: null,
              has_requested_advance: null,
              has_secondary_destination_address: null,
              has_secondary_pickup_address: null,
              id: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
              payment_packet_id: null,
              pickup_postal_address_id: '1582b2fd-9657-42e8-95e7-e226bf4e45dc',
              pickup_postal_code: '62223',
              pro_gear_weight: 1009,
              reviewed_at: null,
              secondary_destination_postal_address_id: null,
              secondary_destination_postal_code: null,
              secondary_pickup_postal_address_id: null,
              secondary_pickup_postal_code: null,
              shipment_id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              sit_estimated_cost: 18652,
              sit_estimated_departure_date: null,
              sit_estimated_entry_date: null,
              sit_estimated_weight: null,
              sit_expected: false,
              sit_location: null,
              spouse_pro_gear_weight: 50,
              status: 'SUBMITTED',
              submitted_at: null,
              w2_address_id: null,
            },
            relId: 20141,
            schemaName: 'public',
            sessionUserEmail: 'services_counselor_role@office.mil',
            sessionUserFirstName: 'Leo',
            sessionUserId: 'a6c8663f-998f-4626-a978-ad60da2476ec',
            sessionUserLastName: 'Spaceman',
            sessionUserTelephone: '415-555-1212',
            tableName: 'ppm_shipments',
            transactionId: 2188,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-10-25T23:07:32.573Z',
            actionTstampStm: '2024-10-25T23:07:32.573Z',
            actionTstampTx: '2024-10-25T23:07:32.569Z',
            changedValues: {
              diversion_reason: 'Needs diverted!',
              status: 'DIVERSION_REQUESTED',
            },
            context: [
              {
                shipment_id_abbr: '81a3e',
                shipment_locator: 'DVRS0N-01',
                shipment_type: 'HHG',
              },
            ],
            eventName: 'requestShipmentDiversion',
            id: 'dd6c7225-0f0c-47fc-b7bf-95a1c676b7d7',
            objectId: '81a3ef01-f09e-445f-a5c4-fb7e6973232f',
            oldValues: {
              actual_delivery_date: null,
              actual_pickup_date: '2020-03-16',
              actual_pro_gear_weight: null,
              actual_spouse_pro_gear_weight: null,
              approved_date: '2024-10-25',
              billable_weight_cap: null,
              billable_weight_justification: null,
              counselor_remarks: null,
              customer_remarks: 'Please treat gently',
              days_in_storage: null,
              deleted_at: null,
              dest_sit_auth_end_date: null,
              destination_address_type: null,
              distance: null,
              diversion: true,
              diversion_reason: null,
              diverted_from_shipment_id: null,
              first_available_delivery_date: null,
              has_secondary_delivery_address: null,
              has_secondary_pickup_address: null,
              has_tertiary_delivery_address: null,
              has_tertiary_pickup_address: null,
              id: '81a3ef01-f09e-445f-a5c4-fb7e6973232f',
              market_code: null,
              nts_recorded_weight: null,
              origin_sit_auth_end_date: null,
              prime_actual_weight: 980,
              prime_estimated_weight: null,
              prime_estimated_weight_recorded_date: null,
              rejection_reason: null,
              requested_delivery_date: '2020-03-15',
              requested_pickup_date: '2020-03-15',
              required_delivery_date: null,
              sac_type: null,
              scheduled_delivery_date: '2020-03-17',
              scheduled_pickup_date: '2020-03-16',
              service_order_number: null,
              shipment_locator: 'DVRS0N-01',
              shipment_type: 'HHG',
              sit_days_allowance: null,
              status: 'APPROVED',
              tac_type: null,
              tertiary_delivery_address_id: null,
              tertiary_pickup_address_id: null,
              uses_external_vendor: false,
            },
            relId: 19018,
            schemaName: 'public',
            sessionUserEmail: 'too_role@office.mil',
            sessionUserFirstName: 'Leo',
            sessionUserId: 'dcf86235-53d3-43dd-8ee8-54212ae3078f',
            sessionUserLastName: 'Spaceman',
            sessionUserTelephone: '415-555-1212',
            tableName: 'mto_shipments',
            transactionId: 1875,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-10-25T23:14:34.326Z',
            actionTstampStm: '2024-10-25T23:14:34.322Z',
            actionTstampTx: '2024-10-25T23:14:34.311Z',
            changedValues: {
              deleted_at: '2024-10-25T23:14:34.320423+00:00',
            },
            context: [
              {
                shipment_id_abbr: 'a9dbf',
                shipment_locator: '6MD77M-02',
                shipment_type: 'HHG',
              },
            ],
            eventName: 'deleteShipment',
            id: 'b9ffb64f-e2fb-4ba2-b009-97765fb1019d',
            objectId: 'a9dbfb10-cc86-4a02-8839-c57161da77d0',
            oldValues: {
              actual_delivery_date: null,
              actual_pickup_date: '2020-03-16',
              actual_pro_gear_weight: null,
              actual_spouse_pro_gear_weight: null,
              approved_date: null,
              billable_weight_cap: null,
              billable_weight_justification: null,
              counselor_remarks: null,
              customer_remarks: 'Please treat gently',
              days_in_storage: null,
              deleted_at: null,
              dest_sit_auth_end_date: null,
              destination_address_type: null,
              distance: null,
              diversion: false,
              diversion_reason: null,
              diverted_from_shipment_id: null,
              first_available_delivery_date: null,
              has_secondary_delivery_address: null,
              has_secondary_pickup_address: null,
              has_tertiary_delivery_address: null,
              has_tertiary_pickup_address: null,
              id: 'a9dbfb10-cc86-4a02-8839-c57161da77d0',
              market_code: null,
              nts_recorded_weight: null,
              origin_sit_auth_end_date: null,
              prime_actual_weight: 980,
              prime_estimated_weight: null,
              prime_estimated_weight_recorded_date: null,
              rejection_reason: null,
              requested_delivery_date: '2024-01-08',
              requested_pickup_date: '2024-01-01',
              required_delivery_date: null,
              sac_type: null,
              scheduled_delivery_date: '2020-03-17',
              scheduled_pickup_date: '2020-03-16',
              service_order_number: null,
              shipment_locator: '6MD77M-02',
              shipment_type: 'HHG',
              sit_days_allowance: null,
              status: 'SUBMITTED',
              tac_type: null,
              tertiary_delivery_address_id: null,
              tertiary_pickup_address_id: null,
              uses_external_vendor: false,
            },
            relId: 19018,
            schemaName: 'public',
            sessionUserEmail: 'services_counselor_role@office.mil',
            sessionUserFirstName: 'Leo',
            sessionUserId: 'a6c8663f-998f-4626-a978-ad60da2476ec',
            sessionUserLastName: 'Spaceman',
            sessionUserTelephone: '415-555-1212',
            tableName: 'mto_shipments',
            transactionId: 1883,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-10-25T23:14:34.326Z',
            actionTstampStm: '2024-10-25T23:14:34.322Z',
            actionTstampTx: '2024-10-25T23:14:34.311Z',
            changedValues: {
              deleted_at: '2024-10-25T23:14:34.320423+00:00',
            },
            context: [
              {
                shipment_id_abbr: 'a9dbf',
                shipment_locator: '6MD77M-02',
                shipment_type: 'PPM',
              },
            ],
            eventName: 'deleteMTOShipment',
            id: 'b9ffb64f-e2fb-4ba2-b009-97765fb1019d',
            objectId: 'a9dbfb10-cc86-4a02-8839-c57161da77d0',
            oldValues: {
              actual_delivery_date: null,
              actual_pickup_date: '2020-03-16',
              actual_pro_gear_weight: null,
              actual_spouse_pro_gear_weight: null,
              approved_date: null,
              billable_weight_cap: null,
              billable_weight_justification: null,
              counselor_remarks: null,
              customer_remarks: 'Please treat gently',
              days_in_storage: null,
              deleted_at: null,
              dest_sit_auth_end_date: null,
              destination_address_type: null,
              distance: null,
              diversion: false,
              diversion_reason: null,
              diverted_from_shipment_id: null,
              first_available_delivery_date: null,
              has_secondary_delivery_address: null,
              has_secondary_pickup_address: null,
              has_tertiary_delivery_address: null,
              has_tertiary_pickup_address: null,
              id: 'a9dbfb10-cc86-4a02-8839-c57161da77d0',
              market_code: null,
              nts_recorded_weight: null,
              origin_sit_auth_end_date: null,
              prime_actual_weight: 980,
              prime_estimated_weight: null,
              prime_estimated_weight_recorded_date: null,
              rejection_reason: null,
              requested_delivery_date: '2024-01-08',
              requested_pickup_date: '2024-01-01',
              required_delivery_date: null,
              sac_type: null,
              scheduled_delivery_date: '2020-03-17',
              scheduled_pickup_date: '2020-03-16',
              service_order_number: null,
              shipment_locator: '6MD77M-02',
              shipment_type: 'HHG',
              sit_days_allowance: null,
              status: 'SUBMITTED',
              tac_type: null,
              tertiary_delivery_address_id: null,
              tertiary_pickup_address_id: null,
              uses_external_vendor: false,
            },
            relId: 19018,
            schemaName: 'public',
            sessionUserEmail: 'services_counselor_role@office.mil',
            sessionUserFirstName: 'Leo',
            sessionUserId: 'a6c8663f-998f-4626-a978-ad60da2476ec',
            sessionUserLastName: 'Spaceman',
            sessionUserTelephone: '415-555-1212',
            tableName: 'ppm_shipments',
            transactionId: 1883,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-18T17:19:02.829Z',
            actionTstampStm: '2024-03-18T17:19:02.829Z',
            actionTstampTx: '2024-03-18T17:19:01.782Z',
            changedValues: {
              estimated_incentive: 146135160,
              estimated_weight: 12314,
              has_requested_advance: null,
              sit_estimated_departure_date: null,
              sit_estimated_entry_date: null,
              sit_estimated_weight: null,
              sit_expected: false,
              sit_location: null,
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            contextId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            eventName: 'updateMTOShipment',
            id: 'f36ccd2b-267b-404e-9d04-68137e825213',
            objectId: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
            oldValues: {
              actual_destination_postal_code: null,
              actual_move_date: null,
              actual_pickup_postal_code: null,
              advance_amount_received: null,
              advance_amount_requested: null,
              advance_status: null,
              aoa_packet_id: null,
              approved_at: null,
              deleted_at: null,
              destination_postal_address_id: 'd1fe1b5c-624c-4ab3-8b72-b58bedab2a63',
              destination_postal_code: '01730',
              estimated_incentive: 118685743,
              estimated_weight: 10001,
              expected_departure_date: '2024-03-12',
              final_incentive: null,
              has_pro_gear: true,
              has_received_advance: null,
              has_requested_advance: false,
              has_secondary_destination_address: null,
              has_secondary_pickup_address: null,
              id: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
              payment_packet_id: null,
              pickup_postal_address_id: '1582b2fd-9657-42e8-95e7-e226bf4e45dc',
              pickup_postal_code: '62223',
              pro_gear_weight: 1009,
              reviewed_at: null,
              secondary_destination_postal_address_id: null,
              secondary_destination_postal_code: null,
              secondary_pickup_postal_address_id: null,
              secondary_pickup_postal_code: null,
              shipment_id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              sit_estimated_cost: 18652,
              sit_estimated_departure_date: '2024-03-31',
              sit_estimated_entry_date: '2024-03-01',
              sit_estimated_weight: 420,
              sit_expected: true,
              sit_location: 'ORIGIN',
              spouse_pro_gear_weight: 50,
              status: 'SUBMITTED',
              submitted_at: null,
              w2_address_id: null,
            },
            relId: 20141,
            schemaName: 'public',
            sessionUserEmail: 'services_counselor_role@office.mil',
            sessionUserFirstName: 'Leo',
            sessionUserId: 'a6c8663f-998f-4626-a978-ad60da2476ec',
            sessionUserLastName: 'Spaceman',
            sessionUserTelephone: '415-555-1212',
            tableName: 'ppm_shipments',
            transactionId: 2186,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-18T17:18:35.615Z',
            actionTstampStm: '2024-03-18T17:18:35.615Z',
            actionTstampTx: '2024-03-18T17:18:35.560Z',
            changedValues: {
              has_requested_advance: false,
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            contextId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            eventName: 'updateMTOShipment',
            id: '3780c05c-fe35-447f-a064-592efc92b47b',
            objectId: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
            oldValues: {
              actual_destination_postal_code: null,
              actual_move_date: null,
              actual_pickup_postal_code: null,
              advance_amount_received: null,
              advance_amount_requested: null,
              advance_status: null,
              aoa_packet_id: null,
              approved_at: null,
              deleted_at: null,
              destination_postal_address_id: 'd1fe1b5c-624c-4ab3-8b72-b58bedab2a63',
              destination_postal_code: '01730',
              estimated_incentive: 118685743,
              estimated_weight: 10001,
              expected_departure_date: '2024-03-12',
              final_incentive: null,
              has_pro_gear: true,
              has_received_advance: null,
              has_requested_advance: null,
              has_secondary_destination_address: null,
              has_secondary_pickup_address: null,
              id: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
              payment_packet_id: null,
              pickup_postal_address_id: '1582b2fd-9657-42e8-95e7-e226bf4e45dc',
              pickup_postal_code: '62223',
              pro_gear_weight: 1009,
              reviewed_at: null,
              secondary_destination_postal_address_id: null,
              secondary_destination_postal_code: null,
              secondary_pickup_postal_address_id: null,
              secondary_pickup_postal_code: null,
              shipment_id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              sit_estimated_cost: 18652,
              sit_estimated_departure_date: '2024-03-31',
              sit_estimated_entry_date: '2024-03-01',
              sit_estimated_weight: 420,
              sit_expected: true,
              sit_location: 'ORIGIN',
              spouse_pro_gear_weight: 50,
              status: 'SUBMITTED',
              submitted_at: null,
              w2_address_id: null,
            },
            relId: 20141,
            schemaName: 'public',
            sessionUserEmail: 'services_counselor_role@office.mil',
            sessionUserFirstName: 'Leo',
            sessionUserId: 'a6c8663f-998f-4626-a978-ad60da2476ec',
            sessionUserLastName: 'Spaceman',
            sessionUserTelephone: '415-555-1212',
            tableName: 'ppm_shipments',
            transactionId: 2185,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-18T17:18:35.570Z',
            actionTstampStm: '2024-03-18T17:18:35.570Z',
            actionTstampTx: '2024-03-18T17:18:35.560Z',
            changedValues: {
              counselor_remarks: 'test',
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            eventName: 'updateMTOShipment',
            id: '4e4216fa-6a1a-4bd2-aae2-729d465a7e75',
            objectId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            oldValues: {
              actual_delivery_date: null,
              actual_pickup_date: null,
              actual_pro_gear_weight: null,
              actual_spouse_pro_gear_weight: null,
              approved_date: null,
              billable_weight_cap: null,
              billable_weight_justification: null,
              counselor_remarks: '',
              customer_remarks: null,
              days_in_storage: null,
              deleted_at: null,
              destination_address_type: null,
              distance: 1152,
              diversion: false,
              diverted_from_shipment_id: null,
              first_available_delivery_date: null,
              has_secondary_delivery_address: false,
              has_secondary_pickup_address: false,
              id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              nts_recorded_weight: null,
              prime_actual_weight: null,
              prime_estimated_weight: null,
              prime_estimated_weight_recorded_date: null,
              rejection_reason: null,
              requested_delivery_date: null,
              requested_pickup_date: null,
              required_delivery_date: null,
              sac_type: null,
              scheduled_delivery_date: null,
              scheduled_pickup_date: null,
              service_order_number: null,
              shipment_type: 'PPM',
              sit_days_allowance: 90,
              status: 'SUBMITTED',
              tac_type: null,
              uses_external_vendor: false,
            },
            relId: 19074,
            schemaName: 'public',
            sessionUserEmail: 'services_counselor_role@office.mil',
            sessionUserFirstName: 'Leo',
            sessionUserId: 'a6c8663f-998f-4626-a978-ad60da2476ec',
            sessionUserLastName: 'Spaceman',
            sessionUserTelephone: '415-555-1212',
            tableName: 'mto_shipments',
            transactionId: 2185,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-18T17:18:24.771Z',
            actionTstampStm: '2024-03-18T17:18:24.769Z',
            actionTstampTx: '2024-03-18T17:18:24.761Z',
            changedValues: {
              closeout_office_id: '645cc264-a0ff-4ea1-9aff-84644d7ade3c',
            },
            context: [
              {
                closeout_office_name: 'PPPO Hanscom AFB - USAF',
              },
            ],
            eventName: 'updateCloseoutOffice',
            id: '3893e81f-ca76-4691-b792-57b0916d4717',
            objectId: 'b4559deb-3eab-4c64-82dc-4b6e159384a6',
            oldValues: {
              approvals_requested_at: null,
              available_to_prime_at: null,
              billable_weights_reviewed_at: null,
              cancel_reason: null,
              closeout_office_id: '0931a9dc-c1fd-444a-b138-6e1986b1714c',
              excess_weight_acknowledged_at: null,
              excess_weight_qualified_at: null,
              financial_review_flag: false,
              financial_review_flag_set_at: null,
              financial_review_remarks: null,
              id: 'b4559deb-3eab-4c64-82dc-4b6e159384a6',
              locator: 'CBD3MD',
              ppm_type: 'FULL',
              prime_counseling_completed_at: null,
              reference_id: '4615-4174',
              service_counseling_completed_at: null,
              show: true,
              status: 'NEEDS SERVICE COUNSELING',
              submitted_at: '2024-03-11T19:50:07.747192',
              tio_remarks: null,
            },
            relId: 16592,
            schemaName: 'public',
            sessionUserEmail: 'services_counselor_role@office.mil',
            sessionUserFirstName: 'Leo',
            sessionUserId: 'a6c8663f-998f-4626-a978-ad60da2476ec',
            sessionUserLastName: 'Spaceman',
            sessionUserTelephone: '415-555-1212',
            tableName: 'moves',
            transactionId: 2184,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-18T17:18:22.850Z',
            actionTstampStm: '2024-03-18T17:18:22.845Z',
            actionTstampTx: '2024-03-18T17:18:22.826Z',
            changedValues: {
              counselor_remarks: '',
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            eventName: 'updateMTOShipment',
            id: '48765b49-eee7-4106-8f6c-f8cfbaced446',
            objectId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            oldValues: {
              actual_delivery_date: null,
              actual_pickup_date: null,
              actual_pro_gear_weight: null,
              actual_spouse_pro_gear_weight: null,
              approved_date: null,
              billable_weight_cap: null,
              billable_weight_justification: null,
              counselor_remarks: null,
              customer_remarks: null,
              days_in_storage: null,
              deleted_at: null,
              destination_address_type: null,
              distance: 2121,
              diversion: false,
              diverted_from_shipment_id: null,
              first_available_delivery_date: null,
              has_secondary_delivery_address: false,
              has_secondary_pickup_address: false,
              id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              nts_recorded_weight: null,
              prime_actual_weight: null,
              prime_estimated_weight: null,
              prime_estimated_weight_recorded_date: null,
              rejection_reason: null,
              requested_delivery_date: null,
              requested_pickup_date: null,
              required_delivery_date: null,
              sac_type: null,
              scheduled_delivery_date: null,
              scheduled_pickup_date: null,
              service_order_number: null,
              shipment_type: 'PPM',
              sit_days_allowance: 90,
              status: 'SUBMITTED',
              tac_type: null,
              uses_external_vendor: false,
            },
            relId: 19074,
            schemaName: 'public',
            sessionUserEmail: 'services_counselor_role@office.mil',
            sessionUserFirstName: 'Leo',
            sessionUserId: 'a6c8663f-998f-4626-a978-ad60da2476ec',
            sessionUserLastName: 'Spaceman',
            sessionUserTelephone: '415-555-1212',
            tableName: 'mto_shipments',
            transactionId: 2183,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-18T17:18:24.282Z',
            actionTstampStm: '2024-03-18T17:18:24.281Z',
            actionTstampTx: '2024-03-18T17:18:22.826Z',
            changedValues: {
              distance: 1152,
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            eventName: 'updateMTOShipment',
            id: '7f2f7d0c-bb5d-4555-9daa-878914efe097',
            objectId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            oldValues: {
              actual_delivery_date: null,
              actual_pickup_date: null,
              actual_pro_gear_weight: null,
              actual_spouse_pro_gear_weight: null,
              approved_date: null,
              billable_weight_cap: null,
              billable_weight_justification: null,
              counselor_remarks: '',
              customer_remarks: null,
              days_in_storage: null,
              deleted_at: null,
              destination_address_type: null,
              distance: 2121,
              diversion: false,
              diverted_from_shipment_id: null,
              first_available_delivery_date: null,
              has_secondary_delivery_address: false,
              has_secondary_pickup_address: false,
              id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              nts_recorded_weight: null,
              prime_actual_weight: null,
              prime_estimated_weight: null,
              prime_estimated_weight_recorded_date: null,
              rejection_reason: null,
              requested_delivery_date: null,
              requested_pickup_date: null,
              required_delivery_date: null,
              sac_type: null,
              scheduled_delivery_date: null,
              scheduled_pickup_date: null,
              service_order_number: null,
              shipment_type: 'PPM',
              sit_days_allowance: 90,
              status: 'SUBMITTED',
              tac_type: null,
              uses_external_vendor: false,
            },
            relId: 19074,
            schemaName: 'public',
            sessionUserEmail: 'services_counselor_role@office.mil',
            sessionUserFirstName: 'Leo',
            sessionUserId: 'a6c8663f-998f-4626-a978-ad60da2476ec',
            sessionUserLastName: 'Spaceman',
            sessionUserTelephone: '415-555-1212',
            tableName: 'mto_shipments',
            transactionId: 2183,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-18T17:18:24.731Z',
            actionTstampStm: '2024-03-18T17:18:24.730Z',
            actionTstampTx: '2024-03-18T17:18:22.826Z',
            changedValues: {
              advance_amount_requested: null,
              destination_postal_code: '01730',
              estimated_incentive: 118685743,
              estimated_weight: 10001,
              expected_departure_date: '2024-03-12',
              has_requested_advance: null,
              pickup_postal_code: '62223',
              pro_gear_weight: 1009,
              sit_estimated_cost: 18652,
              sit_estimated_departure_date: '2024-03-31',
              sit_estimated_entry_date: '2024-03-01',
              sit_estimated_weight: 420,
              sit_expected: true,
              sit_location: 'ORIGIN',
              spouse_pro_gear_weight: 50,
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            contextId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            eventName: 'updateMTOShipment',
            id: 'c720b247-8d2a-4a63-b8ee-23a275fa9d06',
            objectId: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
            oldValues: {
              actual_destination_postal_code: null,
              actual_move_date: null,
              actual_pickup_postal_code: null,
              advance_amount_received: null,
              advance_amount_requested: 100000,
              advance_status: null,
              aoa_packet_id: null,
              approved_at: null,
              deleted_at: null,
              destination_postal_address_id: 'd1fe1b5c-624c-4ab3-8b72-b58bedab2a63',
              destination_postal_code: '01731',
              estimated_incentive: 234825561,
              estimated_weight: 10000,
              expected_departure_date: '2024-03-11',
              final_incentive: null,
              has_pro_gear: true,
              has_received_advance: null,
              has_requested_advance: true,
              has_secondary_destination_address: null,
              has_secondary_pickup_address: null,
              id: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
              payment_packet_id: null,
              pickup_postal_address_id: '1582b2fd-9657-42e8-95e7-e226bf4e45dc',
              pickup_postal_code: '62225',
              pro_gear_weight: 1000,
              reviewed_at: null,
              secondary_destination_postal_address_id: null,
              secondary_destination_postal_code: null,
              secondary_pickup_postal_address_id: null,
              secondary_pickup_postal_code: null,
              shipment_id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              sit_estimated_cost: null,
              sit_estimated_departure_date: null,
              sit_estimated_entry_date: null,
              sit_estimated_weight: null,
              sit_expected: false,
              sit_location: null,
              spouse_pro_gear_weight: 250,
              status: 'SUBMITTED',
              submitted_at: null,
              w2_address_id: null,
            },
            relId: 20141,
            schemaName: 'public',
            sessionUserEmail: 'services_counselor_role@office.mil',
            sessionUserFirstName: 'Leo',
            sessionUserId: 'a6c8663f-998f-4626-a978-ad60da2476ec',
            sessionUserLastName: 'Spaceman',
            sessionUserTelephone: '415-555-1212',
            tableName: 'ppm_shipments',
            transactionId: 2183,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-11T19:50:07.752Z',
            actionTstampStm: '2024-03-11T19:50:07.752Z',
            actionTstampTx: '2024-03-11T19:50:07.731Z',
            changedValues: {
              status: 'NEEDS SERVICE COUNSELING',
              submitted_at: '2024-03-11T19:50:07.747192',
            },
            context: [{}],
            eventName: 'submitMoveForApproval',
            id: '008d7c44-cee2-447d-9a94-cf77f4f5656a',
            objectId: 'b4559deb-3eab-4c64-82dc-4b6e159384a6',
            oldValues: {
              approvals_requested_at: null,
              available_to_prime_at: null,
              billable_weights_reviewed_at: null,
              cancel_reason: null,
              closeout_office_id: '0931a9dc-c1fd-444a-b138-6e1986b1714c',
              excess_weight_acknowledged_at: null,
              excess_weight_qualified_at: null,
              financial_review_flag: false,
              financial_review_flag_set_at: null,
              financial_review_remarks: null,
              id: 'b4559deb-3eab-4c64-82dc-4b6e159384a6',
              locator: 'CBD3MD',
              ppm_type: 'FULL',
              prime_counseling_completed_at: null,
              reference_id: '4615-4174',
              service_counseling_completed_at: null,
              show: true,
              status: 'DRAFT',
              submitted_at: null,
              tio_remarks: null,
            },
            relId: 16592,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'moves',
            transactionId: 1853,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-11T19:50:07.748Z',
            actionTstampStm: '2024-03-11T19:50:07.748Z',
            actionTstampTx: '2024-03-11T19:50:07.731Z',
            changedValues: {
              status: 'SUBMITTED',
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            eventName: 'submitMoveForApproval',
            id: '6ee1a6d1-c36c-4f57-b608-93d3794a69bf',
            objectId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            oldValues: {
              actual_delivery_date: null,
              actual_pickup_date: null,
              actual_pro_gear_weight: null,
              actual_spouse_pro_gear_weight: null,
              approved_date: null,
              billable_weight_cap: null,
              billable_weight_justification: null,
              counselor_remarks: null,
              customer_remarks: null,
              days_in_storage: null,
              deleted_at: null,
              destination_address_type: null,
              distance: 2121,
              diversion: false,
              diverted_from_shipment_id: null,
              first_available_delivery_date: null,
              has_secondary_delivery_address: false,
              has_secondary_pickup_address: false,
              id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              nts_recorded_weight: null,
              prime_actual_weight: null,
              prime_estimated_weight: null,
              prime_estimated_weight_recorded_date: null,
              rejection_reason: null,
              requested_delivery_date: null,
              requested_pickup_date: null,
              required_delivery_date: null,
              sac_type: null,
              scheduled_delivery_date: null,
              scheduled_pickup_date: null,
              service_order_number: null,
              shipment_type: 'PPM',
              sit_days_allowance: 90,
              status: 'DRAFT',
              tac_type: null,
              uses_external_vendor: false,
            },
            relId: 19074,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'mto_shipments',
            transactionId: 1853,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-11T19:50:07.750Z',
            actionTstampStm: '2024-03-11T19:50:07.750Z',
            actionTstampTx: '2024-03-11T19:50:07.731Z',
            changedValues: {
              status: 'SUBMITTED',
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            contextId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            eventName: 'submitMoveForApproval',
            id: 'e0b50212-f34f-4531-8249-e3fca554a59c',
            objectId: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
            oldValues: {
              actual_destination_postal_code: null,
              actual_move_date: null,
              actual_pickup_postal_code: null,
              advance_amount_received: null,
              advance_amount_requested: 100000,
              advance_status: null,
              aoa_packet_id: null,
              approved_at: null,
              deleted_at: null,
              destination_postal_address_id: 'd1fe1b5c-624c-4ab3-8b72-b58bedab2a63',
              destination_postal_code: '01731',
              estimated_incentive: 234825561,
              estimated_weight: 10000,
              expected_departure_date: '2024-03-11',
              final_incentive: null,
              has_pro_gear: true,
              has_received_advance: null,
              has_requested_advance: true,
              id: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
              payment_packet_id: null,
              pickup_postal_address_id: '1582b2fd-9657-42e8-95e7-e226bf4e45dc',
              pickup_postal_code: '62225',
              pro_gear_weight: 1000,
              reviewed_at: null,
              secondary_destination_postal_address_id: null,
              secondary_destination_postal_code: null,
              secondary_pickup_postal_address_id: null,
              secondary_pickup_postal_code: null,
              shipment_id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              sit_estimated_cost: null,
              sit_estimated_departure_date: null,
              sit_estimated_entry_date: null,
              sit_estimated_weight: null,
              sit_expected: false,
              sit_location: null,
              spouse_pro_gear_weight: 250,
              status: 'DRAFT',
              submitted_at: null,
              w2_address_id: null,
            },
            relId: 20141,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'ppm_shipments',
            transactionId: 1853,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-11T19:49:59.294Z',
            actionTstampStm: '2024-03-11T19:49:59.294Z',
            actionTstampTx: '2024-03-11T19:49:59.260Z',
            changedValues: {
              advance_amount_requested: 100000,
              has_requested_advance: true,
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            contextId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            eventName: 'updateMTOShipment',
            id: '8cec63d2-de54-44da-9cc3-626a70f906cb',
            objectId: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
            oldValues: {
              actual_destination_postal_code: null,
              actual_move_date: null,
              actual_pickup_postal_code: null,
              advance_amount_received: null,
              advance_amount_requested: null,
              advance_status: null,
              aoa_packet_id: null,
              approved_at: null,
              deleted_at: null,
              destination_postal_address_id: 'd1fe1b5c-624c-4ab3-8b72-b58bedab2a63',
              destination_postal_code: '01731',
              estimated_incentive: 234825561,
              estimated_weight: 10000,
              expected_departure_date: '2024-03-11',
              final_incentive: null,
              has_pro_gear: true,
              has_received_advance: null,
              has_requested_advance: null,
              id: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
              payment_packet_id: null,
              pickup_postal_address_id: '1582b2fd-9657-42e8-95e7-e226bf4e45dc',
              pickup_postal_code: '62225',
              pro_gear_weight: 1000,
              reviewed_at: null,
              secondary_destination_postal_address_id: null,
              secondary_destination_postal_code: null,
              secondary_pickup_postal_address_id: null,
              secondary_pickup_postal_code: null,
              shipment_id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              sit_estimated_cost: null,
              sit_estimated_departure_date: null,
              sit_estimated_entry_date: null,
              sit_estimated_weight: null,
              sit_expected: false,
              sit_location: null,
              spouse_pro_gear_weight: 250,
              status: 'DRAFT',
              submitted_at: null,
              w2_address_id: null,
            },
            relId: 20141,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'ppm_shipments',
            transactionId: 1852,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-11T19:49:52.688Z',
            actionTstampStm: '2024-03-11T19:49:52.688Z',
            actionTstampTx: '2024-03-11T19:49:52.532Z',
            changedValues: {
              estimated_incentive: 234825561,
              estimated_weight: 10000,
              has_pro_gear: true,
              pro_gear_weight: 1000,
              spouse_pro_gear_weight: 250,
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            contextId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            eventName: 'updateMTOShipment',
            id: '396ba624-8acd-4942-9adc-527bc56c3b52',
            objectId: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
            oldValues: {
              actual_destination_postal_code: null,
              actual_move_date: null,
              actual_pickup_postal_code: null,
              advance_amount_received: null,
              advance_amount_requested: null,
              advance_status: null,
              aoa_packet_id: null,
              approved_at: null,
              deleted_at: null,
              destination_postal_address_id: 'd1fe1b5c-624c-4ab3-8b72-b58bedab2a63',
              destination_postal_code: '01731',
              estimated_incentive: null,
              estimated_weight: null,
              expected_departure_date: '2024-03-11',
              final_incentive: null,
              has_pro_gear: null,
              has_received_advance: null,
              has_requested_advance: null,
              id: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
              payment_packet_id: null,
              pickup_postal_address_id: '1582b2fd-9657-42e8-95e7-e226bf4e45dc',
              pickup_postal_code: '62225',
              pro_gear_weight: null,
              reviewed_at: null,
              secondary_destination_postal_address_id: null,
              secondary_destination_postal_code: null,
              secondary_pickup_postal_address_id: null,
              secondary_pickup_postal_code: null,
              shipment_id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              sit_estimated_cost: null,
              sit_estimated_departure_date: null,
              sit_estimated_entry_date: null,
              sit_estimated_weight: null,
              sit_expected: false,
              sit_location: null,
              spouse_pro_gear_weight: null,
              status: 'DRAFT',
              submitted_at: null,
              w2_address_id: null,
            },
            relId: 20141,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'ppm_shipments',
            transactionId: 1851,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-11T19:49:52.615Z',
            actionTstampStm: '2024-03-11T19:49:52.615Z',
            actionTstampTx: '2024-03-11T19:49:52.532Z',
            changedValues: {
              distance: 2121,
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            eventName: 'updateMTOShipment',
            id: 'edc9861a-fee1-46ef-a173-2841aef9f96f',
            objectId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            oldValues: {
              actual_delivery_date: null,
              actual_pickup_date: null,
              actual_pro_gear_weight: null,
              actual_spouse_pro_gear_weight: null,
              approved_date: null,
              billable_weight_cap: null,
              billable_weight_justification: null,
              counselor_remarks: null,
              customer_remarks: null,
              days_in_storage: null,
              deleted_at: null,
              destination_address_type: null,
              distance: null,
              diversion: false,
              diverted_from_shipment_id: null,
              first_available_delivery_date: null,
              has_secondary_delivery_address: false,
              has_secondary_pickup_address: false,
              id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              nts_recorded_weight: null,
              prime_actual_weight: null,
              prime_estimated_weight: null,
              prime_estimated_weight_recorded_date: null,
              rejection_reason: null,
              requested_delivery_date: null,
              requested_pickup_date: null,
              required_delivery_date: null,
              sac_type: null,
              scheduled_delivery_date: null,
              scheduled_pickup_date: null,
              service_order_number: null,
              shipment_type: 'PPM',
              sit_days_allowance: 90,
              status: 'DRAFT',
              tac_type: null,
              uses_external_vendor: false,
            },
            relId: 19074,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'mto_shipments',
            transactionId: 1851,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-11T19:49:02.986Z',
            actionTstampStm: '2024-03-11T19:49:02.986Z',
            actionTstampTx: '2024-03-11T19:49:02.951Z',
            changedValues: {
              closeout_office_id: '0931a9dc-c1fd-444a-b138-6e1986b1714c',
            },
            context: [
              {
                closeout_office_name: 'PPPO Scott AFB - USAF',
              },
            ],
            eventName: 'patchMove',
            id: '72d81ccf-f6d3-47c2-aaf1-f27286d1560a',
            objectId: 'b4559deb-3eab-4c64-82dc-4b6e159384a6',
            oldValues: {
              approvals_requested_at: null,
              available_to_prime_at: null,
              billable_weights_reviewed_at: null,
              cancel_reason: null,
              closeout_office_id: null,
              excess_weight_acknowledged_at: null,
              excess_weight_qualified_at: null,
              financial_review_flag: false,
              financial_review_flag_set_at: null,
              financial_review_remarks: null,
              id: 'b4559deb-3eab-4c64-82dc-4b6e159384a6',
              locator: 'CBD3MD',
              ppm_type: 'FULL',
              prime_counseling_completed_at: null,
              reference_id: '4615-4174',
              service_counseling_completed_at: null,
              show: true,
              status: 'DRAFT',
              submitted_at: null,
              tio_remarks: null,
            },
            relId: 16592,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'moves',
            transactionId: 1850,
          },
          {
            action: 'INSERT',
            actionTstampClk: '2024-03-11T19:49:02.777Z',
            actionTstampStm: '2024-03-11T19:49:02.776Z',
            actionTstampTx: '2024-03-11T19:49:02.751Z',
            changedValues: {
              actual_destination_postal_code: null,
              actual_move_date: null,
              actual_pickup_postal_code: null,
              advance_amount_received: null,
              advance_amount_requested: null,
              advance_status: null,
              aoa_packet_id: null,
              approved_at: null,
              deleted_at: null,
              destination_postal_address_id: 'd1fe1b5c-624c-4ab3-8b72-b58bedab2a63',
              destination_postal_code: '01731',
              estimated_incentive: null,
              estimated_weight: null,
              expected_departure_date: '2024-03-11',
              final_incentive: null,
              has_pro_gear: null,
              has_received_advance: null,
              has_requested_advance: null,
              id: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
              payment_packet_id: null,
              pickup_postal_address_id: '1582b2fd-9657-42e8-95e7-e226bf4e45dc',
              pickup_postal_code: '62225',
              pro_gear_weight: null,
              reviewed_at: null,
              secondary_destination_postal_address_id: null,
              secondary_destination_postal_code: null,
              secondary_pickup_postal_address_id: null,
              secondary_pickup_postal_code: null,
              shipment_id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              sit_estimated_cost: null,
              sit_estimated_departure_date: null,
              sit_estimated_entry_date: null,
              sit_estimated_weight: null,
              sit_expected: false,
              sit_location: null,
              spouse_pro_gear_weight: null,
              status: 'DRAFT',
              submitted_at: null,
              w2_address_id: null,
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            contextId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            eventName: 'createMTOShipment',
            id: '3c9d3904-9022-44e6-b19d-41b20305f6f2',
            objectId: '20926ba4-26f9-4d8b-93c4-ae3d9dc8b5fa',
            oldValues: null,
            relId: 20141,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'ppm_shipments',
            transactionId: 1849,
          },
          {
            action: 'INSERT',
            actionTstampClk: '2024-03-11T19:49:02.768Z',
            actionTstampStm: '2024-03-11T19:49:02.766Z',
            actionTstampTx: '2024-03-11T19:49:02.751Z',
            changedValues: {
              actual_delivery_date: null,
              actual_pickup_date: null,
              actual_pro_gear_weight: null,
              actual_spouse_pro_gear_weight: null,
              approved_date: null,
              billable_weight_cap: null,
              billable_weight_justification: null,
              counselor_remarks: null,
              customer_remarks: null,
              days_in_storage: null,
              deleted_at: null,
              destination_address_type: null,
              distance: null,
              diversion: false,
              diverted_from_shipment_id: null,
              first_available_delivery_date: null,
              has_secondary_delivery_address: false,
              has_secondary_pickup_address: false,
              id: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
              nts_recorded_weight: null,
              prime_actual_weight: null,
              prime_estimated_weight: null,
              prime_estimated_weight_recorded_date: null,
              rejection_reason: null,
              requested_delivery_date: null,
              requested_pickup_date: null,
              required_delivery_date: null,
              sac_type: null,
              scheduled_delivery_date: null,
              scheduled_pickup_date: null,
              service_order_number: null,
              shipment_type: 'PPM',
              sit_days_allowance: 90,
              status: 'DRAFT',
              tac_type: null,
              uses_external_vendor: false,
            },
            context: [
              {
                shipment_id_abbr: 'd6cc2',
                shipment_type: 'PPM',
              },
            ],
            eventName: 'createMTOShipment',
            id: '504f7e51-0d9f-4c55-b6ca-f2c1eca6330c',
            objectId: 'd6cc22e9-5d3a-466c-be98-153664df5e8f',
            oldValues: null,
            relId: 19074,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'mto_shipments',
            transactionId: 1849,
          },
          {
            action: 'UPDATE',
            actionTstampClk: '2024-03-11T19:49:02.856Z',
            actionTstampStm: '2024-03-11T19:49:02.856Z',
            actionTstampTx: '2024-03-11T19:49:02.751Z',
            changedValues: {
              ppm_type: 'FULL',
            },
            context: [{}],
            eventName: 'createMTOShipment',
            id: '7fb224b1-8d31-4c07-b381-2a06ca1d5956',
            objectId: 'b4559deb-3eab-4c64-82dc-4b6e159384a6',
            oldValues: {
              approvals_requested_at: null,
              available_to_prime_at: null,
              billable_weights_reviewed_at: null,
              cancel_reason: null,
              closeout_office_id: null,
              excess_weight_acknowledged_at: null,
              excess_weight_qualified_at: null,
              financial_review_flag: false,
              financial_review_flag_set_at: null,
              financial_review_remarks: null,
              id: 'b4559deb-3eab-4c64-82dc-4b6e159384a6',
              locator: 'CBD3MD',
              ppm_type: null,
              prime_counseling_completed_at: null,
              reference_id: '4615-4174',
              service_counseling_completed_at: null,
              show: true,
              status: 'DRAFT',
              submitted_at: null,
              tio_remarks: null,
            },
            relId: 16592,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'moves',
            transactionId: 1849,
          },
          {
            action: 'INSERT',
            actionTstampClk: '2024-03-11T19:43:16.334Z',
            actionTstampStm: '2024-03-11T19:43:16.333Z',
            actionTstampTx: '2024-03-11T19:43:16.311Z',
            changedValues: {
              deleted_at: null,
              id: 'e3dae3d8-de9d-42a4-a7b8-c38eb7582f5f',
            },
            context: [
              {
                filename: 'Screenshot 2024-01-12 at 11.35.03 AM.png',
                moving_expense_type: '',
                shipment_id_abbr: '',
                shipment_type: '',
                upload_type: 'orders',
              },
            ],
            eventName: 'createUpload',
            id: '88107d90-2c6c-4846-87a0-ad30f009d2cf',
            objectId: 'e3dae3d8-de9d-42a4-a7b8-c38eb7582f5f',
            oldValues: null,
            relId: 19383,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'user_uploads',
            transactionId: 1848,
          },
          {
            action: 'INSERT',
            actionTstampClk: '2024-03-11T19:43:11.434Z',
            actionTstampStm: '2024-03-11T19:43:11.430Z',
            actionTstampTx: '2024-03-11T19:43:11.395Z',
            changedValues: {
              amended_orders_acknowledged_at: null,
              department_indicator: null,
              gbloc: 'AGFM',
              grade: 'O_5',
              has_dependents: true,
              id: '11a5a61d-ee3b-4ec0-8278-05b6679fea84',
              issue_date: '2024-03-01',
              method_of_payment:
                'Payment will be made using the Third-Party Payment System (TPPS) Automated Payment System',
              naics: '488510 - FREIGHT TRANSPORTATION ARRANGEMENT',
              new_duty_location_id: 'a119e2b3-3617-4c8f-85aa-55d204da100a',
              nts_sac: null,
              nts_tac: null,
              orders_number: null,
              orders_type: 'PERMANENT_CHANGE_OF_STATION',
              orders_type_detail: null,
              origin_duty_location_id: '70c957eb-54b6-42a3-8d87-fe4849e6e578',
              packing_and_shipping_instructions:
                'Packaging, packing, and shipping instructions as identified in the Conformed Copy of HTC111-11-1-1112 Attachment 1 Performance Work Statement',
              report_by_date: '2024-03-31',
              sac: null,
              spouse_has_pro_gear: false,
              status: 'DRAFT',
              supply_and_services_cost_estimate:
                'Prices for services under this task order will be in accordance with rates provided in GHC Attachment 2 - Pricing Rate Table. It is the responsibility of the contractor to provide the estimated weight quantity to apply to services on this task order, when applicable (See Attachment 1 - Performance Work Statement).',
              tac: null,
            },
            context: [
              {
                new_duty_location_name: 'Hanscom AFB, MA 01731',
                origin_duty_location_name: 'Scott AFB, IL 62225',
              },
            ],
            eventName: 'createOrders',
            id: '6923ac75-6c0c-4f29-acca-eee3adc9713e',
            objectId: '11a5a61d-ee3b-4ec0-8278-05b6679fea84',
            oldValues: null,
            relId: 16879,
            schemaName: 'public',
            sessionUserEmail: 'territester@bob.com',
            sessionUserFirstName: 'Papa',
            sessionUserId: '9268ebf9-f899-48e9-ac49-acdecc9698ec',
            sessionUserLastName: 'PPM',
            sessionUserTelephone: '318-817-5408',
            tableName: 'orders',
            transactionId: 1847,
          },
        ],
        id: 'b4559deb-3eab-4c64-82dc-4b6e159384a6',
        locator: 'CBD3MD',
        page: 1,
        perPage: 20,
        referenceId: '4615-4174',
        totalCount: 29,
      },
    };
  },
}));

describe('MoveHistory', () => {
  it.each(['/moves', '/counseling/moves'])(
    'render the different elements of the Move history tab at path %s',
    async (basePath) => {
      const { baseElement } = render(
        <MockProviders path={`${basePath}/:moveCode/history`} params={{ moveCode: mockMoveCode }}>
          <MoveHistory moveCode={mockMoveCode} />,
        </MockProviders>,
      );

      screen.logTestingPlaygroundURL(baseElement);

      expect(screen.getByText('Move history (29)')).toBeInTheDocument();
      expect(screen.getByRole('table')).toBeInTheDocument();

      // expect(screen.getByTestId('move-history-date-time-0')).toHaveTextContent('09 Mar 22 15:33');
      // expect(screen.getByTestId('move-history-event-0')).toHaveTextContent('Approved move');
      // expect(screen.getByTestId('move-history-details-0')).toBeInTheDocument();
      // expect(screen.getByTestId('move-history-modified-by-0')).toBeInTheDocument();

      // expect(screen.getByTestId('move-history-date-time-1')).toHaveTextContent('08 Mar 22 18:28');
      // expect(screen.getByTestId('move-history-event-1')).toHaveTextContent('Approved shipment');
      // expect(screen.getByTestId('move-history-details-1')).toBeInTheDocument();
      // expect(screen.getByTestId('move-history-modified-by-1')).toBeInTheDocument();

      // expect(screen.getByTestId('pagination')).toBeInTheDocument();
    },
  );
});
