const serviceItemCodes = {
  CS: 'Counseling',
  DBHF: 'Domestic haul away boat factor',
  DBTF: 'Domestic tow away boat factor',
  DCRT: 'Domestic crating',
  DDASIT: "Domestic destination add'l SIT",
  DDDSIT: 'Domestic destination SIT delivery',
  DDFSIT: 'Domestic destination 1st day SIT',
  DDP: 'Domestic destination price',
  DDSHUT: 'Domestic destination shuttle service',
  DLH: 'Domestic linehaul',
  DMHF: 'Domestic mobile home factor',
  DNPK: 'Domestic NTS packing',
  DOASIT: "Domestic origin add'l SIT",
  DOFSIT: 'Domestic origin 1st day SIT',
  DOP: 'Domestic origin price',
  DOPSIT: 'Domestic origin SIT pickup',
  DOSHUT: 'Domestic origin shuttle service',
  DPK: 'Domestic packing',
  DSH: 'Domestic shorthaul',
  DUCRT: 'Domestic uncrating',
  DUPK: 'Domestic unpacking',
  FSC: 'Fuel surcharge',
  IBHF: 'International haul away boat factor',
  IBTF: 'International tow away boat factor',
  ICOLH: 'International C->O shipping & LH',
  ICOUB: 'International C->O UB',
  ICRT: 'International crating',
  ICRTSA: 'International crating - standalone',
  IDASIT: "International destination add'l day SIT",
  IDDSIT: 'International destination SIT delivery',
  IDFSIT: 'International destination 1st day SIT',
  IDSHUT: 'International destination shuttle service',
  IHPK: 'International HHG pack',
  IHUPK: 'International HHG unpack',
  INPK: 'International NTS packing',
  IOASIT: "International origin add'l day SIT",
  IOCLH: 'International O->C shipping & LH',
  IOCUB: 'International O->C UB',
  IOFSIT: 'International origin 1st day SIT',
  IOOLH: 'International O->O shipping & LH',
  IOOUB: 'International O->O UB',
  IOPSIT: 'International origin SIT pickup',
  IOSHUT: 'International origin shuttle service',
  IUBPK: 'International UB pack',
  IUBUPK: 'International UB unpack',
  IUCRT: 'International uncrating',
  MS: 'Move management',
  NSTH: 'Nonstandard HHG',
  NSTUB: 'Nonstandard UB',
};

export default serviceItemCodes;
export { serviceItemCodes };
