export default {
  AIR_FORCE: 'AIR_FORCE',
  ARMY: 'ARMY',
  COAST_GUARD: 'COAST_GUARD',
  NAVY: 'NAVY',
  MARINES: 'MARINES',
};

export const SERVICE_MEMBER_AGENCY_LABELS = {
  AIR_FORCE: 'Air Force',
  ARMY: 'Army',
  COAST_GUARD: 'Coast Guard',
  NAVY: 'Navy',
  MARINES: 'Marine Corps',
};

export const rankLabels = {
  E_1: 'E-1',
  E_2: 'E-2',
  E_3: 'E-3',
  E_4: 'E-4',
  E_5: 'E-5',
  E_6: 'E-6',
  E_7: 'E-7',
  E_8: 'E-8',
  E_9: 'E-9',
  O_1_ACADEMY_GRADUATE: 'O-1/Service Academy Graduate',
  O_2: 'O-2',
  O_3: 'O-3',
  O_4: 'O-4',
  O_5: 'O-5',
  O_6: 'O-6',
  O_7: 'O-7',
  O_8: 'O-8',
  O_9: 'O-9',
  O_10: 'O-10',
  W_1: 'W-1',
  W_2: 'W-2',
  W_3: 'W-3',
  W_4: 'W-4',
  W_5: 'W-5',
  AVIATION_CADET: 'Aviation Cadet',
  CIVILIAN_EMPLOYEE: 'Civilian Employee',
  ACADEMY_CADET: 'Service Academy Cadet',
  MIDSHIPMAN: 'Midshipman',
};
