#! /usr/bin/env bash

set -eu -o pipefail

#
# Get general information from a CAC
#

# Check the CAC Pre-Requirements
# shellcheck source=scripts/cac-prereqs
. cac-prereqs

echo -e "\n----- List Info -----\n"

"${PKCS15}" --list-info

echo -e "\n----- List Certificates -----\n"

"${PKCS15}" --list-certificates

echo -e "\n----- List Slots -----\n"

"${PKCS11}" -r --module "${MODULE}" --list-slots || true

echo -e "\n----- List Objects -----\n"

"${PKCS11}" -O --module "${MODULE}" || true

