#!/usr/bin/env bash

set -u -o pipefail

#
# Ensure JIRA issue is tagged to commit message
#

COMMIT_FILE=$1
COMMIT_MSG=$(cat "$1")
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
# Expected branch pattern initials_JIRA-123_branch_name
# Break down of this command
#  -F_ flag tells perl to splits on underscores
#  -ane
#   a turns on auto split mode so input fields are placed into @F array
#   n wraps the expression in a while loop placing each input line into $_
#   e executes the expression in the quotes
#  @F[1] returns second parsed element
#  if ... ensures parsed portion matches expected pattern of Jira IDs
# The command will be a no-op if not in that pattern in cluding initials_branch_name
JIRA_ID=$(echo "$CURRENT_BRANCH" |  /usr/bin/perl -F_ -ane 'print @F[1] if /[A-Z0-9]{1,10}-?[A-Z0-9]+-\d+/')

if [ -n "$JIRA_ID" ]; then
  echo "[$JIRA_ID] $COMMIT_MSG" > "$COMMIT_FILE"
  echo "JIRA ID '[$JIRA_ID]' prepended to commit message. (Use --no-verify to skip)"
else
  echo "Skipping... No JIRA ID found in branch name: $CURRENT_BRANCH"
fi
