#! /usr/bin/env bash

# Dupes experimental secrets to target params

set -eu -o pipefail

usage() {
    echo "usage: $0 <target-env>"
    echo ""
    echo "This tool duplicates SSM Parameter Secrets from app-experimental environment to target-env. It will not allow copying to app-staging or app-production environments."
    exit 1
}

# ensure arg is provided and not staging or prod
[[ $# == 0  || -z $1 || $1 == "app-staging" || $1 == "app-prod" ]] && usage

echo "Export from app-experimental"
chamber export app-experimental > export.json

echo "Import to $1"
chamber import "$1" export.json

echo "Removing export file"
rm export.json
