#! /usr/bin/env bash
#
# A script to help manage the creation of secure migrations
# https://transcom.github.io/mymove-docs/docs/backend/setup/database-migrations#secure-migrations
#

set -eu -o pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly dir

readonly local_secure_migrations_dir="${dir}/../migrations/app/secure"
readonly prod_migrations_temp_dir="${dir}/../tmp"

#
# Pre-flight checks
#

if [[ -z ${1:-} ]]; then
  echo "usage: $0 <migration_name>"
  exit 1
fi

if [[ ! -d "$prod_migrations_temp_dir" ]]; then
  mkdir "$prod_migrations_temp_dir"
fi

readonly migration_name="$1"

#
# Build secure migration file names
#

# Generate the secure migration filename:
# - remove ".up.fizz" from filename
# - remove "migrations/" from filename
# - append ".sql"
version=$(date +"%Y%m%d%H%M%S")
readonly version
readonly secure_migration_name="${version}_${migration_name}.up.sql"

readonly local_test_migration_name="${local_secure_migrations_dir}/${secure_migration_name}"
readonly prod_migration_name="${prod_migrations_temp_dir}/${secure_migration_name}"

#
# Build secure migration stub content
#

# Create empty file for local test migration
cat > "${local_test_migration_name}" << EOM
-- Local test migration.
-- This will be run on development environments.
-- It should mirror what you intend to apply on loadtest/demo/exp/stg/prd
-- DO NOT include any sensitive data.
EOM

# Create empty file for real secure migration
cat > "${prod_migration_name}" << EOM
-- Production Migration!
-- This will be distributed to all deployed environments (e.g. loadtest/demo/exp/stg/prd)
EOM

#
# Display next steps for user
#

cat << EOM
Generated migration files:

Local test migration: ${local_test_migration_name}
Production migration: ${prod_migration_name}

Next:
    1. Edit the production migration to have the actual change you wish to deploy
    2. Copy the production migration into the local secure migration, scrubbing sensitive data
    3. If everything looks good, upload the migration to S3 with this utility:
       scripts/upload-secure-migration \\
          ${prod_migration_name}
    4. Run make run_prd_migrations to verify that the upload worked and that the migration can be applied successfully.
    5. Open a pull request for this change; when it is accepted, your migration will run on staging.
EOM

#
# Update the migrations manifest
#

./scripts/update-migrations-manifest
