#! /usr/bin/env bash

set -eu -o pipefail

#
# Anti Virus Scanning of Source Code
#
# More information about the docker setup is found here: https://github.com/mko-x/docker-clamav
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
readonly DIR
SLEEP=15
readonly SLEEP
CONTAINER_NAME=anti_virus
readonly CONTAINER_NAME
MOUNT_DIR=/transcom/mymove
readonly MOUNT_DIR
IGNORE_FILES=pkg/handlers/fixtures/orders.pdf
readonly IGNORE_FILES
WHITELIST=whitelist_files.fp
readonly WHITELIST

# Remove any existing containers
echo
echo "Cleaning up existing containers and files:"
docker rm -f "${CONTAINER_NAME}" || true
rm -f "${WHITELIST}"

# Start the clamd service and update with freshclam (takes several minutes to be running)
# Mount the project directory inside for scanning later
docker run -d -p 3310:3310 -v "${DIR}:${MOUNT_DIR}:ro" --name "${CONTAINER_NAME}" mk0x/docker-clamav:alpine

# Create a whitelist of files to ignore
# See https://www.clamav.net/documents/whitelist-databases
# See https://owlbearconsulting.com/doku.php?id=linux_wiki:clamav#whitelist_a_file
for file in ${IGNORE_FILES}; do
  docker exec -it anti_virus sigtool --md5 "${MOUNT_DIR}/${file}"  >> "${WHITELIST}"
done

# Copy the ignore list into the container in the same directory as the virus database
docker cp "${WHITELIST}" "${CONTAINER_NAME}:/store/"
docker exec -it "${CONTAINER_NAME}" chown clamav:clamav "/store/${WHITELIST}"

echo
echo "********************************************************************************"
echo "WARNING: Ignoring these specific files in sigtool format:"
cat "${WHITELIST}"
echo "********************************************************************************"
echo

# Wait for the clamd service to be available by checking on the existence of the socket
while true; do
  if docker exec -it anti_virus ls /tmp/clamd.sock &> /dev/null ; then
    break
  else
    echo "Waiting ${SLEEP} seconds for clamd service to be available"
    sleep "${SLEEP}"
  fi
done

# Print the logs so we can see the state of clamd prior to scanning
docker logs "${CONTAINER_NAME}"

# List the version we're working with for auditing reasons
echo
echo "Version Information:"
docker exec -it "${CONTAINER_NAME}" clamd --version
echo

# Run the scan against the mounted folder
docker exec -it "${CONTAINER_NAME}" clamdscan -v "${MOUNT_DIR}"

# Clean up
# docker rm -f "${CONTAINER_NAME}"
# rm -f "${WHITELIST}"
