#! /usr/bin/env bash

set -eu -o pipefail

#
# Anti Virus Scanning of Source Code
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
readonly DIR

FILES=pkg/handlers/fixtures/orders.pdf
for file in ${FILES}; do
  name=$(basename "${file}")
  md5=$(md5sum "${DIR}/${file}" | cut -d" " -f1)
  size=$(wc -c < "${file}" | xargs)
  echo "${md5}:${size}:${name}" >> whitelist_files.fp
done

echo "Ignoring these files:"
cat whitelist_files.fp
