#! /usr/bin/env bash

set -eu -o pipefail

#
# Get a certificate from CAC
#

# Check the CAC Pre-Requirements
# shellcheck source=scripts/cac-prereqs
. cac-prereqs

# Certificate
#"${PKCS11}" --module "${MODULE}" -r --id 01 --type cert 2>/dev/null | openssl x509 -inform der -text
