#! /usr/bin/env bash

set -eu -o pipefail

#
# Check the prereqs for CAC
#
# Note: This script has no output other than Exit 0 on success  so it can be used in other scripts.
#

readonly PKCS11=/usr/local/bin/pkcs11-tool
readonly PKCS15=/usr/local/bin/pkcs15-tool

if [[ ! -x "${PKCS11}" ]]; then
  echo "${PKCS11} has not been installed"
  echo "Please install with 'brew install opensc'"
  exit 1
fi

if [[ ! -x "${PKCS15}" ]]; then
  echo "${PKCS15} has not been installed"
  echo "Please install with 'brew install opensc'"
  exit 1
fi

readonly MODULE=/usr/local/lib/pkcs11/cackey.dylib

if [[ -f "${MODULE}" ]]; then
  echo "${MODULE} must be removed for MacOS versions 10.15 or later"
  exit 1
fi
