#! /usr/bin/env bash

set -eu -o pipefail

#
# Check the prereqs for CAC
#

readonly MODULE=/usr/local/lib/pkcs11/cackey.dylib
readonly PKCS11=/usr/local/bin/pkcs11-tool
readonly PKCS15=/usr/local/bin/pkcs15-tool

echo "Checking for opensc.... "

if [[ ! -x "${PKCS11}" ]]; then
  echo "${PKCS11} has not been installed"
  echo "Please install with 'brew install opensc'"
  exit 1
fi

if [[ ! -x "${PKCS15}" ]]; then
  echo "${PKCS15} has not been installed"
  echo "Please install with 'brew install opensc'"
  exit 1
fi

echo "opensc found!"


OS_VERSION=$(/usr/bin/sw_vers -productVersion)
MAC_OS="10.15"
if [[ $OS_VERSION != *$MAC_OS* && ! -f "${MODULE}" ]]; then
  echo "${MODULE} must be installed for MacOS versions prior to ${MAC_OS}"
  echo "Please visit http://militarycac.org/MacVideos.htm#CACKey_packages and follow instructions to install"
  exit 1
elif [[ -f "${MODULE}" ]]; then
  echo "${MODULE} must be removed for MacOS versions equal to or after ${MAC_OS}"
  exit 1
fi

echo "cac preeqs check complete ✓"
