#! /usr/bin/env bash

set -eu -o pipefail

#
# Get the Token Label from CAC
#

# Check the CAC Pre-Requirements
cac-prereqs

if [[ -f /usr/local/lib/opensc-pkcs11.so ]]; then
  MODULE=/usr/local/lib/opensc-pkcs11.so
elif [[ -f /usr/local/lib/pkcs11/opensc-pkcs11.so ]]; then
  MODULE=/usr/local/lib/pkcs11/opensc-pkcs11.so
fi

readonly MODULE
readonly PKCS11=/usr/local/bin/pkcs11-tool

# Token Label
"${PKCS11}" --module "${MODULE}" -r --id 01 --list-slots 2>/dev/null| grep label | perl -ne 's/^  token label        : //; print' | head -n1
