#! /usr/bin/env bash

set -eu -o pipefail

#
# Get a public key from CAC
#
# From: https://github.com/OpenSC/OpenSC/wiki/Using-pkcs11-tool-and-OpenSSL#signverify-using-private-keycertificate
#

read -r -s -p "Enter CAC PIN: " CAC_PIN
echo ""
read -r -s -p "Enter Sign Key: " SIGN_KEY
echo ""

readonly MODULE=/usr/local/lib/pkcs11/opensc-pkcs11.so

## Public Key Only
/usr/local/bin/pkcs11-tool -r -p "${CAC_PIN}" --id "${SIGN_KEY}" --type pubkey --module "${MODULE}" > "${SIGN_KEY}.der"
openssl rsa -inform DER -outform PEM -in "${SIGN_KEY}.der" -pubin > "${SIGN_KEY}.pub"
cat "${SIGN_KEY}.pub"
