#! /usr/bin/env bash

set -eu -o pipefail

#
# Get general information from a CAC
#

# Check the CAC Pre-Requirements
cac-prereqs

if [[ -f /usr/local/lib/opensc-pkcs11.so ]]; then
  MODULE=/usr/local/lib/opensc-pkcs11.so
elif [[ -f /usr/local/lib/pkcs11/opensc-pkcs11.so ]]; then
  MODULE=/usr/local/lib/pkcs11/opensc-pkcs11.so
fi

readonly MODULE
readonly PKCS11=/usr/local/bin/pkcs11-tool
readonly PKCS15=/usr/local/bin/pkcs15-tool

echo -e "\n----- List Info -----\n"

"${PKCS15}" --list-info

echo -e "\n----- List Certificates -----\n"

"${PKCS15}" --list-certificates

echo -e "\n----- List Slots -----\n"

"${PKCS11}" -r --module "${MODULE}" --list-slots || true

echo -e "\n----- List Objects -----\n"

"${PKCS11}" -O --module "${MODULE}" || true

