#! /usr/bin/env bash

set -eu -o pipefail

#
# Get the Token Label from CAC
#

# Check the CAC Pre-Requirements
# shellcheck source=scripts/cac-prereqs
. cac-prereqs

# Token Label
"${PKCS11}" --module "${MODULE}" -r --id 01 --list-slots 2>/dev/null| grep label | perl -ne 's/^  token label        : //; print' | head -n1
