#! /usr/bin/env bash

set -eu -o pipefail

#
# Get Subject of the certificate from CAC
#

# Check the CAC Pre-Requirements
cac-prereqs

if [[ -f /usr/local/lib/opensc-pkcs11.so ]]; then
  MODULE=/usr/local/lib/opensc-pkcs11.so
elif [[ -f /usr/local/lib/pkcs11/opensc-pkcs11.so ]]; then
  MODULE=/usr/local/lib/pkcs11/opensc-pkcs11.so
fi

readonly MODULE
readonly PKCS11=/usr/local/bin/pkcs11-tool

# Certificate Subject
"${PKCS11}" --module "${MODULE}" -r --id 01 --type cert 2>/dev/null | openssl x509 -inform der -noout -subject -nameopt RFC2253 | perl -ne 's/^subject= //; print'
