#! /usr/bin/env bash

set -eu -o pipefail

#
# Get a certificate from CAC
#

readonly MODULE=/usr/local/lib/pkcs11/opensc-pkcs11.so
readonly PKCS11=/usr/local/bin/pkcs11-tool

# Check the CAC Pre-Requirements
cac-prereqs

# Certificate
"${PKCS11}" --module "${MODULE}" -r --id 01 --type cert 2>/dev/null | openssl x509 -inform der -text
