#! /usr/bin/env bash

set -eu -o pipefail

RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# First ensure old versions have been removed
if [[ -x "${GOPATH}/bin/chamber" ]]; then
  echo -e "${RED}Please remove previously installed versions on your \$GOPATH with 'rm -f \$GOPATH/bin/chamber'${NC}"
  echo "This project expect chamber to be installed with brew at /usr/local/bin/chamber"
  exit 1
fi

VERSION="2.8"

CHAMBER_VERSION=$(type -p chamber && DISABLE_AWS_VAULT_WRAPPER=1 chamber version)

# Knocks off everything after the last decimal
SHORT_VERSION=${CHAMBER_VERSION%.*}
if [[ $SHORT_VERSION = *$VERSION* ]]; then
  echo "${CHAMBER_VERSION} installed"
else
  echo -e "${YELLOW}chamber ${VERSION}.x is required to run this project! Found '${CHAMBER_VERSION}'.${NC}"
  echo "Run 'brew install chamber' or 'brew upgrade chamber'"
  exit 1
fi
