#! /usr/bin/env bash

#
# Script to check the available disk space Docker has used
#

set -eu -o pipefail

# Location of the reserved docker disk space
DOCKER_RAW=~/Library/Containers/com.docker.docker/Data/vms/0/Docker.raw

# Listing the logical size reserved by docker requires stat
SIZE_RESERVED=$(/usr/bin/stat -f%z "${DOCKER_RAW}")

# Listing the actual used size by docker requires du
SIZE_ACTUAL=$(/usr/bin/du "${DOCKER_RAW}" | cut -f1)

# Compare the size to get percentage used
PERCENT_USED=$(/usr/bin/bc <<< "scale=2; $SIZE_ACTUAL/$SIZE_RESERVED * 100")
echo "Docker is using $PERCENT_USED% of its available disk space!"
if [[ ${PERCENT_USED} -gt 90 ]]; then
  echo "Consider running 'docker system prune --volumes' to free up space"
  exit 1
fi
