#! /usr/bin/env bash

set -eu -o pipefail

VERSION="v5.0"

VAULT_VERSION=$(aws-vault --version)

# Knocks off everything after the last decimal
SHORT_VERSION=${VAULT_VERSION%.*}
if [[ $SHORT_VERSION = *$VERSION* ]]; then
  echo "aws-vault $VAULT_VERSION installed"
else
  echo "aws-vault $VERSION.x is required to run this project! Found $VAULT_VERSION"
  echo "Run 'brew cask install aws-vault' or 'brew cask upgrade aws-vault'"
  exit 1
fi
