#! /usr/bin/env bash

set -eu -o pipefail

gpath=${GOPATH:-}
if [ -z "$gpath" ]; then
  gpath=$HOME/go
fi

# Strip a trailing slash off of gpath if it exists (makes binpath below more robust)
gpath=${gpath%/}

goodpath=$gpath/src/github.com/transcom/mymove

# Ensure project not in GOPATH
if [ "$PWD" -ef "$goodpath" ]; then
  echo "In order to build tools the project must NOT be checked out into your gopath"
  echo "read more at https://github.com/golang/go/wiki/Modules"
  echo "Found in: $goodpath"
  exit 1
fi

if [[ "$gpath" == *"$HOME" ]]; then
  if [[ ! ":$PATH:" == *":$gpath/bin:"* ]] && [[ ! ":$PATH:" == *":~${gpath#"$HOME"}/bin:"* ]]; then
    echo "In order for go dependencies to be runnable, \$GOPATH/bin must be in your \$PATH"
    echo "Please run 'make prereqs' to set your PATH."
    echo "Expected: $gpath/bin"
    echo "Actual: $PATH"
    exit 1
  fi
else
  if [[ ! ":$PATH:" == *":$gpath/bin:"* ]]; then
    echo "In order for go dependencies to be runnable, \$GOPATH/bin must be in your \$PATH"
    echo "Please run 'make prereqs' to set your PATH."
    echo "Expected: $gpath/bin"
    echo "Actual: $PATH"
    exit 1
  fi
fi
