#! /usr/bin/env bash

set -eu -o pipefail

VERSION="2.1"

AWS_VERSION=$(DISABLE_AWS_VAULT_WRAPPER=1 env -u AWS_PROFILE aws --version)

# Knocks off everything after the last decimal
SHORT_VERSION=${AWS_VERSION%.*}
if [[ $SHORT_VERSION = *$VERSION* ]]; then
  echo "$AWS_VERSION installed"
else
  echo "aws $VERSION.x is required to run this project! Found $AWS_VERSION"
  echo "Run 'brew install awscli' or 'brew upgrade awscli'"
  exit 1
fi
