#! /usr/bin/env bash

set -eu -o pipefail

# Script helps ensure that /etc/hosts has all the correct entries in it

function check_host () {
  host=$1
  host_line=$(grep "$host" /etc/hosts || true)
  if [ -z "${host_line}" ]; then
    # shellcheck disable=SC1117
    echo -e "\033[0;33mPlease add ${host} to your hosts file using the command:\033[0m 'echo \"127.0.0.1 ${host}\" | sudo tee -a /etc/hosts'"
    if [ "${host}" = primelocal ]; then
      echo "More information at https://github.com/transcom/mymove#setup-prime-api"
    elif [ "${host}" = orderslocal ]; then
      echo "More information at https://github.com/transcom/mymove#setup-orders-gateway"
    else
      echo "More information at https://github.com/transcom/mymove#setup-${host}-client"
    fi
    exit 1
  fi
}

check_host milmovelocal
check_host officelocal
check_host orderslocal
check_host adminlocal
check_host engadminlocal
check_host primelocal
