#! /usr/bin/env bash

set -eu -o pipefail

YELLOW='\033[0;33m'
NC='\033[0m' # No Color

VERSION="v6.2"

# first part gets path of aws-vault
# second part gets version, which is returned on stderr thus rerouted to stdout
VAULT_VERSION="$(type -p aws-vault) $(aws-vault --version 2>&1)"

# Knocks off everything after the last decimal
SHORT_VERSION=${VAULT_VERSION%.*}
if [[ $SHORT_VERSION = *$VERSION* ]]; then
  echo "aws-vault ${VAULT_VERSION} installed"
else
  echo -e "${YELLOW}aws-vault ${VERSION}.x is required to run this project! Found '${VAULT_VERSION}'.${NC}"
  echo "Run 'brew cask install aws-vault' or 'brew cask upgrade aws-vault'"
  exit 1
fi
