#! /usr/bin/env bash

set -eu -o pipefail

VERSION_NUMBER=12
VERSION="v${VERSION_NUMBER}."

NODE_VERSION=$(node --version)
if [[ $NODE_VERSION = *$VERSION* ]]; then
  echo "Node $NODE_VERSION installed"
else
  echo "Node $VERSION_NUMBER is required to run this project! Found $NODE_VERSION"
  echo "Run 'nodenv local ${VERSION_NUMBER} to install"
  exit 1
fi

