#! /usr/bin/env bash
#
#   check-deployed-commit checks that the deployed commit and given commit match.
#
set -euo pipefail

usage() {
    echo "$0 <hosts> <commit> [<key> <cert> <ca>]"
    exit 1
}
[[ -z $1 || -z $2 ]] && usage

hosts=$1
target_commit=$2
nargs=$#

# shellcheck disable=SC2001
for host in $(echo "$hosts" | sed "s/,/ /g")
do
    deployed_commit=""
    # If
    if [[ "$nargs" -eq 5 ]]; then
      deployed_commit=$(curl -sk --key <(echo "$3" | base64 --decode) --cert <(echo "$4" | base64 --decode) --cacert <(echo "$5" | base64 --decode) "https://$host/health"  | jq -r .gitCommit)
    else
      deployed_commit=$(curl -s "https://$host/health" | jq -r .gitCommit)
    fi
    if [[ "$deployed_commit" != "$target_commit" ]]; then
      echo "* On host $host, the deployed commit ($deployed_commit) DOES NOT match the given commit ($target_commit)."
      echo "* Re-run this job from failure to try again."
      echo "* This may happen due to multiple deployments happening at the same time."
      exit 1
    else
      echo "* On host $host, the deployed commit ($deployed_commit) matches given commit ($target_commit)."
    fi
done
