#! /usr/bin/env bash

set -eu -o pipefail

VERSION="go1.13"

GOLANG_VERSION=$(go version)
if [[ $GOLANG_VERSION = *$VERSION* ]]; then
  echo "Golang $GOLANG_VERSION installed"
else
  echo "Golang $VERSION is required to run this project! Found $GOLANG_VERSION"
  echo "Run 'brew install go && brew link --force go' to install"
  exit 1
fi

