#! /usr/bin/env bash

set -eu -o pipefail

VERSION_NUMBER="$(cat < ".node-version")"
VERSION="v${VERSION_NUMBER}"

NODE_VERSION=$(node --version)
if [[ $NODE_VERSION = *$VERSION* ]]; then
  echo "Node $NODE_VERSION installed"
else
  echo "Node $VERSION_NUMBER is required to run this project! Found $NODE_VERSION"
  echo "Run 'make setup' to update your dev environment"
  exit 1
fi

