#! /usr/bin/env bash

set -eu -o pipefail

YELLOW='\033[0;33m'
NC='\033[0m' # No Color

VERSION="v0.21"

SWAGGER_VERSION=$(type -p swagger > /dev/null && swagger version | head -n1)

# Knocks off everything after the last decimal
SHORT_VERSION=${SWAGGER_VERSION%.*}
if [[ $SHORT_VERSION = *$VERSION* ]]; then
  echo "swagger ${SWAGGER_VERSION} installed"
else
  echo -e "${YELLOW}swagger ${VERSION}.x is required to run this project! Found '${SWAGGER_VERSION}'.${NC}"
  echo "rm -f bin/swagger && scripts/build-swagger"
  exit 1
fi
