#! /usr/bin/env bash

#
# Open CloudWatch log groups console page directly
#

readonly environment="$1"

# Validate the environments
if [[ "${environment}" != "experimental" ]] && [[ "${environment}" != "staging" ]] && [[ "${environment}" != "prod" ]] ; then
  echo "<environment> must be one of experimental, staging, or prod"
  exit 1
fi

open "https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logStream:group=ecs-tasks-app-${environment}"
