#! /usr/bin/env bash

#
# Open CloudWatch log groups console page directly
#

readonly environment="$1"

# Validate the environments
if [[ "${environment}" != "exp" ]] && [[ "${environment}" != "stg" ]] && [[ "${environment}" != "prd" ]] ; then
  echo "<environment> must be one of exp, stg, prd."
  exit 1
fi

open "https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/ecs-tasks-app-${environment}"
