#! /usr/bin/env bash
# Truncate the tables in the database

set -eu -o pipefail

psql_url="postgres://${DB_USER}:${PGPASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"

exec psql "${psql_url}" -c "
DO \$\$ DECLARE
    r RECORD;
BEGIN

    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = current_schema()
            AND tablename NOT IN ('country_holidays',
                                    'country_weekends',
                                    'gbloc_aors',
                                    'gcc_multipliers',
                                    'ghc_diesel_fuel_prices',
                                    'hhg_allowances',
                                    'jppso_region_state_assignments',
                                    'jppso_regions',
                                    'pay_grade_ranks',
                                    'pay_grades',
                                    'port_locations',
                                    'ports',
                                    'postal_code_to_gblocs',
                                    'privileges',
                                    're_cities',
                                    're_contract_years',
                                    're_contracts',
                                    're_countries',
                                    're_domestic_accessorial_prices',
                                    're_domestic_linehaul_prices',
                                    're_domestic_other_prices',
                                    're_domestic_service_area_prices',
                                    're_domestic_service_areas',
                                    're_fsc_multipliers',
                                    're_intl_accessorial_prices',
                                    're_intl_other_prices',
                                    're_intl_prices',
                                    're_intl_transit_times',
                                    're_oconus_rate_areas',
                                    're_rate_areas',
                                    're_service_items',
                                    're_services',
                                    're_shipment_type_prices',
                                    're_states',
                                    're_us_post_regions',
                                    're_zip3s',
                                    'roles_privileges',
                                    'roles',
                                    'service_item_param_keys',
                                    'service_params',
                                    'ub_allowances',
                                    'us_post_region_cities',
                                    'zip3_distances',
                                    'ranks'
                                    ) order by tablename ) LOOP
        EXECUTE 'TRUNCATE TABLE ' || quote_ident(r.tablename) || ' CASCADE';
    END LOOP;
END \$\$;
"
