#! /usr/bin/env bash

set -eu -o pipefail

#
# Deploy the app
#

usage() {
  echo "$0 <environment>"
  exit 1
}

readonly environment="${1:-experimental}"

[[ -z "${environment}" ]] && usage

case "${environment}" in
  experimental)
    compare_host=my.experimental.move.mil
    health_check_hosts=my.experimental.move.mil,office.experimental.move.mil,admin.experimental.move.mil
    ;;
  staging)
    compare_host=my.staging.move.mil
    health_check_hosts=my.staging.move.mil,office.staging.move.mil,admin.staging.move.mil
    ;;
  prod)
    compare_host=my.move.mil
    health_check_hosts=my.move.mil,office.move.mil,admin.move.mil
    ;;
  *)
    echo "<environment> must be one of experimental, staging, or prod"
    exit 1
    ;;
esac

if [ -z "${AWS_ACCOUNT_ID}" ]; then
  echo "AWS_ACCOUNT_ID not found!"
  echo "Please add 'AWS_ACCOUNT_ID' to your .envrc.local"
  exit 1
fi

APP_ENVIRONMENT="${environment}"
AWS_DEFAULT_REGION=us-west-2
CIRCLE_SHA1=$(curl -s "https://${compare_host}/health" | jq -r .gitCommit)

scripts/compare-deployed-commit "${compare_host}" "${CIRCLE_SHA1}"

scripts/ecs-deploy-service-container app config/app.container-definition.json "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app:git-${CIRCLE_SHA1}" "${APP_ENVIRONMENT}" FARGATE

bin/health-checker --schemes http,https --hosts "${health_check_hosts}" --tries 10 --backoff 3 --log-level info --timeout 15m

scripts/check-deployed-commit "${health_check_hosts}" "${CIRCLE_SHA1}"
