#! /usr/bin/env bash

set -eu -o pipefail

#
# Deploy the app tasks
#

usage() {
  echo "$0 <environment>"
  exit 1
}

readonly environment="${1:-experimental}"

[[ -z "${environment}" ]] && usage

case "${environment}" in
  experimental)
    compare_host=my.experimental.move.mil
    ;;
  staging)
    compare_host=my.staging.move.mil
    ;;
  prod)
    compare_host=my.move.mil
    ;;
  *)
    echo "<environment> must be one of experimental, staging, or prod"
    exit 1
    ;;
esac

if [ -z "${AWS_ACCOUNT_ID}" ]; then
  echo "AWS_ACCOUNT_ID not found!"
  echo "Please add 'AWS_ACCOUNT_ID' to your .envrc.local"
  exit 1
fi

APP_ENVIRONMENT="${environment}"
AWS_DEFAULT_REGION=us-west-2
CIRCLE_SHA1=$(curl -s "https://${compare_host}/health" | jq -r .gitCommit)

scripts/compare-deployed-commit "${compare_host}" "${CIRCLE_SHA1}"

readonly image="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-tasks:git-${CIRCLE_SHA1}"
scripts/ecs-deploy-task-container save-ghc-fuel-price-data "${image}" "${APP_ENVIRONMENT}"
scripts/ecs-deploy-task-container send-post-move-survey "${image}" "${APP_ENVIRONMENT}"
scripts/ecs-deploy-task-container send-payment-reminder "${image}" "${APP_ENVIRONMENT}"
scripts/ecs-deploy-task-container post-file-to-gex "${image}" "${APP_ENVIRONMENT}"
