#! /usr/bin/env bash

set -eu -o pipefail

#
# Deploy the app tasks
#

usage() {
  echo "$0 <environment>"
  exit 1
}

readonly environment="${1:-exp}"

[[ -z "${environment}" ]] && usage

case "${environment}" in
  loadtest)
    compare_host=my.loadtest.dp3.us
    export AWS_ACCOUNT_ID=469892416004
    ;;
  demo)
    compare_host=my.demo.dp3.us
    export AWS_ACCOUNT_ID=447641181206
    ;;
  exp)
    compare_host=my.exp.move.mil
    export AWS_ACCOUNT_ID=015681133840
    ;;
  stg)
    compare_host=my.stg.move.mil
    export AWS_ACCOUNT_ID=015932076428
    ;;
  prd)
    compare_host=my.move.mil
    export AWS_ACCOUNT_ID=015533997236
    ;;
  *)
    echo "<environment> must be one of loadtest, demo, exp, stg, or prd"
    exit 1
    ;;
esac

APP_ENVIRONMENT="${environment}"
AWS_DEFAULT_REGION=us-gov-west-1
CIRCLE_SHA1=$(curl -s "https://${compare_host}/health" | jq -r .gitCommit)

scripts/compare-deployed-commit "${compare_host}" "${CIRCLE_SHA1}"

readonly image="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-tasks:git-${CIRCLE_SHA1}"
scripts/ecs-deploy-task-container connect-to-gex-via-sftp "${image}" "${APP_ENVIRONMENT}"
scripts/ecs-deploy-task-container post-file-to-gex "${image}" "${APP_ENVIRONMENT}"
scripts/ecs-deploy-task-container process-edis "${image}" "${APP_ENVIRONMENT}"
scripts/ecs-deploy-task-container save-ghc-fuel-price-data "${image}" "${APP_ENVIRONMENT}"
scripts/ecs-deploy-task-container send-payment-reminder "${image}" "${APP_ENVIRONMENT}"
scripts/ecs-deploy-task-container send-post-move-survey "${image}" "${APP_ENVIRONMENT}"
scripts/ecs-deploy-task-container export-db-data "${image}" "${APP_ENVIRONMENT}"
