#! /usr/bin/env bash

set -eu -o pipefail

#
# Deploy the app tasks
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

usage() {
  echo "$0 <environment>"
  exit 1
}

readonly environment="${1:-experimental}"

[[ -z "${environment}" ]] && usage

case "${environment}" in
  experimental)
    compare_host=my.experimental.move.mil
    ;;
  staging)
    compare_host=my.staging.move.mil
    ;;
  prod)
    compare_host=my.move.mil
    ;;
  *)
    echo "<environment> must be one of experimental, staging, or prod"
    exit 1
    ;;
esac

APP_ENVIRONMENT="${environment}"
AWS_DEFAULT_REGION=us-west-2
CIRCLE_SHA1=$(curl -s "https://${compare_host}/health" | jq -r .gitCommit)

scripts/compare-deployed-commit "${compare_host}" "${CIRCLE_SHA1}"

bin/ecs-deploy-task-container \
  --aws-account-id "${AWS_ACCOUNT_ID}" \
  --aws-region "${AWS_DEFAULT_REGION}" \
  --service app \
  --environment "${APP_ENVIRONMENT}" \
  --repository-name app-tasks \
  --image-tag "git-${CIRCLE_SHA1}" \
  --command "milmove-tasks save-fuel-price-data" \
  --variables-file "${DIR}/../config/env/${APP_ENVIRONMENT}.save-fuel-price-data.env" \
  --debug-logging

bin/ecs-deploy-task-container \
  --aws-account-id "${AWS_ACCOUNT_ID}" \
  --aws-region "${AWS_DEFAULT_REGION}" \
  --service app \
  --environment "${APP_ENVIRONMENT}" \
  --repository-name app-tasks \
  --image-tag "git-${CIRCLE_SHA1}" \
  --command "milmove-tasks send-post-move-survey" \
  --command-args "--email-backend=ses --offset-days 15" \
  --variables-file "${DIR}/../config/env/${APP_ENVIRONMENT}.send-post-move-survey.env" \
  --debug-logging
