#! /usr/bin/env bash

set -eu -o pipefail

#
# Deploy the app migrations
#

usage() {
  echo "$0 <environment>"
  exit 1
}

readonly environment="${1:-exp}"

[[ -z "${environment}" ]] && usage

case "${environment}" in
  loadtest)
    compare_host=my.loadtest.dp3.us
    export AWS_ACCOUNT_ID=469892416004
    export AWS_PROFILE=transcom-gov-milmove-loadtest
    ;;
  demo)
    compare_host=my.demo.dp3.us
    export AWS_ACCOUNT_ID=447641181206
    export AWS_PROFILE=transcom-gov-milmove-demo
    ;;
  exp)
    compare_host=my.exp.move.mil
    export AWS_ACCOUNT_ID=015681133840
    export AWS_PROFILE=transcom-gov-milmove-exp
    ;;
  stg)
    compare_host=my.stg.move.mil
    export AWS_ACCOUNT_ID=015932076428
    export AWS_PROFILE=transcom-gov-milmove-stg
    ;;
  prd)
    compare_host=my.move.mil
    export AWS_ACCOUNT_ID=015533997236
    export AWS_PROFILE=transcom-gov-milmove-prd
    ;;
  *)
    echo "<environment> must be one of loadtest, demo, exp, stg, or prd"
    exit 1
    ;;
esac

APP_ENVIRONMENT="${environment}"
export AWS_DEFAULT_REGION=us-gov-west-1
CIRCLE_SHA1=$(curl -s "https://${compare_host}/health" | jq -r .gitCommit)

scripts/compare-deployed-commit "${compare_host}" "${CIRCLE_SHA1}"

readonly image="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-migrations:git-${CIRCLE_SHA1}"
scripts/ecs-run-app-migrations-container "${image}" "${APP_ENVIRONMENT}"
