#! /usr/bin/env bash
#
# A script to download secure migrations from all environments
# https://github.com/transcom/mymove#secure-migrations
#

set -eu -o pipefail

readonly aws_command="aws"
# Environments to download production migrations from
# shellcheck disable=SC2206
readonly environments=(${ENVIRONMENTS:-exp stg prd})
readonly valid_envs=("exp" "stg" "prd")
readonly aws_gov_prefix="transcom-gov-milmove-"
readonly aws_gov_region="us-gov-west-1"
readonly aws_gov_bucket_suffix="-app-${aws_gov_region}"
# The Gov ID account is the aws profile used to access other accounts
readonly aws_gov_id_account="transcom-gov-id"
readonly aws_path_prefix="secure-migrations"

readonly usage="usage: $0 <production_migration_file>"

function proceed() {
  proceed_message=${1:-"proceed"}
  echo -n "${proceed_message} (y/N) "
  read -r proceed
  if [[ "$proceed" =~ ^[^yY]*$ ]]; then
    echo "exiting"
    exit 0
  fi
}

#
# Pre-flight checks
#

for environment in "${environments[@]}"; do
  if [[ ! ${valid_envs[*]} =~ $environment ]]; then
    echo "error: you submitted environment $environment. You may only pass in a subset of the following: ${valid_envs[*]}."
    exit 1
  fi
done

if [[ -z "${1:-}" ]]; then
  echo "$usage"
  exit 1
fi
readonly production_migration_file="$1"

for environment in "${environments[@]}"; do
  # Test AWS command and freshen AWS session token
  DISABLE_AWS_VAULT_WRAPPER=1 AWS_REGION=${aws_gov_region} AWS_PROFILE=${aws_gov_id_account} aws-vault exec "${aws_gov_prefix}${environment}" -- ${aws_command} s3 ls "${aws_gov_prefix}${environment}${aws_gov_bucket_suffix}" > /dev/null
done
#
# Download secure migration
#

for environment in "${environments[@]}"; do
  echo "Downloading from: $environment"
  sleep 1
  migration_dir="./tmp/secure_migrations/${environment}"
  mkdir -p "${migration_dir}"
  DISABLE_AWS_VAULT_WRAPPER=1 \
    AWS_REGION=${aws_gov_region} \
    AWS_PROFILE=${aws_gov_id_account} \
    aws-vault exec "${aws_gov_prefix}${environment}" -- \
    ${aws_command} s3 cp \
    "s3://${aws_gov_prefix}${environment}${aws_gov_bucket_suffix}/${aws_path_prefix}/${production_migration_file}" \
    "${migration_dir}/$production_migration_file" --sse AES256
done

echo
echo "Files have been downloaded to these locations:"
echo
find ./tmp/secure_migrations -type f

echo
echo "Please remember to 'rm -rf ./tmp/secure_migrations' when you are finished working"
echo
