#! /usr/bin/env bash

#
# ecr-describe-image-scan-findings checks an uploaded image scan results
#

set -eu -o pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: ${0##*/} <repo-name> <git-commit>"
  exit 1
fi

repoName=$1
gitCommit=$2

get_findings() {
  findings=$(aws ecr describe-image-scan-findings --repository-name "${repoName}" --image-id "imageTag=\"git-${gitCommit}\"")
  echo "${findings}" | jq .
  echo
  status=$(echo "${findings}" | jq -r ".imageScanStatus.status")

  # Exclude certain findings.
  #
  # ID: CVE-2021-36159
  # Ticket to remove this exclusion: https://dp3.atlassian.net/browse/MB-TBD
  # Description:
  # As of 2021-07-27, no description of this vulnerability is available and no fix is available.
  # ECR scanning detects this as a vulnerability, but there is no way to fix it, so our builds are
  # blocked. To unblock this, we are excluding it from our scans since this is a non-actionable
  # finding.
  validFindings=$(echo "${findings}" | jq 'del(.imageScanFindings.findings[] | select(.name == "CVE-2021-36159"))')
  numberOfValidFindings=$(echo "${validFindings}" | jq -r ".imageScanFindings.findings | length")
}

# Get the results of the scan or wait until they are ready
get_findings
while [[ "${status}" == "IN_PROGRESS" ]]; do
  sleep 15
  get_findings
done

if [[ "${status}" != *COMPLETE* ]]; then
  echo "Scan does not appear COMPLETE"
  exit 1
fi

if [[ "${numberOfValidFindings}" -gt 0 ]]; then
  echo "Scan found ${numberOfValidFindings} findings!"
  exit 1
fi
