#! /usr/bin/env bash

#
# ecr-describe-image-scan-findings checks an uploaded image scan results
#

set -eu -o pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: ${0##*/} <repo-name> <git-commit>"
  exit 1
fi

repoName=$1
gitCommit=$2

get_findings() {
  # Get the findings reported by ECR.
  findings=$(aws ecr describe-image-scan-findings --repository-name "${repoName}" --image-id "imageTag=\"git-${gitCommit}\"")
  echo "${findings}" | jq .
  echo

  # Save the status of the scan.
  status=$(echo "${findings}" | jq -r ".imageScanStatus.status")

  # Extract the findings array. If it is null, set it to an empty array.
  findingsArray=$(echo "${findings}" | jq .imageScanFindings.findings)
  if [[ "${findingsArray}" == "null" ]]; then
    findingsArray='[]'
  fi

  # Exclude certain findings.
  #
  # ID: CVE-2022-37434
  # Ticket to remove this exclusion: https://dp3.atlassian.net/browse/MB-13464
  # Description:
  # https://github.com/docker-library/official-images/pull/12929
  # awaiting successful merge of the above PR.
  validFindings=$(echo "${findingsArray}" | jq 'del(.[] | select(.name == "CVE-2022-37434"))')

  # Save the total number of findings.
  totalNumberOfFindings=$(echo "${findingsArray}" | jq -r ". | length")

  # Save the number of valid scan findings.
  numberOfValidFindings=$(echo "${validFindings}" | jq -r ". | length")
}

# Get the results of the scan or wait until they are ready
get_findings
while [[ "${status}" == "IN_PROGRESS" ]]; do
  sleep 15
  get_findings
done

if [[ "${status}" != *COMPLETE* ]]; then
  echo "Scan does not appear COMPLETE"
  exit 1
fi

if [[ "${numberOfValidFindings}" -gt 0 ]]; then
  echo "Scan found ${numberOfValidFindings} findings!"
  exit 1
elif [[ "${numberOfValidFindings}" -ne "${totalNumberOfFindings}" ]]; then
  echo "Scan found findings, but excluded one or more them."
fi
