#! /usr/bin/env bash
#
#   Show logs from the containers running for the named service.
#
set -eo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../bin" && pwd )"
readonly DIR

usage() {
    echo "${0##*/} <name> <environment> [git-branch [git-commit]] | less"
    exit 1
}

[[ $# -lt 2 || $# -gt 4 ]] && usage
set -u

[[ -f "$DIR/ecs-service-logs" ]] || (echo "Missing $DIR/ecs-service-logs. Run make build_tools" && exit 1)

"$DIR/ecs-service-logs" show --cluster "app-${2}" --service "${1}" --git-branch "${3:-}" --git-commit "${4:-}" --status "RUNNING" --verbose
