#! /usr/bin/env bash
#
#   Updates the named task with the given name, image, and environment.
#
set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

usage() {
    echo "$0 <name> <image> <environment>"
    exit 1
}
[[ -z $1 || -z $2 || -z $3 ]] && usage

# Display command being run
echo "$0 $*"

set -u

readonly name=$1
readonly image=$2
readonly environment=$3

readonly RESERVATION_CPU=256
readonly RESERVATION_MEM=512

if [[ "${name}" == "connect-to-gex-via-sftp" ]] && [[ "${environment}" != "prd" ]]; then
  echo "We do not deploy connect-to-gex-via-sftp to non-prd environments. Skipping deployment."
  exit 0
fi

echo "Checking for existence of variables file"

variables_file="${DIR}/../config/env/${environment}.${name}.env"
if [ ! -f "${variables_file}" ]; then
  echo "Variables file '${variables_file}' does not exist!"
  exit 1
fi

check_arn() {
    local arn=$1
    [[ $arn = arn:* ]] || { echo "Error: Bad ARN: ${arn}"; exit 1; }
}

echo
echo "Preparing ECS task definition for ${name}"

dry_run_task_definition_date=$("${DIR}/../bin/ecs-deploy" task-def \
  --aws-account-id "${AWS_ACCOUNT_ID}" \
  --aws-region "${AWS_DEFAULT_REGION}" \
  --service app-tasks \
  --environment "${environment}" \
  --image "${image}" \
  --cpu "${RESERVATION_CPU}" \
  --memory "${RESERVATION_MEM}" \
  --variables-file "${variables_file}" \
  --entrypoint "/bin/milmove-tasks ${name}" \
  --dry-run)

dry_run_task_definition=$(echo "${dry_run_task_definition_date}" | cut -d ' ' -f 3)
echo "${dry_run_task_definition}" | jq .

echo
echo "Registering ECS task definition for ${name}"
set +e
task_definition_date_arn=$("${DIR}/../bin/ecs-deploy" task-def \
  --aws-account-id "${AWS_ACCOUNT_ID}" \
  --aws-region "${AWS_DEFAULT_REGION}" \
  --service app-tasks \
  --environment "${environment}" \
  --image "${image}" \
  --cpu "${RESERVATION_CPU}" \
  --memory "${RESERVATION_MEM}" \
  --variables-file "${variables_file}" \
  --entrypoint "/bin/milmove-tasks ${name}" \
  --register)
# shellcheck disable=SC2181
if [ "$?" != "0" ]; then echo "$task_definition_date_arn"; exit 1; fi
set -e

task_definition_arn=$(echo "${task_definition_date_arn}" | cut -d ' ' -f 3)
check_arn "$task_definition_arn"

echo
echo "Registered ECS task definition ${task_definition_arn}"

echo
echo "Put new CloudWatch Event target for ${name}"

"${DIR}/../bin/ecs-deploy" put-target \
  --aws-account-id "${AWS_ACCOUNT_ID}" \
  --aws-region "${AWS_DEFAULT_REGION}" \
  --environment "${environment}" \
  --name "${name}" \
  --task-def-arn "${task_definition_arn}" \
  --put-target

echo
echo "Successfully put new CloudWatch Event target for ${name} with ECS task definition ${task_definition_arn}"
