#!/usr/bin/env python3

import os.path
import sys

if len(sys.argv) != 3:
  print(f"Usage: {sys.argv[0]} baseline_coverage.txt new_coverage.txt")
  sys.exit(1)

def total_coverage_percent(filename):
  """parse out the total coverage percentage which is on the line
   with (statements) and strip off the % sign
  """
  with open(filename) as f:
    for line in f:
      if "(statements)" in line:
        percent = line.split()[-1]
        return float(percent.rstrip('%'))

def coverage_diff(filename1, filename2):
  if not filename1 or not filename2:
    return
  os.system(f"git --no-pager diff --no-index -U0 '{filename1}' '{filename2}'")


baseline_file = sys.argv[1]
new_file = sys.argv[2]

baseline_percent = 0.0
# we can remove this conditional once the baselines are being saved on master
if not os.path.exists(baseline_file):
  print(f"Baseline file '{baseline_file}' does not exist, assuming 0")
else:
  baseline_percent = total_coverage_percent(baseline_file)

new_percent = total_coverage_percent(new_file)

print(f"Baseline test coverage: {baseline_percent}")
print(f"New test coverage: {new_percent}")

if new_percent < baseline_percent:
  print("\n--- DIFF of the baseline test coverage compared to this PR ---")
  print("    Note, not all changes will be meaningful, look for test coverage %% decreases\n")
  coverage_diff(baseline_file, new_file)

  print(f"\nBaseline test coverage: {baseline_percent}")
  print(f"New test coverage: {new_percent}")
  print("Test Coverage has decreased\n")
  sys.exit(1)
