#!/bin/sh
set -e

# Code predominantly adapted from https://github.com/gravitee-io/keeper-circleci-orb

InstallKsm() {
  is_alpine=$(isAlpine)
  if [ "$is_alpine" = "true" ]; then
    prepareEnvOnAlpine
  fi

  if [ "${KSM_CLI_VERSION:-latest}" != "latest" ]; then
    VERSION=${KSM_CLI_VERSION}
  else
    VERSION=$(getLatestVersion)
  fi

  # Exit if version is already installed
  if isVersionAlreadyInstalled; then
    echo "➡️ Version ${VERSION} is already installed"
    exit 0
  fi

  echo "after is ksm already installed check"
  echo "version $VERSION"
  echo "is alpine $is_alpine"

  LINK_TAR="$(buildBinaryUrl "$VERSION" "$is_alpine")"

  echo "after building the binary url"

  installKsmWithBinary "$LINK_TAR"
}

isAlpine() {
  os_release_id=$(readOsReleaseFile | grep ^ID= | cut -d "=" -f 2)
  if [ "$os_release_id" = "alpine" ];
  then
    echo "true"
  else
    echo "false"
  fi
}

readOsReleaseFile() {
  cat /etc/os-release 2>/dev/null
}

isLinux() {
  UNAME=$(uname)
  if [ "$UNAME" = "Linux" ]; then
    echo "true"
  else
    echo "false"
  fi
}

getLatestVersion() {
  curl --silent "https://api.github.com/repos/Keeper-Security/secrets-manager/releases/latest" | grep tag_name | awk -F\" '{ print $4 }' | awk -F- '{print $3}'
}

isVersionAlreadyInstalled() {
  command -v ksm >/dev/null 2>&1 && ksm version 2>&1 | grep "CLI Version: " | cut -d " " -f 3 | grep -q "${VERSION}$"
  echo "finished checking if version is installed"
}

buildBinaryUrl() {
  VERSION=$1
  is_alpine=$2

  echo "inside buildbinaryurl"

  if [ "$is_alpine" = "true" ]; then
      OS=alpine-linux
  else
    is_linux=$(isLinux)
    if [ "$is_linux" = "true" ]; then
        OS=linux
    else
        echo "❌ Cannot determine compatible OS type. Exiting..."
        echo "test"
        exit 1;
    fi
  fi

  ARCHIVE_NAME=keeper-secrets-manager-cli-$OS-$VERSION
  echo "${ARCHIVE_NAME}"
  echo "https://github.com/Keeper-Security/secrets-manager/releases/download/ksm-cli-$VERSION/$ARCHIVE_NAME.tar.gz"
}

fetchBinary() {
  echo "inside of fetch binary"
  SUDO=$1
  LINK_TAR=$2

  $SUDO mkdir -p /usr/local/ksm/bin
  curl -fsSL "${LINK_TAR}" | $SUDO tar -xz -C /usr/local/ksm;

  # symlink in the PATH
  $SUDO ln -sf /usr/local/ksm/ksm /usr/local/bin/ksm
}

installKsmWithBinary() {
  LINK_TAR=$1
  echo "➡️ Install KSM from ${LINK_TAR}"

  # Make sure we have root privileges.
  SUDO=""
  if [ "$(id -u)" -ne 0 ]; then
      if ! [ "$(command -v sudo)" ]; then
          echo "❌ Installer requires root privileges. Please run this script as root."
          exit;
      fi
      SUDO="sudo"
  fi

  fetchBinary "$SUDO" "$LINK_TAR"
}

prepareEnvOnAlpine() {
  apk add --update --no-cache curl
}

generate_random_heredoc_identifier() {
  env LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 64 | head -n 1
}

get_secret_from_ksm() {
  url=$1
  ksm secret notation "${url}"
}

EnvExport() {
  secret_name=$1
  secret_url=$2

  cd /tmp

  # To support multiline secrets, we'll use the heredoc syntax to populate the environment variables.
  # As the heredoc identifier, we'll use a randomly generated 64-character string,
  # so that collisions are practically impossible.
  random_heredoc_identifier=$(generate_random_heredoc_identifier) || true
  SECRET=$(get_secret_from_ksm "${secret_url}")

  {
    printf "export %s=\$(cat <<%s\n" "${secret_name}" "${random_heredoc_identifier}"
    printf "%s\n" "${SECRET}"
    printf "%s\n)\n" "${random_heredoc_identifier}"
  } >> "${BASH_ENV}"
}

# Will not run if sourced from another script.
# This is done so this script may be tested.
if [ "${0#*"$TEST_ENV"}" = "$0" ]; then
    InstallKsm
    EnvExport "$@"
fi
