#! /usr/bin/env bash
#
#   go-test runs go test but with the correct DB port
#   For example: scripts/go-test ./pkg/models
#

if [[ -z "${COVERAGE:-}" ]]; then
  DB_PORT=${DB_PORT_TEST} go test "$@"
else
  DB_PORT=${DB_PORT_TEST} go test -coverprofile=coverage.out -covermode=count -p 1 -count 1 -short "$@"
  go tool cover -html=coverage.out
fi
