#! /usr/bin/env bash

#
# Post a comment to a GitHub pull request
#

# This leans on the following orb for code suggestions
# https://circleci.com/developer/orbs/orb/interstellar/github

# TODO: clean up pass

set -eu -o pipefail

circle_branch="$1"
artifact_url="$2"
app="$3"
status="$4"

COMMENT_TITLE="Test coverage on $app failed."
owner="transcom"
repo="mymove"
documentation_url="https://transcom.github.io/mymove-docs/docs/about/development/test-coverage-reports"

echo "Branch: $circle_branch"

echo "Artifact URL: $artifact_url"

echo "Comment title: $COMMENT_TITLE"

# Get PR issue number

PR_NUMBER=$(
  curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $DANGER_GITHUB_API_TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/$owner/$repo/pulls?head=$owner:$circle_branch" | \
  jq '.[] | .number'
)

# Exit if it's not a PR

if [[ -z ${PR_NUMBER} ]]; then
    echo "Not a PR, nothing to do"
    exit
else
  echo "Found Pull request number: ${PR_NUMBER}"
fi


# Get comment ID
COMMENT_ID=$(curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $DANGER_GITHUB_API_TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/$owner/$repo/issues/"$PR_NUMBER"/comments |
  jq --arg COMMENT_TITLE "$COMMENT_TITLE" -r \
  '.[] | select(.body | contains($COMMENT_TITLE)) | .id'
)

if [[ "$status" == "failure" ]]; then

  # Structure comment

  comment="# $COMMENT_TITLE\n\
  **Last run: $(date)**\n\
  Refer to [this report]($artifact_url) to see coverage details for the $app app.\n\
  Documentation for test coverage can be found [at this link]($documentation_url)."

  # Check if comment already exists

  # In no comment exists POST

  # If comment already exists PATCH

  if [[ -z ${COMMENT_ID} ]]; then
      echo "This is first run, posting new comment"

      curl -L \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $DANGER_GITHUB_API_TOKEN" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/repos/$owner/$repo/issues/"$PR_NUMBER"/comments \
      -d "{\"body\":\"$comment\"}"

  else
      echo "Found existing comment, updating comment ID ${COMMENT_ID}"

      curl \
      -X PATCH \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $DANGER_GITHUB_API_TOKEN" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      "https://api.github.com/repos/$owner/$repo/issues/comments/$COMMENT_ID" \
      -d "{\"body\":\"$comment\"}"
  fi
fi

if [[ "$status" == "success" && (-n ${COMMENT_ID})]]; then
  echo "Found existing comment, deleting comment ID ${COMMENT_ID}"

      curl \
      -X DELETE \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $DANGER_GITHUB_API_TOKEN" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      "https://api.github.com/repos/$owner/$repo/issues/comments/$COMMENT_ID"
fi
