#! /usr/bin/env bash

set -eu -o pipefail

#
# Run health and TLS version checks
#

usage() {
  echo "$0 <environment>"
  exit 1
}

readonly environment="${1:-experimental}"

[[ -z "${environment}" ]] && usage

case "${environment}" in
  experimental)
    health_check_hosts=my.experimental.move.mil,office.experimental.move.mil,admin.experimental.move.mil
    ;;
  staging)
    health_check_hosts=my.staging.move.mil,office.staging.move.mil,admin.staging.move.mil
    ;;
  prod)
    health_check_hosts=my.move.mil,office.move.mil,admin.move.mil
    ;;
  *)
    echo "<environment> must be one of experimental, staging, or prod"
    exit 1
    ;;
esac

if [ -z "${AWS_ACCOUNT_ID}" ]; then
  echo "AWS_ACCOUNT_ID not found!"
  echo "Please add 'AWS_ACCOUNT_ID' to your .envrc.local"
  exit 1
fi

go run cmd/health-checker/main.go --schemes http,https --hosts "${health_check_hosts}" --tries 10 --backoff 3 --log-level info --timeout 15m
go run cmd/tls-checker/main.go --schemes http,https --hosts "${health_check_hosts}" --log-level info --timeout 15m --verbose
