#! /usr/bin/env bash
# A script to automate the landing of your GitHub pull requests.

set -eu -o pipefail

readonly repo="transcom/mymove"
readonly sleep=10
readonly pr_number=${1:-}

if [[ -z "$pr_number" ]]; then
  echo "usage: $0 <pr_number>"
  exit 1
fi

if [[ -z "${GITHUB_MERGE_TOKEN:-}" ]]; then
  echo "error: \$GITHUB_MERGE_TOKEN not found."
  echo
  echo "Fix with the following steps:"
  echo "1. Visit https://github.com/settings/tokens/new"
  echo "2. Create a personal access token with the 'repo' scope"
  echo "3. Add it to your .envrc.local. The line should look something like:"
  echo "   export GITHUB_MERGE_TOKEN='xxxxxxxxx'"
  exit 1
fi

while :; do
  result=$(curl \
    -s \
    -H "Authorization: token $GITHUB_MERGE_TOKEN" \
    -X PUT \
    "https://api.github.com/repos/$repo/pulls/$pr_number/merge")

  if [[ $result =~ status\ check.*pending ]]; then
    echo "...waiting on status checks to pass."
  elif [[ "$result" =~ Not\ Found ]]; then
    echo "Pull Request #$pr_number was not found! This may have already been merged."
    exit 1
  elif [[ "$result" =~ review\ requesting\ changes ]]; then
    echo -e "Reviewer is requesting changes!\\a"
  elif [[ "$result" =~ Pull\ Request\ successfully\ merged ]]; then
    echo "Merged!"
    exit 0
  else
    echo "$result"
  fi

  sleep $sleep
done
