#! /usr/bin/env bash

set -eu -o pipefail

#
# Get a sha256 hash of the public certificate from a *.cer file
#
# certificates table contains sha256 of public cert -
# middleware gets cert, terminates at tls, passes on to middleware
# in middleware we pull out key, digest it and compare fingerprint
# to what's stored in DB and then we can authorize effectively

# Fingerprint
openssl x509 -inform pem -noout -fingerprint -sha256 -in "$1" | perl -ne 's/^SHA256 Fingerprint=//; print lc' | sed s/://g
