#! /usr/bin/env bash

set -eu -o pipefail

#
# Get Subject of the certificate from CAC
#
# certificates table contains sha256 of public cert -
# middleware gets cert, terminates at tls, passes on to middleware
# in middleware we pull out key, digest it and compare to what's stored in DB and then we can authorize effectively

# Certificate Subject
openssl x509 -inform pem -noout -subject -nameopt RFC2253 -in "$1" | perl -ne 's/^subject= //; print'
