#! /usr/bin/env bash

#
# Pre-commit hook to run a go custom hook against all go files (except the ones in the testdata directory (excluded by
# pre-commit config).
#

set -eu -o pipefail

hook="$1"; shift

go run ./cmd/"$hook"/main.go -- ./...
