#! /usr/bin/env bash
# Wrapper script to generate table of contents on Markdown files.
# Markdown files must have the `<!-- toc -->` tag in them in order to receive
# a TOC.
#
# This is intended to be called by a pre-commit hook to reduce overhead.
#
# Generated with https://github.com/jonschlinkert/markdown-toc

set -eu -o pipefail

ybin=$(yarn bin)

if [[ ! -f "${ybin}/markdown-toc" && ! -L "${ybin}/markdown-toc" ]]; then
  echo "markdown-toc tool is required."
  exit 1
fi

if [ "$#" -le 1 ]; then
  echo "error: must supply a markdown file to generate table of contents."
  exit 1
fi

for filename in "$@"; do
  # Using backticks in this appended comment seems to make the script
  # indicated run after a 3/5 update to markdown-toc 1.2.0;
  # stick with quotes for now.
  regen=$'\n\nRegenerate with "scripts/pre-commit-markdown-toc"'

  # shellcheck disable=SC2016
  yarn run --silent markdown-toc --bullets='*' --append="${regen}" -i "${filename}"
done
