#!/usr/bin/env bash
set -eou pipefail

# Get directory of script in order to get directory of project
# This allows the script to work from any sub directory in the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}/" )/.." >/dev/null 2>&1 && pwd )"
readonly DIR

# skip analyzing dutystationsloader until repeated tags from embedded types are fixed in Go1.12.2
# https://github.com/golang/go/issues/30465
go_vet_pkgs=$(go list "${DIR}"/... | grep -v /pkg/gen/ | grep -v internal/pkg/dutystationsloader | tr "\n" " ")

# shellcheck disable=SC2086
go vet -vettool="$(command -v shadow)" $go_vet_pkgs
# shellcheck disable=SC2086
go vet $go_vet_pkgs
