#! /usr/bin/env bash

#
# Pre-commit hook to run `swagger validate` that is different based on environment
#

set -eu -o pipefail

filename="$1"
readonly filename

UNAME_S=$(uname -s)
if [ "$UNAME_S" == "Linux" ]; then
  /usr/local/bin/swagger validate "${filename}"
else
  # Locally we need to download the docker image to get the binary
  image=milmove/circleci-docker:milmove-app-c272e99bc356ce400a42526c5e5694e6cae3c68a
  docker pull -q "${image}"
  docker run --rm=true -v "${PWD}:${PWD}" -w "${PWD}" "${image}" swagger validate "${filename}"
fi
