#!/usr/bin/env bash
#
# Capture and print stdout, since gofmt doesn't use proper exit codes
#
set -e

exec 5>&1
# -local flag ensures our local imports get their own group
output=$(goimports -w -local github.com/transcom/mymove "$@" | tee /dev/fd/5)
[[ -z "$output" ]]
