#! /usr/bin/env bash

#
# Pre-commit hook to run `swagger validate`
#

set -eu -o pipefail

# Check swagger version
SWAGGER_VERSION=0.30.3
if ! swagger version 2>/dev/null | grep -q -E "v?${SWAGGER_VERSION}"; then
  echo "ERROR: Please install go-swagger version ${SWAGGER_VERSION}"
  exit 1
fi

for filename in "$@"; do
  swagger validate "${filename}"
done
