#! /usr/bin/env bash

set -eu -o pipefail

RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

prereqs_found=true

# if nix is in use
if [ ! -r .nix-disable ] && [ -f ~/.nix-profile/bin/nix-env ]; then
  nix_dir="nix"
  # add the nix files so that if they change, direnv needs to be reloaded
  config_hash=$(nix-hash "${nix_dir}")
  store_hash=$(nix-store -q --hash "${NIX_PROFILE}")

  # Install Docker
  brew install --cask docker

  # The .nix-hash file is created by nix/update.sh
  if [ ! -r .nix-hash ] || ! grep -q "${config_hash}-${store_hash}" .nix-hash; then
    echo -e "${YELLOW}WARNING: nix packages out of date Run ${nix_dir}/update.sh${NC}"
    prereqs_found=false
  else
    echo "nix dependencies installed"
  fi
else # things only required without nix
  make setup
fi

if [[ $prereqs_found == "true" ]]; then
    echo "OK: all prereqs found"
else
    echo -e "${RED}ERROR: some prereqs missing, please install them.${NC}"
    exit 1
fi

# Now check versions are correct for prereqs
echo
check-gopath
check-go-version
check-hosts-file
check-node-version
