#! /usr/bin/env bash

#
# script to help with prime demo script
#

# =====================================
#     USAGE AND DEFAULTS
# =====================================
set -eu -o pipefail
proofs=(./tmp/uploads/proof_of_service.pdf)
function usage() {
  echo "Usage: prime-api-demo <movecode> [ <hostname> [ <proofs> ... ] ]"
  echo "  movecode   Either moveCode or orderID or orderID can be provided"
  echo "  hostname   Target host of api calls, defaults to 'local' which is primelocal:9443"
  echo "  proofs     Paths to proof of service docs. Defaults to (${proofs[0]})"
  echo "             You can specify as many proofs as you want"
  echo
  echo "EXAMPLES:"
  echo "$0 --help # prints this help"
  echo "$0 9c7b255c-2981-4bf8-839f-61c7458e2b4d"
  echo "$0 RDY4PY"
  echo "$0 9c7b255c-2981-4bf8-839f-61c7458e2b4d local path/to/proof.pdf path/to/proof.jpg"
  echo "$0 RDY4PY api.stg.move.mil"
  echo "$0 9c7b255c-2981-4bf8-839f-61c7458e2b4d api.stg.move.mil path/to/proof.pdf path/to/proof.jpg"
}


# =====================================
#     FUNCTIONS
# =====================================
# These functions generate different payment requests and store to files
function generatePRJson() {
  jq '.mtoServiceItems | map(select((.mtoShipmentID == '"${shipmentID}"') and (.reServiceCode == "FSC" or .reServiceCode == "DLH" or .reServiceCode == "DDFSIT") or .reServiceCode == "MS" or .reServiceCode == "CS"))  | { body: { isFinal: false, moveTaskOrderID: "'"${mtoid}"'", serviceItems: map({ id: .id }) } }' tmp/pad_demo_mto.json > tmp/pad_create_payment_request.json
  echo tmp/pad_create_payment_request.json
}
function generatePRJsonEmpty() {
  jq '{ body: { isFinal: false, moveTaskOrderID: "'"${mtoid}"'", serviceItems: [] } }' tmp/pad_demo_mto.json > tmp/pad_create_payment_request_empty.json
  echo tmp/pad_create_payment_request_empty.json
}
function generatePRJsonFinal() {
  jq '.mtoServiceItems | map(select((.mtoShipmentID == '"${shipmentID}"') and (.reServiceCode == "FSC" or .reServiceCode == "DLH" or .reServiceCode == "DDFSIT") or .reServiceCode == "MS" or .reServiceCode == "CS"))  | { body: { isFinal: true, moveTaskOrderID: "'"${mtoid}"'", serviceItems: map({ id: .id }) } }' tmp/pad_demo_mto.json > tmp/pad_create_payment_request_final.json
  echo tmp/pad_create_payment_request_final.json
}

# This function expects a filename for a stored json create-payment-request body
# It creates the pr and uploads the orders
function createPaymentRequest() {

  # Get json file
  prfile=$1

  printf "The prime submits a payment request as shown below:\n\n"
  jq . "$prfile"

  echo

  printf "\n==========\n\n"

  # Send request to create-payment-request endpoint
  read -p "Ready to send? Hit enter..." -n 1 -r
  bin/prime-api-client "${primeapiopts[@]}" create-payment-request --filename "${prfile}" > tmp/pad_create_payment_request_response.json

  jq . tmp/pad_create_payment_request_response.json

  printf "\n==========\n\n"

  # Collect data from response
  tempPrID=$(jq .id tmp/pad_create_payment_request_response.json | tr -d '"')
  tempPrNumber=$(jq .paymentRequestNumber tmp/pad_create_payment_request_response.json)
  prStatus=$(jq .status tmp/pad_create_payment_request_response.json)

  echo "Payment Request ID: \"${tempPrID}\""
  echo "Payment Request Number: ${tempPrNumber}"
  echo "Payment Request Status: ${prStatus}"
  echo

  # If PR was not created exit function
  if [ "$prStatus" == "\"PENDING\"" ]; then
    echo "setting prID"
    prID=$tempPrID
    prNumber=$tempPrNumber
  else
    return 0
  fi

  printf "\n==========\n\n"

  printf "Now add the proof of service docs in any of the three formats: PNG, JPG, and PDF\n\n"

  read -p "Ready to continue? Hit enter..." -n 1 -r

  printf "\n==========\n\n"

  for proofOfService in "${proofs[@]}"
  do
    proofBase=$(basename "${proofOfService}")
    bin/prime-api-client "${primeapiopts[@]}" create-upload --paymentRequestID "${prID}" --filename "${proofOfService}" > tmp/pad_create_upload_response_"${proofBase}".json

    jq . tmp/pad_create_upload_response_"${proofBase}".json

    echo
  done

  printf "\n==========\n\n"

  printf "Now we wait for the payment request to be approved.\n\n"
  read -p "Ready to continue? Hit enter..." -n 1 -r
}


function addAccessorialServiceItem() {
  printf "The prime can create a DDFSIT service item to later request payment for:\n\n"
  read -p "Ready to continue? Hit enter..." -n 1 -r
  mtoid=$1
  shipmentID=$2

cat > tmp/pad_create_ddfsit_service_item.json <<- EOM
{
  "body": {
    "moveTaskOrderID": "${mtoid}",
    "mtoShipmentID": ${shipmentID},
    "modelType": "MTOServiceItemDestSIT",
    "reServiceCode": "DDFSIT",
    "timeMilitary1": "1705Z",
    "firstAvailableDeliveryDate1": "2021-01-31",
    "timeMilitary2": "0719Z",
    "firstAvailableDeliveryDate2": "2021-02-03",
    "sitEntryDate": "2021-01-12"
  }
}
EOM

  bin/prime-api-client "${primeapiopts[@]}" create-mto-service-item --filename ./tmp/pad_create_ddfsit_service_item.json > tmp/pad_create_ddfsit_response.json

  printf "The prime fetches mto updates to capture the newly created DDFSIT service item:\n\n"

  bin/prime-api-client "${primeapiopts[@]}" fetch-mto-updates | jq -e 'map(select(.id == "'"${mtoid}"'")) | .[0]' > tmp/pad_demo_mto.json

  printf "Now we wait for the TOO to approve the service items.\n\n"
}

# =====================================
#     OPTIONS HANDLING
# =====================================
if [ "${#@}" -eq 0 ]; then
  usage
  exit 1
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  usage
  exit 0
fi

primeapiopts=(--insecure)
mtoid=$1
readonly environment=${2:-local}
# check to see if proofs are passed in
if [ "${#@}" -gt 2 ]; then
  shift # to remove mtoid from $@
  shift # to remove environment from $@
  proofs=("$@")
fi

for proofOfService in "${proofs[@]}"
do
  if [ ! -f "${proofOfService}" ]; then
    echo "Expected proof of service doc ${proofOfService} is missing."
    echo "You can either use this default path or supply a path as a parameter"
    exit 1
  fi
done

printf "\nRunning against "
if [ "$environment" == "local" ]; then
  echo "local server"
else
  echo "remote ${environment}"
  primeapiopts=(--cac --hostname "${environment}" --port 443)
fi

if bin/prime-api-client "${primeapiopts[@]}" fetch-mto-updates > tmp/pad_all_mtos.json; then
  echo "server is running"
else
  echo "server is not running"
  exit 1
fi

# =====================================
#     START WORKFLOW
# =====================================


# -----------------
# GET MTO
printf "\n==========\n\n"

echo "The prime is notified of a new move task order ID: ${mtoid}"
printf "\nThe prime will now fetch the new MTO.\n\n"


printf "\n==========\n\n"

# Find MTO By MTO ID
if jq -e 'map(select(.id == "'"${mtoid}"'")) | .[0]' tmp/pad_all_mtos.json > tmp/pad_demo_mto.json; then
  echo "Found by Move ID"
# Find MTO By orderID
elif jq -e 'map(select(.orderID == "'"${mtoid}"'")) | .[0]' tmp/pad_all_mtos.json > tmp/pad_demo_mto.json; then
  # extract the mtoid
  mtoid=$(jq '.id' tmp/pad_demo_mto.json | tr -d '"')
  echo "Found by Order ID."
# Find MTO by moveCode aka locator
elif jq -e 'map(select(.moveCode == "'"${mtoid}"'")) | .[0]' tmp/pad_all_mtos.json > tmp/pad_demo_mto.json; then
  # extract the mtoid
  mtoid=$(jq '.id' tmp/pad_demo_mto.json | tr -d '"')
  echo "Found by Move Code."
else
  echo "ID not found"
  exit 1
fi


shipmentID=$(jq '.mtoShipments | .[0] | .id' tmp/pad_demo_mto.json)
shipmentEtag=$(jq '.mtoShipments | .[0] | .eTag' tmp/pad_demo_mto.json)


destDutyZip=$(jq '.order.destinationDutyStation.address.postalCode' tmp/pad_demo_mto.json | tr -d '"')
destDutyCity=$(jq '.order.destinationDutyStation.address.city' tmp/pad_demo_mto.json | tr -d '"')
destDutyState=$(jq '.order.destinationDutyStation.address.state' tmp/pad_demo_mto.json | tr -d '"')
destStreetAddress1="7 Q St"
scheduledPickupDate="2021-01-01"
actualPickupDate="2021-01-01"

firstName=$(jq '.order.customer.firstName' tmp/pad_demo_mto.json | tr -d '"')
lastName=$(jq '.order.customer.lastName' tmp/pad_demo_mto.json | tr -d '"')
dds=$(jq '.order.destinationDutyStation.name' tmp/pad_demo_mto.json | tr -d '"')

echo
echo "Customer Name: ${firstName} ${lastName}"
echo "Found approved move to: ${dds}"
echo "MTO ID: ${mtoid}"

cat > tmp/pad_update_mto_shipment.json <<- EOM
{
  "mtoShipmentID": ${shipmentID},
  "ifMatch": ${shipmentEtag},
  "body": {
    "scheduledPickupDate": "${scheduledPickupDate}",
    "actualPickupDate": "${actualPickupDate}",
    "destinationAddress": {
      "streetAddress1": "${destStreetAddress1}",
      "city": "${destCity:-${destDutyCity}}",
      "state": "${destState:-${destDutyState}}",
      "postalCode": "${destZip:-${destDutyZip}}",
      "country": "US"
    }
  }
}
EOM

# --------------------
# UPDATE MTO SHIPMENT

printf "\nThe prime updates the mto shipment with destination address as well the scheduled and actual pickup dates\n\n"
read -p "Ready to continue? Hit enter..." -n 1 -r

bin/prime-api-client "${primeapiopts[@]}" update-mto-shipment --filename ./tmp/pad_update_mto_shipment.json > tmp/pad_update_response_mto_shipment.json

printf "\n-----\n\n"

shipmentEtag=$(jq '.eTag' tmp/pad_update_response_mto_shipment.json)

printf "The prime will now update the estimated and actual shipment weights\n\n"

estimatedWeight="1600"
actualWeight="1540"
if jq -e '.primeEstimatedWeight' tmp/pad_update_response_mto_shipment.json > tmp/pad_estimated_weight; then
  # estimated weight is set already
  cat > tmp/pad_update_weights.json <<- EOM
{
  "mtoShipmentID": ${shipmentID},
  "ifMatch": ${shipmentEtag},
  "body": {
    "primeActualWeight": ${actualWeight}
  }
}
EOM
  bin/prime-api-client "${primeapiopts[@]}" update-mto-shipment --filename ./tmp/pad_update_weights.json > tmp/pad_update_response_weights.json
else # estimated weight not set
  cat > tmp/pad_update_weights.json <<- EOM
{
  "mtoShipmentID": ${shipmentID},
  "ifMatch": ${shipmentEtag},
  "body": {
    "primeEstimatedWeight": ${estimatedWeight},
    "primeActualWeight": ${actualWeight}
  }
}
EOM
  bin/prime-api-client "${primeapiopts[@]}" update-mto-shipment --filename ./tmp/pad_update_weights.json > tmp/pad_update_response_weights.json
fi

shipmentEtag=$(jq '.eTag' tmp/pad_update_response_weights.json)
printf "\n==========\n\n"

# --------------------
# ADD SERVICE ITEM

addAccessorialServiceItem "$mtoid" "$shipmentID"


# -----------------------
# CREATE PAYMENT REQUEST

printf "The prime creates a payment request.\n\n"
askpr=1

while [ $askpr -eq 1 ]; do
  echo "Do you want to create a payment request? (enter a number)"
  select yn in "Empty" "With Service Items" "With Service Items Final" "No"; do
    case $yn in
    Empty )
      prfile=$(generatePRJsonEmpty)
      createPaymentRequest "$prfile"
      break
      ;;
    "With Service Items" )
      prfile=$(generatePRJson)
      createPaymentRequest "$prfile"
      break
      ;;
    "With Service Items Final" )
      prfile=$(generatePRJsonFinal)
      createPaymentRequest "$prfile"
      break
      ;;
    No )
      askpr=0
      break
      ;;
    esac
  done
done

if [[ -z ${prID+x} ]]; then
  exit 1
fi

# -----------------------
# SEND TO SYNCADA
printf "\n==========\n\n"

cat > ./tmp/pad_get_payment_request_edi.json <<-EOM
{
  "paymentRequestID": "${prID}"
}
EOM

printf "Sending the following to generate an EDI:\n\n"
jq . tmp/pad_get_payment_request_edi.json

echo

read -p "Ready to continue? Hit enter..." -n 1 -r

printf "\n==========\n\n"

echo "EDI for payment request number: ${prNumber}:"

printf "\n-----\n\n"

bin/prime-api-client "${primeapiopts[@]}" support-get-payment-request-edi --filename ./tmp/pad_get_payment_request_edi.json > tmp/pad_edi_response.json

jq -r .edi tmp/pad_edi_response.json

echo

echo "Payment request status updated for payment request number: ${prNumber}:"

printf "\n-----\n\n"

cat > ./tmp/pad_update_payment_request_status.json <<-EOM
{
  "body": {
    "paymentRequestID": "${prID}",
    "sendToSyncada": false,
    "readFromSyncada": false,
    "deleteFromSyncada": false
  }
}
EOM

bin/prime-api-client "${primeapiopts[@]}" support-reviewed-payment-requests --filename ./tmp/pad_update_payment_request_status.json > tmp/pad_pr_update_response.json

jq . tmp/pad_pr_update_response.json
