#! /usr/bin/env bash

set -eu -o pipefail

db_password="mysecretpassword"
db_port="${DB_PORT:-5432}"

command="${*:-}"

# Determin if psql is installed in the path and fail with an error message
# TODO: code to go here

# nix-friendly option
psql_exe=/usr/local/bin/psql
if [ -n "${NIX_PROFILE+x}" ]; then
  psql_exe="/nix/var/nix/profiles/per-user/${LOGNAME}/mymove/bin/psql"
fi

if [ -n "${command[*]}" ]; then
  exec  "$psql_exe" --variable "ON_ERROR_STOP=1" postgres://postgres:"${db_password}"@localhost:"${db_port}"/"${DB_NAME}" -c "${command}"
else
  exec "$psql_exe"  --variable "ON_ERROR_STOP=1" postgres://postgres:"${db_password}"@localhost:"${db_port}"/"${DB_NAME}"
fi
