#! /usr/bin/env bash
#
# A script to apply all migrations, including secure migrations, to a local database.
# https://github.com/transcom/mymove/blob/master/docs/how-to/migrate-the-database.md#secure-migrations

set -eu -o pipefail

# Required env vars for apply-secure-migration.sh
export SECURE_MIGRATION_SOURCE=${SECURE_MIGRATION_SOURCE:-s3}
export SECURE_MIGRATION_BUCKET_NAME="${SECURE_MIGRATION_BUCKET_NAME:-transcom-ppp-app-prod-us-west-2}"
export PSQL_SSL_MODE=disable
export DB_NAME="${DB_NAME_PROD_MIGRATIONS:-prod_migrations}"
export DB_PORT="${DB_PORT_PROD_MIGRATIONS:-5434}"

function proceed() {
  proceed_message=${1:-"proceed"}
  echo -en "\e[31m${proceed_message} (y/N) \e[39m"
  read -r proceed
  if [[ "$proceed" =~ ^[^yY]*$ ]]; then
    echo "exiting"
    exit 0
  fi
}

function run() {
  readonly command=( "$@" )
  echo "...executing: ${command[*]}"
  ${command[*]}
}

#
# Pre-flight checks
#

# Ensure our `aws` command is the one infra has wrapped with aws-vault
command -v aws 2> /dev/null | grep "ppp-infra/bin/aws" &> /dev/null || \
  ( echo "error: aws command not pointing to 'ppp-infra/bin/aws"
    echo "see https://github.com/transcom/ppp-infra/blob/master/transcom-ppp/README.md#using-aws-vault"
    exit 1
  )

# Test AWS command and freshen AWS session token
aws s3 ls "${SECURE_MIGRATION_BUCKET_NAME}/secure-migrations" > /dev/null

#
# Run migrations
#

echo
echo -e "\e[33mUsing ${SECURE_MIGRATION_BUCKET_NAME} to gather secure migrations\e[39m"
echo
proceed "Running production migrations against the ${DB_NAME} database. This will delete everything in that db."

export PGPASSWORD=${DB_PASSWORD}
make db_prod_migrations_reset
run make db_prod_migrations_migrate || (
  echo "error: migrations failed!"
  exit 1
  )

echo "Production migrations applied to ${DB_NAME}."
