#!/bin/bash

set -eux -o pipefail

# Setting REACT_APP_NODE_ENV to development enables the "Local Sign In" button
export REACT_APP_NODE_ENV=development
make client_build server_build

export LOGIN_GOV_CALLBACK_PORT=8080
export PLAYWRIGHT_MY_URL=http://milmovelocal:8080
export PLAYWRIGHT_ADMIN_URL=http://adminlocal:8080
export PLAYWRIGHT_OFFICE_URL=http://officelocal:8080


INTERFACE=localhost ./bin/milmove serve > tmp/e2e_server.log 2>&1 &
server_pid=$!

# Runs both the webserver and playwright in parallel
function cleanup {
  kill $server_pid
}
trap cleanup SIGINT
trap cleanup exit

yarn playwright test "$@"
