#!/bin/bash

[[ -n "${DEBUG}" ]] && set -x

set -eu -o pipefail

# Setting REACT_APP_NODE_ENV to development enables the "Local Sign In" button
export REACT_APP_NODE_ENV=development
make client_build server_build

export LOGIN_GOV_CALLBACK_PORT=8080
export OKTA_TENANT_CALLBACK_PORT=8080
export PLAYWRIGHT_MY_URL=http://milmovelocal:8080
export PLAYWRIGHT_ADMIN_URL=http://adminlocal:8080
export PLAYWRIGHT_OFFICE_URL=http://officelocal:8080


INTERFACE=localhost ./bin/milmove serve > tmp/e2e_server.log 2>&1 &
server_pid=$!

# Runs both the webserver and playwright in parallel
function cleanup {
  kill $server_pid
}

# wait for server to be ready
while ! grep -q 'Starting listener' tmp/e2e_server.log; do
      sleep 1
done

trap cleanup SIGINT
trap cleanup exit

A11Y_AUDIT=true yarn playwright test "$@"
