#! /usr/bin/env bash

set -eu -o pipefail

docker-compose -f docker-compose.storybook.yml up --build storybook_tests
container=$(docker-compose -f docker-compose.storybook.yml ps | grep storybook_tests | awk '{print $1}')
return_code=$(docker-compose -f docker-compose.storybook.yml ps | grep storybook_tests | awk '{print $6}')

echo "Clean .loki directory"
rm -rf .loki

echo "Copy results to .loki directory"
docker cp "$container":/home/circleci/project/.loki/ .loki
ls -lR .loki

echo "Shutdown containers"
docker-compose -f docker-compose.storybook.yml down

exit "$return_code"
