#! /usr/bin/env bash

set -eu -o pipefail

# Runs both the webserver and Cypress in parallel
trap "kill %1" SIGINT

# Make a backup of the e2e DB
make db_test_e2e_backup

CYPRESS_PORT=4000
ENV=test DB_PORT="$DB_PORT_TEST" LOGIN_GOV_CALLBACK_PORT="$CYPRESS_PORT" NO_TLS_ENABLED=1 NO_TLS_PORT="$CYPRESS_PORT" \
    ./bin/gin \
    --build cmd/milmove \
		--bin /bin/webserver_e2e \
		--port 8090 --appPort 8091 \
		--excludeDir vendor --excludeDir node_modules \
    --immediate \
		--buildArgs "-i" serve &
npx cypress open || true

# Terminate the background webserver
kill %1

# Remvoe the backup of the e2e DB
make db_test_e2e_cleanup
