#!/usr/bin/env bash

#
# This script is used inside docker-compose.circle.yml to run the server_test task
#

set -eu -o pipefail

if [ "${APPLICATION}" != "app" ] && [ "${APPLICATION}" != "orders" ]; then
  echo "Must provider the environment variable APPLICATION and set to 'app' or 'orders'"
  exit 1
fi

make clean

go get ./...

# Test that go tests will build first
make server_test_build

# Migrate the DB
make bin/milmove
make db_test_migrate

function cleanup()
{
  # These targets are built with GOARCH=amd64 GOOS=linux and overwrite the local binaries
  # because docker-compose mounts the local directory and the bin directory is used
  rm -f bin/milmove
  rm -f bin/go-junit-report
}

## setup a trap incase the tests fail, we still want to generate the report
trap cleanup EXIT
SERVER_REPORT=1 make server_test_standalone
