#! /usr/bin/env bash

#
# Runs the storybook tests in docker containers for CircleCI testing.
#

set -eu -o pipefail

if [[ -z ${CIRCLECI-} ]]; then
  # not on CircleCI
  docker-compose -f docker-compose.storybook.yml -f docker-compose.storybook_local.yml build --pull
  docker-compose -f docker-compose.storybook.yml -f docker-compose.storybook_local.yml up storybook_tests
else
  # on CircleCI
  docker-compose -f docker-compose.storybook.yml build --pull
  docker-compose -f docker-compose.storybook.yml up storybook_tests
fi
container=$(docker-compose -f docker-compose.storybook.yml ps --filter=name=storybook_tests | awk 'END{print $1}')
return_code=$(docker-compose -f docker-compose.storybook.yml ps --filter=name=storybook_tests | awk 'END{print $6}')

echo "Clean .loki directory"
rm -rf .loki

echo "Copy results to .loki directory"
docker cp "$container":/home/circleci/project/.loki/ .loki
ls -lR .loki

echo "Shutdown containers"
docker-compose -f docker-compose.storybook.yml down

exit "$return_code"
