#!/usr/bin/env bash

set -eu -o pipefail

make clean
make bin/go-junit-report
# Debian stretch only supports 9.6 client, so add the Postgresql apt repository for 10.x
echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" | sudo tee -a /etc/apt/sources.list.d/pgdg.list
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get -qq update
sudo apt-get -qq -y install postgresql-client-10

make bin/milmove


createdb -h database -U postgres "$DB_NAME_TEST" || true
make db_test_migrate
mkdir -p tmp/test-results/gotest
## setup a trap incase the tests fail, we still want to generate the report
trap "bin/go-junit-report < tmp/test-results/gotest/go-test.out >  tmp/test-results/gotest/go-test-report.xml" EXIT
make server_test_standalone | tee tmp/test-results/gotest/go-test.out

