#! /usr/bin/env bash

#
# Intended to run inside a docker container, will wait for a 'storybook' container to have started before running the tests.
#

set -eu -o pipefail

retries=0
timeout="${STORYBOOK_SERVER_TIMEOUT:-80}"
concurrent="${CHROME_CONCURRENCY:-1}"

# wait for the storybook server to start
echo "Wait for storybook server to start"
while [[ "$(curl -s -o /dev/null -w '%{http_code}' http://storybook:6006)" != 200 ]]; do
  retries=$(( retries + 1 ))
  echo -n "."
  if [[ $retries -eq $timeout ]]; then
    echo "failed!"
    exit 1
  fi
  sleep 1
done

echo ""
echo "Running loki tests with chromeConcurrency=$concurrent"
yarn run loki test --chromeConcurrency "$concurrent" --chromeRetries 5 --host storybook --requireReference
