#! /usr/bin/env bash

# This script is intended to run inside the storybook container

set -eu -o pipefail

retries=0
timeout="${STORYBOOK_SERVER_TIMEOUT:-40}"

# wait for the storybook server to start
echo "Wait for storybook server to start"
while [[ "$(curl -s -o /dev/null -w '%{http_code}' http://storybook:6006)" != 200 ]]; do
  retries=$(( retries + 1 ))
  echo -n "."
  if [[ $retries -eq $timeout ]]; then
    echo "failed!"
    exit 1
  fi
  sleep 1
done

echo ""
echo "Running loki tests"
yarn run loki test --host storybook --requireReference
