#! /usr/bin/env bash

set -eu -o pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: ${0##*/} <duty station name>"
  exit 1
fi

name=$1

printf "These are the names of transportation offices with the same GBLOC as %s: \\n\\n" "$name"

# The -t option prints just the names as opposed to the default formatting that
# includes the column name underlined
psql -t postgres://"$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME" << EOF
SELECT name FROM transportation_offices
  WHERE gbloc IN (
    SELECT gbloc FROM transportation_offices
    INNER JOIN duty_locations
    ON duty_locations.transportation_office_id = transportation_offices.id
    WHERE duty_locations.name = '$name'
  )
EOF

