#! /usr/bin/env bash

#
# A script to rename secure migrations from all environments
#

set -u -o pipefail

readonly aws_command="aws"
readonly aws_bucket_prefix="transcom-ppp-app-"
readonly aws_bucket_suffix="-us-west-2"
readonly aws_path_prefix="secure-migrations"

readonly usage="usage: $0 <environment_name>"

#
# Pre-flight checks
#

if [[ -z "${1:-}" ]]; then
  echo "$usage"
  exit 1
fi
readonly environment="${1}"

# Ensure our `aws` command is the one infra has wrapped with aws-vault
command -v "$aws_command" 2> /dev/null | grep "ppp-infra/scripts/aws" &> /dev/null || \
  ( echo "error: aws command not pointing to 'ppp-infra/scripts/aws"
    echo "see https://github.com/transcom/ppp-infra/blob/master/transcom-ppp/README.md#using-aws-vault"
    exit 1
  )

bucket="${aws_bucket_prefix}${environment}${aws_bucket_suffix}"

# Find only the files that need to be renamed
filenames=$(${aws_command} s3api list-objects --bucket "${bucket}"  --prefix "${aws_path_prefix}/" | jq -r ".Contents[].Key" | grep -E -v ".up.sql" | grep "sql" | sort)

# Copy to new name
for file in $filenames; do
  new_file="${file%.*}.up.sql"
  ${aws_command} s3 cp --sse AES256 "s3://${bucket}/${file}" "s3://${bucket}/${new_file}"
done

# Check for any missing files
${aws_command} s3api list-objects --bucket "${bucket}"  --prefix "${aws_path_prefix}/" | jq -r ".Contents[].Key" | grep -E -v ".up.sql" | grep "sql" | sort
