#! /usr/bin/env bash
#
#   Update manifest for migrations
#

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

# If in CI exit immediately, since pre-commit might reorder the manifest on branches not in sync with master.
[[ "${CI:-}" == "true" ]] && exit 0

echo -e "# This is the migrations manifest.\n# If a migration is not recorded here, then it will error." > "$DIR/../migrations_manifest.txt"
find "${DIR}/../migrations"  -type f -exec basename {} \; | sort | uniq | grep -v "^schema[.]sql$" >> "$DIR/../migrations_manifest.txt"
