#! /usr/bin/env bash

#
# Update branch name before running docker-compose
#

set -eu -o pipefail
shopt -s extglob

readonly filename=$1

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
perl -pi.bak -e "s/(.*git-branch).*/\$1-${BRANCH_NAME//+([^A-Za-z0-9-.])/-}/g" "${filename}"
rm "${filename}".bak
