#! /usr/bin/env bash

set -eu -o pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: ${0##*/} <GBLOC>"
  echo "Example: ${0##*/} AGFM"
  exit 1
fi

gbloc=$1

printf "Here are a few ZIP codes in the %s GBLOC: \\n\\n" "$gbloc"

# The -t option prints just the values as opposed to the default formatting that
# includes the column name underlined
psql -t postgres://"$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME" << EOF
SELECT postal_code FROM postal_code_to_gbloc
WHERE gbloc = UPPER('$gbloc')
LIMIT 10;
EOF
