package services

import (
	"io"

	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
	"github.com/spf13/afero"

	"github.com/transcom/mymove/pkg/appcontext"
)

// WeightEstimatorPage1 is an object representing fields from Page 1 of the pdf
type WeightEstimatorPage1 struct {
	LivingRoomCuFt1    string
	LivingRoomPieces1  string
	LivingRoomTotal1   string
	LivingRoomCuFt2    string
	LivingRoomPieces2  string
	LivingRoomTotal2   string
	LivingRoomCuFt3    string
	LivingRoomPieces3  string
	LivingRoomTotal3   string
	LivingRoomCuFt4    string
	LivingRoomPieces4  string
	LivingRoomTotal4   string
	LivingRoomCuFt5    string
	LivingRoomPieces5  string
	LivingRoomTotal5   string
	LivingRoomCuFt6    string
	LivingRoomPieces6  string
	LivingRoomTotal6   string
	LivingRoomCuFt7    string
	LivingRoomPieces7  string
	LivingRoomTotal7   string
	LivingRoomCuFt8    string
	LivingRoomPieces8  string
	LivingRoomTotal8   string
	LivingRoomCuFt9    string
	LivingRoomPieces9  string
	LivingRoomTotal9   string
	LivingRoomCuFt10   string
	LivingRoomPieces10 string
	LivingRoomTotal10  string
	LivingRoomCuFt11   string
	LivingRoomPieces11 string
	LivingRoomTotal11  string
	LivingRoomCuFt12   string
	LivingRoomPieces12 string
	LivingRoomTotal12  string
	LivingRoomCuFt13   string
	LivingRoomPieces13 string
	LivingRoomTotal13  string
	LivingRoomCuFt14   string
	LivingRoomPieces14 string
	LivingRoomTotal14  string
	LivingRoomCuFt15   string
	LivingRoomPieces15 string
	LivingRoomTotal15  string
	LivingRoomCuFt16   string
	LivingRoomPieces16 string
	LivingRoomTotal16  string
	LivingRoomCuFt17   string
	LivingRoomPieces17 string
	LivingRoomTotal17  string
	LivingRoomCuFt18   string
	LivingRoomPieces18 string
	LivingRoomTotal18  string
	LivingRoomCuFt19   string
	LivingRoomPieces19 string
	LivingRoomTotal19  string
	LivingRoomCuFt20   string
	LivingRoomPieces20 string
	LivingRoomTotal20  string
	LivingRoomCuFt21   string
	LivingRoomPieces21 string
	LivingRoomTotal21  string
	LivingRoomCuFt22   string
	LivingRoomPieces22 string
	LivingRoomTotal22  string
	LivingRoomCuFt23   string
	LivingRoomPieces23 string
	LivingRoomTotal23  string
	LivingRoomCuFt24   string
	LivingRoomPieces24 string
	LivingRoomTotal24  string
	LivingRoomCuFt25   string
	LivingRoomPieces25 string
	LivingRoomTotal25  string
	LivingRoomCuFt26   string
	LivingRoomPieces26 string
	LivingRoomTotal26  string
	LivingRoomCuFt27   string
	LivingRoomPieces27 string
	LivingRoomTotal27  string
	LivingRoomCuFt28   string
	LivingRoomPieces28 string
	LivingRoomTotal28  string
	LivingRoomCuFt29   string
	LivingRoomPieces29 string
	LivingRoomTotal29  string
	LivingRoomCuFt30   string
	LivingRoomPieces30 string
	LivingRoomTotal30  string
	LivingRoomCuFt31   string
	LivingRoomPieces31 string
	LivingRoomTotal31  string
	LivingRoomCuFt32   string
	LivingRoomPieces32 string
	LivingRoomTotal32  string
}

// WeightEstimatorPage2 is an object representing fields from Page 2 of the pdf
type WeightEstimatorPage2 struct {
	LivingRoomCuFt33       string
	LivingRoomPieces33     string
	LivingRoomTotal33      string
	LivingRoomCuFt34       string
	LivingRoomPieces34     string
	LivingRoomTotal34      string
	LivingRoomCuFt35       string
	LivingRoomPieces35     string
	LivingRoomTotal35      string
	LivingRoomCuFt36       string
	LivingRoomPieces36     string
	LivingRoomTotal36      string
	LivingRoomCuFt37       string
	LivingRoomPieces37     string
	LivingRoomTotal37      string
	LivingRoomCuFt38       string
	LivingRoomPieces38     string
	LivingRoomTotal38      string
	LivingRoomCuFt39       string
	LivingRoomPieces39     string
	LivingRoomTotal39      string
	LivingRoomCuFt40       string
	LivingRoomPieces40     string
	LivingRoomTotal40      string
	LivingRoomPiecesTotal1 string
	LivingRoomCuFtTotal1   string
	LivingRoomCuFt41       string
	LivingRoomPieces41     string
	LivingRoomTotal41      string
	LivingRoomPiecesTotal2 string
	LivingRoomCuFtTotal2   string
	LivingRoomTotalItems   string
	LivingRoomTotalCube    string
	LivingRoomWeight       string
	DiningRoomCuFt1        string
	DiningRoomPieces1      string
	DiningRoomTotal1       string
	DiningRoomCuFt2        string
	DiningRoomPieces2      string
	DiningRoomTotal2       string
	DiningRoomCuFt3        string
	DiningRoomPieces3      string
	DiningRoomTotal3       string
	DiningRoomCuFt4        string
	DiningRoomPieces4      string
	DiningRoomTotal4       string
	DiningRoomCuFt5        string
	DiningRoomPieces5      string
	DiningRoomTotal5       string
	DiningRoomCuFt6        string
	DiningRoomPieces6      string
	DiningRoomTotal6       string
	DiningRoomCuFt7        string
	DiningRoomPieces7      string
	DiningRoomTotal7       string
	DiningRoomCuFt8        string
	DiningRoomPieces8      string
	DiningRoomTotal8       string
	DiningRoomCuFt9        string
	DiningRoomPieces9      string
	DiningRoomTotal9       string
	DiningRoomCuFt10       string
	DiningRoomPieces10     string
	DiningRoomTotal10      string
	DiningRoomCuFt11       string
	DiningRoomPieces11     string
	DiningRoomTotal11      string
	DiningRoomCuFt12       string
	DiningRoomPieces12     string
	DiningRoomTotal12      string
	DiningRoomCuFt13       string
	DiningRoomPieces13     string
	DiningRoomTotal13      string
	DiningRoomPiecesTotal1 string
	DiningRoomCuFtTotal1   string
	DiningRoomPiecesTotal2 string
	DiningRoomCuFtTotal2   string
	DiningRoomTotalItems   string
	DiningRoomTotalCube    string
}

type WeightEstimatorPage3 struct {
	DiningRoomWeight    string
	BedRoomCuFt1        string
	BedRoomPieces1      string
	BedRoomTotal1       string
	BedRoomCuFt2        string
	BedRoomPieces2      string
	BedRoomTotal2       string
	BedRoomCuFt3        string
	BedRoomPieces3      string
	BedRoomTotal3       string
	BedRoomCuFt4        string
	BedRoomPieces4      string
	BedRoomTotal4       string
	BedRoomCuFt5        string
	BedRoomPieces5      string
	BedRoomTotal5       string
	BedRoomCuFt6        string
	BedRoomPieces6      string
	BedRoomTotal6       string
	BedRoomCuFt7        string
	BedRoomPieces7      string
	BedRoomTotal7       string
	BedRoomCuFt8        string
	BedRoomPieces8      string
	BedRoomTotal8       string
	BedRoomCuFt9        string
	BedRoomPieces9      string
	BedRoomTotal9       string
	BedRoomCuFt10       string
	BedRoomPieces10     string
	BedRoomTotal10      string
	BedRoomCuFt11       string
	BedRoomPieces11     string
	BedRoomTotal11      string
	BedRoomCuFt12       string
	BedRoomPieces12     string
	BedRoomTotal12      string
	BedRoomCuFt13       string
	BedRoomPieces13     string
	BedRoomTotal13      string
	BedRoomCuFt14       string
	BedRoomPieces14     string
	BedRoomTotal14      string
	BedRoomCuFt15       string
	BedRoomPieces15     string
	BedRoomTotal15      string
	BedRoomCuFt16       string
	BedRoomPieces16     string
	BedRoomTotal16      string
	BedRoomCuFt17       string
	BedRoomPieces17     string
	BedRoomTotal17      string
	BedRoomCuFt18       string
	BedRoomPieces18     string
	BedRoomTotal18      string
	BedRoomCuFt19       string
	BedRoomPieces19     string
	BedRoomTotal19      string
	BedRoomCuFt20       string
	BedRoomPieces20     string
	BedRoomTotal20      string
	BedRoomCuFt21       string
	BedRoomPieces21     string
	BedRoomTotal21      string
	BedRoomCuFt22       string
	BedRoomPieces22     string
	BedRoomTotal22      string
	BedRoomPiecesTotal1 string
	BedRoomCuFtTotal1   string
	BedRoomPiecesTotal2 string
	BedRoomCuFtTotal2   string
	BedRoomTotalItems   string
	BedRoomTotalCube    string
	BedRoomWeight       string
}

type WeightEstimatorPage4 struct {
	DenCuFt1            string
	DenPieces1          string
	DenTotal1           string
	DenCuFt2            string
	DenPieces2          string
	DenTotal2           string
	DenCuFt3            string
	DenPieces3          string
	DenTotal3           string
	DenCuFt4            string
	DenPieces4          string
	DenTotal4           string
	DenCuFt5            string
	DenPieces5          string
	DenTotal5           string
	DenCuFt6            string
	DenPieces6          string
	DenTotal6           string
	DenCuFt7            string
	DenPieces7          string
	DenTotal7           string
	DenCuFt8            string
	DenPieces8          string
	DenTotal8           string
	DenCuFt9            string
	DenPieces9          string
	DenTotal9           string
	DenCuFt10           string
	DenPieces10         string
	DenTotal10          string
	DenCuFt11           string
	DenPieces11         string
	DenTotal11          string
	DenCuFt12           string
	DenPieces12         string
	DenTotal12          string
	DenCuFt13           string
	DenPieces13         string
	DenTotal13          string
	DenCuFt14           string
	DenPieces14         string
	DenTotal14          string
	DenPiecesTotal1     string
	DenCuFtTotal1       string
	DenPiecesTotal2     string
	DenCuFtTotal2       string
	DenTotalItems       string
	DenTotalCube        string
	DenWeight           string
	NurseryCuFt1        string
	NurseryPieces1      string
	NurseryTotal1       string
	NurseryCuFt2        string
	NurseryPieces2      string
	NurseryTotal2       string
	NurseryCuFt3        string
	NurseryPieces3      string
	NurseryTotal3       string
	NurseryCuFt4        string
	NurseryPieces4      string
	NurseryTotal4       string
	NurseryCuFt5        string
	NurseryPieces5      string
	NurseryTotal5       string
	NurseryCuFt6        string
	NurseryPieces6      string
	NurseryTotal6       string
	NurseryCuFt7        string
	NurseryPieces7      string
	NurseryTotal7       string
	NurseryCuFt8        string
	NurseryPieces8      string
	NurseryTotal8       string
	NurseryCuFt9        string
	NurseryPieces9      string
	NurseryTotal9       string
	NurseryCuFt10       string
	NurseryPieces10     string
	NurseryTotal10      string
	NurseryCuFt11       string
	NurseryPieces11     string
	NurseryTotal11      string
	NurseryPiecesTotal1 string
	NurseryCuFtTotal1   string
	NurseryCuFt12       string
	NurseryPieces12     string
	NurseryTotal12      string
	NurseryTotalItems   string
}

type WeightEstimatorPage5 struct {
	NurseryPiecesTotal2 string
	NurseryCuFtTotal2   string
	NurseryTotalCube    string
	NurseryWeight       string
	KitchenCuFt1        string
	KitchenPieces1      string
	KitchenTotal1       string
	KitchenCuFt2        string
	KitchenPieces2      string
	KitchenTotal2       string
	KitchenCuFt3        string
	KitchenPieces3      string
	KitchenTotal3       string
	KitchenCuFt4        string
	KitchenPieces4      string
	KitchenTotal4       string
	KitchenCuFt5        string
	KitchenPieces5      string
	KitchenTotal5       string
	KitchenCuFt6        string
	KitchenPieces6      string
	KitchenTotal6       string
	KitchenCuFt7        string
	KitchenPieces7      string
	KitchenTotal7       string
	KitchenCuFt8        string
	KitchenPieces8      string
	KitchenTotal8       string
	KitchenCuFt9        string
	KitchenPieces9      string
	KitchenTotal9       string
	KitchenCuFt10       string
	KitchenPieces10     string
	KitchenTotal10      string
	KitchenCuFt11       string
	KitchenPieces11     string
	KitchenTotal11      string
	KitchenCuFt12       string
	KitchenPieces12     string
	KitchenTotal12      string
	KitchenPiecesTotal1 string
	KitchenCuFtTotal1   string
	KitchenPiecesTotal2 string
	KitchenCuFtTotal2   string
	KitchenTotalItems   string
	KitchenTotalCube    string
	KitchenWeight       string
	AppliancesCuFt1     string
	AppliancesPieces1   string
	AppliancesTotal1    string
	AppliancesCuFt2     string
	AppliancesPieces2   string
	AppliancesTotal2    string
	AppliancesCuFt3     string
	AppliancesPieces3   string
	AppliancesTotal3    string
	AppliancesCuFt4     string
	AppliancesPieces4   string
	AppliancesTotal4    string
	AppliancesCuFt5     string
	AppliancesPieces5   string
	AppliancesTotal5    string
	AppliancesCuFt6     string
	AppliancesPieces6   string
	AppliancesTotal6    string
	AppliancesCuFt7     string
	AppliancesPieces7   string
	AppliancesTotal7    string
	AppliancesCuFt8     string
	AppliancesPieces8   string
	AppliancesTotal8    string
}

type WeightEstimatorPage6 struct {
	AppliancesCuFt9        string
	AppliancesPieces9      string
	AppliancesTotal9       string
	AppliancesCuFt10       string
	AppliancesPieces10     string
	AppliancesTotal10      string
	AppliancesCuFt11       string
	AppliancesPieces11     string
	AppliancesTotal11      string
	AppliancesCuFt12       string
	AppliancesPieces12     string
	AppliancesTotal12      string
	AppliancesCuFt13       string
	AppliancesPieces13     string
	AppliancesTotal13      string
	AppliancesCuFt14       string
	AppliancesPieces14     string
	AppliancesTotal14      string
	AppliancesCuFt15       string
	AppliancesPieces15     string
	AppliancesTotal15      string
	AppliancesCuFt16       string
	AppliancesPieces16     string
	AppliancesTotal16      string
	AppliancesPiecesTotal1 string
	AppliancesCuFtTotal1   string
	AppliancesCuFt17       string
	AppliancesPieces17     string
	AppliancesTotal17      string
	AppliancesTotalItems   string
	AppliancesCuFt18       string
	AppliancesPieces18     string
	AppliancesTotal18      string
	AppliancesTotalCube    string
	AppliancesPiecesTotal2 string
	AppliancesCuFtTotal2   string
	AppliancesWeight       string
	OutdoorCuFt1           string
	OutdoorPieces1         string
	OutdoorTotal1          string
	OutdoorCuFt2           string
	OutdoorPieces2         string
	OutdoorTotal2          string
	OutdoorCuFt3           string
	OutdoorPieces3         string
	OutdoorTotal3          string
	OutdoorCuFt4           string
	OutdoorPieces4         string
	OutdoorTotal4          string
	OutdoorCuFt5           string
	OutdoorPieces5         string
	OutdoorTotal5          string
	OutdoorCuFt6           string
	OutdoorPieces6         string
	OutdoorTotal6          string
	OutdoorCuFt7           string
	OutdoorPieces7         string
	OutdoorTotal7          string
	OutdoorCuFt8           string
	OutdoorPieces8         string
	OutdoorTotal8          string
	OutdoorCuFt9           string
	OutdoorPieces9         string
	OutdoorTotal9          string
	OutdoorCuFt10          string
	OutdoorPieces10        string
	OutdoorTotal10         string
	OutdoorCuFt11          string
	OutdoorPieces11        string
	OutdoorTotal11         string
	OutdoorCuFt12          string
	OutdoorPieces12        string
	OutdoorTotal12         string
	OutdoorCuFt13          string
	OutdoorPieces13        string
	OutdoorTotal13         string
	OutdoorCuFt14          string
	OutdoorPieces14        string
	OutdoorTotal14         string
	OutdoorCuFt15          string
	OutdoorPieces15        string
	OutdoorTotal15         string
	OutdoorCuFt16          string
	OutdoorPieces16        string
	OutdoorTotal16         string
	OutdoorCuFt17          string
	OutdoorPieces17        string
	OutdoorTotal17         string
	OutdoorCuFt18          string
	OutdoorPieces18        string
	OutdoorTotal18         string
	OutdoorCuFt19          string
	OutdoorPieces19        string
	OutdoorTotal19         string
	OutdoorCuFt20          string
	OutdoorPieces20        string
	OutdoorTotal20         string
}

type WeightEstimatorPage7 struct {
	OutdoorCuFt21        string
	OutdoorPieces21      string
	OutdoorTotal21       string
	OutdoorCuFt22        string
	OutdoorPieces22      string
	OutdoorTotal22       string
	OutdoorCuFt23        string
	OutdoorPieces23      string
	OutdoorTotal23       string
	OutdoorCuFt24        string
	OutdoorPieces24      string
	OutdoorTotal24       string
	OutdoorCuFt25        string
	OutdoorPieces25      string
	OutdoorTotal25       string
	OutdoorCuFt26        string
	OutdoorPieces26      string
	OutdoorTotal26       string
	OutdoorCuFt27        string
	OutdoorPieces27      string
	OutdoorTotal27       string
	OutdoorCuFt28        string
	OutdoorPieces28      string
	OutdoorTotal28       string
	OutdoorCuFt29        string
	OutdoorPieces29      string
	OutdoorTotal29       string
	OutdoorPiecesTotal1  string
	OutdoorCuFtTotal1    string
	OutdoorCuFt30        string
	OutdoorPieces30      string
	OutdoorTotal30       string
	OutdoorTotalItems    string
	OutdoorPiecesTotal2  string
	OutdoorCuFtTotal2    string
	OutdoorTotalCube     string
	OutdoorWeight        string
	ExerciseCuFt1        string
	ExercisePieces1      string
	ExerciseTotal1       string
	ExerciseCuFt2        string
	ExercisePieces2      string
	ExerciseTotal2       string
	ExerciseCuFt3        string
	ExercisePieces3      string
	ExerciseTotal3       string
	ExerciseCuFt4        string
	ExercisePieces4      string
	ExerciseTotal4       string
	ExerciseCuFt5        string
	ExercisePieces5      string
	ExerciseTotal5       string
	ExerciseCuFt6        string
	ExercisePieces6      string
	ExerciseTotal6       string
	ExerciseCuFt7        string
	ExercisePieces7      string
	ExerciseTotal7       string
	ExerciseCuFt8        string
	ExercisePieces8      string
	ExerciseTotal8       string
	ExerciseCuFt9        string
	ExercisePieces9      string
	ExerciseTotal9       string
	ExerciseCuFt10       string
	ExercisePieces10     string
	ExerciseTotal10      string
	ExerciseCuFt11       string
	ExercisePieces11     string
	ExerciseTotal11      string
	ExercisePiecesTotal1 string
	ExerciseCuFtTotal1   string
	ExerciseCuFt12       string
	ExercisePieces12     string
	ExerciseTotal12      string
	ExerciseTotalItems   string
	ExerciseCuFt13       string
	ExercisePieces13     string
	ExerciseTotal13      string
	ExerciseTotalCube    string
	ExercisePiecesTotal2 string
	ExerciseCuFtTotal2   string
	ExerciseWeight       string
}

type WeightEstimatorPage8 struct {
	MiscCuFt1        string
	MiscPieces1      string
	MiscTotal1       string
	MiscCuFt2        string
	MiscPieces2      string
	MiscTotal2       string
	MiscCuFt3        string
	MiscPieces3      string
	MiscTotal3       string
	MiscCuFt4        string
	MiscPieces4      string
	MiscTotal4       string
	MiscCuFt5        string
	MiscPieces5      string
	MiscTotal5       string
	MiscCuFt6        string
	MiscPieces6      string
	MiscTotal6       string
	MiscCuFt7        string
	MiscPieces7      string
	MiscTotal7       string
	MiscCuFt8        string
	MiscPieces8      string
	MiscTotal8       string
	MiscCuFt9        string
	MiscPieces9      string
	MiscTotal9       string
	MiscCuFt10       string
	MiscPieces10     string
	MiscTotal10      string
	MiscCuFt11       string
	MiscPieces11     string
	MiscTotal11      string
	MiscCuFt12       string
	MiscPieces12     string
	MiscTotal12      string
	MiscCuFt13       string
	MiscPieces13     string
	MiscTotal13      string
	MiscCuFt14       string
	MiscPieces14     string
	MiscTotal14      string
	MiscCuFt15       string
	MiscPieces15     string
	MiscTotal15      string
	MiscCuFt16       string
	MiscPieces16     string
	MiscTotal16      string
	MiscCuFt17       string
	MiscPieces17     string
	MiscTotal17      string
	MiscCuFt18       string
	MiscPieces18     string
	MiscTotal18      string
	MiscCuFt19       string
	MiscPieces19     string
	MiscTotal19      string
	MiscCuFt20       string
	MiscPieces20     string
	MiscTotal20      string
	MiscCuFt21       string
	MiscPieces21     string
	MiscTotal21      string
	MiscCuFt22       string
	MiscPieces22     string
	MiscTotal22      string
	MiscCuFt23       string
	MiscPieces23     string
	MiscTotal23      string
	MiscCuFt24       string
	MiscPieces24     string
	MiscTotal24      string
	MiscCuFt25       string
	MiscPieces25     string
	MiscTotal25      string
	MiscCuFt26       string
	MiscPieces26     string
	MiscTotal26      string
	MiscCuFt27       string
	MiscPieces27     string
	MiscTotal27      string
	MiscCuFt28       string
	MiscPieces28     string
	MiscTotal28      string
	MiscCuFt29       string
	MiscPieces29     string
	MiscTotal29      string
	MiscCuFt30       string
	MiscPieces30     string
	MiscTotal30      string
	MiscPiecesTotal1 string
	MiscCuFtTotal1   string
	MiscPiecesTotal2 string
	MiscCuFtTotal2   string
	MiscTotalItems   string
	MiscTotalCube    string
	MiscWeight       string
}

type WeightEstimatorPage9 struct {
	GarageCuFt1          string
	GaragePieces1        string
	GarageTotal1         string
	GarageCuFt2          string
	GaragePieces2        string
	GarageTotal2         string
	GarageCuFt3          string
	GaragePieces3        string
	GarageTotal3         string
	GarageCuFt4          string
	GaragePieces4        string
	GarageTotal4         string
	GarageCuFt5          string
	GaragePieces5        string
	GarageTotal5         string
	GarageCuFt6          string
	GaragePieces6        string
	GarageTotal6         string
	GarageCuFt7          string
	GaragePieces7        string
	GarageTotal7         string
	GarageCuFt8          string
	GaragePieces8        string
	GarageTotal8         string
	GarageCuFt9          string
	GaragePieces9        string
	GarageTotal9         string
	GarageCuFt10         string
	GaragePieces10       string
	GarageTotal10        string
	GarageCuFt11         string
	GaragePieces11       string
	GarageTotal11        string
	GarageCuFt12         string
	GaragePieces12       string
	GarageTotal12        string
	GarageCuFt13         string
	GaragePieces13       string
	GarageTotal13        string
	GarageCuFt14         string
	GaragePieces14       string
	GarageTotal14        string
	GaragePiecesTotal1   string
	GarageCuFtTotal1     string
	GaragePiecesTotal2   string
	GarageCuFtTotal2     string
	GarageTotalItems     string
	GarageTotalCube      string
	GarageWeight         string
	MilitaryTotalItems   string
	CivilianTotalItems   string
	MilitaryTotalCube    string
	CivilianTotalCube    string
	CartonsCuFt1         string
	CartonsPieces1       string
	CartonsTotal1        string
	CartonsCuFt2         string
	CartonsPieces2       string
	CartonsTotal2        string
	MilitaryWeight       string
	CivilianWeight       string
	CartonsCuFt3         string
	CartonsPieces3       string
	CartonsTotal3        string
	MilitaryProGear      string
	CivilianProGear      string
	CartonsCuFt4         string
	CartonsPieces4       string
	CartonsTotal4        string
	MilitaryMinusProGear string
	CivilianMinusProGear string
	CartonsCuFt5         string
	CartonsPieces5       string
	CartonsTotal5        string
	MilitaryPacking      string
}

type WeightEstimatorPage10 struct {
	CartonsCuFt6             string
	CartonsPieces6           string
	CartonsTotal6            string
	MilitaryWeightChargeable string
	CivilianWeightChargeable string
	CartonsCuFt7             string
	CartonsPieces7           string
	CartonsTotal7            string
	MilitaryWeightAllowance  string
	CivilianWeightAllowance  string
	CartonsCuFt8             string
	CartonsPieces8           string
	CartonsTotal8            string
	MilitaryWeightOverUnder  string
	CivilianWeightOverUnder  string
	CartonsCuFt9             string
	CartonsPieces9           string
	CartonsTotal9            string
	CartonsPiecesTotal1      string
	CartonsCuFtTotal1        string
	ProGearCuFt1             string
	ProGearPieces1           string
	ProGearTotal1            string
	ProGearCuFt2             string
	ProGearPieces2           string
	ProGearTotal2            string
	ProGearCuFt3             string
	ProGearPieces3           string
	ProGearTotal3            string
	ProGearCuFt4             string
	ProGearPieces4           string
	ProGearTotal4            string
	ProGearCuFt5             string
	ProGearPieces5           string
	ProGearTotal5            string
	ProGearCuFt6             string
	ProGearPieces6           string
	ProGearTotal6            string
	ProGearCuFt7             string
	ProGearPieces7           string
	ProGearTotal7            string
	ProGearCuFt8             string
	ProGearPieces8           string
	ProGearTotal8            string
	ProGearCuFt9             string
	ProGearPieces9           string
	ProGearTotal9            string
	ProGearCuFt10            string
	ProGearPieces10          string
	ProGearTotal10           string
	ProGearCuFt11            string
	ProGearPieces11          string
	ProGearTotal11           string
	ProGearCuFt12            string
	ProGearPieces12          string
	ProGearTotal12           string
}

type WeightEstimatorPage11 struct {
	ProGearCuFt13       string
	ProGearPieces13     string
	ProGearTotal13      string
	ProGearPiecesTotal1 string
	ProGearCuFtTotal1   string
	ProGearWeight       string
	ProGearPieces       string
}

type WeightEstimatorPages struct {
	Page1  WeightEstimatorPage1
	Page2  WeightEstimatorPage2
	Page3  WeightEstimatorPage3
	Page4  WeightEstimatorPage4
	Page5  WeightEstimatorPage5
	Page6  WeightEstimatorPage6
	Page7  WeightEstimatorPage7
	Page8  WeightEstimatorPage8
	Page9  WeightEstimatorPage9
	Page10 WeightEstimatorPage10
	Page11 WeightEstimatorPage11
}

//go:generate mockery --name WeightTicketComputer
type WeightTicketComputer interface {
	ParseWeightEstimatorExcelFile(appCtx appcontext.AppContext, file io.ReadCloser) (*WeightEstimatorPages, error)
}

//go:generate mockery --name WeightTicketGenerator
type WeightTicketGenerator interface {
	FillWeightEstimatorPDFForm(PageValues WeightEstimatorPages, fileName string) (WeightWorksheet afero.File, pdfInfo *pdfcpu.PDFInfo, returnErr error)
	CleanupFile(weightFile afero.File) error
}
