FROM alpine:3.11.2

COPY ./generate-test-data /bin/generate-test-data
COPY ./test.pdf /bin/pkg/testdatagen/testdata/test.pdf

# Install tools needed in container
RUN apk update
RUN apk add postgresql-client bash --no-cache

WORKDIR /bin
