export default {
  has_pro_gear: 'has_pro_gear',
  sit_expected: 'sit_expected',
  dependents_authorized: 'dependents_authorized',
  has_dependents: 'has_dependents',
  has_requested_advance: 'has_requested_advance',
  owns_trailer: 'Trailer',
  trailer_meets_criteria: 'Trailer meets criteria',
  belongs_to_self: 'belongs_to_self',
  has_received_advance: 'has_received_advance',
  paid_with_gtcc: 'paid_with_gtcc',
  missing_receipt: 'missing_receipt',
  organizational_clothing_and_individual_equipment: 'organizational_clothing_and_individual_equipment',
  gun_safe: 'gun_safe',
  email_is_preferred: 'email_is_preferred',
  phone_is_preferred: 'phone_is_preferred',
  uses_external_vendor: 'uses_external_vendor',
  diversion: 'diversion',
  has_secondary_pickup_address: 'Secondary Pickup Address',
  has_secondary_delivery_address: 'Secondary Delivery Address',
  has_tertiary_pickup_address: 'Third Pickup Address',
  has_tertiary_delivery_address: 'Third Delivery Address',
};
