export default {
  requested_delivery_date: 'requested_delivery_date',
  scheduled_pickup_date: 'scheduled_pickup_date',
  approved_date: 'approved_date',
  actual_pickup_date: 'actual_pickup_date',
  report_by_date: 'report_by_date',
  issue_date: 'issue_date',
  requested_pickup_date: 'requested_pickup_date',
  sit_departure_date: 'sit_departure_date',
  sit_entry_date: 'sit_entry_date',
  first_available_delivery_date: 'first_available_delivery_date',
  second_available_delivery_date: 'second_available_delivery_date',
  retirement_date: 'retirement_date',
  separation_date: 'separation_date',
  expected_departure_date: 'expected_departure_date',
  sit_estimated_departure_date: 'sit_estimated_departure_date',
  sit_requested_delivery: 'sit_requested_delivery',
  sit_estimated_entry_date: 'sit_estimated_entry_date',
  sit_start_date: 'sit_start_date',
  sit_end_date: 'sit_end_date',
  sit_customer_contacted: 'sit_customer_contacted',
  actual_move_date: 'actual_move_date',
  decision_date: 'decision_date',
  required_delivery_date: 'required_delivery_date',
};
