export default {
  updated_at: 'Updated at',
  diversion: 'Diversion',
  billable_weight_cap: 'Billable weight',
  billable_weight_justification: 'Billable weight remarks',
  uses_external_vendor: 'Uses external vendor',
  requested_delivery_date: 'Requested delivery date',
  scheduled_pickup_date: 'Scheduled pickup date',
  status: 'Status',
  customer_remarks: 'Customer remarks',
  approved_date: 'Approved date',
  actual_pickup_date: 'Departure date',
  prime_estimated_weight: 'Prime estimated weight',
  counselor_remarks: 'Counselor remarks',
  service_order_number: 'Service order number',
  tac_type: 'TAC type',
  sac_type: 'SAC type',
  authorized_weight: 'Authorized weight',
  report_by_date: 'Report by date',
  issue_date: 'Orders date',
  orders_type: 'Orders type',
  orders_type_detail: 'Orders type detail',
  origin_duty_location_name: 'Origin duty location name',
  new_duty_location_name: 'New duty location name',
  orders_number: 'Orders number',
  tac: 'HHG TAC',
  sac: 'HHG SAC',
  nts_tac: 'NTS TAC',
  nts_sac: 'NTS SAC',
  department_indicator: 'Dept. indicator',
  amended_orders_acknowledged_at: 'Amended orders acknowledged at',
  storage_in_transit: 'Storage in transit (SIT)',
  dependents_authorized: 'Dependents',
  has_dependents: 'Dependents included',
  has_pro_gear: 'Pro-gear',
  pro_gear_weight: 'Pro-gear weight',
  pro_gear_weight_spouse: 'Spouse pro-gear weight',
  spouse_pro_gear_weight: 'Spouse pro-gear weight', // ppm_shipments table
  required_medical_equipment_weight: 'Required medical equipment',
  organizational_clothing_and_individual_equipment: 'OCIE',
  gun_safe: 'Gun Safe',
  requested_pickup_date: 'Requested pickup date',
  grade: 'Pay grade',
  shipment_type: 'Shipment type',
  pickup_address: 'Origin address',
  secondary_pickup_address: 'Secondary origin address',
  destination_address: 'Delivery Address',
  secondary_destination_address: 'Secondary delivery address',
  receiving_agent: 'Receiving agent',
  releasing_agent: 'Releasing agent',
  tio_remarks: 'Max billable weight remark',
  prime_actual_weight: 'Shipment weight',
  actual_weight: 'Actual weight',
  estimated_weight: 'Estimated weight',
  allowable_weight: 'Allowable weight',
  description: 'Description',
  reason: 'Reason',
  rejection_reason: 'Reason',
  sit_departure_date: 'SIT departure date',
  sit_entry_date: 'SIT entry date',
  sit_postal_code: 'SIT postal code',
  sit_destination_address_final: 'Final SIT delivery address',
  sit_destination_address_initial: 'Initial SIT delivery address',
  sit_requested_delivery: 'Requested SIT delivery date ',
  contractor_remarks: 'Contractor remarks',
  office_remarks: 'Office remarks',
  item_size: 'Item size',
  crate_size: 'Crate size',
  first_available_delivery_date: 'First available delivery date',
  second_available_delivery_date: 'Second available delivery date',
  first_available_delivery_time: 'First available delivery time',
  second_available_delivery_time: 'Second available delivery time',
  reweigh_weight: 'Reweigh weight',
  destination_address_type: 'Destination type',
  affiliation: 'Branch',
  first_name: 'First name',
  middle_name: 'Middle name',
  last_name: 'Last name',
  suffix: 'Suffix',
  personal_email: 'Personal email',
  phone_is_preferred: 'Phone preferred',
  email_is_preferred: 'Email preferred',
  secondary_email: 'Secondary email',
  secondary_telephone: 'Secondary telephone',
  telephone: 'Telephone',
  residential_address: 'Pickup Address',
  backup_address: 'Backup address',
  current_duty_location_name: 'Current duty location name',
  financial_review_remarks: 'Financial review remarks',
  backup_contact_name: 'Backup contact name',
  backup_contact_email: 'Backup contact email',
  backup_contact_phone: 'Backup contact phone',
  max_billable_weight: 'Max billable weight',
  retirement_date: 'Date of retirement',
  separation_date: 'Date of separation',
  expected_departure_date: 'Expected departure date',
  sit_expected: 'Sit expected',
  sit_estimated_entry_date: 'SIT estimated storage start',
  sit_estimated_departure_date: 'SIT estimated storage end',
  sit_estimated_weight: 'SIT estimated storage weight',
  pickup_postal_code: 'Pickup postal code',
  destination_postal_code: 'Destination postal code',
  secondary_pickup_postal_code: 'Secondary pickup postal code',
  secondary_destination_postal_code: 'Secondary destination postal code',
  advance_status: 'Advance status',
  advance_amount_requested: 'Advance amount requested',
  has_requested_advance: 'Advance requested',
  empty_weight: 'Empty weight',
  full_weight: 'Full weight',
  weight: 'Weight',
  owns_trailer: 'Trailer',
  trailer_meets_criteria: 'Trailer meets criteria',
  net_weight_remarks: 'Remarks',
  adjusted_net_weight: 'Net weight',
  amount: 'Amount',
  sit_start_date: 'SIT start date',
  sit_end_date: 'SIT end date',
  shipment_weight: 'Shipment weight',
  belongs_to_self: 'Service member',
  sit_customer_contacted: 'SIT customer contacted',
  sit_location: 'SIT location',
  sit_estimated_cost: 'SIT estimated cost',
  estimated_incentive: 'PPM estimated incentive',
  ppm_type: 'PPM type',
  actual_move_date: 'Departure date',
  actual_pickup_postal_code: 'Starting ZIP',
  actual_destination_postal_code: 'Ending ZIP',
  has_received_advance: 'Advance received',
  advance_amount_received: 'Advance amount received',
  w2_address: 'W2 Address',
  final_incentive: 'Final incentive',
  upload_type: 'Document type',
  filename: 'Filename',
  paid_with_gtcc: 'Paid with gtcc',
  missing_receipt: 'Missing receipt',
  closeout_office_name: 'Closeout office',
  distance: 'Shipping distance',
  vehicle_description: 'Vehicle description',
  ppm_status: 'PPM status', // custom front end status, not database value
  moving_expense_type: 'Expense type',
  dest_sit_auth_end_date: 'Destination SIT authorized date',
  approvals_requested_at: 'Approvals requested at',
  approved_at: 'Approved at',
  counseling_office_name: 'Counseling office',
};
