export default {
  updated_at: 'Updated at',
  diversion: 'Diversion',
  billable_weight_cap: 'Billable weight',
  billable_weight_justification: 'Billable weight remarks',
  uses_external_vendor: 'Uses external vendor',
  requested_delivery_date: 'Requested delivery date',
  scheduled_pickup_date: 'Scheduled pickup date',
  status: 'Status',
  customer_remarks: 'Customer remarks',
  approved_date: 'Approved date',
  actual_pickup_date: 'Departure date',
  prime_estimated_weight: 'Prime estimated weight',
  counselor_remarks: 'Counselor remarks',
  service_order_number: 'Service order number',
  tac_type: 'TAC type',
  sac_type: 'SAC type',
  authorized_weight: 'Authorized weight',
  report_by_date: 'Report by date',
  issue_date: 'Orders date',
  orders_type: 'Orders type',
  orders_type_detail: 'Orders type detail',
  origin_duty_location_name: 'Origin duty location name',
  new_duty_location_name: 'New duty location name',
  orders_number: 'Orders number',
  tac: 'HHG TAC',
  sac: 'HHG SAC',
  nts_tac: 'NTS TAC',
  nts_sac: 'NTS SAC',
  department_indicator: 'Dept. indicator',
  amended_orders_acknowledged_at: 'Amended orders acknowledged at',
  storage_in_transit: 'Storage in transit (SIT)',
  dependents_authorized: 'Dependents',
  pro_gear_weight: 'Pro-gear',
  pro_gear_weight_spouse: 'Spouse pro-gear',
  required_medical_equipment_weight: 'RME',
  organizational_clothing_and_individual_equipment: 'OCIE',
  requested_pickup_date: 'Requested pickup date',
  grade: 'Rank',
  shipment_type: 'Shipment type',
  pickup_address: 'Origin address',
  destination_address: 'Destination address',
  receiving_agent: 'Receiving agent',
  releasing_agent: 'Releasing agent',
  tio_remarks: 'Max billable weight remark',
  prime_actual_weight: 'Shipment weight',
  move_services: 'Move services',
  shipment_services: 'Shipment services',
};
