export default {
  WAITING_ON_CUSTOMER: 'WAITING ON CUSTOMER',
  PAYMENT_APPROVED: 'PAYMENT APPROVED',
  NEEDS_ADVANCE_APPROVAL: 'NEEDS ADVANCE APPROVAL',
  NEEDS_PAYMENT_APPROVAL: 'NEEDS PAYMENT APPROVAL',
};
