export default {
  WAITING_ON_CUSTOMER: 'WAITING ON CUSTOMER',
  CLOSEOUT_COMPLETE: 'PAYMENT APPROVED',
  TERMINATED_FOR_CAUSE: 'TERMINATED FOR CAUSE',
  APPROVALS_REQUESTED: 'APPROVALS REQUESTED',
};
