export default {
  billable_weight_cap: 'billable_weight_cap',
  prime_estimated_weight: 'prime_estimated_weight',
  authorized_weight: 'authorized_weight',
  pro_gear_weight: 'pro_gear_weight',
  pro_gear_weight_spouse: 'pro_gear_weight_spouse',
  spouse_pro_gear_weight: 'spouse_pro_gear_weight',
  prime_actual_weight: 'prime_actual_weight',
  required_medical_equipment_weight: 'required_medical_equipment_weight',
  reweigh_weight: 'reweigh_weight',
  max_billable_weight: 'max_billable_weight',
  actual_weight: 'actual_weight',
  estimated_weight: 'estimated_weight',
  allowable_weight: 'allowable_weight',
  sit_estimated_weight: 'sit_estimated_weight',
  adjusted_net_weight: 'adjusted_net_weight',
  empty_weight: 'empty_weight',
  full_weight: 'full_weight',
  shipment_weight: 'shipment_weight',
  weight: 'weight',
};
