package notifications

import (
	"fmt"
	"strings"

	"github.com/transcom/mymove/pkg/auth"
	"github.com/transcom/mymove/pkg/factory"
	"github.com/transcom/mymove/pkg/models/roles"
)

func (suite *NotificationSuite) TestReweighRequestedOnSuccess() {
	move := factory.BuildAvailableToPrimeMove(suite.DB(), nil, nil)
	shipment := factory.BuildMTOShipment(suite.DB(), nil, nil)
	officeUser := factory.BuildOfficeUserWithRoles(nil, nil, []roles.RoleType{roles.RoleTypeTOO})

	notification := NewReweighRequested(move.ID, shipment)

	shipmentID := shipment.ID.String()
	var shipmentNumber string

	// Shipment # is the first 8 characters of shipmentId
	if len(shipmentID) >= 8 {
		firstEight := shipmentID[:8]
		shipmentNumber = strings.ToUpper(firstEight)
	} else {
		shipmentNumber = ""
	}

	subject := fmt.Sprintf("FYI: A reweigh has been requested for your shipment #%v, and must be reweighed before it is delivered", shipmentNumber)

	emails, err := notification.emails(suite.AppContextWithSessionForTest(&auth.Session{
		UserID:          officeUser.ID,
		ApplicationName: auth.OfficeApp,
	}))
	suite.NoError(err)
	suite.Equal(len(emails), 1)

	email := emails[0]
	sm := move.Orders.ServiceMember
	suite.Equal(email.recipientEmail, *sm.PersonalEmail)
	suite.Equal(email.subject, subject)
	suite.NotEmpty(email.htmlBody)
	suite.NotEmpty(email.textBody)
	suite.True(strings.Contains(email.textBody, "Your shipment must be reweighed before it reaches your destination."))
}

func (suite *NotificationSuite) TestReweighRequestedHTMLTemplateRender() {
	move := factory.BuildAvailableToPrimeMove(suite.DB(), nil, nil)
	shipment := factory.BuildMTOShipment(suite.DB(), nil, nil)
	officeUser := factory.BuildOfficeUserWithRoles(nil, nil, []roles.RoleType{roles.RoleTypeTOO})
	notification := NewReweighRequested(move.ID, shipment)
	s := reweighRequestedEmailData{
		MilitaryOneSourceLink: OneSourceTransportationOfficeLink,
	}
	expectedHTMLContent := `<p><strong>*** DO NOT REPLY directly to this email ***</strong></p>
<p><strong>*** This is an email generated by the U.S. Government system – MilMove. ***</strong></p>

<p><strong>Essential information</strong></p>
<ul>
  <li>Your shipment must be reweighed before it reaches your destination.</li>
  <li>Your HomeSafe Alliance (HSA) Customer Care Representative will tell you where and when they will perform the reweigh.</li>
  <li>You have the right to witness the reweigh, but it is your decision whether to do so.</li>
</ul>

<p><strong>Why was a reweigh requested?</strong></p>
<p>When a shipment’s weight brings you <strong><u>within 10% (or above) your standard weight allowance</u></strong>, the system will automatically request a reweigh.</p>
<p>It is also possible for a transportation office to manually request a reweigh for a shipment.</p>
<p>The official weight of your shipment will be the lower net weight between the original weighing and the reweigh.</p>
<p>Remember, if you move more weight than your allowance, you are subject to excess cost charges pending a review of all shipment(s) weights.</p>

<p><strong>What do you need to do?</strong></p>
<p>Nothing, unless you wish to witness the reweigh.</p>
<p>If you wish to witness the reweigh, your HSA Customer Care Representative is required to let you know <strong>when</strong> and <strong>where</strong> they will reweigh your shipment (any cost incurred to witness a reweigh is at your own expense).</p>
<p>Reweighs typically happen near your destination and close to your delivery date; however, this is not always the case. If your shipment goes into storage-in-transit (SIT) and the transportation service provider (TSP) does not reweigh it beforehand, the TSP still has the opportunity to perform a reweigh after you schedule a delivery date and your personal property leaves the warehouse.</p>

<p><strong>Who should you talk to about the reweigh?</strong></p>
<p>Your HSA Customer Care Representative will be arranging the logistics of the reweigh. You should talk to them directly if you have questions or wish to be present for the reweigh.</p>
<p>If your HSA Customer Care Representative does not give you a date and time for this reweigh, ask them for this information.</p>

<p><strong>Make sure your shipment has been reweighed before you accept delivery.</strong></p>
<p>The only time a reweigh cannot be performed is when the shipment has already been unloaded.</p>
<p>If you believe your shipment should be reweighed and has not been, do not accept delivery. Tell your HSA Customer Care Representative that they need to reweigh the shipment before they unload it.</p>
<p>Remember, your HomeSafe Alliance (HSA) Customer Care Representative is your first point of contact; however, if you are unsatisfied at any time, contact a government transportation office. You can see a listing of transportation offices on Military One Source here: <a href="` + OneSourceTransportationOfficeLink + `">` + OneSourceTransportationOfficeLink + `</a>.</p>
<p>Thank you,</p>
<p>USTRANSCOM MilMove Team</p>
<p>The information contained in this email may contain Privacy Act information and is therefore protected under the Privacy Act of 1974. Failure to protect Privacy Act information could result in a $5,000 fine.</p>
`

	htmlContent, err := notification.RenderHTML(suite.AppContextWithSessionForTest(&auth.Session{
		UserID:          officeUser.ID,
		ApplicationName: auth.OfficeApp,
	}), s)

	suite.NoError(err)
	suite.Equal(expectedHTMLContent, htmlContent)

}

func (suite *NotificationSuite) TestReweighRequestedTextTemplateRender() {
	move := factory.BuildAvailableToPrimeMove(suite.DB(), nil, nil)
	shipment := factory.BuildMTOShipment(suite.DB(), nil, nil)
	officeUser := factory.BuildOfficeUserWithRoles(nil, nil, []roles.RoleType{roles.RoleTypeTOO})
	notification := NewReweighRequested(move.ID, shipment)
	s := reweighRequestedEmailData{
		MilitaryOneSourceLink: OneSourceTransportationOfficeLink,
	}
	expectedTextContent := `*** DO NOT REPLY directly to this email ***

*** This is an email generated by the U.S. Government system – MilMove. ***

Essential information
* Your shipment must be reweighed before it reaches your destination.
* Your HomeSafe Alliance (HSA) Customer Care Representative will tell you where and when they will perform the reweigh.
* You have the right to witness the reweigh, but it is your decision whether to do so.

Why was a reweigh requested?
When a shipment’s weight brings you within 10% (or above) your standard weight allowance, the system will automatically request a reweigh.

It is also possible for a transportation office to manually request a reweigh for a shipment.

The official weight of your shipment will be the lower net weight between the original weighing and the reweigh.

Remember, if you move more weight than your allowance, you are subject to excess cost charges pending a review of all shipment(s) weights.

What do you need to do?
Nothing, unless you wish to witness the reweigh.

If you wish to witness the reweigh, your HSA Customer Care Representative is required to let you know when and where they will reweigh your shipment (any cost incurred to witness a reweigh is at your own expense).

Reweighs typically happen near your destination and close to your delivery date; however, this is not always the case. If your shipment goes into storage-in-transit (SIT) and the transportation service provider (TSP) does not reweigh it beforehand, the TSP still has the opportunity to perform a reweigh after you schedule a delivery date and your personal property leaves the warehouse.

Who should you talk to about the reweigh?
Your HSA Customer Care Representative will be arranging the logistics of the reweigh. You should talk to them directly if you have questions or wish to be present for the reweigh.

If your HSA Customer Care Representative does not give you a date and time for this reweigh, ask them for this information.

Make sure your shipment has been reweighed before you accept delivery.
The only time a reweigh cannot be performed is when the shipment has already been unloaded.

If you believe your shipment should be reweighed and has not been, do not accept delivery. Tell your HSA Customer Care Representative that they need to reweigh the shipment before they unload it.

Remember, your HomeSafe Alliance (HSA) Customer Care Representative is your first point of contact; however, if you are unsatisfied at any time, contact a government transportation office. You can see a listing of transportation offices on Military One Source here: ` + OneSourceTransportationOfficeLink + `.

Thank you,

USTRANSCOM MilMove Team

The information contained in this email may contain Privacy Act information and is therefore protected under the Privacy Act of 1974. Failure to protect Privacy Act information could result in a $5,000 fine.
`
	textContent, err := notification.RenderText(suite.AppContextWithSessionForTest(&auth.Session{
		UserID:          officeUser.ID,
		ApplicationName: auth.OfficeApp,
	}), s)

	suite.NoError(err)
	suite.Equal(expectedTextContent, textContent)
}
