// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	handlers "github.com/transcom/mymove/pkg/handlers"

	models "github.com/transcom/mymove/pkg/models"

	supportmessages "github.com/transcom/mymove/pkg/gen/supportmessages"
)

// InternalMoveTaskOrderCreator is an autogenerated mock type for the InternalMoveTaskOrderCreator type
type InternalMoveTaskOrderCreator struct {
	mock.Mock
}

// InternalCreateMoveTaskOrder provides a mock function with given fields: moveTaskOrder, logger
func (_m *InternalMoveTaskOrderCreator) InternalCreateMoveTaskOrder(moveTaskOrder supportmessages.MoveTaskOrder, logger handlers.Logger) (*models.MoveTaskOrder, error) {
	ret := _m.Called(moveTaskOrder, logger)

	var r0 *models.MoveTaskOrder
	if rf, ok := ret.Get(0).(func(supportmessages.MoveTaskOrder, handlers.Logger) *models.MoveTaskOrder); ok {
		r0 = rf(moveTaskOrder, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MoveTaskOrder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(supportmessages.MoveTaskOrder, handlers.Logger) error); ok {
		r1 = rf(moveTaskOrder, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
