// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	appcontext "github.com/transcom/mymove/pkg/appcontext"

	models "github.com/transcom/mymove/pkg/models"

	supportmessages "github.com/transcom/mymove/pkg/gen/supportmessages"

	testing "testing"
)

// InternalMoveTaskOrderCreator is an autogenerated mock type for the InternalMoveTaskOrderCreator type
type InternalMoveTaskOrderCreator struct {
	mock.Mock
}

// InternalCreateMoveTaskOrder provides a mock function with given fields: appCtx, moveTaskOrder
func (_m *InternalMoveTaskOrderCreator) InternalCreateMoveTaskOrder(appCtx appcontext.AppContext, moveTaskOrder supportmessages.MoveTaskOrder) (*models.Move, error) {
	ret := _m.Called(appCtx, moveTaskOrder)

	var r0 *models.Move
	if rf, ok := ret.Get(0).(func(appcontext.AppContext, supportmessages.MoveTaskOrder) *models.Move); ok {
		r0 = rf(appCtx, moveTaskOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Move)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(appcontext.AppContext, supportmessages.MoveTaskOrder) error); ok {
		r1 = rf(appCtx, moveTaskOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInternalMoveTaskOrderCreator creates a new instance of InternalMoveTaskOrderCreator. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewInternalMoveTaskOrderCreator(t testing.TB) *InternalMoveTaskOrderCreator {
	mock := &InternalMoveTaskOrderCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
