name: App Client Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'src/**'
              - '.storybook/**'
              - '.happo.js'
              - 'dangerfile.ts'
              - 'package.json'
              - 'yarn.lock'
              - 'playwright/**'
              - '.eslintrc.js'
              - '.eslintignore'
              - '.github/**'

  client:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.3.0

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pre-commit==2.20.0

      - name: pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-v1|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install and run client pre-commmit except eslint and prettier
        env:
          SKIP: 'go-version,golangci-lint,ato-go-linter,appcontext-linter,gomod,swagger,eslint,prettier'
        run: |
          python -m pip install pre-commit==2.20.0
          pre-commit run --all-files

      - name: Run client test:coverage
        run: |
          yarn test:coverage

      - name: Publish client test report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'coverage/clover.xml'

      - name: Archive client code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: client-code-coverage-report
          path: coverage
