name: auto approve
on:
  pull_request_target:
    paths-ignore:
      - '.github/workflows/go-auto-approve.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  approve:
    name: auto-approve dependabot PRs
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-latest
    steps:
      - name: approve
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
