name: auto approve
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/gosum.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  approve:
    name: auto-approve dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: approve
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"